### PR TITLE
remove hack/dind

### PR DESCRIPTION
**Pull request by vrothberg**
The docker-in-docker was script was needed to run AppArmor tests in
Travis, which is not required anymore since Travis isn't being used
for a while.  Removing the script will also cure some hiccups on
some atomic testing nodes.

### CODE REVIEW

**Comment by giuseppe** [comment]
LGTM

**Comment by rhatdan** [comment]
Should we have a pinp script?
@vrothberg What was broken before?

**Comment by baude** [comment]
@rhatdan we dont know what is going on

**Comment by vrothberg** [comment]
My brain might be tired but I am out of ideas. The dind is now entirely removed and we're getting things like:
```
.papr.sh: line 90: /go/src/github.com/containers/libpod/hack/selinux_tag.sh: Permission denied
```

**Comment by vrothberg** [comment]
I think we need to debug on one of those nodes. It feels a bit of a whack a mole and I certainly spent my energy budget :D

**Pull request merged**
