### PR TITLE
vendor github.com/containers/storage@v1.13.5

### PR DESCRIPTION
**Pull request by vrothberg**
* Do not discard errors when panicing on lockfile open
* config: drop skip_mount_home
* storage: drop ostree deduplication

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@mheon @cevich, this will hopefully help tracking down the lock open issues :+1:

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
Lot of stuff dropped out of go.mod, but `go mod` works in mysterious ways

**Comment by rhatdan** [comment]
/lgtm
/hold
hold cancel once tests pass.

**Pull request merged**
