### PR TITLE
docs: trivial change to highlight a term

### PR DESCRIPTION
**Pull request by cevich**
Testing if prow/tide will auto-merge this PR despite some cirrus-ci status checks having failed/incomplete.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM, vendor isn't happy?

**Comment by cevich** [comment]
@TomSweeneyRedHat thx for looking.  We're testing something here, sorry for not making that obvious.

**Comment by cevich** [comment]
okay, this is only sort-of-good. The 'Cirrus CI' status requirement is not the one we want.  It should have gone *red* but still shows pending even though all the tasks are complete.

The good news is that *tide* did not merge (despite saying 'in merge pool' quite a while). Let's let this sit here in this state, to be sure it won't merge.  If it doesn't, that means it is sensitive to the general github *statuses* (wouldn't be surprising to me).  Meaning I can point github at the more general 'success' task from cirrus, and we can use that for now.

**Comment by cevich** [comment]
Okay, still no merge in over an hour.  Also [based on some docs I found](https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#protecting-status-contexts), I'm going forward believing prow/tide to honor the branch-protection based status set by github.

I'll set it up with the list of checks we have now, while I investigate a better long-term solution.

**Comment by cevich** [comment]
@mheon @baude just for ref. you can see the rules I set here: https://github.com/containers/libpod/settings/branch_protection_rules (under master)

The branch-protection based checks I added are imperfect, but better than we had before: There's no way to have it monitor matrix tasks, since the name includes the axis items (like image name).  For now let's leave this PR as-is, while I look into fixing this more permanently from the prow/tide side...

**Comment by stevekuznetsov** [comment]
@cevich branch protection settings are being managed by automation and your changes will get removed ...

**Comment by stevekuznetsov** [comment]
You also misinterpreted the documentation there. Please submit a pull request to add non-Prow managed contexts to your branch protection rules in `openshift/release`

**Comment by cevich** [comment]
@stevekuznetsov  oh thanks for responding.  Okay, fair enough about the branch-protection, that was just a band-aid anyway until I could figure out a better way.  I sent you an e-mail re: the github-actions API calls we need to make from tide (?).  Simply adding a job won't be enough, since the github-actions run in parallel.  It's got to happen near the very end, like when tide (?) is polling for label changes.

Hints on where I could add this and the docs. that cover it?

**Comment by cevich** [comment]
We're going to fix this a different way.

**Pull request closed without merging**
