### PR TITLE
Cirrus: Use branch-specific container image tag

### PR DESCRIPTION
**Pull request by cevich**
***N/B:*** This is against the v1.4.2-stable branch, not master.

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
Uh-oh. Are we using the same test images for this branch as master? We can't drop OSTree in a stable stream, so we might need to re-add it to all the images until we no longer support a release with it.

**Comment by cevich** [comment]
> Uh-oh. Are we using the same test images for this branch as master?

Yes, this is exactly the problem.  So before we can fix it here (by adding branch-specific builds to quay) we need this (otherwise CI on master will break):

#4503

**Comment by mheon** [comment]
With #4503 landed I think this needs a rebase

**Comment by rhatdan** [comment]
@cevich You still working on this one?

**Comment by cevich** [comment]
I think so, maybe.  I'll peek at it next year :smile:

**Comment by cevich** [comment]
Update: Since the container-based tasks weren't running, meta never touched the VM images, causing them to be considered disused and pruned.  This is bad, but hopefully not irrecoverable.  Attempting to rebuild the VM images, then I'll manually mark them to be preserved.

**Comment by cevich** [comment]
@mheon this PR seems to be failing on a bunch of podman & test issues I'm pretty sure we've fixed in master.  Does that mean there is back-porting work to be done here and for RHEL?

**Comment by mheon** [comment]
Hm. Our ability to do that for non-critical bugs is somewhat limited. I don't know how much we can justify changing (and how much we actually want to - patching 1.0.x has become actively painful at this point)

**Comment by cevich** [comment]
> for non-critical bugs is somewhat limited

Yep I understand on all accounts.

What about only updating `./test/` maybe?  I can attempt that, just not sure if/how it will work.  The other-side of the coin is needing to test some critical update, but have automation break :confounded:

**Comment by cevich** [comment]
Another idea:  I can simply make all the CI tasks "optional" on this branch.  They'll still run and report, just won't block anything.

**Comment by cevich** [comment]
@mheon okay, well it's kind of gray-green status now :smile:   Good 'nuff?

**Comment by mheon** [comment]
Certainly better than how things were... We can work the rest later if we end up with further backport requests.

**Comment by cevich** [comment]
Okay, this is ready to go then.

**Comment by rhatdan** [comment]
This LGTM
But should we update the images now, they are looking a little old.

**Comment by cevich** [comment]
@rhatdan that's intentional: This is the `v1.4.2-stable` branch, so it **SHOULD** be running whatever was "current" at time of branching.  Unless I'm misunderstanding something.

**Pull request merged**
