### PR TITLE
Test that PTYs created by 'podman exec --tty' have non-zero size

### PR DESCRIPTION
**Pull request by debarshiray**
Signed-off-by: Debarshi Ray <rishi@fedoraproject.org>

### CODE REVIEW

**Comment by debarshiray** [comment]
This is an attempted test for https://github.com/containers/libpod/issues/3903

**Comment by rhatdan** [comment]
@debarshiray looks like your tests is failing for rootless.

**Comment by mheon** [comment]
```

[+0766s]   Expected
[+0766s]       <bool>: true
[+0766s]   to be false
[+0766s] 
[+0766s]   /var/tmp/go/src/github.com/containers/libpod/test/e2e/exec_test.go:138
```

**Comment by mheon** [comment]
Hmmm. We're forwarding TTY size over from the parent process, right?

Is it possible the parent (Ginkgo) doesn't have a non-zero PTY size?

**Comment by debarshiray** [comment]
> Hmmm. We're forwarding TTY size over from the parent process, right?
> 
> Is it possible the parent (Ginkgo) doesn't have a non-zero PTY size?

I see that it's querying the outer terminal size using [TIOCGWINSZ](http://man7.org/linux/man-pages/man2/ioctl_tty.2.html) in `GetWinsize` in `github.com/docker/docker/pkg/term`. So, I guess this shows that the outer terminal doesn't have a non-zero size.

Is there even an outer terminal device provided by Ginkgo? I don't know. I will try poking around at Ginkgo to see if I can figure anything out.

**Pull request closed without merging**
