### PR TITLE
cirrus: run tests with crun

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.  Some look to be a bit unhappy atm.

**Comment by mheon** [comment]
LGTM once things go green

**Comment by giuseppe** [comment]
one of the tests I've disabled is an issue in crun that I'll have to investigate (notify socket).

Other ones are expected and are generated by the same reason as they depend on a runc behavior.  I'll probably add a mode to follow runc here so that we don't need any special handling.

**Comment by giuseppe** [comment]
tests are green now

**Comment by giuseppe** [comment]
the issue with NOTIFY_SOCKET is fixed here: https://github.com/containers/crun/pull/72

**Pull request merged**
