### PR TITLE
[CI:DOCS] api: pull: fix reference parsing

### PR DESCRIPTION
**Pull request by vrothberg**
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM. Really hate sticking CI:DOCS on code PRs, though.

**Comment by rhatdan** [comment]
Why is this a Docs only?  Are we not testing this code now?

**Comment by vrothberg** [comment]
> Why is this a Docs only? Are we not testing this code now?

No. There are no tests for this endpoint yet.

**Pull request merged**
