### PR TITLE
Eat our own dogfood

### PR DESCRIPTION
**Pull request by rhatdan**
Switch all tests to use podman installed on the system, or Docker if podman
does not exist.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
@mheon I think this replaces https://github.com/containers/libpod/pull/1475

**Comment by rhatdan** [comment]
@baude @umohnani8 @mheon @giuseppe @TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
Going to try LGTM assuming happy tests once more.

**Comment by mheon** [comment]
Agree that this replaces #1475

**Comment by mheon** [comment]
LGTM

**Comment by umohnani8** [comment]
LGTM

**Pull request merged**
