### PR TITLE
display proper error when rmi -fa with infra containers

### LINKED ISSUE #1991: podman rmi/rm -af and infra containers
Podman is unable to delete all images (`podman rmi -af`) when an infra container of a Pod still exists.

The first attempt of `podman rmi -af` will yield a helpful error message, e.g.:
`
error removing image da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e: container 05bd830d6625975d8013d6004099c4df92daa050f12637c7e85bd0a1664d6273 using image could not be removed: container 05bd830d6625975d8013d6004099c4df92daa050f12637c7e85bd0a1664d6273 is the infra container of pod 159a2a2b6a937e49340cd251e8543bfe273ea13b61cef63a8cb33d25613fcc26 and cannot be removed without removing the pod            
`

Following attempts of `podman rmi -af`, however, will only yield a
`unable to delete all images; re-run the rmi command again.` which isn't very helpful.

If special-casing infra containers is still desired, the descriptive error message should always be printed. If we decide to treat an infra container like any other, we could delete the Pod if it has been paused.

### PR DESCRIPTION
**Pull request by baude**
when deleting infra containers, we were not checking the error of the
image deletion and therefore resulting in not reporting the error.

Fixes #1991

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
LGTM (but I didn't test)

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by baude** [comment]
@TomSweeneyRedHat mind merging? you are the second lgtm

**Pull request merged**
