### PR TITLE
[WIP] Add support for annotations and labels

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@haircommander PTAL

**Comment by rhatdan** [comment]
@mrunalp PTAL.

The reason this is a WIP is I am not sure how `podman play kube` should work.

Currently libpod/podman pods do not support Annotations.  I think they should.  The goal I have is to allow us to easily transition containers/pods that have annotations for KATA to be able to move back and forth between kubernetes and libpod.

**Comment by haircommander** [comment]
As it stands, this is incomplete. You only add annotations to `podman generate kube containername` which generates just for one container (a functionality I didn't even realize existed). You'll also want to do the same in the `podWithContainers` function

Though, in general, I don't think this approach will satisfy what Kata needs. What we should really do is unconditionally set the correct annotations (regardless of source, like in: https://github.com/containers/libpod/pull/4368), which will allow pods created in kata and whatever other runtime to work. 

Not to say this isn't useful work, adding annotations to a container is something that exists in the k8s pod api, and thus we want to implement. But I don't want the two things to get mixed up

**Comment by mheon** [comment]
The original justification there was labels vs annotations - how are they different, and why do pods need both?

**Comment by mheon** [comment]
Agree with @haircommander that we should do annotations for the Kata runtime unconditionally if we detect it.

**Comment by rhatdan** [comment]
@mheon Don't know.  Kubernetes seems to have ignored the existence of Labels and created Annotations.  But I don't know the history.

**Comment by haircommander** [comment]
> The goal I have is to allow us to easily transition containers/pods that have annotations for KATA to be able to move back and forth between kubernetes and libpod.

I am not sure this functionality exists right now in kubernetes. We would definitely want some sort of unified api structure for declaring which runtime to use for which pod/container before we go down this path.

**Pull request closed without merging**
