### PR TITLE
update the latest version to 1.8.2

### PR DESCRIPTION
**Pull request by dmitris**
PR updates the latest version number to be in sync with the linked latest release https://github.com/containers/libpod/releases/latest

### CODE REVIEW

**Comment by mheon** [comment]
Can you add a signoff to your commit to kick CI? `git commit -s --amend` and re-pushing should work.

Otherwise LGTM.
/approve

**Comment by TomSweeneyRedHat** [comment]
LGTM once signed

**Comment by rhatdan** [comment]
Of course we are about to do a new release...

**Comment by dmitris** [comment]
> Of course we are about to do a new release...

c'est la vie 😄

**Comment by dmitris** [comment]
> Can you add a signoff to your commit to kick CI? `git commit -s --amend` and re-pushing should work.

done, please re-approve if needed @mheon

**Comment by rhatdan** [comment]
Thanks @dmitris

**Comment by mheon** [comment]
/hold

One test flaked

**Comment by mheon** [comment]
`[Fail] Podman checkpoint [It] podman checkpoint with --leave-running `

@edsantiago This looks like a new one, no?

**Comment by mheon** [comment]
Very interesting failure. It looks like restore is failing as it thinks the container is running, but a `podman ps` immediately before shows it as Exited

**Comment by edsantiago** [comment]
[log link for posterity](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5340808991735808/html/integration_test.log.html#t--podman-checkpoint-with---leave-running--1). And log excerpt:
```
Running: podman [options] --storage-driver=vfs ps --all --format={{.Status}}
Exited (143) Less than a second ago

Running: podman [options] --storage-driver=vfs container restore f999ed900f5dfbb124f54110ad3773a330e44acf0482a930c84ca548c5c2d920
Error: failed to restore container f999ed900f5dfbb124f54110ad3773a330e44acf0482a930c84ca548c5c2d920: container f999ed900f5dfbb124f54110ad3773a330e44acf0482a930c84ca548c5c2d920 is running or paused, cannot restore: container state improper
```
I mostly agree with your assessment; my one quibble is that you say "container is running", whereas the error itself includes "state improper". I don't know what "improper" means in this context. There have long been problems with `podman ps` and `Exited` vs `Stopped`; could this be one such?

Also, as you say, this is a new (to me) error. I have not seen it before.

**Comment by TomSweeneyRedHat** [comment]
Happy green test buttons.  Will let @mheon merge as appropriate for the pending release.

**Comment by rhatdan** [comment]
We need to wait for the make vendor/tidy changes by @mtrmac

**Pull request merged**
