### PR TITLE
/images/.../json: fix port parsing

### PR DESCRIPTION
**Pull request by vrothberg**
Fix a bug when parsing the `ExposedPorts` of the image that lead to
panics when the field was set.  The OCI image spec allows three valid
formats: `tcp/port`, `udp/port` and `port`

Fixes: #6490
Reported-by: @jgallucci32
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@baude @giuseppe @jwhonce @mheon @rhatdan PTAL

**Comment by rhatdan** [comment]
LGTM
But what happens when the user just specifies `port`.  Does this just default to `tcp` or `udp` or are you supposed to use both?

**Comment by vrothberg** [comment]
> LGTM
> But what happens when the user just specifies `port`. Does this just default to `tcp` or `udp` or are you supposed to use both?

Then it defaults to `tcp`. That's what the spec wants:

https://github.com/containers/libpod/pull/6491/files#diff-2c1834810ca2c977e6dec2367e27701eR341-R342

**Pull request merged**
