### PR TITLE
rootless: move ns open before fork

### PR DESCRIPTION
**Pull request by giuseppe**
commit 788fdc685b00dee5ccb594bef845204250c4c123 introduced a race
where the target process dies before the child process opens the
namespace files.  Move the open before the fork so if it fails the
parent process can attempt to join a different container instead of
failing.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
I'll have to backport to 1.9

**Comment by rhatdan** [comment]
We have already started a podman 1.9.2

**Comment by mheon** [comment]
Are we backporting this to 1.9.x? I don't see a PR for it

**Pull request merged**
