### PR TITLE
exec: remove polling for PID file

### PR DESCRIPTION
**Pull request by giuseppe**
a couple of improvements for exec:

- we use fsnotify to take advantage of inotify on Linux so we don't poll for the file being created
- if the OCI runtime exited don't let the timeout expire first, but return an error immediately.

We recently bumped the timeout value, that means we could block the container lock for 60s if the runtime failed

### CODE REVIEW

**Comment by vrothberg** [comment]
LGTM

**Comment by vrothberg** [comment]
bot, retest this please (CNI hiccup)

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but tests don't seem to be hip atm.

**Comment by vrothberg** [comment]
bot, retest this please

**Comment by vrothberg** [comment]
@giuseppe, the linter isn't happy:
```
libpod/container_api.go:349:10:warning: if block ends with a return statement, so drop this else and outdent its block (golint)
```

**Comment by mheon** [comment]
Is fsnotify safe to use for this? There is a (if I recall correctly, fairly
low) global cap on inotify sessions, and since we're not a daemon we can
probably exhaust those if a lot of exec sessions are running

**Comment by EmilienM** [comment]
LGTM thanks @giuseppe

**Comment by rhatdan** [comment]
@mheon From googling around their looks like their is max watch of a directory.  The default is 8192.

```
cat /proc/sys/fs/inotify/max_user_watches
8192
```

I think we are safe with this change.

**Comment by mheon** [comment]
More general comment - we should retain the timeout even if we use inotify
here. The exit file might not be created for various reasons on the conmon
side, and we don't want to hang forever

**Comment by giuseppe** [comment]
to avoid any kind of issue with hitting the inotify limit, I've changed the implementation to fallback to polling if the watcher cannot be created.

The timeout is still honored, this change only adds another check for the OCI process.  If the runtime has exited there is no need to let the timeout expire and we can assume the PID file is not going to be written as there is no process running.

**Comment by umohnani8** [comment]
LGTM

**Comment by mheon** [comment]
Falling back to polling SGTM

**Comment by mheon** [comment]
Code LGTM with these changes

**Comment by vrothberg** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@giuseppe Seems to be causing issues with checkpointing?

**Comment by rhatdan** [comment]
@giuseppe This might need a rebase

**Comment by giuseppe** [comment]
rebased.  I've lost track of all the PRs that are blocked because of PAPR failures since weeks.

**Comment by rhatdan** [comment]
Yup that is why I am going through the old ones, to see if we can get some stuff merged  but of course the CI is crashing again.  :^(

**Comment by rhatdan** [comment]
bot, retest this please
/retest

**Pull request merged**
