### PR TITLE
Do never override podman with docker

### PR DESCRIPTION
**Pull request by isimluk**
Similar to https://github.com/containers/skopeo/pull/566

🍔

### CODE REVIEW

**Comment by mheon** [comment]
Oops. LGTM.

**Comment by mheon** [comment]
bot, add author to whitelist

**Comment by mheon** [comment]
@isimluk Can you add a signoff your commit with `git commit --amend -s` and repush?

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
