### PR TITLE
Use StopAtEOF() to avoid early termination of following logs

### PR DESCRIPTION
**Pull request by jgallucci32**
Signed-off-by: jgallucci32 <john.gallucci.iv@gmail.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@QiWang19 @ashley-cui @jwhonce @mheon PTAL

**Comment by jgallucci32** [comment]
/hold

2 checks failed. Seem to be the sames ones as before. No better, no worse.

**Comment by jgallucci32** [comment]
@edsantiago I am able to reliably get this to fail with the following commands from the test
```
podman run --rm --name logs-f-rm -dt docker.io/library/alpine:latest sh -c 'echo podman; sleep 1; echo podman'
podman logs -f logs-f-rm
podman run --rm --name logs-f-rm -dt docker.io/library/alpine:latest true

```
NOTE: You have to run the 3 commands at the same time. Any delay in running the third command results in expected behavior.

This gives a good starting point to figure out where the race condition lives.

**Comment by jgallucci32** [comment]
> @edsantiago I am able to reliably get this to fail with the following commands from the test
> 
> ```
> podman run --rm --name logs-f-rm -dt docker.io/library/alpine:latest sh -c 'echo podman; sleep 1; echo podman'
> podman logs -f logs-f-rm
> podman run --rm --name logs-f-rm -dt docker.io/library/alpine:latest true
> ```
> 
> NOTE: You have to run the 3 commands at the same time. Any delay in running the third command results in expected behavior.
> 
> This gives a good starting point to figure out where the race condition lives.

Ok it looks like PR https://github.com/containers/libpod/pull/6614 fixes this condition. What I need to test is if `StopAtEOF()` in combination with event channels is the correct fix. It's possible it is waiting for DONE because event channels is faster and not completing the log to end of file.

**Comment by edsantiago** [comment]
There's no race condition, this is a broken, badly written test. `logs -f` should terminate when the container terminates, we all agree on that -- there is no reason whatsoever, though, for it to guarantee that the container has been removed and cleaned up. This e2e test needs to be rewritten.

**Comment by jgallucci32** [comment]
@edsantiago Which specific test needs to be rewritten?

I'm thinking of closing this PR since it proved using `Stop()` and `StopAtEOF()` had to effect and this is being reworked in a separate PR.

**Comment by edsantiago** [comment]
@jgallucci32 see #6640

**Comment by jgallucci32** [comment]
/Close

This has been superseded by #6644 and #6614

**Pull request closed without merging**
