### PR TITLE
Fix container inspect endpoint returning null for network settings / ports

### PR DESCRIPTION
**Pull request by skorhone**
Fixes compatibility issue with testcontainers.

This pull requests adds list of ports to NetworkSettings.Ports

Docker inspect returns Ports:

```
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "8481a8888bee4be0737c003ab80224e8bbcf22064e55a19e93a7eb33f253fd9c",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "2222/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32770"
                    }
                ]
            },
```

After this change podman returns ports from compat API interface:

```
  "NetworkSettings": {
    "Bridge": "",
    "SandboxID": "",
    "HairpinMode": false,
    "LinkLocalIPv6Address": "",
    "LinkLocalIPv6PrefixLen": 0,
    "Ports": {
      "2222/tcp": [
        {
          "HostIp": "",
          "HostPort": "38947"
        }
      ]
    },
```

Incorrect HostIp is out of scope for this pull request. I think that mapping empty string to 0.0.0.0 should be done in libpod/container_inspect.go rather than doing it in api/compat/container.go. Considering that I don't fully understand side effects that change to container_inspect could have caused, I decided to not to implement it.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@mheon @baude PTAL

**Comment by baude** [comment]
lgtm, @mheon ptal

**Pull request merged**
