### PR TITLE
rootlessport: use x/sys/unix instead of syscall

### PR DESCRIPTION
**Pull request by giuseppe**
Dup2 is not defined on arm64 in the syscall package.

Closes: https://github.com/containers/libpod/issues/5587

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by giuseppe** [comment]
CI failure addressed here: https://github.com/containers/libpod/pull/5590

**Comment by rhatdan** [comment]
/hold cancel
Special testing is not blocking right now, I believe.

**Comment by giuseppe** [comment]
rebased

**Pull request merged**
