### PR TITLE
Update release notes and README for 1.9.1 release

### PR DESCRIPTION
**Pull request by mheon**
Mirror the release notes from the v1.9 branch, and update README as well

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @baude @giuseppe @vrothberg @jwhonce @QiWang19 PTAL

**Comment by TomSweeneyRedHat** [comment]
Late to the ball on this one, but LGTM

**Pull request merged**
