### PR TITLE
[v2] containers, init: skip invalid state errors with --all

### PR DESCRIPTION
**Pull request by giuseppe**
reintroduce the same check that exists in v1.9.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
Gating is failing, though

**Comment by TomSweeneyRedHat** [comment]
LGTM once gofmt is run against containers.go

**Comment by giuseppe** [comment]
repushed now

**Pull request merged**
