### PR TITLE
Fix Dockerfile

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by baude** [comment]
lgtm

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by edsantiago** [comment]
cirrus-flake-summarize, for later analysis:

#### test fedora-31 fedora-31

  2020-05-26T08:42:04  [integration_test](https://api.cirrus-ci.com/v1/task/6407429363597312/logs/integration_test.log)
*   [Podman stats [It] podman stats with json output ](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6407429363597312/html/integration_test.log.html#t--podman-stats-with-json-output--1)
  *   [[same]](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6407429363597312/html/integration_test.log.html#t--podman-stats-with-json-output--2)
  *   [[same]](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6407429363597312/html/integration_test.log.html#t--podman-stats-with-json-output--3)
*   [Podman run networking [It] podman run network expose duplicate host port results in error ](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6407429363597312/html/integration_test.log.html#t--podman-run-network-expose-duplicate-host-port-results-in-error--1)

  2020-05-26T09:22:25  [integration_test](https://api.cirrus-ci.com/v1/task/6429389598490624/logs/integration_test.log)
*   [Podman trust [It] podman image trust show ](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6429389598490624/html/integration_test.log.html#t--podman-image-trust-show--1)
  *   [[same]](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6429389598490624/html/integration_test.log.html#t--podman-image-trust-show--2)
*   [Podman rmi [It] podman rmi image that is a parent of another image ](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6429389598490624/html/integration_test.log.html#t--podman-rmi-image-that-is-a-parent-of-another-image--1)
*   [Podman stats [It] podman stats with json output ](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6429389598490624/html/integration_test.log.html#t--podman-stats-with-json-output--1)
  *   [[same]](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6429389598490624/html/integration_test.log.html#t--podman-stats-with-json-output--2)
  *   [[same]](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6429389598490624/html/integration_test.log.html#t--podman-stats-with-json-output--3)

  2020-05-26T09:50:29  [integration_test](https://api.cirrus-ci.com/v1/task/6262854254854144/logs/integration_test.log)
*   [Podman stats [It] podman stats with json output ](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6262854254854144/html/integration_test.log.html#t--podman-stats-with-json-output--1)
  *   [[same]](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6262854254854144/html/integration_test.log.html#t--podman-stats-with-json-output--2)
  *   [[same]](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6262854254854144/html/integration_test.log.html#t--podman-stats-with-json-output--3)
*   [Podman pod rm [It] podman pod rm removes a pod with a container ](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6262854254854144/html/integration_test.log.html#t--podman-pod-rm-removes-a-pod-with-a-container--1)
*   [Podman run networking [It] podman run network expose duplicate host port results in error ](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6262854254854144/html/integration_test.log.html#t--podman-run-network-expose-duplicate-host-port-results-in-error--1)

**Pull request merged**
