### PR TITLE
WIP - DONOT MERGE - ensure buildroot is deleted

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

Hope this gets the build forward.

@baude @rhatdan @mheon PTAL

### CODE REVIEW

**Comment by lsm5** [comment]
This should hopefully address the issue in https://storage.googleapis.com/origin-ci-test/pr-logs/pull/containers_libpod/3703/pull-ci-containers-libpod-master-images/7380/build-log.txt

**Comment by lsm5** [comment]
My `~/.rpmmacros has:

```%_smp_mflags %( \
    [ -z "$RPM_BUILD_NCPUS" ] \\\
        && RPM_BUILD_NCPUS="`/usr/bin/nproc 2>/dev/null || \\\
                             /usr/bin/getconf _NPROCESSORS_ONLN`"; \\\
    if [ "$RPM_BUILD_NCPUS" -gt 16 ]; then \\\
        echo "-j16"; \\\
    elif [ "$RPM_BUILD_NCPUS" -gt 3 ]; then \\\
        echo "-j$RPM_BUILD_NCPUS"; \\\
    else \\\
        echo "-j3"; \\\
    fi )

%__arch_install_post \
    [ "%{buildarch}" = "noarch" ] || QA_CHECK_RPATHS=0 ; \
    case "${QA_CHECK_RPATHS:-}" in [1yY]*) /usr/lib/rpm/check-rpaths ;; esac \
    /usr/lib/rpm/check-buildroot
```

the check-buildroot script at the end takes care of cleaning out the buildroots, which I only noticed now (was a copy-paste from long back). It'd be great if we could have this file installed as a ~/.rpmmacros on the CI environments, or if `rm -rf %{buildroot}` works well enough, then maybe we can just go with that

**Comment by giuseppe** [comment]
LGTM

**Comment by rhatdan** [comment]
/test/images

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by lsm5** [comment]
so, @baude mentioned that this patch didn't help RE: https://github.com/containers/libpod/pull/3703/files . I'm working on another one.

**Comment by lsm5** [comment]
closed in favour of https://github.com/containers/libpod/pull/3757

**Pull request closed without merging**
