### PR TITLE
auto-update

### PR DESCRIPTION
**Pull request by vrothberg**
Add the `podman auto-update` command. There have been no tests in v1, so
there are no in v2 either ... for now :)

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@baude @jwhonce @mheon @rhatdan PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM but tests sooner would be good if possible.

**Comment by vrothberg** [comment]
> LGTM but tests sooner would be good if possible.

Definitely! It's on my todo but has a low priority given it's targeted for 8.4. Once the heavy v2 lifting is done, I want to iron out some warts in `generate systemd` and improve testing there. After that, we have a good base to work on tests for `auto-update`.

**Comment by vrothberg** [comment]
Updated the error message to make the help system tests happy.

**Comment by vrothberg** [comment]
Integration tests are flakes

**Comment by vrothberg** [comment]
Here's  a PR to make systemd tests run https://github.com/containers/libpod/pull/6134

**Pull request merged**
