### PR TITLE
system df: reject invalid arguments

### PR DESCRIPTION
**Pull request by edsantiago**
Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
/approve
LGTM

**Comment by mheon** [comment]
@baude @rhatdan @TomSweeneyRedHat PTAL

**Comment by edsantiago** [comment]
In case context helps for reviewing:
```
$ grep -Rh -3 noSubArgs cmd/podman
```

**Comment by TomSweeneyRedHat** [comment]
LGTM
Test out nicely, nice little fix @edsantiago

**Pull request merged**
