### PR TITLE
Remove reference to "upcoming" RHEL 7.7

### LINKED ISSUE #6349: remove doc reference to upcoming RHEL 7.7 release
/kind bug

**Description**

The troubleshooting documentation says "Note RHEL 7 and CentOS 7 will not have support for this until RHEL7.7 is released", and Red Hat [shipped RHEL 7.7](https://access.redhat.com/errata/RHBA-2019:2351) a while ago.

**Describe the results you expected:**

The documentation should describe the default behavior with the latest released RHEL 7 utilities.

### PR DESCRIPTION
**Pull request by mheon**
7.7 has been released for a while now, so change troubleshooting reference to indicate that.

Fixes #6349

### CODE REVIEW

**Comment by mheon** [comment]
Damn, forgot to CI:DOCS this

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat @QiWang19 @jwhonce @baude PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
