### PR TITLE
Dockerfile.*: bump CNI plugins commit

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@vrothberg @mheon @baude @TomSweeneyRedHat @ashley-cui @QiWang19 @jwhonce PTAL

**Comment by QiWang19** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by mheon** [comment]
LGTM

**Pull request merged**
