### PR TITLE
Move to containers/image v5, support manifest lists

### PR DESCRIPTION
**Pull request by nalind**
Since https://github.com/containers/storage/pull/283, the storage library's Image type has been able to track multiple digests for an image in storage, so we should support that, as proposed changes in https://github.com/containers/image/pull/400 will start storing manifest lists alongside runnable images.  This also extends the exported API and inspection types to provide that information.

When we encounter an image in local storage that we can read as an image library `ImageSource` but not as an `Image`, we should handle it gracefully, since it might be an image list with no corresponding runnable image, as https://github.com/containers/buildah/pull/1902 will start creating.

Add some tests to exercise pulling using tags that point to manifest lists, using digests of manifest lists, and digests of images that aren't manifest lists, that we're able to successfully inspect the result, and that when we create an image using the result of one of the pulls, that we get back the name we specified when creating the image.  The tests require `--override-os` and `--override-arch` flags to `pull`, which we add but leave hidden, for now at least.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Do you foresee issues with containers and/or images on the system that were created before these changes go into play?  i.e. will each pre-existing containers and images need to be migrated/updated?

**Comment by nalind** [comment]
No, the contents on disk stay the same when we pull an image down using a tag or a digest that doesn't point to a list.  For such images, the only visible differences should be in the `podman images` output, where we stop outputting a digest in the `tag` column, and in image `inspect` output, where we likewise don't have names with digests in them in the `RepoTags` field.

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by TomSweeneyRedHat** [comment]
@nalind, are you OK with removing the WIP label on this?  Looks like you're still fighting with the tests.

**Comment by nalind** [comment]
Yeah, other than the tests, I think this is complete.

**Comment by rhatdan** [comment]
/lgtm
/hold
hold cancel once tests pass.

**Pull request merged**
