### PR TITLE
enable ci on go binding tests

### PR DESCRIPTION
**Pull request by baude**
Signed-off-by: Brent Baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
You need to rebase against current master. Sorry. #5282

**Comment by baude** [comment]
ready for review and merge

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM but it looks like we're fighting the CI again.

**Comment by baude** [comment]
it passes all tests ... the rdo test is always failing and not required.

**Pull request merged**
