### PR TITLE
Vendor in logrus v1.4.2

### LINKED ISSUE #3346: please upgrade "logrus"
Currently a fairly old _logrus_ library is [vendored](https://github.com/containers/libpod/blob/master/vendor.conf#L69-L70).

Upgrade is straightforward and much similar to https://github.com/x-cray/logrus-prefixed-formatter/issues/22.

The following (untested) patch fixes compilation with logrus-1.3.0:

```patch
--- a/cmd/podman/export.go
+++ b/cmd/podman/export.go
@@ -6,9 +6,9 @@
 	"github.com/containers/libpod/cmd/podman/cliconfig"
 	"github.com/containers/libpod/cmd/podman/shared/parse"
 	"github.com/containers/libpod/pkg/adapter"
 	"github.com/pkg/errors"
-	"github.com/sirupsen/logrus"
+	"golang.org/x/crypto/ssh/terminal"
 	"github.com/spf13/cobra"
 )
 
 var (
@@ -61,9 +61,9 @@
 	}
 
 	if len(output) == 0 {
 		file := os.Stdout
-		if logrus.IsTerminal(file) {
+		if terminal.IsTerminal(int(file.Fd())) {
 			return errors.Errorf("refusing to export to terminal. Use -o flag or redirect")
 		}
 		output = "/dev/stdout"
 	}
--- a/cmd/podman/save.go
+++ b/cmd/podman/save.go
@@ -8,9 +8,9 @@
 	"github.com/containers/libpod/cmd/podman/shared/parse"
 	"github.com/containers/libpod/pkg/adapter"
 	"github.com/containers/libpod/pkg/util"
 	"github.com/pkg/errors"
-	"github.com/sirupsen/logrus"
+	"golang.org/x/crypto/ssh/terminal"
 	"github.com/spf13/cobra"
 )
 
 const (
@@ -81,9 +81,9 @@
 	}
 
 	if len(c.Output) == 0 {
 		fi := os.Stdout
-		if logrus.IsTerminal(fi) {
+		if terminal.IsTerminal(int(fi.Fd())) {
 			return errors.Errorf("refusing to save to terminal. Use -o flag or redirect")
 		}
 		c.Output = "/dev/stdout"
 	}

```

### PR DESCRIPTION
**Pull request by jwhonce**
Fixes #3346

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
@TomSweeneyRedHat did we end up deciding this wouldn't break Buildah?

**Comment by TomSweeneyRedHat** [comment]
@mheon we think it won't break Buildah, but it's next on my list of things to do and can verify then.

**Comment by TomSweeneyRedHat** [comment]
@jhonce why 1.3 and not latest 1.4.2?

**Comment by jwhonce** [comment]
@TomSweeneyRedHat Good call, going for latest.

**Comment by mheon** [comment]
/retest

Seeing a lot of flakes in Prow trying to connect to the Fedora mirrors

**Pull request merged**
