### PR TITLE
Cirrus: Add check for make varlink_api_generate

### PR DESCRIPTION
**Pull request by cevich**
Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by baude** [comment]
LGTM

**Comment by cevich** [comment]
(rebase and `--force` push)

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but fedora-29 tests are failing with a segv.  Not sure if it's related to this PR or not....

**Comment by cevich** [comment]
(rebase and `--force` push)

**Comment by cevich** [comment]
Thanks @TomSweeneyRedHat ya I think it might be flakes, re-ran it a few times and it breaks differently each go :confused:   Folks are chasing some of those problems down, so hopefully a few rebase/pushes and it'll run clean.

**Comment by cevich** [comment]
mmm...dangit...the new check is doing something strange :confounded:

**Comment by cevich** [comment]
Okay, few more runs and rebases got it, all green now.

**Comment by baude** [comment]
LGTM

**Pull request merged**
