### PR TITLE
Start testing with cross compilation

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
Huh. Darwin is failing too, with manpage issues.

**Comment by rhatdan** [comment]
@mheon @giuseppe @baude @QiWang19 @TomSweeneyRedHat @vrothberg @jwhonce PTAL

**Comment by QiWang19** [comment]
LGTM

**Comment by mheon** [comment]
Nice! I spent a half-hour chasing down Varlink stuff as the culprit for pkg/spec, but it turned out to be much simpler.

/lgtm

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
