### PR TITLE
replacing podman logo SVG and PNG files

### PR DESCRIPTION
**Pull request by mairin**
updating podman logo source to have text as paths (which won't require the correct font be installed to display properly) as well as updating PNG to accurately reflect design intent (which will allow for logotype to match other logos in the containers family such as buildah and cri-o)

Addresses #3350

### CODE REVIEW

**Comment by mheon** [comment]
@mairin Mind adding a signoff to fix CI? `git commit --amend -s` should do it.

**Comment by mairin** [comment]
i'm not sure what the vendor test is looking for or what i can do to fix, any advice?

**Comment by mheon** [comment]
Looks like a network flake... It's trying to verify the existence of a package, but can't connect to its listed repo. Restarting.

**Comment by TomSweeneyRedHat** [comment]
#3354  from @dankohn was merged just about an hour ago.  Does this replace that or did we have a merge race?

**Comment by mairin** [comment]
@TomSweeneyRedHat #3354 has the wrong version of the files :( i think it was merged first tho

**Comment by TomSweeneyRedHat** [comment]
@mairin OK, well merging this will fix that up.  Thanks for the clarification.
LGTM assuming happy tests.

**Comment by mairin** [comment]
I'm not sure why it's failing, is it another network issue?

**Comment by mheon** [comment]
CI's having issues everywhere. Since it's all Google cloud hosted, I'm blaming whatever outage killed Google Calendar.

**Pull request merged**
