### PR TITLE
Cirrus: Update VM Images

### LINKED ISSUE #5668: CI: can we get a new conmon?
CI is still flaking with "timed out waiting for file" (#5339): [example from 2020-03-30](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4841949664378880/html/system_test.log.html).

This is apparently fixed in [conmon PR 128](https://github.com/containers/conmon/pull/128) which, if I read logs correctly, made it into conmon 2.0.13; the failed log above is 2.0.12-1.fc31.

@cevich when convenient, could you do the necessary magic to get conmon updated in the CI systems? Koji shows a recent `2.0.14` build.

(And if it's not too much trouble, an updated `skopeo` also please?)

### PR DESCRIPTION
**Pull request by cevich**
Fixes #5668

Fedora release 31 (Thirty One)
```
Kernel:  5.5.11-200.fc31.x86_64
Cgroups:  cgroup2fs
conmon-2.0.14-1.fc31-x86_64
containernetworking-plugins-0.8.5-1.fc31-x86_64
containers-common-0.1.41-1.fc31-x86_64
container-selinux-2.129.0-1.fc31-noarch
criu-3.13-5.fc31-x86_64
crun-0.13-1.fc31-x86_64
golang-1.13.6-1.fc31-x86_64
libseccomp-2.4.2-2.fc31-x86_64
package runc is not installed
podman-1.8.2-2.fc31-x86_64
skopeo-0.1.41-1.fc31-x86_64
slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31-x86_64
```

Ubuntu 18.04.4 LTS
```
Kernel:  5.0.0-1031-gcp
Cgroups:  tmpfs
conmon-2.0.14~1-amd64
containernetworking-plugins-0.8.5~1-amd64
containers-common-0.1.41~1-all
cri-o-runc-1.0.0-3~dev2-amd64
criu-3.13-2ppa1.18.04-amd64
golang-2:1.14-1longsleep1+bionic-all
libseccomp2-2.4.1-0ubuntu0.18.04.2-amd64
podman-1.8.2~1-amd64
skopeo-0.1.41~1-amd64
slirp4netns-0.4.3~1-amd64
```

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
@edsantiago this is ready for ya.

**Comment by edsantiago** [comment]
|     | old | new |
| --- | --- | --- |
| f30 | 2.0.10-2 | 2.0.13-1 |
| f31 | 2.0.12-1 | 2.0.14-1 |
| ubuntu-18 | 2.0.13~1 | 2.0.14~1 |

Bummer about not getting a new skopeo, but that's because (sigh) [there's no actual build](https://bodhi.fedoraproject.org/updates/?packages=skopeo). Not much we can do about that.

/lgtm

Thank you!

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
