### PR TITLE
Re-allow the : character in container names, but warn

### PR DESCRIPTION
**Pull request by mheon**
Per discussion in #2876, our initial container name regular expression allowed the : character (more specifically, it just didn't force the match to extend to the entirety of the container name, so any name containing at least one alphanumeric character was considered valid). The Fedora Toolbox used names including the : character, so making the regex actually match the entire container name broke them.

Make : an allowed character again, but warn that it is deprecated and may be removed.

Fixes: #2876

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM, but rootless tests seem unhappy

**Comment by mheon** [comment]
@vrothberg I'm no longer certain we want to do this - I've found a few places where it breaks established parsing (for example, `--volumes-from`)

**Comment by vrothberg** [comment]
> @vrothberg I'm no longer certain we want to do this - I've found a few places where it breaks established parsing (for example, `--volumes-from`)

@mheon, I am okay with forbidding `:` :)

**Comment by rhatdan** [comment]
I agree, this breaks toolbox though, can we work with them to fix their issues.

**Comment by mheon** [comment]
They've already migrated away from using it, so we should be good. Closing.

**Pull request closed without merging**
