### PR TITLE
turn on remote stop_test

### PR DESCRIPTION
**Pull request by QiWang19**
turn on stop_test  --cidfile

Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by mheon** [comment]
LGTM

**Comment by vrothberg** [comment]
Removed and re-added the lgtm label in hope to waken the bot.

**Pull request merged**
