### PR TITLE
Reveal magic, parallel system-testing and system-testing simplification

### PR DESCRIPTION
**Pull request by cevich**
*  Previously, several magic strings were in place to affect cirrus-ci
    operations.  Two were buried within scripts.  One to optionally
    execute system-tests within a PR. Another to avoid re-building
    cache-images upon every merge.
    
    Move these magic strings out into the open, buy locating their
    logic up-front in the ``.cirrus.yml`` file.  This improves
    readability and reduces surprise/astonishment at runtime.

*   Previously it was required to call the verify, unit, and integration
    scripts in order to build/install dependencies, and libpod.  This
    wastes time during the (optional) system-testing, since the
    actual unit/integration testing is also happening in parallel.
    
    Consolidate only the distribution-specific build steps into the
    system-testing script.  This way, only the required steps are performed
    in their respective (parallel) tasks.

### CODE REVIEW

**Comment by cevich** [comment]
***DO NOT MERGE***: There is still a bug in cirrus, I am in contact with their engineering and working on a fix.  They're typically really fast with these things, expect resolution today / early next week.

**Comment by rhatdan** [comment]
PASSES all test.
LGTM

**Comment by cevich** [comment]
@rhatdan thanks for taking a look.  There are some not-so-obvious systemic bugs I need to work out.  Hence the **WIP** and **DO NOT MERGE**.  There's no better way to beat on the CI system than from w/in a PR,  so there's a bunch of duct-tape in here temporarily.  I'll strip all that out when the code is more solid (it's almost there).

**Comment by cevich** [comment]
***Update***: Cirrus bug has been fixed, this PR is ready to go, PTAL.   (Assuming happy tests)

**Comment by cevich** [comment]
Okay, this is working as designed:  Having the magic words in the description caused this run to happen: https://cirrus-ci.com/task/5163575452631040  <-- Failed due to missing system tests (we know this).

**Comment by cevich** [comment]
Removed magic string, rebased and ``--force`` pushed: No system tests run :smile:

**Comment by edsantiago** [comment]
LGTM too

**Comment by umohnani8** [comment]
LGTM

**Pull request merged**
