### PR TITLE
apiv2: Image filtering and fixup docs

### PR DESCRIPTION
**Pull request by marusak**

### CODE REVIEW

**Comment by jwhonce** [comment]
LGTM

**Comment by marusak** [comment]
Not all tests are green - is this issue with these changes and is it blocking on me?

**Comment by TomSweeneyRedHat** [comment]
@marusak I don't believe the issue lies within your changes.  I think it's just the CI not behaving as it should.  I've just restarted the failing test, it looked to be a network hiccup.

**Pull request merged**
