### PR TITLE
Fix the double replySendFile()

### PR DESCRIPTION
**Pull request by haraldh**

### CODE REVIEW

**Comment by giuseppe** [comment]
/ok-to-test
/approve

LGTM

**Comment by mheon** [comment]
Needs a rebase to fix tests

**Comment by haraldh** [comment]
Rebased

**Comment by mheon** [comment]
@cevich What's release doing here? Can we merge with it red?

**Comment by cevich** [comment]
> @cevich What's release doing here? Can we merge with it red?

Release runs for PRs to validate that the workflow is functioning and (on the off-chance) some third-party needs to check/validate a fix in a PR prior to merging.  Happy to change this behavior if desired.

Yes, merging when it's red is probably mostly safe.   I looked through the past runs for this PR, but the only "red release" I found was marked with some odd "Canceled by user" error message - I've never seen that one before.  Seems to be green now though.

**Comment by mheon** [comment]
I think Prow is down.

**Comment by mheon** [comment]
CI is confirmed down

**Comment by mheon** [comment]
CI should be back
/retest

**Pull request merged**
