### PR TITLE
tutorial: add ostree dependency

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
bot, retest this please

**Comment by vrothberg** [comment]
LGTM, but the F28 Cloud test sneezed

**Comment by mheon** [comment]
bot, retest this please

**Comment by mheon** [comment]
@giuseppe I think you need the runc from #1887 to fix the tests

**Comment by baude** [comment]
@giuseppe  rebase and should be good

**Comment by giuseppe** [comment]
rebased, tests are happy now

**Pull request merged**
