### PR TITLE
Switch all references to image.ContainerConfig to image.Config

### PR DESCRIPTION
**Pull request by rhatdan**
This will more closely match what Docker is doing.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes: https://github.com/containers/libpod/issues/2017

**Comment by rhatdan** [comment]
@baude PTAL

**Comment by rhatdan** [comment]
Nope will fix.

**Comment by rhatdan** [comment]
@cevich The version in the cirrus.yml file seems to be old.  We need golang 1.11 to make validate work correctly.

**Comment by baude** [comment]
@rhatdan this is not for @cevich , it's for me and the origin team.  At last check they didn't have a 1.11 image we could test against.  I'll engage again today.

**Comment by baude** [comment]
@rhatdan revert the cmd/podman/rmi.go file and it will pass ... nothing is going to change quickly here.

**Comment by baude** [comment]
rebase and fix tests and should be good to go

**Comment by rhatdan** [comment]
@baude @mheon @umohnani8 @giuseppe @vrothberg @TomSweeneyRedHat PTAL
All Green.

**Comment by mheon** [comment]
Sure, LGTM. One more and we can merge.

**Comment by TomSweeneyRedHat** [comment]
And all happy green test buttons.

**Comment by vrothberg** [comment]
/lgtm

@mheon, we should mention this in the release notes in case some users relied on the `ContainerConfig` key.

**Pull request merged**
