### PR TITLE
Add create and pull commands

### PR DESCRIPTION
**Pull request by jwhonce**
* Rename id_ to ident, make non-PEP8'ers happier
* Fix bug where port was required on local connections
* Improve error messages for exceptions

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
Looks like it expects the ffjson command to be present?

**Comment by mheon** [comment]
@jwhonce Fix should have landed in master, try rebasing

**Comment by jwhonce** [comment]
flake: varlink.error.VarlinkError: {'parameters': {'reason': 'unable to load cgroup at /libpod_parent/libpod-dda34eb5b1e54eced95cdcd35e13ee379084c5cee47dea12b47032a96248cb0e: cgroups: cgroup mountpoint does not exist'}, 'error': 'io.podman.ErrorOccurred'}

**Comment by mheon** [comment]
Restarted travis

**Comment by jwhonce** [comment]
bot, retest this please

**Comment by jwhonce** [comment]
bot, retest this please

**Comment by jwhonce** [comment]
bot, retest this please

**Comment by jwhonce** [comment]
bot, retest this please

**Comment by jwhonce** [comment]
bot, retest this please

**Comment by jwhonce** [comment]
bot, retest this please

**Comment by mheon** [comment]
LGTM
@baude @rhatdan PTAL

**Comment by rhatdan** [comment]
LGTM
@rh-atomic-bot r+

**Pull request closed without merging**
