### PR TITLE
Set Pod hostname as Pod name

### PR DESCRIPTION
**Pull request by chenzhiwei**
Fixes https://github.com/containers/libpod/issues/3732

Signed-off-by: Chen Zhiwei <zhiweik@gmail.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
bot, add author to whitelist

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM, remote tests are unhappy, but I don't think it's related.

**Comment by haircommander** [comment]
LGTM
though i'd say this is a partial fix (we should eventually allow users to configure the hostbame, as a kubernetes pod, separate from name), this is a good start. Thanks @chenzhiwei

**Comment by chenzhiwei** [comment]
@haircommander Yes, the other part of fix should consider the hostNetwork and hostname in Pod Spec, but this will be a little complex.

**Pull request merged**
