### PR TITLE
WIP: fix podman pod rm -a race

### LINKED ISSUE #2733: test-race: podman pod rm -a doesn't remove a running container
/kind bug

**Description**

Test occasionally in CI fails, when running as a user (rootless testing).  

**Steps to reproduce the issue:**

1. Re-run tests until it fails :frowning_face: 

**Describe the results you received:**

``Error: pod 15d...74f contains containers and cannot be removed: container already exists``

**Describe the results you expected:**

Test consistently passes

**Additional information you deem important (e.g. issue happens only occasionally):**

Code is: ``test/e2e/pod_rm_test.go`` line 97

**Output of `podman version`:**

Happening on master, ``v1.1.2-269-gb83d0572``

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Two examples:

* https://cirrus-ci.com/build/6328612444700672
* https://cirrus-ci.com/task/5367713881915392

### PR DESCRIPTION
**Pull request by cevich**
fixes #2733

### CODE REVIEW

**Comment by mheon** [comment]
Wait why is all of cirrus.yml gone? Is this WIP?

**Comment by cevich** [comment]
@mheon lol...because I'm cheating:  Look at the commit title: ``DO NOT MERGE: FOCUSED TESTING``.  It's temporary.

I know which cirrus task and script reproduces the problem, so it's MUCH faster if I remove everything else.  There's probably a more elegant way to do this, but I know this way works :grinning:

**Comment by mheon** [comment]
@cevich Can we tag these [WIP] in the title? It makes sure the mergebot doesn't cause accidents

**Comment by cevich** [comment]
@mheon oh ya, absolutely.  Good idea.

**Comment by cevich** [comment]
Latest example: https://cirrus-ci.com/task/5826816450232320

**Comment by cevich** [comment]
Closing in favor of proper fix: #2706

**Pull request closed without merging**
