### PR TITLE
Update c/image to v4.0.0 + Buildah to 1.11.3

### PR DESCRIPTION
**Pull request by mtrmac**
<s>**Do not merge:** This is to invoke CI on both Buildah and Podman to gain some confidence with this code. Includes UNMERGED <s>containers/image#724 = containers/image#721 + containers/image#723</s> https://github.com/containers/buildah/pull/1891 .</s>

Note: made using `go get github.com/containers/image@v4.0.0+incompatible` so that import paths don't have to updated, and because using the proper `github.com/containers/image/v4@v4.0.0` rejects the `go.mod` of c/image it should declare itself to be a /v4.

This is clearly a bug in c/image, though it’s somewhat tempting to call it a feature if we are going to keep increasing the major versions at the pace we’ve been recently.

### CODE REVIEW

**Comment by mtrmac** [comment]
> Note: made using `go get github.com/containers/image@v4.0.0+incompatible` so that import paths don't have to updated, and because using the proper `github.com/containers/image/v4@v4.0.0` rejects the `go.mod` of c/image it should declare itself to be a /v4.

Hum, that didn’t work out, `proxy.golang.org` (unlike the language itself!) doesn’t like that:
```
not found: github.com/containers/image@v4.0.0+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required
```

**Comment by mtrmac** [comment]
Let’s try with `go mod replace` just to see what the CI does, but that’s _absolutely unsupportable_.

I suppose we’ll have to do Go major versions properly in c/image, keep updating all callers, and _that_ will, in turn, increase the urgency of reviewing the c/image API to minimize major version bumps.

**Comment by mtrmac** [comment]
(For the record, `go get …@commit` notices that buildah uses `@v.3.0.2+incompatible`, that the two are different and therefore conflict, and silently “solves” that by keeping downgrading buildah until it finds a version that does not contain a `go.mod` at all.)

**Comment by mtrmac** [comment]
@vrothberg The tests here do show actual failures:

```
 "reason": "unable to save \"docker.io/library/alpine:latest\": Error copying image to the remote destination: Error creating an updated image manifest: Error preparing updated manifest: unsupported media type for compression: \"application/vnd.docker.image.rootfs.diff.tar.gzip\""
```

**Comment by mtrmac** [comment]
Retrying with containers/image#721 + https://github.com/containers/buildah/pull/1891 , to use Go module major versions properly. “Fun”:
```
go mod edit -replace github.com/containers/image/v4=github.com/mtrmac/image/v4@go-mod-major
go get github.com/containers/image/v4@v4.0.0
go mod edit -replace github.com/containers/buildah=github.com/mtrmac/buildah@c-image-4
```

**Comment by vrothberg** [comment]
Once merged, this PR will fix https://github.com/containers/libpod/issues/2013.

**Comment by vrothberg** [comment]
> @vrothberg The tests here do show actual failures:
> 
> ```
>  "reason": "unable to save \"docker.io/library/alpine:latest\": Error copying image to the remote destination: Error creating an updated image manifest: Error preparing updated manifest: unsupported media type for compression: \"application/vnd.docker.image.rootfs.diff.tar.gzip\""
> ```

Tracked it down. Preparing a fix now.

**Comment by cevich** [comment]
FWIW: The scattering of login/logout failures could be flakes (I did not look super closely).  I vaguely recall seeing those on PRs/master testing before.  The other failures seem legitimate (again, didn't look closely) since they're related to the changes being made here.  @baude what's your opinion?

**Comment by mtrmac** [comment]
Testing the combined containers/image#724 now.

**Comment by mtrmac** [comment]
More failures:
```
[+0522s] [It] podman with images with no layers
[+0522s]   /var/tmp/go/src/github.com/containers/libpod/test/e2e/images_test.go:323
[+0522s] Running: /usr/bin/podman --root /tmp/podman_test374753381/crio --runroot /tmp/podman_test374753381/crio-run --runtime /usr/bin/runc --conmon /usr/libexec/podman/conmon --cni-config-dir /etc/cni/net.d --cgroup-manager cgroupfs --tmpdir /tmp/podman_test374753381 --events-backend file --storage-driver=vfs build --layers=true -t foo --file /tmp/podman_test374753381/Dockerfile /tmp/podman_test374753381
[+0522s] STEP 1: FROM scratch
[+0522s] STEP 2: LABEL org.opencontainers.image.authors="<somefolks@example.org>"
[+0522s] Error: error committing container for step {Env:[ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:label Args:[org.opencontainers.image.authors <somefolks@example.org>] Flags:[] Attrs:map[] Message:LABEL org.opencontainers.image.authors "<somefolks@example.org>" Original:LABEL org.opencontainers.image.authors="<somefolks@example.org>"}: error copying layers and metadata for container "f25b62cbb83b260ce5621ed7f5a3e12a368e696d50b43db28204c7ff14996a88": Error committing the finished image: error parsing manifest: unsupported docker v2s2 media type: ""
```

**Comment by lsm5** [comment]
> ```
> [+0522s] Running: /usr/bin/podman --root /tmp/podman_test374753381/crio --runroot /tmp/podman_test374753381/crio-run --runtime /usr/bin/runc --conmon /usr/libexec/podman/conmon --cni-config-dir /etc/cni/net.d --cgroup-manager cgroupfs --tmpdir /tmp/podman_test374753381 --events-backend file --storage-driver=vfs build --layers=true -t foo --file /tmp/podman_test374753381/Dockerfile /tmp/podman_test374753381
> ```

Just checking if it's actually finding conmon binary at `/usr/libexec/podman/conmon`. If it's using conmon rpm or deb, it's most likely at `/usr/bin/conmon`.

**Comment by vrothberg** [comment]
> More failures:
> 
> ```
> [+0522s] [It] podman with images with no layers
> [+0522s]   /var/tmp/go/src/github.com/containers/libpod/test/e2e/images_test.go:323
> [+0522s] Running: /usr/bin/podman --root /tmp/podman_test374753381/crio --runroot /tmp/podman_test374753381/crio-run --runtime /usr/bin/runc --conmon /usr/libexec/podman/conmon --cni-config-dir /etc/cni/net.d --cgroup-manager cgroupfs --tmpdir /tmp/podman_test374753381 --events-backend file --storage-driver=vfs build --layers=true -t foo --file /tmp/podman_test374753381/Dockerfile /tmp/podman_test374753381
> [+0522s] STEP 1: FROM scratch
> [+0522s] STEP 2: LABEL org.opencontainers.image.authors="<somefolks@example.org>"
> [+0522s] Error: error committing container for step {Env:[ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:label Args:[org.opencontainers.image.authors <somefolks@example.org>] Flags:[] Attrs:map[] Message:LABEL org.opencontainers.image.authors "<somefolks@example.org>" Original:LABEL org.opencontainers.image.authors="<somefolks@example.org>"}: error copying layers and metadata for container "f25b62cbb83b260ce5621ed7f5a3e12a368e696d50b43db28204c7ff14996a88": Error committing the finished image: error parsing manifest: unsupported docker v2s2 media type: ""
> ```

@mtrmac @nalind @rhatdan ... I'm not entirely sure how to fix this one. It seems wrong to generate a layer without a media/mime type. I guess we have no other choice than supporting that to not break backwards compat but it certainly seems odd. Do you know if an empty media type is OCI conform?

**Comment by mtrmac** [comment]
I can’t see how the empty type could have happened from an initial look at the relevant Buildah code; I’ll need to find the exact code path before having any opinion.

**Comment by nalind** [comment]
Based on the context applied to the error, it looks like `storageImage.Commit()` calls `manifest.GuessMIMEType()` to get the manifest type to pass to `manifest.FromBlob()`, and it's getting back an empty value.

The length check on the empty `layers` list fails at https://github.com/containers/image/blob/master/manifest/manifest.go#L135 since our manifest won't have any layers in it, and `GuessMIMEType()` is returning an empty value, then the decode attempt at https://github.com/containers/image/blob/master/manifest/manifest.go#L142 must be failing, too.

**Comment by mtrmac** [comment]
> Based on the context applied to the error, it looks like `storageImageDestination.Commit()` calls `manifest.GuessMIMEType()` to get the manifest type to pass to `manifest.FromBlob()`, and it's getting back an empty value.

Great diagnosis, yes.

> The length check on the empty `layers` list fails at https://github.com/containers/image/blob/master/manifest/manifest.go#L135 since our manifest won't have any layers in it, and `GuessMIMEType()` is returning an empty value, then the decode attempt at https://github.com/containers/image/blob/master/manifest/manifest.go#L142 must be failing, too.

Tiny correction: That decode does succeed, but it is used to differentiate between OCI indices and v2s2 manifests; i.e. the end result is that zero-layer OCI manifests are detected as v2s2.

**Comment by mtrmac** [comment]
Now includes https://github.com/containers/image/pull/725.

**Comment by mtrmac** [comment]
> > ```
> > [+0522s] Error: error committing container for step {Env:[ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:label Args:[org.opencontainers.image.authors <somefolks@example.org>] Flags:[] Attrs:map[] Message:LABEL org.opencontainers.image.authors "<somefolks@example.org>" Original:LABEL org.opencontainers.image.authors="<somefolks@example.org>"}: error copying layers and metadata for container "f25b62cbb83b260ce5621ed7f5a3e12a368e696d50b43db28204c7ff14996a88": Error committing the finished image: error parsing manifest: unsupported docker v2s2 media type: ""
> > ```
> 
> @mtrmac @nalind @rhatdan ... I'm not entirely sure how to fix this one. It seems wrong to generate a layer without a media/mime type. I guess we have no other choice than supporting that to not break backwards compat but it certainly seems odd.

This is really a separate conversation: the failing manifest is
```go
manifest.Schema2{
  SchemaVersion:2,
  MediaType:"",
  ConfigDescriptor:manifest.Schema2Descriptor{MediaType:"application/vnd.oci.image.config.v1+json", Size:476, Digest:"sha256:d7179e9747291d2a1d46395fceacbf4a54c33f7d127308c3a3cbc89c7a3e788f", URLs:[]string(nil)},
  LayersDescriptors:[]manifest.Schema2Descriptor{}
}
```
i.e. the underlying cause is, as @nalind found, that we are treating an OCI manifest as a v2s2; the immediate failure is that the code is verifying the MIME type of the _manifest_ (and, btw, not checking the MIME type of the config descriptor).

It’s not quite clear to me why a unified `SupportedSchema2MediaType` which accepts _all kinds_ of v2s2 MIME types, regardless of context, is ever the right check to use — OTOH, it did find this inconsistency, and it is too lenient rather than too strict, so we can clean that up at our, hypothetical, leisure.

**Comment by mtrmac** [comment]
TEST_REMOTE_CLIENT:true image:fedora-30-libpod:
```
[+0271s] Trying to pull registry.fedoraproject.org/fedora-minimal...
[+0271s] Getting image source signatures
[+0272s] Copying blob sha256:fbeae81c958c2fd568c90f6c996eb51a54a616c98037af4e58c68af9719d2125
[+0277s] Copying config sha256:53dcc6ef21e6ef9a67009cca2a3750cf13dd7a113d08c335207c73f22a6e7a5f
[+0277s] Writing manifest to image destination
[+0277s] Storing signatures
[+0279s]   Error processing tar file(io: read/write on closed pipe): 
[+0279s] --- FAIL: TestImage_New (36.27s)
[+0279s]     image_test.go:152: 
[+0279s]         	Error Trace:	image_test.go:152
[+0279s]         	Error:      	Received unexpected error:
[+0279s]         	            	Error processing tar file(io: read/write on closed pipe): 
[+0279s]         	            	error adding layer with blob "sha256:fbeae81c958c2fd568c90f6c996eb51a54a616c98037af4e58c68af9719d2125"
[+0279s]         	            	github.com/containers/libpod/vendor/github.com/containers/image/v4/storage.(*storageImageDestination).Commit
[+0279s]         	            		/var/tmp/go/src/github.com/containers/libpod/vendor/github.com/containers/image/v4/storage/storage_image.go:691
```
This is `reexec.Command("storage-untar", …).Wait()` failing with `io.ErrClosedPipe` — maybe the input `decompressedArchive` is failing with that error, not sure.

**Comment by mtrmac** [comment]
The other failures don’t look _obviously_ related:
- (remote) “podman failed to start with --rm should delete the container”, no error reported trying to remove anything
- Error: error configuring network namespace for container …: running [/usr/sbin/iptables -t filter -N CNI-FORWARD --wait]: exit status 1: iptables: Chain already exists.
- “podman pod rm empty pod”: ENOENT on `/sys/fs/cgroup/blkio/machine.slice`.
- “podman port multiple ports”: Error: cannot listen on the TCP port: listen tcp4 :5000: bind: address already in use

**Comment by rhatdan** [comment]
The others might be race conditions.  @nalind what do you think of the storage one?

**Comment by mtrmac** [comment]
/retest

let’s see what changes.

**Comment by nalind** [comment]
If #4127 forgot to add a `TestMain()` that initializes reexec (like the one in `libpod/image/image_test.go`) to a place where it was needed, we might see this sort of thing, but we've seen the affected test pass for other PRs since that was merged, so it could be a transient failure.

**Comment by mtrmac** [comment]
All green now, although that hides repeated failures:
```
[Fail] Podman start [It] podman failed to start with --rm should delete the container 
```
in 2 of the tests runs I’ve been watching, it failed once in one and twice in the other. Worth fixing, I guess — but that’s not for _this_ PR.

**Comment by mtrmac** [comment]
Updated to use released c/image v4.0.1, still requires UNMERGED https://github.com/containers/buildah/pull/1891 .

**Comment by mtrmac** [comment]
> This is really a separate conversation… so we can clean that up at our, hypothetical, leisure.

https://github.com/containers/image/issues/728

**Comment by vrothberg** [comment]
> All green now, although that hides repeated failures:
> 
> ```
> [Fail] Podman start [It] podman failed to start with --rm should delete the container 
> ```
> 
> in 2 of the tests runs I’ve been watching, it failed once in one and twice in the other. Worth fixing, I guess — but that’s not for _this_ PR.

That's a known flake in the CI that @baude is currently chasing.

**Comment by vrothberg** [comment]
@mtrmac, can you rename the commit so we can merge? Looks like we're good to go.

**Comment by mtrmac** [comment]
Updated to use released Buildah 1.11.3.

I can't figure out the reason for go.mod tracking
```
            github.com/containers/image v3.0.2+incompatible // indirect
```
(`go mod graph` lists it as a direct dependency of libpod, but `go list -json -m all` lists it as an indirect dependency), but at least looking at the `vendor` subdirectory, it doesn't seem to be actually used in the built binaries.

**Comment by TomSweeneyRedHat** [comment]
@mheon and @baude, it's OK to merge this now, but I will need to update the 'podman build' man page in a separate PR before we do the next release of Podman.

**Comment by mheon** [comment]
LGTM.

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Pull request merged**
