### PR TITLE
[1.4.2-stable] Vendor in c/storage fix on double-locking mounts list

### PR DESCRIPTION
**Pull request by umohnani8**
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
@mheon @nalind @rhatdan PTAL

**Comment by mheon** [comment]
LGTM.

@nalind @rhatdan Can we get a tagged release of c/storage with this patch included for the new Podman 1.6 release on Friday?

**Comment by umohnani8** [comment]
@mheon @baude tests are green, can we get this. Will we need to tag a new v1.4.2-stable or can @lsm5 create and tag a new build from this branch?

**Comment by lsm5** [comment]
> @mheon @baude tests are green, can we get this. Will we need to tag a new v1.4.2-stable or can @lsm5 create and tag a new build from this branch?

tag would help to keep things cleaner of course, but not totally necessary.

**Comment by mheon** [comment]
I'd prefer not to make an additional tag in the 1.4.2-stable branch if this is not hitting 8.1

**Comment by umohnani8** [comment]
@mheon what do you suggest then? should we create a specific ocp tag like  v1.4.2-stable-ocp? or should we just create a build from the v1.4.2-stable branch?

**Comment by lsm5** [comment]
> @mheon what do you suggest then? should we create a specific ocp tag like v1.4.2-stable-ocp? or should we just create a build from the v1.4.2-stable branch?

i can just build from here. Btw, I have a PR coming in that I'd like to get merged on this branch as well.

**Comment by mheon** [comment]
@lsm5 I think they want to pin to 1.4.2-stable to keep rough parity with 8.1, so I think this patch on top of the head of the 1.4.2 branch is what you want

**Comment by mheon** [comment]
Oh, this is targetted against 1.4.2-stable already. Alright, we can merge and build from there.

**Pull request merged**
