### PR TITLE
tutorials: describe how to use podman in updates-testing

### PR DESCRIPTION
**Pull request by ktdreyer**
@vorburger was asking in https://github.com/containers/libpod/issues/1973#issuecomment-454989393 about Bodhi. Add some explanation about this to our documentation.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
bot, add author to whitelist

**Comment by TomSweeneyRedHat** [comment]
@ktdreyer can you sign your commit please?   `git commit --amend -s` then repush?

**Comment by rhatdan** [comment]
Forcing merge rather then dealing with ci/prow/images.

**Pull request merged**
