### PR TITLE
system tests: run test: reenable and fix

### PR DESCRIPTION
**Pull request by edsantiago**
Test had incorrectly been disabled for all podman; it
should've been disabled only for podman-remote. Fixed
that, and fixed the problem that was causing failures:
podman-remote is gobbling up stdin (#4095), so no
tests were actually being run at all, or only one.
Fixed by redirecting input on the run_podman invocation.
Added, as backup, a confirmation mechanism to ensure
that all expected tests are being run.

Test remains disabled for podman-remote due to #4096

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
/approve
LGTM

**Comment by edsantiago** [comment]
UPDATE: force-pushed a better idea - instead of blanket-disabling this test for podman-remote, enable it, but disable the output check. This at least lets us check exit status of podman-remote.

**Comment by edsantiago** [comment]
tests green

**Comment by mheon** [comment]
@baude @vrothberg @TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
