### PR TITLE
Store and print PID of conmon

### PR DESCRIPTION
**Pull request by mheon**
Can be useful for debugging, and I think we might need it internally (to verify liveliness of conmon process).

Also, address a bug where we weren't clearing PID after the container died.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by mheon** [comment]
Our flakes are IP overlap issues in `checkpoint restore`. We checkpoint a container with IP `a.b.c.d` and restore it, expected it to (again) be allocated `a.b.c.d`, but it's been allocated to another container as part of a parallel test. Not sure what the solution is here... Maybe we can run the checkpoint tests with a separate CNI network?

**Comment by mheon** [comment]
Latest flake: `[+0549s] useradd: cannot create directory /home/test123` out of a `podman exec` test. That's a `useradd` inside the container, for reference. Not sure what's going on here.

**Comment by mheon** [comment]
Next flake: `podman port` nginx issues I tried to solve in another PR.

**Comment by rhatdan** [comment]
/lgtm
What happens if the container does not exit cleanly?  Would their be an issue?  
I will still merge.

**Comment by mheon** [comment]
Handling that is the next step - I want to ping the Conmon PID before we go
waiting for things like exit files, for example, to make sure it's still
there.

**Pull request merged**
