### PR TITLE
Enable pod stats with short ID

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: haircommander <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
@baude PTAL :)

**Comment by mheon** [comment]
Can you add a test for stats by name too? Otherwise LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.

**Comment by mheon** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
