### PR TITLE
Containers sharing a netns should share resolv/hosts

### PR DESCRIPTION
**Pull request by mheon**
When sharing a network namespace, containers should also share resolv.conf and /etc/hosts in case a container process made changes to either (for example, if I set up a VPN client in container A and join container B to its network namespace, I expect container B to use the DNS servers from A to ensure it can see everything on the VPN).

Resolves: #1546

### CODE REVIEW

**Comment by mheon** [comment]
Still needs an integration test - working on that now

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, tests aren't hip.  Would like a head nod from @giuseppe or @rhatdan

**Comment by mheon** [comment]
Added a test

**Comment by rhatdan** [comment]
Do you know if this is what Docker does?  What happens if container A modifies the /etc/resolv.conf while running, will Container B see the modification?

**Comment by mheon** [comment]
@rhatdan Yeah, confirmed that when I wrote the patch. My original version just took the version we used when we created the container, but Docker reflects runtime modifications.

**Comment by mheon** [comment]
Tests finally green
@rhatdan @baude @TomSweeneyRedHat @vrothberg PTAL

**Pull request merged**
