### PR TITLE
DO NOT MERGE: update cirrus cache images

### PR DESCRIPTION
**Pull request by edsantiago**
Follow directions in contrib/cirrus/README.md to add 'jq'.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
@edsantiago We're merging #2991 (you said you wanted to try it) b/c brent reminded me, it fixes a flake which is affecting all PRs.  However, I can still help get this PR in next week (independent of #2561) if you like.  Despite being somewhat of a pain, the manual steps aren't difficult, just require lots of waiting (the gcloud compute images create command is VERY slow).

**Comment by mheon** [comment]
@edsantiago Are you handling this one with @cevich in the other Cirrus PR for updating/testing images?

**Comment by edsantiago** [comment]
@mheon this PR is almost definitely going to be closed; I'm hoping that #2561 takes care of it. I wanted to leave it open as a backup; but if open PRs are causing noise, please feel free to close.

**Comment by mheon** [comment]
Naw, just doing status checks on open PRs to see what I can get merged - feel free to keep open

**Pull request closed without merging**
