### PR TITLE
secrets: fix fips-mode with user namespaces

### PR DESCRIPTION
**Pull request by giuseppe**
When using a user namespace, we create the mount point under
`mountPrefix` so that the uid != 0 can access that directory.

Change the addFIPSModeSecret code to honor that, and also ensure we
are creating the directories with the right ownership.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
LGTM, thanks @giuseppe !

**Comment by rhatdan** [comment]
LGTM

**Comment by giuseppe** [comment]
still seeing an issue:

/hold

**Comment by giuseppe** [comment]
SELinux is blocking access to the `/run/secrets/system-fips` file:

```
$ sealert -l f5e1d3f6-1197-44e6-8dc0-1d261c0f68fc
/usr/bin/sealert:32: DeprecationWarning: Importing dbus.glib to use the GLib main loop with dbus-python is deprecated.
Instead, use this sequence:

    from dbus.mainloop.glib import DBusGMainLoop

    DBusGMainLoop(set_as_default=True)

  import dbus.glib
SELinux is preventing ls from read access on the directory secrets.

*****  Plugin catchall (100. confidence) suggests   **************************

If you believe that ls should be allowed read access on the secrets directory by default.
Then you should report this as a bug.
You can generate a local policy module to allow this access.
Do
allow this access for now by executing:
# ausearch -c 'ls' --raw | audit2allow -M my-ls
# semodule -X 300 -i my-ls.pp


Additional Information:
Source Context                system_u:system_r:container_t:s0:c62,c656
Target Context                unconfined_u:object_r:container_var_run_t:s0
Target Objects                secrets [ dir ]
Source                        ls
Source Path                   ls
Port                          <Unknown>
Host                          helium
Source RPM Packages           
Target RPM Packages           
Policy RPM                    selinux-policy-3.14.2-49.fc29.noarch
Selinux Enabled               True
Policy Type                   targeted
Enforcing Mode                Permissive
Host Name                     helium
Platform                      Linux helium 4.20.10-200.fc29.x86_64 #1 SMP Fri
                              Feb 15 18:33:14 UTC 2019 x86_64 x86_64
Alert Count                   4
First Seen                    2019-02-27 22:15:11 CET
Last Seen                     2019-02-27 22:17:54 CET
Local ID                      f5e1d3f6-1197-44e6-8dc0-1d261c0f68fc

Raw Audit Messages
type=AVC msg=audit(1551302274.135:3177): avc:  denied  { read } for  pid=20720 comm="ls" name="secrets" dev="tmpfs" ino=4620198 scontext=system_u:system_r:container_t:s0:c62,c656 tcontext=unconfined_u:object_r:container_var_run_t:s0 tclass=dir permissive=1


Hash: ls,container_t,container_var_run_t,dir,read
```

**Comment by rhatdan** [comment]
The secrets directory was never relabeled when it was created.

Should have a 
label.Relabel(secretsdir, mount_label, fals)
Call in there.

**Comment by giuseppe** [comment]
> Should have a
> label.Relabel(secretsdir, mount_label, fals)
> Call in there.

Thanks for the hint, it fixes the issue I've seen

/hold cancel

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
