### PR TITLE
sign: some fixes

### PR DESCRIPTION
**Pull request by giuseppe**
a couple of fixes that were noticed during the review but we decided to fix as follow ups

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
LGTM

**Comment by rhatdan** [comment]
@QiWang19 @baude @TomSweeneyRedHat @mheon @vrothberg

**Comment by mheon** [comment]
LGTM, but I mirror Valentin's thoughts - that strings.Replace is the stuff of nightmares

**Comment by mheon** [comment]
I assume we want this in 1.0 so I'm going to merge
/approve
/lgtm

**Pull request merged**
