### PR TITLE
[2.0] move go module to v2

### PR DESCRIPTION
**Pull request by vrothberg**
With the advent of Podman 2.0.0 we crossed the magical barrier of go
modules. While we were able to continue importing all packages inside
of the project, the project could not be vendored anymore from the
outside.

Move the go module to new major version and change all imports to
github.com/containers/libpod/v2. The renaming of the imports
was done via gomove [1].

[1] https://github.com/KSubedi/gomove

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by vrothberg** [comment]
A /lgtm is missing

**Pull request merged**
