### PR TITLE
Cirrus: Update Ubuntu 18 to 20

### PR DESCRIPTION
**Pull request by cevich**
Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
@baude PTAL, I'm not sure how to read the bindings test failure.  Other items are either skipped or  :shamrock: (I guess?)

Let me know if you want me to poke Ubuntu additionally (somehow).  The VM build was basically uneventful and boring, even `Dockerfile.ubuntu` built cleanly.  So I had to sneak in a small fix to `hack/get_ci_vm.sh` to :hot_pepper: the PR up a bit :grin:

**Comment by cevich** [comment]
(rebased)

**Comment by cevich** [comment]
(rebase)

**Comment by baude** [comment]
lgtm

**Pull request merged**
