### PR TITLE
AppArmor refactorings and improvements

### PR DESCRIPTION
**Pull request by vrothberg**
A bunch of changes and improvements (buildtime and runtime) for pkg/apparmor.

### CODE REVIEW

**Comment by vrothberg** [comment]
Once that's in, I'll make CRI-O use this package (Cc @mrunalp).

**Comment by vrothberg** [comment]
@baude @mheon @rhatdan PTAL, the changes make a simple `podman run --rm alpine ls` around 200ms faster on my faster, which is surprising but very welcome ;-)

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
The tests are green, but only because papr isn't running. That threw me off for a bit.

Code LGTM though.
Let's see if homu is in an accomodating mood.

@rh-atomic-bot r+

**Comment by mheon** [comment]
...Did we lose the mergebot after moving to containers/libpod?

**Comment by vrothberg** [comment]
bot, test pull request

**Comment by vrothberg** [comment]
bot, add author to whitelist

**Comment by mheon** [comment]
bot, add author to whitelist

**Comment by mheon** [comment]
bot, retest this please

**Comment by vrothberg** [comment]
bot, test pull request

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green test buttons.

**Comment by vrothberg** [comment]
bot, test pull request

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by mheon** [comment]
@rh-atomic-bot r+

**Comment by mheon** [comment]
This is going to fail, given that papr tests are failing for now... Going to force it to proceed to the next PR
@rh-atomic-bot force

**Comment by mheon** [comment]
Alright, that didn't really work. Oh well.

Once #1267 merges we can start retrying failed PRs.

**Comment by mheon** [comment]
@rh-atomic-bot retry

**Comment by mheon** [comment]
@rh-atomic-bot r-

**Comment by mheon** [comment]
My attempts to force testing of another PR are probably just making things even slower, so I'm going to stop messing with this.

**Comment by mheon** [comment]
@rh-atomic-bot retry

**Comment by vrothberg** [comment]
@rh-atomic-bot retry

**Comment by vrothberg** [comment]
bot, retest this please

**Comment by vrothberg** [comment]
@rh-atomic-bot retry

**Comment by mheon** [comment]
Hm. I think I successfully unmarked this for merge with r- but it didn't actually stop the tests and start the next PR which was my intent.

**Pull request closed without merging**
