### PR TITLE
docs: Add CI section and links

### PR DESCRIPTION
**Pull request by cevich**
Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
@TomSweeneyRedHat this is a very rough first-draft.  Please only look through your left eye, and a pair of sunglasses :smile:   Let me know if there's any general suggestions of content I should add/drop/change.

**Comment by rhatdan** [comment]
@cevich Any update on this?

**Comment by cevich** [comment]
@TomSweeneyRedHat @rhatdan sorry, maybe my fault.  I was waiting for some initial feedback here, I'm not sure if I should give more details or other details or maybe less?

**Comment by TomSweeneyRedHat** [comment]
LGTM
FWIW, I think you hit the mark on the more/less info.  If we find we need more based on feedback, we can add it in.  Nice addition and sorry for missing the initial PR ping.

**Pull request merged**
