### PR TITLE
System tests: support for crun on f31/rawhide

### PR DESCRIPTION
**Pull request by edsantiago**
crun emits wildly different error messages than runc in
two cases:

    podman run ... /no/such/path   (enoent)
    podman run ... /etc            (trying to exec a directory)

Deal with it by getting the runtime from 'podman info' and,
if crun, changing what we expect.

There may be more tweaks needed to get system tests working
with crun, but right now podman rawhide is too broken to
have any hope of finding them all.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
Change LGTM

**Comment by rhatdan** [comment]
LGTM
FYI @giuseppe

**Comment by giuseppe** [comment]
LGTM

**Comment by rhatdan** [comment]
/lgtm
/hold
Feel free to hold cancel once tests pass.

**Pull request merged**
