### PR TITLE
Update containerd/cgroups to 4994991857f9b0ae

### PR DESCRIPTION
**Pull request by mheon**
As the title says

### CODE REVIEW

**Comment by mheon** [comment]
Apparently this managed to break completely-unrelated images tests?

**Comment by mheon** [comment]
Filter before image is broken in master

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but tests aren't hip @mheon, I'm not sure if it's related or not.

**Comment by mheon** [comment]
Rebased, should go green now

**Comment by stevekuznetsov** [comment]
OK, in case this was not clear. Please do not put things into the merge queue until all of your statuses are successful, or the automation just thrashes trying to merge.

/hold

**Comment by mheon** [comment]
Tests green now
/hold cancel

**Pull request merged**
