### PR TITLE
List the long variant of each option before its shorter counterpart

### LINKED ISSUE #2104: Scrub man pages for long vs short option ordering
**kind bug**

**Description**

As fixed and reported in #2097, the podman-create and podman-run man pages list the short variant of an option before the longer variant.  i.e. `**-w, --workdir**=""`.  This is a low level issue to scrub these and the remaining man pages to ensure the odering is long form is listed first.

**Output of `podman version`:**

```
0.12.1
```

### PR DESCRIPTION
**Pull request by debarshiray**
This is the style followed in most of the other man pages.

Signed-off-by: Debarshi Ray <rishi@fedoraproject.org>

Fixes #2104

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @debarshiray 
/approve
LGTM

**Comment by mheon** [comment]
Sure, LGTM

**Pull request merged**
