### PR TITLE
docs: clarify bools in `podman --help`

### PR DESCRIPTION
**Pull request by vrothberg**
* clarify that --syslog and --trace expects arguments
* mention defaults in --help text
* add --trace to docs

### CODE REVIEW

**Comment by rhatdan** [comment]
Should we document --trace or hide it as an option?  Do we want users actually using this?

**Comment by vrothberg** [comment]
> Should we document --trace or hide it as an option? Do we want users actually using this?

No preference. The purist inside of me just wants consistency :^)

**Comment by rhatdan** [comment]
@baude @mheon  WDYT.   I think we should remove documentation for it and hide it.

**Comment by mheon** [comment]
Uhm. Hiding seems appropriate.

**Comment by vrothberg** [comment]
`--trace` is now hidden. @mheon @rhatdan PTAL

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
