### PR TITLE
Codify and document base-image production + Enable testing with Fedora

### PR DESCRIPTION
**Pull request by cevich**
Summary of additions/changes:
* General re-organizing of `.cirrus.yml` for readability.  Moved all env. vars to a single section at the top, added labels/comments.
* Added semi-automation for building non-native GCE *base-images* (e.g. Fedora & Atomic).  Infrequent but complex process, requires human attention for every new distribution release.
* Fully documented the non-native GCE *base-image* production process.
* Converted JSON configuration to YAML for readability, and Implemented `Makefile` to drive image-building processes.  Added simple unit-test to verify `YAML` syntax and `JSON` conversion.
* Updated all the `.cirrus.yml` values for `*_BASE_IMAGE` to GCE images produced using the documented (`Makefile`) process (above).
* Updated scripts function in Fedora Atomic VMs
* Enabled PR testing on Fedora 29

***CIRRUS: REBUILD IMAGES***

### CODE REVIEW

**Comment by cevich** [comment]
Oops, dupe PR.

**Comment by cevich** [comment]
***note to me***:
* FAH 29 fails w/ permission-denied creating ``/go``
* Fedora 29 finds lint in `cmd/podman/rmi.go`

**Comment by cevich** [comment]
@rhatdan Work is on pause for https://github.com/containers/conmon/pull/6 then I'll hop back here (unless someone else wants to take over).  The major task left on this one is getting FAH to play nice with Cirrus's VM bootup script.  I think all that requires is moving `$GOPATH` from `/go` to `/tmp/go`, but there could be other SNAFU's hiding.  The other failures (Ubuntu and Fedora) are trivial typo's to fix IIUC, just a typo.

An option here could be that I split it up into smaller PR's, but then they become dependent on merge-order (which can be annoying).  Only advantage I see there is getting the new (easier to read) organization, and updated documentation.  Making FAH work could be more involved than just changing directories.

**Comment by mheon** [comment]
Sure, LGTM

**Comment by giuseppe** [comment]
I've playedf on Ubuntu with rootless containers, but the runc available there is too old and doesn't work with rootless containers.  Unless we build a custom runc, we should probably just disable rootless tests there

**Comment by cevich** [comment]
> I've playedf on Ubuntu with rootless containers, but the runc available there is too old and doesn't work with rootless containers. Unless we build a custom runc, we should probably just disable rootless tests there

@giuseppe for the Cirrus tests we do build runc (and other deps) from source on all platforms.  However, to save testing-time, it's done when the VM image is produced.  It's possible the images could get out of sync with each other, but I don't think that's an issue here.  In either case, I should probably make that detail available.

**Comment by cevich** [comment]
@baude @mheon Okay I think I've got it this time.  The winning combination is to use the ``*-libpod-0c954a67`` images which have the freshly built runc, and also include Giuseppe's fix.  Fingers-crossed.

**Comment by cevich** [comment]
(adding a jira card to simplify the runc + other deps situation, so we just install the packages at test-time instead of VM image build time)

**Comment by cevich** [comment]
`*sigh*` still seeing rootless tests fail on F29: https://cirrus-ci.com/task/5966156714213376

**Comment by cevich** [comment]
@giuseppe thx again for the help w/ runc.  @baude @mheon PTAL (when you have a moment).  Only change other than rebasing is, I added a big list of env. vars to murder (``unset``) prior to testing. Maybe there's a cleaner way to do this, or it's not necessary.  I'm open to changing/dropping that part if you like.

The major improvements in this PR are:
    * Testing with both Ubuntu and Fedora
    * Documentation
    * Makefile for working with VM images
    * Manual-but-scripted base-image importing into GCE

**Comment by cevich** [comment]
resolved conflict, rebased, --force pushed.

**Comment by cevich** [comment]
bot, retest this please

**Comment by cevich** [comment]
rebased, updated to include ``RUNC_COMMIT`` from #1887, --force pushed.

**Comment by cevich** [comment]
Rebased & --force pushed

**Comment by cevich** [comment]
@mheon @baude all green now.

**Comment by mheon** [comment]
This LGTM, but will defer merge to @baude - he's worked a lot more with our CI than I have

**Comment by cevich** [comment]
@mheon of course, no problem at all.  Though it would be good to take a look at some point.  It's not as complicated as you may think.  Everything below ``.cirrus.yml`` is very linear.  There's even (***gasp***) ``contrib/cirrus/README.md`` documentation :grin:

**Pull request merged**
