### PR TITLE
exposes tcp port only if no proto specified.

### LINKED ISSUE #735: podman exposes udp port on tcp-only image
podman with `--publish-all` exposes udp even if image is tcp-only:
```
# cat >Dockerfile
FROM centos
EXPOSE 8080      ! default is tcp, but you can append '/tcp' if you like; no diff
^D
# img=$(podman build --quiet .)
# cid=$(podman run -d --publish-all $img sleep 60)
# podman port $cid
8080/udp -> 0.0.0.0:35365
8080/tcp -> 0.0.0.0:35365
```
It doesn't seem to be buildah's fault:
```
# podman inspect $img|grep -2 8080
        "ContainerConfig": {
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Cmd": [
```
RPMs:
```
buildah-0.16-1524754276.git83f4830.fc27.x86_64
podman-0.5.2-1525700809.gitfaa8c3e.fc27.x86_64
```

### PR DESCRIPTION
**Pull request by kunalkushwaha**
Also it fix the issue of exposing both tc/udp port even if only one proto specified.

Fixes #735 

Signed-off-by: Kunal Kushwaha <kushwaha_kunal_v7@lab.ntt.co.jp>

### CODE REVIEW

**Comment by rhatdan** [comment]
You need to fix the test.

```
  podman port  -l nginx [It]
  /go/src/github.com/containers/libpod/test/e2e/port_test.go:47

  Expected
      <bool>: false
  to be true

  /go/src/github.com/containers/libpod/test/e2e/port_test.go:57

  Full Stack Trace
  	/go/src/github.com/onsi/gomega/internal/assertion/assertion.go:69 +0x1ed
  github.com/onsi/gomega/internal/assertion.(*Assertion).To(0xc420fa57c0, 0x11eb100, 0x1ac9fb8, 0x0, 0x0, 0x0, 0xc420fa57c0)
  	/go/src/github.com/onsi/gomega/internal/assertion/assertion.go:35 +0xae
  github.com/containers/libpod/test/e2e.glob..func29.5()
  	/go/src/github.com/containers/libpod/test/e2e/port_test.go:57 +0x4b7
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc4200c4720, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/go/src/github.com/containers/libpod/test/e2e/libpod_suite_test.go:83 +0xaa
  testing.tRunner(0xc4204741e0, 0x11517d8)
  	/usr/lib/golang/src/testing/testing.go:777 +0xd0
  created by testing.(*T).Run
  	/usr/lib/golang/src/testing/testing.go:824 +0x2e0
  ```

**Comment by kunalkushwaha** [comment]
Fixed.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by mheon** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
