### PR TITLE
Adds more docker py test

### PR DESCRIPTION
**Pull request by sujil02**
Addes more docker py test
Optimize test to import images from cache
Rename test class and dir for python unittest framework

Signed-off-by: Sujil02 <sushah@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
/approve

**Comment by edsantiago** [comment]
The README.md is pretty seriously wrong. Could you please update it to make it possible for someone to actually try running the tests? For instance:
* Indicate the working directory where someone needs to be cd'ed
* fix PYTHONPATH in all examples, to align with ^^
* add missing `-m unittest` to first example
* change directory and file paths (i.e. add `_test`)
* Indicate why sudo is necessary, or remove it
* indicate which packages need to be dnf-installed (for `ModuleNotFoundError: No module named 'docker'`)

...possibly more. Thanks.

**Comment by TomSweeneyRedHat** [comment]
LGTM, would be nice to get @edsantiago 's concerns addressed in at least a separate PR.  @sujil02 if you can not do so today, please create a new issue.

**Comment by sujil02** [comment]
> The README.md is pretty seriously wrong. Could you please update it to make it possible for someone to actually try running the tests? For instance:
> 
> * Indicate the working directory where someone needs to be cd'ed
> * fix PYTHONPATH in all examples, to align with ^^
> * add missing `-m unittest` to first example
> * change directory and file paths (i.e. add `_test`)
> * Indicate why sudo is necessary, or remove it
> * indicate which packages need to be dnf-installed (for `ModuleNotFoundError: No module named 'docker'`)
> 
> ...possibly more. Thanks.

Thank you @edsantiago I will get in a separate or addressing this.

**Pull request merged**
