### PR TITLE
commandNotFoundHandler: use stderr and exit code 1

### PR DESCRIPTION
**Pull request by vrothberg**
Fixes: #1395
Signed-off-by: Valentin Rothberg <vrothberg@suse.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
And again - CI times out after an exit 0. We need to look into this on Tuesday.

**Comment by mheon** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
Actually I think we should just do 
exit(exitCode)

Since we document in at least podman run that the exit is 125.

**Pull request closed without merging**
