### PR TITLE
Tests for API v2

### PR DESCRIPTION
**Pull request by edsantiago**
Initial framework for testing the version 2 (HTTP) API.
Includes a collection of tests for some of the existing
endpoints. Not all tests are currently passing.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
I'm not terribly happy with the file-descriptor muckery[1]. Suggestions welcome.

 [1] Because subtests are expected to run `podman` or other commands that may emit spurious output, and said output would affect the TAP (`ok/not ok`) stream, I've done some acrobatics to restrict stdout/stderr.

**Comment by stbischof** [comment]
@rhatdan you wrote a LGTM but the /lgtm tag is missing. is this by exident?

**Comment by baude** [comment]
> @rhatdan you wrote a LGTM but the /lgtm tag is missing. is this by exident?

our process generally requires two lgtms.  the second has the leading slash which indicates it is approved to merge.

**Comment by rhatdan** [comment]
@baude Could you give this the aforementioned lgtm

**Pull request merged**
