### PR TITLE
Makefile: update epoch validation commit to v1.0.1

### PR DESCRIPTION
**Pull request by vbatts**
ping @baude

### CODE REVIEW

**Comment by vbatts** [comment]
Well good grief

**Comment by mheon** [comment]
Oh, oops - the release script we use automatically updates the epoch, so it looks like we overwrote this

**Comment by vbatts** [comment]
No worries. Baude had just said it was a slow point in the CI

**Comment by rhatdan** [comment]
No longer needed, so closing.

**Pull request closed without merging**
