### PR TITLE
[WIP] vendor containers/{image,storage}

### PR DESCRIPTION
**Pull request by vrothberg**
Avoid redundantly pulling the same image (or layer).

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
Do not merge this PR, it's used to increase confidence for the changes to storage and image by letting it pass libpod's CI.

**Comment by vrothberg** [comment]
Need to fix up some things in the PR and merge https://github.com/containers/buildah/pull/1400 first to unblock.

**Comment by mheon** [comment]
@vrothberg I'll mark this as WIP then

**Comment by vrothberg** [comment]
bot, retest this please

**Comment by vrothberg** [comment]
Closing in favour of Closing in favour of https://github.com/containers/image/pull/611.

**Pull request closed without merging**
