### PR TITLE
Use newer runc commit in VM images

### PR DESCRIPTION
**Pull request by cevich**

### CODE REVIEW

**Comment by rhatdan** [comment]
Looks like one of the PR says DO NOT MERGE?

**Comment by cevich** [comment]
@rhatdan yeah, @mheon wants to try this newer runc commit on his #1689 then I'll kill the 'DO NOT MERGE' thing here (assuming it fixes the prob. he's having).

**Comment by cevich** [comment]
The newer ubuntu VM image didn't result in any dramatic change in what we were testing.  However, @mheon said re: keep this PR or not, "probably a good idea, considering the old commit is really old? good idea to match it to what fedora is using imo".

**Comment by giuseppe** [comment]
LGTM

**Pull request merged**
