### PR TITLE
container Exists: fix URL

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@baude @mheon @jwhonce PTAL

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
I am not sure what this test failure it. Trying to restart...

**Comment by lsm5** [comment]
@mheon any luck?

**Comment by mheon** [comment]
@cevich @edsantiago @baude Looks like we have an exec failure in the system tests, now - https://cirrus-ci.com/task/4845339475705856

Restarting it here so this can go in

**Comment by edsantiago** [comment]
>Looks like we have an exec failure in the system tests, now

Yeah, it's the same one as always (#5339). It seems less frequent in system tests than in e2e, but still happens.

**Pull request merged**
