### PR TITLE
Fix podman stop --all attempting to stop created ctrs

### LINKED ISSUE #2993: podman stop fails
Seeing this in a recent rawhide (podman-1.3.0-17.dev.gitbf5ffda.fc31.x86_64):

```
$ sudo podman stop --all
Error: can only stop created, running, or stopped containers. 4ce604a830f62a37ad71eca9b43c78cb2d50d96598e14711032c6d238dd522fb in state configured: container state improper
```

If this is caused by my containers being created by a previous podman release, may I suggest that your testsuite needs to cover this case: create a container with an older version, and verify that the tested podman can handle it.

These are pets, so I'm not prepared to shoot them everytime you push a new podman into rawhide...

### PR DESCRIPTION
**Pull request by mheon**
Fixes #2993 

Ignore container state errors when trying to stop all containers. Probably more efficient than trying to filter based on state (less DB lookups, less potential for races)

### CODE REVIEW

**Comment by mheon** [comment]
Hold merge until after lunch, I want to add a test to make sure we don't regress on this

**Comment by mheon** [comment]
Added some tests, and changed existing stop tests to verify results.

**Comment by rhatdan** [comment]
LGTM but tests are not happy.

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.

**Comment by mheon** [comment]
Tests are green aside from our known SELinux failures

**Comment by rhatdan** [comment]
Needs a rebase to get the SELinux fixes.

**Comment by mheon** [comment]
Rebased

**Pull request merged**
