### PR TITLE
container create: os/arch check

### PR DESCRIPTION
**Pull request by vrothberg**
Unless explicitely overridden, check the image's OS and architecture
and throw an errors in case of a mismatch.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
Inspired by a recent blog post from @fatherlinux: http://crunchtools.com/deeply-understanding-the-different-between-portability-compatibility-and-supportability/

We're now throwing a meaningful errors instead of the rather cryptic one trying to access paths on the root fs.

**Comment by vrothberg** [comment]
@giuseppe @mheon @baude PTAL

**Comment by mheon** [comment]
Code LGTM

**Pull request merged**
