### PR TITLE
Allow --ip and --mac to be set when joining a CNI net

### LINKED ISSUE #4500: cannot set a static IP if joining additional CNI networks
```
sudo podman network create --subnet '172.25.0.0/24' mynetwork
sudo podman run -d --rm --name instance0 --network mynetwork --ip 172.25.0.200 image:version
Error: error running container create option: cannot set a static IP if joining additional CNI networks: invalid argument
```

When '--ip 172.25.0.200' is removed, it assigns next available IP from the subnet.

podman version
Version:            1.6.1

### PR DESCRIPTION
**Pull request by mheon**
These only conflict when joining more than one network. We can still set a single CNI network and set a static IP and/or static MAC.

Fixes #4500

### CODE REVIEW

**Comment by mheon** [comment]
I'll add a test after lunch

**Comment by TomSweeneyRedHat** [comment]
LGTM
remote prune test died, I expect unrelated to this change.  I restarted.

**Comment by giuseppe** [comment]
LGTM

**Comment by rhatdan** [comment]
@mheon Reminder on Tests.
Looks like the CI system is hung.

**Comment by mheon** [comment]
Added a test

**Comment by mheon** [comment]
Some test failures are (wierd) flakes, but it seems like `--ip` with `--net $CNINETWORK` is not working. I'm passing the right things into OCICNI, so the problem has to be there.

**Comment by vbohinc** [comment]
This does not work, 

network.RuntimeConfig = map[string]ocicni.RuntimeConfig{
			defaultNetwork: rt,
		}

is always set to the "podman" netconf, so the static allocations do not get applied.

The problem is that defaultNetwork = r.netPlugin.GetDefaultNetworkName() returns "podman" instead of the user provided value.

Ugly hack I'm using to set defaultNetwork:

if len(networks) == 0 {
		defaultNetwork = r.netPlugin.GetDefaultNetworkName()
	} else {
		defaultNetwork = networks[0]
	}

**Comment by mheon** [comment]
Good catch - pushed an updated version that should set that properly

**Comment by mheon** [comment]
It's green.
@vrothberg @baude @TomSweeneyRedHat @rhatdan PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
