### PR TITLE
output of port grouping in ps command added as example

### PR DESCRIPTION
**Pull request by kunalkushwaha**
example added in man page as suggested in review  https://github.com/containers/libpod/pull/2664#pullrequestreview-215007446

Signed-off-by: Kunal Kushwaha <kushwaha_kunal_v7@lab.ntt.co.jp>

### CODE REVIEW

**Comment by vrothberg** [comment]
bot, add author to whitelist

**Comment by vrothberg** [comment]
LGTM, thanks @kunalkushwaha

**Comment by TomSweeneyRedHat** [comment]
LGTM, thanks for circling back on this @kunalkushwaha !

**Comment by TomSweeneyRedHat** [comment]
Ugh, our "old friend" rootless_test failures are back today.  Test failures are not related to this PR.

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
I'm pretty sure test failures are fixed upstream - you might want to rebase?

**Pull request merged**
