### PR TITLE
Cirrus: Collect audit log on success and failure

### PR DESCRIPTION
**Pull request by cevich**
Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
@rhatdan @mheon @baude adding collection of logs is pretty easy: just [cat the file in it's own `script` section](https://console.cloud.google.com/compute/instancesDetail/zones/us-central1-a/instances/cirrus-task-5764209857003520?project=libpod-218412&folder&organizationId) (so it's separated in the WebUI).  Note: It needs to be added in two places, once for success and the other in case of failure.

Question:  For rootless testing and podman-in-podman, also grab ``audit.log`` from the host?

'nother Question:  Assuming I can get `audit.log` working, what else shall I grab while I'm at it?

**Comment by rhatdan** [comment]
Maybe `journal -b`

**Comment by rhatdan** [comment]
Needs a rebase to get the SELinux fixes.

**Comment by cevich** [comment]
@rhatdan good idea, adding 'journalctl -b'.  okay, rebased and --force pushed.

**Comment by cevich** [comment]
Hrmmm, dang, no 'audit.log' on Ubuntu.  Google tells me `kern.log` is the same, so grabbing that.

**Comment by cevich** [comment]
@baude @mheon When you have a moment PTAL.  This collects the journal and audit logs on all platforms, making them available through the Cirrus WebUI (and a google storage bucket), for example [the one from the rootless task on this PR](https://cirrus-ci.com/task/4693419380178944) and [the same thing directly from the storage bucket.](https://storage.cloud.google.com/cirrus-ci-5385732420009984-fcae48/logs/containers/libpod/4693419380178944/audit_log?_ga=2.38663587.-1670000616.1540407237)

**Comment by mheon** [comment]
LGTM
@baude @rhatdan PTAL

**Pull request merged**
