### PR TITLE
Fix golint errors

### PR DESCRIPTION
**Pull request by vrothberg**
I wanted to enable golangci-lint for the `test/` directory (which is currently not checked) and noticed that new errors were introduced to the rest of the code.  I have no idea how that was possible but now the linter is happy again.

@giuseppe @mheon @baude @TomSweeneyRedHat @rhatdan PTAL

### CODE REVIEW

**Comment by vrothberg** [comment]
Note that this PR is _not_ enabling the linter for ./test. Something we can tackle later.

**Comment by mheon** [comment]
LGTM, but gating is angry

**Comment by vrothberg** [comment]
> LGTM, but gating is angry

Should be happy now. Had some whitespaces in the commits :^)

**Comment by mheon** [comment]
Did we turn off branch protection? I have merge permission even though the PR isn't green yet

**Comment by vrothberg** [comment]
> Did we turn off branch protection? I have merge permission even though the PR isn't green yet

I see it too, but  didn't notice before :thinking:

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by vrothberg** [comment]
I assume these are flakes (for the record):

```
[+0925s] [Fail] Podman run with --sig-proxy [It] signals are not forwarded to container with sig-proxy false 
[+0925s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/run_signal_test.go:135
[+0925s] 
[+0925s] [Fail] Podman run with --sig-proxy [It] signals are not forwarded to container with sig-proxy false 
[+0925s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/run_signal_test.go:135
[+0925s] 
[+0925s] [Fail] Podman run with --sig-proxy [It] signals are not forwarded to container with sig-proxy false 
[+0925s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/run_signal_test.go:135
[+0925s] 
[+0925s] [Fail] Podman network [It] podman network rm 
[+0925s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/network_test.go:134
```

**Comment by vrothberg** [comment]
I seem to be unable to restart the flaked test. Maybe someone else can try?

**Comment by vrothberg** [comment]
Seems like an UI issue here. Jobs are running but the UI isn't updating. @cevich is investigating.

**Pull request merged**
