### PR TITLE
papr_prepare: remove double process for starting up .papr.sh

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM, assuming happy tests.

**Comment by mheon** [comment]
@giuseppe Bunch of `Permission denied` errors... Maybe we should be running the script with sh instead of bash?

**Comment by giuseppe** [comment]
a few fixes for the CI so that we don't need the double process to hide a SELinux labelling problem

**Pull request merged**
