### PR TITLE
build: move initialization after SetXdgDirs

### PR DESCRIPTION
**Pull request by giuseppe**
otherwise it triggers the config file initialization from vendor/github.com/containers/common/pkg/config before the init() in main.go can set correctly XDG_RUNTIME_DIR and DBUS_SESSION_BUS_ADDRESS when they are missing.

commit 96de762eedd1470dfbe73cf424eea848589268d7 introduced the regression.

Closes: https://github.com/containers/libpod/issues/5314

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
@edsantiago this solved the issue for me

**Comment by edsantiago** [comment]
Thanks, @giuseppe ! It does fix that particular problem, but introduces a new one:
```console
$ podman build -t build_test
Error: unknown shorthand flag: 't' in -t
```

**Comment by giuseppe** [comment]
> Thanks, @giuseppe ! It does fix that particular problem, but introduces a new one:

thanks for trying it out.  Hopefully I've addressed them both now

**Comment by edsantiago** [comment]
Yes, your 1e94c2964d517ca4840ff5fa7ae1fd76753642de appears to be passing all my tests; will report back once they finish. Thank you!

**Comment by TomSweeneyRedHat** [comment]
LGTM, nice fix Giuseppe!

**Comment by edsantiago** [comment]
Flakes. Restarted.

**Comment by edsantiago** [comment]
LGTM. Thanks again, @giuseppe

**Pull request merged**
