### PR TITLE
WIP: Add Udica test task

### LINKED ISSUE #3555: podman CI should test udica functionality
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
Udica is a tool for generating SELinux security profiles for containers, based on inspecting container. 
It looks like in podman version 1.4+ json structure after inspecting container has changed, which made udica useless.  
I fixed udica today:
https://github.com/containers/udica/commit/47c4c08c94dbcf82e4e96f303429133727b6ae02

It would be great to have udica tests in CI of podman to make sure to inform udica developers (me) that you changed JSON structure for inspecting container. 

The initial test could be really easy. e.g:
```
$ git clone https://github.com/containers/udica
# cd udica && sudo python3 ./setup.py install`
# podman run -v /home:/home:ro -v /var/spool:/var/spool:rw -p 21:21 -it fedora bash
# podman inspect -l > container.json
# udica -j container.json  my_container
```

I can help with udica test, if somebody help me with podman CI. 

Thanks,
Lukas.

### PR DESCRIPTION
**Pull request by cevich**
***Depends on: #3534***

Fixes #3555

### CODE REVIEW

**Comment by rhatdan** [comment]
@wrabcak PTAL

**Comment by cevich** [comment]
@wrabcak Okay this seems to be working at least at a basic level

https://cirrus-ci.com/task/5384833553924096?command=udica_test

Though I'd prefer to [use your`runtest.sh`](https://src.fedoraproject.org/rpms/udica/blob/master/f/tests/sanity/runtest.sh) but need some guidance on setting up the VM.

Since `inspect` is going to be a bit of a moving target (in this repo), I think it makes sense to only run this task on our master branch, after PRs merge.  Also since we don't wait failure to block libpod release, we'll need to wire up some kind of out-of-band notifications.

There are many ways to do this, but I'm not sure what would be convenient for your workflows.  Off-hand, I'm thinking we use a github bot to open containers/udica issues (with some maximum limit, like 3). The bot can post a link back to the containers/libpod CI run that failed, allowing for easier debugging.

What are your thoughts?

**Comment by rhatdan** [comment]
Why not block the release?  I would think we want PR's to continue to test against this.  Only issue I would see is if a new version of udica came out and was broken.

**Comment by wrabcak** [comment]
> @wrabcak Okay this seems to be working at least at a basic level
> 
> https://cirrus-ci.com/task/5384833553924096?command=udica_test
> 

It looks like this test is passing. 

> Though I'd prefer to [use your`runtest.sh`](https://src.fedoraproject.org/rpms/udica/blob/master/f/tests/sanity/runtest.sh) but need some guidance on setting up the VM.
> 

Agree, I would use both tests. (It's quick so it should be ok). To setting VM you need to do:
# boot fresh VM
# clone udica from container/udica repo
# dnf install beakerlib
# Download test: https://src.fedoraproject.org/rpms/udica/blob/master/f/tests/sanity/runtest.sh
# ./runtest.sh

That should be enough. Please let me know if there are some issues. 

> Since `inspect` is going to be a bit of a moving target (in this repo), I think it makes sense to only run this task on our master branch, after PRs merge. Also since we don't wait failure to block libpod release, we'll need to wire up some kind of out-of-band notifications.
> 

It's up to you guys, I would like to see this also on PR CI. 

> There are many ways to do this, but I'm not sure what would be convenient for your workflows. Off-hand, I'm thinking we use a github bot to open containers/udica issues (with some maximum limit, like 3). The bot can post a link back to the containers/libpod CI run that failed, allowing for easier debugging.
> 

I like idea with bot which reports the fails from CI to container/udica issues. Then I can prepare patches for udica.

> What are your thoughts?

Thank you for help!
Lukas.

**Comment by cevich** [comment]
> Why not block the release?

@mheon suggested this, and I agree because effectively udica depends on libpod, but we want to test with that relationship reversed.  Doing this and blocking release necessarily complicates needed libpod JSON changes.  Either:

* udica must remain forever format-tollerant (forward and backward)

or

* a complicated dance is needed in libpod CI:
   1. Branch + modify udica code/tests to use new format
   2. Open libpod PR to use new format
   3. Remember to also change libpod CI to use udica from new branch.
   4. Coordinate any other in-flight PRs also changing the JSON

or

* We make udica a git-module of libpod, and run testing locked to a specific commit instead of "upstream" (which changes).  Then someone remembers to maintain the pointer to the correct udica commit in libpod :confounded: 

---

Thinking about this more...maybe doing this testing in libpod isn't such a good idea.  It may be better to simply have a periodic job run from udica's repo, continuously checking the latest libpod.  This keeps the dependency relationship the "correct" way around, and also eliminates the need for notifications - the test failures are already associated with their related repository.

@wrabcak WTYT?  Unfortunately the Cirrus-CI documentation isn't great, but [it appears like we could set up a webhook to udica](https://cirrus-ci.org/api/#webhooks) when a libpod PR is merged into master.  That could then trigger a new CI run in udica to ensure the JSON format remains compatible.  Maybe this could be a better option?

**Comment by cevich** [comment]
Note: I could help wire up Cirrus-CI in the udica repo as well, if required.  But I'm not certain how to trigger builds using [Cirrus-CI GraphQL schema](https://github.com/cirruslabs/cirrus-ci-web/blob/master/schema.graphql)

**Comment by rhatdan** [comment]
My concern about non blocking is that this test will be ignored as noise.

**Comment by cevich** [comment]
> My concern about non blocking is that this test will be ignored as noise.

Yes I agree, some kind of reliable notifications would be a must.

@wrabcak how about my webhook idea, running testing downstream in udica (triggered by merges into libpod master)?  That would make notification slightly easier as well.

**Comment by wrabcak** [comment]
> > My concern about non blocking is that this test will be ignored as noise.
> 
> Yes I agree, some kind of reliable notifications would be a must.
> 
> @wrabcak how about my webhook idea, running testing downstream in udica (triggered by merges into libpod master)? That would make notification slightly easier as well.

For me, the best solution is to have it in CI in libpod, to really make sure that udica will work with released podman. If this is not possible, we can agree on your idea. 

Could you please help me with setting the CI in udica repo? 
Thanks,
Lukas.

**Comment by cevich** [comment]
> CI in libpod, to really make sure that udica will work with released podman.

As in code we cannot have circular dependencies with relationships in CI or testing.  So unless udica is _part_of_ libpod (I don't think this is a good idea), we must decide on a relationship.  My thinking is that udica's useful work _requires_ podman, not the other way around.  Do you see differently?

Assuming not, I'm imagining three CI feedback-loops in udica:
1. The existing one, part of modularity, before package-release, if Udica w/ podman is broken in some way.  This seems to be standing in for your integration testing (seems fine for now).
2. A new one (does not exist?) for running unit testing of Udica for PR's and again after merge.  I can help set this up if there is not one already.
3. A new one for Udica master, started automatically every time a libpod PR merges into master.  Upon failure, an issue is opened up in Udica repo (unless more than N automatic issues already exist).  We can also easily do IRC notification as well.

> Could you please help me with setting the CI in udica repo?

Yes, happy to.

Another, possibly easier option instead of "2" and "3" above, is if (somehow) we can trigger your existing modularity-based testing to run but inform it to use a pre-release/test build of podman (from upstream master).

@lsm5 do you know if such a thing is possible?  i.e. triggering modularity and standard test via REST API or webhook callback with an additional input variable?

**Comment by rhatdan** [comment]
needs rebase.

**Comment by rhatdan** [comment]
@cevich @wrabcak Couldn't we just have a simple tests for shipping versions of udica to block changes to podman that make it fail, inside of the podman CI.

That we know if we are modifying the `podman inspect` code in such a way that would break shipping udica.
At which point we would need to get patches into udica to support the new format, or fix the inspect code.

**Comment by cevich** [comment]
> Couldn't we just have a simple tests for shipping versions of udica to block changes to podman that make it fail, inside of the podman CI.

It's desirable to keep the relationships in CI matching user-reality, where Udica is dependent on podman (and cri-o and buildah and ...).  This was (is) the source of much pain we experience(d) with conmon CI (testing downstream in upstream).  I really think we need to perform Udica testing, in Udica.  That also supports integration testing for PRs over there, with the relationship the correct way around.

The "noticing" part is still something I want to think about some more.  We need a solution that supports tight-feedback loops, clean, and w/o any circular or backward-facing dependencies.

**Comment by wrabcak** [comment]
I agree with @rhatdan , but also @cevich  comments are correct. Udica is dependent on podman so, CI tests should be on udica side... 

@cevich, For udica we have basic CI testing only if udica is working (we have inspection files templates generated manually from podman inspect). If you can help me to enable your CI in udica repo (ideally send some initial CI testing via PR), I would be happy about it.

**Comment by cevich** [comment]
@rhatdan what I'm concerned about with that approach (the one in this PR) is it creates "spooky effects at a distance".  Udica already has comprehensive late-stage testing vs. _released_ podman, right before releasing it's RPMs.  Therefor there is a significant window for a breaking-change in podman to cause last minute scrambling to update and push out yet another release of Udica because something got missed.

If instead, we notify Udica developers when a podman-master update breaks things, they'll have a heads up to fix it.  We back that up with CI in Udica running against podman-master, to confirm all PRs pass current/upstream podman.  This keeps the relationships the right-way around and brings a feedback-loop closer to Udica changes.

**Comment by cevich** [comment]
> @wrabcak ...If you can help me to enable your CI in udica repo (ideally send some initial CI testing via PR), I would be happy about it.

Yes, this is my intention.  I think only notifying isn't good enough, we need both it and CI testing happening in Udica PRs vs podman master.

@wrabcak question:  Am I correct in believing Udica itself and it's testing is ***not*** sensitive to the podman version being used?  i.e. Udica does not adjust behavior for different versions of podman.  Correct?

**Comment by cevich** [comment]
Opened https://github.com/containers/udica/pull/37

**Comment by wrabcak** [comment]
> > @wrabcak ...If you can help me to enable your CI in udica repo (ideally send some initial CI testing via PR), I would be happy about it.
> 
> Yes, this is my intention. I think only notifying isn't good enough, we need both it and CI testing happening in Udica PRs vs podman master.
> 
> @wrabcak question: Am I correct in believing Udica itself and it's testing is _**not**_ sensitive to the podman version being used? i.e. Udica does not adjust behavior for different versions of podman. Correct?
No, I'm trying to be synced with the latest version of podman in Fedora 30 and Rawhide.

**Comment by cevich** [comment]
ok thx.

**Pull request closed without merging**
