### PR TITLE
[skip ci] Cirrus: Container for tracking image use

### PR DESCRIPTION
**Pull request by cevich**
Once built, this container can be utilized by automation to help keep
track of VM images.  All parameters are passed in via env. vars.

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
@baude @mheon this PR only adds the container definition, PR #2214 actually runs it.  I built the container in my registry for testing with that PR (it works): ``quay.io/cevich/imgts``.  PTAL, and when appropriate, could this be setup to build as ``quay.io/libpod/imgts:latest`` following the same pattern as for the ``gate`` imgage?

**Comment by baude** [comment]
LGTM

**Pull request merged**
