### PR TITLE
Add a test for 'podman play kube' to prevent regression

### PR DESCRIPTION
**Pull request by mheon**
As the title says.

### CODE REVIEW

**Comment by haircommander** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM 
Once you fix your testing/building issues.

**Comment by mheon** [comment]
The generated YAML works on my machine, so I'm not sure what's going on here. Probably issues writing the output of 'generate kube' to file.

I might just add a `--file` to `generate kube` to specify an output file for simplicity.

**Comment by mheon** [comment]
Added `--filename, -f` flag to `generate kube`. Let's see if the tests start passing.

**Comment by mheon** [comment]
@rhatdan @haircommander @giuseppe @baude Anyone want to hit this with an LGTM? Tests went green

**Pull request merged**
