### PR TITLE
Add Jhon Honce (@jwhonce on github) to OWNERS

### PR DESCRIPTION
**Pull request by mheon**
@jwhonce is one of the core contributors to remote client work, so let's make sure he has the ability to merge things.

### CODE REVIEW

**Comment by mheon** [comment]
@rhatdan @giuseppe @vrothberg @baude PTAL

**Comment by giuseppe** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
With great power comes great responsibility @jwhonce !

**Comment by baude** [comment]
@mheon how about a rebase and we make this right?

**Comment by mheon** [comment]
Wait, this didn't merge? Oops.

**Comment by mheon** [comment]
Rebased & force-pushed

**Pull request merged**
