### PR TITLE
CI: add API v2 tests

### PR DESCRIPTION
**Pull request by edsantiago**
API v2 has been quiet for a few days, and the test script is
actually passing. Let's take advantage of this opportunity
to get them running in CI.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
so far changes LGTM are there any additional logs which would be helpful to collect for these tests (see `logcollector.sh`)?

**Comment by edsantiago** [comment]
Thanks for the reminder. There's one log file, full results of all HTTP requests, but I haven't yet had a need to look at it even in daily on-my-laptop testing. It's long, and I don't think it's worth preserving because the tests themselves provide a good dump on error.

**Comment by cevich** [comment]
okay SGTM.

**Comment by edsantiago** [comment]
@cevich the failing job is f30, and it's [failing](https://api.cirrus-ci.com/v1/task/6687830147596288/logs/apiv2_test.log) because the system is cgroups v1, so my test expects to see `runc`, but it's seeing `crun` instead. Is this intentional, using `crun` on f30?

**Comment by TomSweeneyRedHat** [comment]
LGTM and seems to be passing everything but the problematic remote_client test

**Comment by edsantiago** [comment]
@TomSweeneyRedHat that's actually a weird and real failure; see my question to @cevich above (basically, f30 system using crun, so my test is confused, as am I)

**Comment by cevich** [comment]
> Is this intentional, using crun on f30?

Yes this was intentional, unless that's bad, then...errr...it was a mistake :grin:

(Meaning: I'm open to hearing arguments to change it)

**Comment by cevich** [comment]
Okay, decision is: F30 should be runc only.  Working on a PR for that (IIUC, should be small/simple change).

**Comment by edsantiago** [comment]
Yay - with Chris's #5342, this is now passing.

**Pull request merged**
