### PR TITLE
spec: simplify handling of  --ulimit host

### PR DESCRIPTION
**Pull request by giuseppe**
it seems enough to not specify any ulimit block to maintain the host
limits.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
I'm always in favor of simplification... LGTM, but your tests are red

**Comment by rhatdan** [comment]
LGTM

**Comment by giuseppe** [comment]
> @giuseppe, the only diff I found with the hosts limit is the soft limit for open files (host=1024, ctr=524288=hard limit). The behaviour is the same prior to this change.

that happens because we bump immediately the limit in main_local.go.

**Pull request merged**
