### PR TITLE
podman: fix events help string

### PR DESCRIPTION
**Pull request by giuseppe**
make it uppercase as all the other ones.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
and of course, since this is a one char fix to a string, all the tests are unhappy....

**Comment by mheon** [comment]
Filter before image is broken on master

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
Holding until rootless goes green

**Pull request merged**
