### PR TITLE
Vendor buildah, imagebuilder, docker/docker, fsouza and more

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Vendors in Buidah, imagebuilder, fsouza/docker-client, docker/docker and
a few more related.  Of particular note, changes to the TweakCapabilities()
function from docker/docker along with the parse.IDMappingOptions() function
from Buildah.  Please pay particular attention to the related changes in
the call from libpod to those functions during the review.

Passes baseline tests.

### CODE REVIEW

**Comment by vrothberg** [comment]
One dependency seems to be missing: 
```
?? vendor/golang.org/x/sys/windows/registry/
```

**Comment by TomSweeneyRedHat** [comment]
repushed, we'll see how long the tests last this time....

**Comment by mheon** [comment]
@TomSweeneyRedHat I think you pushed master to your branch

**Comment by mheon** [comment]
Github automerges when there are 0 changes

**Pull request closed without merging**
