### PR TITLE
Log libseccomp package version

### PR DESCRIPTION
**Pull request by cevich**
***Depends on: #4836***

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
CC: @nalind

**Comment by baude** [comment]
lgtm

**Comment by cevich** [comment]
Added commit that uses newly built iamges

**Comment by cevich** [comment]
Waiting for new packages https://bugzilla.redhat.com/show_bug.cgi?id=1765314

**Comment by cevich** [comment]
Oops, need to wait for new libseccomp packages.

**Comment by cevich** [comment]
(still waiting on packages)

**Comment by rhatdan** [comment]
@cevich Can we close this one?

**Comment by cevich** [comment]
> Can we close this one?

Naw, it's minor but handy to have the package version logged in every run.  I see we've got new libseccomp packages with the bug-fix.  Trying again with those...

**Comment by cevich** [comment]
sigh...waiting on me to fix the base-images...

**Comment by cevich** [comment]
@baude @mheon PTAL, this one is good-to-go.

**Comment by mheon** [comment]
LGTM

**Pull request merged**
