### PR TITLE
Make "stopped" a valid state that maps to "exited"

### LINKED ISSUE #2526: podman  ps --format status=stopped is invalid
/kind bug

**Description**

These appear to be the supported libpod/podman states:
https://github.com/containers/libpod/blob/993b3a17c58826365136f49d7760f8ac88e320b2/pkg/adapter/pods_remote.go#L246-L257

However, the stopped state is marked as invalid when trying to query it. Even the manual page suggests it should be a supported option.

```
$ man podman-ps | grep Status
       │.Status     │ Status of container                      │
       │status   │ [Status] Container's status, e.g running, stopped                   │
```

**Steps to reproduce the issue:**

1. `$ podman ps -f "status=stopped"`

**Describe the results you received:**

```
$ podman ps -f "status=stopped"
invalid filter: stopped is not a valid status
```

**Describe the results you expected:**

```
$ podman ps -f "status=stopped"
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES
```

**Additional information you deem important (e.g. issue happens only occasionally):**

This was originally brought up in this PR: https://github.com/containers/libpod/pull/2524

**Output of `podman version`:**

```
$ podman version
Version:       1.0.0
Go Version:    go1.11.4
Git Commit:    "49780a1cf10d572edc4e1ea3b8a8429ce391d47d"
Built:         Mon Jan 14 15:38:17 2019
OS/Arch:       linux/amd64
```

**Output of `podman info --debug`:**

```
$ podman info --debug
debug:
  compiler: gc
  git commit: '"49780a1cf10d572edc4e1ea3b8a8429ce391d47d"'
  go version: go1.11.4
  podman version: 1.0.0
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-1.0.0-1.git82e8011.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 49780a1cf10d572edc4e1ea3b8a8429ce391d47d'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 22500847616
  MemTotal: 33543561216
  OCIRuntime:
    package: runc-1.0.0-68.dev.git6635b4f.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: ef9132178ccc3d2775d4fb51f1e431f30cac1398-dirty
      spec: 1.0.1-dev
  SwapFree: 5368705024
  SwapTotal: 5368705024
  arch: amd64
  cpus: 8
  hostname: workstation.localhost
  kernel: 4.19.24-1.lts.fc29.x86_64
  os: linux
  rootless: true
  uptime: 5h 55m 16.81s (Approximately 0.24 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/user/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/user/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
  ImageStore:
    number: 3
  RunRoot: /run/user/1000
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical (laptop).

### PR DESCRIPTION
**Pull request by mheon**
Fixes #2526

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@giuseppe @vrothberg @TomSweeneyRedHat @baude @jwhonce PTAL

**Comment by edsantiago** [comment]
LGTM but... in testing... I was thrown off by:
```
$ podman ps -f state=stopped
[no results]
```
(because, of course, I hadn't specitied `-a`).

What if `-f` automatically turned on `c.All`?

**Comment by mheon** [comment]
I think that's a pretty good idea - @baude @rhatdan Agree?

**Comment by rhatdan** [comment]
Yes but need to document it.

**Pull request merged**
