### PR TITLE
Attempt to turn on integration tests

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@baude @giuseppe @mheon @TomSweeneyRedHat @vrothberg @QiWang19 @jwhonce PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by baude** [comment]
@rhatdan should delete the temporary test(s) with this pr

**Comment by rhatdan** [comment]
Replaces: https://github.com/containers/libpod/pull/6342

**Pull request merged**
