### PR TITLE
Revert "Switch to golangci-lint"

### PR DESCRIPTION
**Pull request by baude**
Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by baude** [comment]
if this works, merge it and hope we're back to just working ...

**Comment by vrothberg** [comment]
LGTM but please explain why it’s needed to revert

**Comment by rhatdan** [comment]
I am attempting to make golangci-lint  work in https://github.com/containers/libpod/pull/2867

**Comment by baude** [comment]
> LGTM but please explain why it’s needed to revert

because it broke us on prow and our CI is dead

**Comment by mheon** [comment]
Why did we merge this when it wasn't passing CI?

**Comment by mheon** [comment]
Regardless, I'm with Brent here. If we don't have a fix soon I'm going to
merge the revert so we can unblock PRs

**Comment by baude** [comment]
because chris asked dan to ... i alerted chris to the problem immediately but he went on to PTO

**Comment by baude** [comment]
the core issue is the linter has to be setup for the tests we do in openshift containers too. that was not done and i think we should revert until chris is back from pto.

**Comment by mheon** [comment]
@baude Based on Steve's comments elsewhere - do we want to update the Dockerfiles for ci/prow/lint instead of this? It seems like that's our last blocker on this.

I'm still open to merging this is we need to unblock stuff ASAP.

**Comment by giuseppe** [comment]
let's merge.  It is blocking all our PRs.  We can reintroduce golangci-lint when it works.

/lgtm

**Pull request merged**
