### PR TITLE
test: cleanup CNI network used by the tests

### PR DESCRIPTION
**Pull request by giuseppe**
issue introduced with:

https://github.com/containers/libpod/pull/1871

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
LGTM

**Comment by mheon** [comment]
bot, retest this please

**Comment by baude** [comment]
bot, retest this please

**Comment by giuseppe** [comment]
@mheon @rhatdan @baude finally tests are passing

**Pull request merged**
