### PR TITLE
Support host networking with podma play kube

### PR DESCRIPTION
**Pull request by rhatdan**
If the hostNetwork boolean is set in the kubernetes yaml file,
set the networking to host.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes: https://github.com/containers/libpod/issues/4432

**Comment by mheon** [comment]
NACK, this won't set the infra container network properly. Working on a fix right now.

**Comment by mheon** [comment]
The work in #5241 will allow this to work

**Comment by mheon** [comment]
Basically will have to pass `WithPodHostNetwork()` when making the pod

**Pull request closed without merging**
