### PR TITLE
Bump to v1.6.6

### PR DESCRIPTION
**Pull request by mheon**
Backport accumulated patches from the RPM spec (excluding Buildah and Containers/storage patches) and bump to v1.6.6

### CODE REVIEW

**Comment by baude** [comment]
LGTM

**Comment by mheon** [comment]
Dropped one commit that was directly modifying vendor/ - we'll have to retain the patch for that

**Comment by mheon** [comment]
`Failed to start: Invalid value for field 'resource.disks[0].initializeParams.sourceImage': 'https://www.googleapis.com/compute/v1/projects/libpod-218412/global/images/fedora-30-libpod-5642998972416000'. The referenced image resource cannot be found.`

@cevich Welp. 1.6 branch CI appears go have exploded again.

**Comment by cevich** [comment]
> @cevich Welp. 1.6 branch CI appears go have exploded again.

Ahh crud.  This is most likely a symptom of the 'meta' task not running frequently enough, and the VM images being pruned.  FYI- previously I checked into [setting up cron jobs to run branch-testing periodically](https://cirrus-ci.org/guide/writing-tasks/#cron-builds), to keep the images alive.  Unfortunately, I was only able to add one for a single branch.  Not sure if this was a bug or what.

Anyhoo, what's needed to fix this [(rebuild the VM images)](https://github.com/containers/libpod/blob/v1.6/contrib/cirrus/README.md#test_build_cache_images_task-task) is normally fairly pain-free, I'll open a PR in a sec...

**Comment by cevich** [comment]
...#6245

**Comment by rhatdan** [comment]
@mheon Do we still need this?

**Comment by mheon** [comment]
Probably not - we can't do anything to this branch until CI is sorted

**Pull request closed without merging**
