### PR TITLE
No podman container ps command exists

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @giuseppe @vrothberg @mheon @baude @edsantiago PTAL

**Comment by mheon** [comment]
Sure, LGTM

**Comment by edsantiago** [comment]
Huh? Did you mean to remove `ls` instead?
```
$ ./bin/podman container ps
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES

$ ./bin/podman container ls
[usage message]
```

**Comment by TomSweeneyRedHat** [comment]
What @edsantiago, although my bits on my vm might be behind.   The change itself looks fine if the command doesn't exist.

**Comment by rhatdan** [comment]
`podman container ps` may work, but it is not supported.  There is no equivalent to `docker container ps`
so we should remove it until we can fix our CLI.
Main reason I want to get rid of it, is lack of support and it is reported by the test podman-commands.sh

**Comment by edsantiago** [comment]
I'm less confused now: at the time I commented, I wasn't aware of @baude's #2480.

Can we hold off on this PR until #2480 is merged? In particular, if 2480 is merged as it is right now, then you should amend this PR to **also remove `ls`**. The new post-2480 command for listing containers is simply `list`, with no `ls` or `ps` aliases.

**Comment by rhatdan** [comment]
Well no because ls is valid.  We are trying to find a way to show list and ls for podman container and not ps.
Lets just merge this and if we have to fix a different man page we can do it in a different PR>

**Comment by edsantiago** [comment]
What I'm trying to say, is, `ls` is not valid. That is: `./bin/podman container ls` does not exist, at least not on current master 4a109a71996e99c9a95b639bbbee1c5e30450c97

**Comment by rhatdan** [comment]
Well it should exists and that is the bug.

**Comment by mheon** [comment]
LGTM, restarting failed test

**Comment by baude** [comment]
ill hit it with a lgtm assuming the rest will pass?

**Pull request merged**
