### PR TITLE
skip test for blkio.weight when kernel does not support it

### PR DESCRIPTION
**Pull request by baude**
Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
Sure, LGTM

**Comment by TomSweeneyRedHat** [comment]
Change LGTM, but gofmt isn't happy with rmi.go.

**Comment by rhatdan** [comment]
Can we change the validate code to only run with golang 1.11, this is what we did with buildah and it eliminated all of this noise.

```
diff --git a/Makefile b/Makefile
index bc70bff2..6cd8f53a 100644
--- a/Makefile
+++ b/Makefile
@@ -5,8 +5,8 @@ BINDIR := $(PREFIX)/bin
 BASHINSTALLDIR=${PREFIX}/share/bash-completion/completions
 BUILDFLAGS := -tags "$(AUTOTAGS) $(TAGS)"
 GO := go
-GO111 := 1.11
-GOVERSION := $(findstring $(GO111),$(shell go version))
+GO110 := 1.10
+GOVERSION := $(findstring $(GO110),$(shell go version))
 
 
 GIT_COMMIT := $(if $(shell git rev-parse --short HEAD),$(shell git rev-parse --short HEAD),$(error "git failed"))
@@ -53,7 +53,7 @@ deps: gopath
 validate:
        # Run gofmt only on version 1.11
        
-ifeq ($(GO111),$(GOVERSION))
+ifneq ($(GO110),$(GOVERSION))
        @./tests/validate/gofmt.sh
 endif
        @./tests/validate/whitespace.sh
```

**Comment by baude** [comment]
> Can we change the validate code to only run with golang 1.11, this is what we did with buildah and it eliminated all of this noise.
> 
> ```
> diff --git a/Makefile b/Makefile
> index bc70bff2..6cd8f53a 100644
> --- a/Makefile
> +++ b/Makefile
> @@ -5,8 +5,8 @@ BINDIR := $(PREFIX)/bin
>  BASHINSTALLDIR=${PREFIX}/share/bash-completion/completions
>  BUILDFLAGS := -tags "$(AUTOTAGS) $(TAGS)"
>  GO := go
> -GO111 := 1.11
> -GOVERSION := $(findstring $(GO111),$(shell go version))
> +GO110 := 1.10
> +GOVERSION := $(findstring $(GO110),$(shell go version))
>  
>  
>  GIT_COMMIT := $(if $(shell git rev-parse --short HEAD),$(shell git rev-parse --short HEAD),$(error "git failed"))
> @@ -53,7 +53,7 @@ deps: gopath
>  validate:
>         # Run gofmt only on version 1.11
>         
> -ifeq ($(GO111),$(GOVERSION))
> +ifneq ($(GO110),$(GOVERSION))
>         @./tests/validate/gofmt.sh
>  endif
>         @./tests/validate/whitespace.sh
> ```

Yes, I know exactly what to do and we are in the middle of doing it; as I said, we need the origin group to merge a PR I have to make this correct.

**Comment by cevich** [comment]
/approve

and

/lgtm

**Pull request merged**
