### PR TITLE
auth pkg support emtpy argument & enable login test

### PR DESCRIPTION
**Pull request by QiWang19**
import auth pkg to support empty login argument and enable login_logout tests
import c/common auth pkg PR https://github.com/containers/common/pull/135
Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by QiWang19** [comment]
@rhatdan PTAL

**Comment by vrothberg** [comment]
We need to squash the commits. Each commit must compile (and ideally pass tests). The reasoning behind is to avoid expensive noise when bisecting issues.

**Comment by rhatdan** [comment]
LGTM
Squash commits and then we can merge.

**Comment by TomSweeneyRedHat** [comment]
LGTM once squished

**Comment by QiWang19** [comment]
@rhatdan @TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Pull request merged**
