### PR TITLE
add godoc link to readme

### PR DESCRIPTION
**Pull request by fiws**

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @fiws You need to sign your PRs

git commit -a --amend -s
git push --force

**Comment by fiws** [comment]
> Thanks @fiws You need to sign your PRs
> 
> git commit -a --amend -s
> git push --force

Sorry. It should be signed now

**Comment by rhatdan** [comment]
LGTM
@vrothberg @giuseppe @mheon @TomSweeneyRedHat @QiWang19 @ashley-cui PTAL

**Comment by rhatdan** [comment]
/lgtm
/hold
Feel free to hold cancel, once tests pass.

**Comment by mheon** [comment]
```
[+0045s] Error: unable to save "registry.fedoraproject.org/fedora-minimal:latest": Error copying image to the remote destination: Error writing blob: Digest did not match, expected sha256:f4119231eb4d87dfc14c23d0f0bbf7cdb88946d21a2c44374923b79dec7638ef, got sha256:8ae3b674494bd7b6d62b8ff72071a6a4d1b2294ea254919bc84b8742f9a30667
```

From the tests while uncaching.
Did someone push a new fedora-minimal, causing us to break?

**Comment by mheon** [comment]
Test failures are from the Fedora registries having issues

**Comment by TomSweeneyRedHat** [comment]
LGTM, nice change and thanks @fiws 
Now if we can get the test system to be hip.

**Comment by rhatdan** [comment]
Forcing merge, the failures have nothing to do with this PR.

**Comment by rhatdan** [comment]
bot, add author to whitelist

**Comment by fiws** [comment]
> Forcing merge, the failures have nothing to do with this PR.

Alright.. Do I have to do anything now?

**Comment by TomSweeneyRedHat** [comment]
@fiws you shouldn't need to do anything further for this PR (fingers crossed).  Hopefully the test system will behave and it will merge later today without further intervention.

**Comment by fiws** [comment]
Ok thanks. And for good luck:

/meow

**Comment by mheon** [comment]
/hold

Success task isn't reporting correctly

**Pull request merged**
