### PR TITLE
Add missing short flag -l for run/create

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
Closes: https://github.com/containers/libpod/issues/2502

**Comment by TomSweeneyRedHat** [comment]
LGTM, but tests aren't hip.

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please

**Pull request merged**
