### PR TITLE
Add mirroring dockerfiles

### PR DESCRIPTION
**Pull request by cevich**
These are built on quay.io in leu of an image-clone service.

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
Setup: https://quay.io/repository/libpod/fedora-minimal?tab=builds

**Comment by mheon** [comment]
Can you add a quick readme/pointer file in each of those directories, so we know what they're for?

**Comment by cevich** [comment]
yepyep

**Comment by cevich** [comment]
https://quay.io/repository/libpod/whalesay?tab=builds

**Comment by baude** [comment]
assuming @mheon gave a lgtm with his comment.

/lgtm

**Pull request merged**
