### PR TITLE
Don't mount /dev/* if user mounted /dev

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM, but gitvalidation is blowing up

**Comment by rhatdan** [comment]
This should fix https://github.com/containers/libpod/issues/1412

**Comment by mheon** [comment]
@rhatdan Lint error

**Comment by mheon** [comment]
bot, retest this please

**Comment by mheon** [comment]
Travis is our known failure

**Comment by mheon** [comment]
@rh-atomic-bot r+

**Comment by mheon** [comment]
And again, exit 1 after the tests passed cleanly

**Comment by mheon** [comment]
Merging manually

**Pull request merged**
