### PR TITLE
Move logs functionality to separate file for APIv2

### PR DESCRIPTION
**Pull request by jgallucci32**
This simply moves the function for the log handler for
APIv2 to a separate file to be consistent with other parts
of the code base.

Signed-off-by: jgallucci32 <john.gallucci.iv@gmail.com>

### CODE REVIEW

**Comment by mheon** [comment]
Think you might need to squash your commits down to fix gating, but otherwise LGTM.

**Comment by TomSweeneyRedHat** [comment]
LGTM once squished

**Comment by QiWang19** [comment]
LGTM

**Comment by rhatdan** [comment]
@jgallucci32 Could you remove the merge PR.
Something like:
```
git rebase -i origin
git push --force
```

**Comment by jgallucci32** [comment]
@rhatdan I seem to have messed up the jgallucci32/libpod:master branch. In general, what is the best way to pull the latest from base/libpod:master? I thought doing a PR to my forked repo was the best approach, but that didn't seem to go so well.

At this point it might be easier to reset and completely redo the branch. Any suggestions?

**Comment by rhatdan** [comment]
@jgallucci32 This looks good

**Comment by TomSweeneyRedHat** [comment]
I think this will need a rebase once #6591 is reverted in #6644

**Comment by jgallucci32** [comment]
@TomSweeneyRedHat I did a rebase on #6644. Not sure if the extra commit will drop on this PR when merged or if I need to repush, but it is running the checks again.

**Comment by TomSweeneyRedHat** [comment]
@jgallucci32 #6644 just went in, you should be able to rebase now and pick it up.

**Pull request merged**
