### PR TITLE
Don't skip rootless storage setup for ps if --size set

### LINKED ISSUE #2824: Regression: 1.2.0: 'ps --size' crashes
```
$ podman run alpine date
[ok]
$ podman ps --size
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x556486a3432a]
[...and many more pages of stacktrace]
```
nonroot only, and only if there's at least one container (not necessarily running). Does not fail after `podman rm -a`.

Baffling and unexpected. Probably a showstopper.

podman-1.2.0-2.git3bd528e.fc29.x86_64

### PR DESCRIPTION
**Pull request by mheon**
We need the store to look up sizes for containers.

Fixes #2824

### CODE REVIEW

**Comment by mheon** [comment]
@giuseppe PTAL
Let's not merge this without his OK - I don't know why we set SkipStorageSetup here in the first place

**Comment by baude** [comment]
@edsantiago as the reporter, care to comment if this makes your tests happy?

**Comment by baude** [comment]
still LGTM

**Comment by edsantiago** [comment]
New code fixes the reported behavior and passes my BATS test. I don't have a setup for running docker-autotest on built binaries, so it'll take me a while to get that going. So far, LGTM.

**Comment by edsantiago** [comment]
Passes docker-autotest as nonroot. LGTM. Thanks for the quick fix.

**Comment by mheon** [comment]
Lots of ps related failures in rootless testing. Not sure what's going on here. Seems to pass locally?

**Comment by MarcoFalke** [comment]
Would it make sense to add a tiny test for this, since this seems trivial to reproduce: https://github.com/containers/libpod/issues/2824#issue-427829035?

**Comment by mheon** [comment]
I'm actually really curious as to why our existing test suite didn't catch this one - it seems like the rootless tests ought to be doing a `ps --size` already

**Comment by mheon** [comment]
@giuseppe Can you take a look at this? The failures on rootless testing are stumping me

**Comment by giuseppe** [comment]
this was one of the issues that convinced me in the refactoring and that should be fixed there.

We'd need to join different namespaces for each container and we cannot do that (unless we re-exec for each container and return back the result).

**Comment by mheon** [comment]
Aw, hell. OK, I'll close this, then. We'll go with your single userns PR instead.

**Comment by MarcoFalke** [comment]
Is there a simple guide on how to write and run tests?

**Comment by mheon** [comment]
@baude has a guide on running the tests at https://github.com/containers/libpod/blob/master/test/README.md

**Pull request closed without merging**
