### PR TITLE
Cirrus: Necessary changes for v1.9 branch automation

### PR DESCRIPTION
**Pull request by cevich**
***Depends on:*** #5826

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by cevich** [comment]
In order to make this PR pass CI, I'm going to just temporarily/manually tag all the `master` tagged container images to `v1.9`.  Once this PR merges, they'll all get rebuilt (I already fixed the quay.io triggers)

**Comment by cevich** [comment]
Okay, this is ready to go.  I had to re-run some tests a few times due to flakes and one known issue that Ed already filed.

**Comment by cevich** [comment]
Oh..and I've got quay rigged up to build images with a v1.9 tag as well so all bases should be covered.

**Pull request merged**
