### PR TITLE
fix bug copy to volume and bind mount

### LINKED ISSUE #3550: podman cp, with volumes + tarfile + exact name match, is a NOP
Looks like an obscrure corner case of #3059 
```
# podman volume create v
v
# vdir=$(podman volume inspect -f '{{.MountPoint}}' v)
# ls -la $vdir
total 8
drwxr-xr-x. 2 root root 4096 Jul 10 17:55 .
drwx------. 3 root root 4096 Jul 10 17:55 ..
```
Now create a tarball:
```
# mkdir mysubdir
# echo this is a file >mysubdir/myfile
# tar cf mysubdir.tar mysubdir
```
Then create a container, mounting the volume _using the same name as the subdirectory in the tarball_. `podman cp` of the tarball into the container will silently fail:
```
# podman create --name foo -v v:/mysubdir alpine
70f1ad4ac78d5933fd2e0ebefdeb46435c38da382c06b77de00073e63f18984b
# podman cp - foo:/ < mysubdir.tar
# ls -la $vdir/
total 8
drwxr-xr-x. 2 root root 4096 Jul 10 18:02 .
drwx------. 3 root root 4096 Jul 10 17:55 ..
```
`cp` into the volume subdirectory works:
```
# podman cp - foo:/mysubdir < mysubdir.tar
# ls -l $vdir/
total 4
drwxr-xr-x. 2 root root 4096 Jul 10 17:57 mysubdir
# ls -l $vdir/mysubdir/
total 4
-rw-r--r--. 1 root root   15 Jul 10 17:57 myfile
```
podman-1.4.4-3.fc30

### PR DESCRIPTION
**Pull request by QiWang19**
close #3550 
This PR mount the container named volumes and bind mount so `podman cp` can cp files/folders to volumes and mounts

Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
This seems rather unsafe for running containers? Theoretically we end up
mounting places where mounts already exist, but I feel like there's still a
substantial risk of leaking this into the container?

**Comment by QiWang19** [comment]
> This seems rather unsafe for running containers? Theoretically we end up mounting places where mounts already exist, but I feel like there's still a substantial risk of leaking this into the container?

@rhatdan WDYT?

**Comment by rhatdan** [comment]
@mheon We should check to see if the mount points are already there, if yes then do nothing.  If not then mount them.  When exiting we should check if container is running, if yes, then leave them, If not then umount.

**Comment by mheon** [comment]
The container should have a separate copy, though - the mounts there will be confined to the mount namespace. We're mounting under them, which might be OK, but could just as easily mess things up by messing with things before the OCI runtime gets there?

**Comment by vrothberg** [comment]
@QiWang19 @mheon an update for this bug fix?

**Comment by QiWang19** [comment]
> @mheon We should check to see if the mount points are already there, if yes then do nothing. If not then mount them. When exiting we should check if container is running, if yes, then leave them, If not then umount.

I added the above checks. Is it enough to merge?

**Comment by rhatdan** [comment]
I think this bug still needs to be fixed, but we don't have a good solution yet, correct @mheon

**Comment by mheon** [comment]
I think we know that the future solution is a rewrite of `podman cp` to run into the mount namespace of the container - I'm reluctant to merge further work into the existing `cp` implementation as such.

**Comment by QiWang19** [comment]
I'll close this PR. Open a new PR if have a better solution.

**Pull request closed without merging**
