### PR TITLE
Add tests to make sure podman container and podman image commands work

### PR DESCRIPTION
**Pull request by rhatdan**
We have little to no testing to make sure we don't break podman image and
podman container commands that wrap traditional commands.

This PR adds tests for each of the commands.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by mheon** [comment]
Tests are all exploding, but code LGTM

**Comment by rhatdan** [comment]
They are exploding because they are testing what is currently broken in the CLI.

**Comment by rhatdan** [comment]
Lets see if we pass these tests now.

**Comment by rhatdan** [comment]
@baude @vrothberg @mheon @TomSweeneyRedHat @giuseppe PTAL

These tests pass, so it gives us confidence the CLI is fully working now.

**Pull request merged**
