### PR TITLE
Fix pod status reporting for new Exited state

### PR DESCRIPTION
**Pull request by mheon**

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@umohnani8 @vrothberg @baude @giuseppe PTAL

**Comment by vrothberg** [comment]
LGTM (although I miss a commit message)

**Comment by mheon** [comment]
Don't merge yet - working on this one to solve some integration test
failures we're seeing (local, not on CI), and this hasn't quite managed to
fix them yet. I'll rename to WIP when I get to my desk.

**Comment by vrothberg** [comment]
Thanks for the notice, @mheon. I added [WIP] in the meantime.

**Comment by TomSweeneyRedHat** [comment]
The change LGTM fwiw.

**Comment by mheon** [comment]
Removing WIP. The issue turned out to be unrelated, filing a new PR to help debug it.

**Comment by mheon** [comment]
@baude Care to drop an LGTM?

**Pull request merged**
