### PR TITLE
Cirrus: Disable F29 testing

### PR DESCRIPTION
**Pull request by cevich**
This should only be temporary, until #3901 is ready.

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
@vrothberg @baude PTAL, F31 released, so no reason to test F29 anymore.

**Comment by rhatdan** [comment]
@cevich can we add f31 then?

**Comment by cevich** [comment]
> can we add f31 then?

Yes, this is just temporary until #3901 (the one I've been working on during beta) merges.

**Comment by rhatdan** [comment]
/approve
/lgtm
But lets get F31 in ASAP.

**Pull request merged**
