### PR TITLE
rootlessport: handle SIGPIPE

### PR DESCRIPTION
**Pull request by giuseppe**
when a sigpipe is received the stdout/stderr pipe was closed, so
reopen them with /dev/null.

Closes: https://github.com/containers/libpod/issues/5541

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
> when a sigpipe is received the stdout/stderr pipe was closed

How is this happening?

**Comment by giuseppe** [comment]
> How is this happening?

that happens when the parent process exits and the two pipes
```
cmd.Stdout = &stdout
cmd.Stderr = io.MultiWriter(logFile, &logrusDebugWriter{"rootlessport: "})
```

are not valid anymore.  Thus if an error happens and the process tries to write to the stdout/stderr it gets terminated by the SIGPIPE

**Comment by rhatdan** [comment]
LGTM
@haircommander @mheon @baude PTAL

**Comment by mheon** [comment]
LGTM, but would appreciate the original reporter checking this out and confirming it's fixed

**Comment by AkihiroSuda** [comment]
LGTM

**Pull request merged**
