### PR TITLE
Remove urfave/cli from libpod

### PR DESCRIPTION
**Pull request by baude**
This is the final cleanup to remove urfave/sli from libpod.  Removed
old, disabled tests that have not been run in over a year.

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
Am I missing something but I see lots of c.Bool and other urfave type stuff

grep c.Bool cmd/podman/*.go | wc -l
33

**Comment by rhatdan** [comment]
A couple of things I hate about the new interface.
1 GlobalOptions are showing up on each podman COMMAND --help, scrolling off the terminal the stuff I care abour.
2 Getting an error dumps the help message.  Again causing the important information to scroll off the terminal.
-  When and error happens I should only see.
```
ls --foobar
ls: unrecognized option '--foobar'
Try 'ls --help' for more information.
```
That not the help info.

**Comment by TomSweeneyRedHat** [comment]
Why did the two test files disappear?  Also looks like you've a load error....

**Comment by baude** [comment]
@rhatdan the c.bool is a convenience wrapper call as a PodmanCommand method.

**Pull request merged**
