### PR TITLE
Remove refs to crio/conmon

### PR DESCRIPTION
**Pull request by cevich**
Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
while we're here can you add to the second line `/usr/local/libexec/podman/conmon` ?

**Comment by haircommander** [comment]
regardless of if you do LGTM thanks @cevich

**Comment by rhatdan** [comment]
Tests are not happy with this PR.
@mheon PTAL

**Comment by cevich** [comment]
@rhatdan @mheon it's only my first try, TBH I'm surprised it even compiled  :grin:

Goal here is to get podman in-line with a new reality of conmon being separated from cri-o when installed via package (the #1936 connection).  So, until that PR merges, I think perhaps I need to set `$CONMON_BINARY` for all distros. so the tests can pass.

> while we're here can you add to the second line /usr/local/libexec/podman/conmon ?

I can, and am happy to adjust anything else as well.  I'm not very happy about the separate paths we search through in the int. tests, there's gotta be a better way to handle that.

**Comment by cevich** [comment]
@mheon @haircommander @rhatdan PTAL, tests passing now.  I tried to change as little as possible here, so it's certainly not ideal.  However, for the vast majority of cases it should allow CI and human testing to function with multiple versions of conmon available at once.  I'm still open if any of the search path order needs to be tweaked, juss lemmie know.

**Comment by haircommander** [comment]
LGTM, I like how podman specific locations are searched first. I can't comment on which should be first /usr/local/.. vs /usr.. and so on though.

**Comment by cevich** [comment]
>  I can't comment on which should be first 

In my experience, typically the list should go in order of most-special to least-special, with env. vars and config files being in the former category.  So less obvious places like `/usr/local/...` should come first, and more "standard" places like `/usr/bin` should be last.

**Pull request merged**
