### PR TITLE
Fix builds on 32 Arches.

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes: https://github.com/containers/libpod/issues/6397

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
@edsantiago PTAL

**Comment by edsantiago** [comment]
LGTM, it's consistent with previous fixes, but I have no way to test it other than letting koji do so.

/lgtm
/hold

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by baude** [comment]
@rhatdan i provided a PR to this to make sure make cross-local will catch this in CI.

**Comment by edsantiago** [comment]
/hold

@mheon I thought we couldn't LGTM while tests were still running?

**Comment by mheon** [comment]
@edsantiago It already had a hold, so I just reapplied the LGTM

**Comment by edsantiago** [comment]
Sorry @mheon, I had missed that.

/hold cancel

**Comment by edsantiago** [comment]
Followup: [koji builds are back to passing](https://koji.fedoraproject.org/koji/buildinfo?buildID=1516819). Thanks everyone.

**Comment by rhatdan** [comment]
@edsantiago, @baude was asking why are we building for x86 32 bit environments?

**Comment by edsantiago** [comment]
>why are we building for x86 32 bit environments?

That's a packaging question, I can't possibly answer it. However:
* in looking at the spec file, I see no arch exclusions or inclusions; and
* in looking at recent koji builds, I see that i686 is a standard target even for fc33.

From that, I would guess that this is simply The Way It Is in koji. It should be possible to add an arch exclusion though.

@lsm5 , can you answer or do you know who can answer?

**Comment by rhatdan** [comment]
I just thought that Fedora no longer supported that arch.

**Comment by baude** [comment]
seems wasteful to continue this for i686

**Comment by edsantiago** [comment]
My understanding is that f31 dropped the 32-bit _kernel_ but still builds packages for multilib. But please take anything I say with a giant lump of salt.

**Comment by lsm5** [comment]
>     * in looking at the spec file, I see no arch exclusions or inclusions; and
> 
>     * in looking at recent koji builds, I see that i686 is a standard target even for fc33.

@edsantiago Idon't remember off-hand but I've had random requests to not disable any of the supported arches, that's why I removed the `ExclusiveArch`. Does the i686 build imply more time and resources for testing? I can check with fedora-devel people as well on this.

**Comment by rhatdan** [comment]
No, this is out of curiosity more then anything.  I am glad we caught this, and fixed the tests to catch it earlier in CI.
Someone somewhere is bound to build podman on a 32 bit system, so we should be ready for it.

**Pull request merged**
