### PR TITLE
logo: correct light source reflection

### PR DESCRIPTION
**Pull request by rst0git**
Before:
podman-logo

After:
podman-logo

### CODE REVIEW

**Comment by rhatdan** [comment]
/ok-to-test
Did you use some tool to o this?
/approve
LGTM

**Comment by rst0git** [comment]
I used Inkscape.

**Comment by TomSweeneyRedHat** [comment]
@mairin PTAL

**Comment by mairin** [comment]
@rst0git can you explain the rationale for the change? the light wasnt meant to be above.

**Comment by rst0git** [comment]
> @rst0git can you explain the rationale for the change? the light wasnt meant to be above.

Hi @mairin, thank you for asking. First, I would like to say that I'm not a professional graphic designer.

This source of light felt more natural for me because when swimming in water the light (usually sunlight) is presumed to come from above. Having looked into this question, I found the following articles interesting: 

https://en.wikipedia.org/wiki/Top-left_lighting

[Is light in pictures presumed to come from the left side?](https://journals.sagepub.com/doi/pdf/10.1068/p5289)

**Comment by mairin** [comment]
@rst0git i actually got confused about the before and after... this is a good fix, thank you! LGTM

**Comment by rhatdan** [comment]
/lgtm
@rst0git Want to look at the Buildah logo? :^)

**Pull request merged**
