### PR TITLE
Opensuse openbuild ubuntu + buildah packages

### PR DESCRIPTION
**Pull request by cevich**
Move installation of packages necessary for buildah CI, here so the projects can both re-use the same VM images.  Make some other minor improvements along with switching to using the Opensuse openbuild Ubuntu packages instead of the (now) unmaintained projectatomic PPA.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by cevich** [comment]
@TomSweeneyRedHat FYI- this PR is waiting on https://github.com/checkpoint-restore/criu/issues/973

**Comment by cevich** [comment]
rebased

**Comment by cevich** [comment]
@baude this PR brings in the new VM images w/ conmon update + moves our Ubuntu VM images off of the old PPA stuff and onto OpenSuse OBS.  There are a few tests failing which I'm not sure how to debug, would you mind taking a look when you have a moment:  https://cirrus-ci.com/build/4842660733124608

**Comment by cevich** [comment]
@lsm5 when u have a moment, PTAL see if any of these test errors seem familiar (it's okay if not)?
https://cirrus-ci.com/build/4842660733124608

**Comment by cevich** [comment]
Rebased and force-pushed.  Prior runs were missing some commits.  Let's see what happens now...

**Comment by cevich** [comment]
@baude @mheon okay, I think this is ready now.  PTAL when you have a moment, it's not urgent.

**Comment by cevich** [comment]
(FWIW: I needed to re-run two flaking tasks, noticed problems in 'search' and 'login/logout' tests on both)

**Pull request merged**
