### PR TITLE
Fix handling of ThrottleWriteIOPSDevice

### PR DESCRIPTION
**Pull request by rhatdan**
This is causing the UBuntu tests to fail.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe @baude @jwhonce @mheon @vrothberg @TomSweeneyRedHat PTAL

**Comment by giuseppe** [comment]
LGTM, I had opened exactly the same PR: https://github.com/containers/libpod/pull/6502

**Comment by rhatdan** [comment]
There is still one more issue with Ubuntu.  The real problem is without Ubuntu we are not testing against Cgroups V1 right now.

**Pull request merged**
