### PR TITLE
lock and sync container before checking mountpoint

### PR DESCRIPTION
**Pull request by baude**
when checking for a container's mountpoint, you must lock and sync
the container or the result may be "".

Fixes: #2304

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
While we're on this - mind changing line 404 from `c.Spec()` to `c.config.spec`?

**Comment by mheon** [comment]
Other than that, LGTM

**Comment by baude** [comment]
> While we're on this - mind changing line 404 from `c.Spec()` to `c.config.spec`?

done!

**Comment by TomSweeneyRedHat** [comment]
LGTM, assuming happy tests.

**Pull request merged**
