### PR TITLE
Vendor in latest containers/buildah code

### PR DESCRIPTION
**Pull request by rhatdan**
This should improve the speed of podman build.
Has fixes from containres/image for parallell pull.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
@TomSweeneyRedHat @umohnani8 @mheon @baude @vrothberg PTAL

**Comment by mheon** [comment]
Do we need a revendor of c/image to pick up the changes there?

**Comment by vrothberg** [comment]
Yes, we need c/image and update the dependencies.

**Comment by baude** [comment]
c-image can be next.  ill merge this one first.

**Comment by vrothberg** [comment]
> c-image can be next. ill merge this one first.

The thing is that without vendoring the new c/image, there are no pull improvements.

**Comment by vrothberg** [comment]
> > c-image can be next. ill merge this one first.
> 
> The thing is that without vendoring the new c/image, there are no pull improvements.

Actually, it's fine as Dan updated the PR before it was merged :)

**Pull request merged**
