### PR TITLE
Bump to v1.0.5

### PR DESCRIPTION
**Pull request by mheon**
Backport some changes to c/storage to fix a potential unusable container store if the system restarts during certain c/storage ops.

### CODE REVIEW

**Comment by mheon** [comment]
@baude @rhatdan @vrothberg @giuseppe @TomSweeneyRedHat PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
(and thought I'd done so last night....)

**Pull request merged**
