### PR TITLE
[WIP] Port Deduplication

### PR DESCRIPTION
**Pull request by mheon**
As of now, we store port mappings as []ocicni.PortMapping, each struct holding a single port. This converts us to use structs which represent an entire contiguous range of ports, which should massively reduce the amoung we're storing in the database.

User-specified ports are deduplicated when they are added to the container, causing these improvements to apply even if the user specifies ports 80, 81, and 82 separately.

As part of this change, to solve a circular import issue, break up pkg/inspect and store its structs in the packages where they are used.

Old-style port mappings will still be (partially) supported - they'll be correctly added to CNI, but won't be displayed in `podman ps`, `podman port`, `podman inspect`.

Still to do:
- Easyjson generation for the new Port struct
- More unit tests for the complicated deduplication logic
- Ensure we don't display more than a set number (5 or so) or ports if many ranges are present during a `podman ps`
- Add a way to convert legacy port mappings into new-style range mappings - should not be hard to add a `podman container migrate` command that does this?
- Investigate if `podman port` still works right since I did not touch it at all yet

### CODE REVIEW

**Comment by mheon** [comment]
Note to self: maybe add convenience methods to PortMapping struct to get the end of the range? We seem to calculate it a lot.

**Comment by rhatdan** [comment]
@mheon Needs rebase.

**Comment by rhatdan** [comment]
@mheon Needs a rebase.

**Comment by rhatdan** [comment]
@mheon Still working on this one?

**Comment by rhatdan** [comment]
Needs a rebase.

**Comment by rhatdan** [comment]
@mheon Did the patches for handling multiple ports have anything to do with this PR?

**Comment by mheon** [comment]
@rhatdan Nope. We need this on the backend so trying to map 10k ports into a container actually works, instead of hanging for days adding IPTables rules.

This one, though, is basically bunk. Needs a rewrite. I'll close.

**Pull request closed without merging**
