### PR TITLE
generate systemd: add `default.target` to INSTALL

### PR DESCRIPTION
**Pull request by vrothberg**
When enabling a systemd service we can specify which target will start
it by specifying it in the `[INSTALL]` section.  In case of root, this
is commonly set to `multi-user.target` which is used to start other
essential system services such as the network manager, D-BUS and more.

However, the `multi-user.target` is not enough on all systems,
especially when running rootless and enabling user services.  Multiple
users have reported issues that there isn't even an attempt to start the
service.

Setting the INSTALL target to `default.target` will fix the rootless
case.  However, `default.target` may vary among systems.  Fedora
Workstation, for instance, sets the `default.target` to the graphical
target (i.e., runlevel 5) while Fedora Server sets it to
`multi-user.target` which is on runlevel 2 and hence way earlier in the
startup sequence.

As INSTALL allows for specifying multiple INSTALL targets, we can set it
to `multi-user.target` to continue supporting existing workloads AND to
`default.target` which MAY redundantly attempt to start it at a later point;
effectively a NOP for the root case and essential for rootless.

Fixes: #5423
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
Once merged, I believe we can close:
- https://github.com/containers/libpod/issues/5291
- https://github.com/containers/libpod/issues/5094
- https://github.com/containers/libpod/issues/5423

**Comment by vrothberg** [comment]
@giuseppe @rhatdan @edsantiago PTAL

**Comment by edsantiago** [comment]
Could you update `docs/source/markdown/podman-generate-systemd.1.md` and `docs/tutorials/rootless_tutorial.md` please? (I feel really dumb for having restarted the flakes before reviewing)

**Comment by vrothberg** [comment]
> Could you update `docs/source/markdown/podman-generate-systemd.1.md` and `docs/tutorials/rootless_tutorial.md` please? (I feel really dumb for having restarted the flakes before reviewing)

Done. Note that I removed the section from the rootless tutorial. The example there was incorrect. As users should use `podman generate systemd` and since there's no real difference between root and rootless (we want so support both), I opted to remove the section.

**Comment by vrothberg** [comment]
Not sure why GitHub is not seeing the new commit ...

**Comment by vrothberg** [comment]
> Not sure why GitHub is not seeing the new commit ...

Accidentally created an upstream branch for it....

**Comment by edsantiago** [comment]
LGTM. Good luck with the flakes.

**Comment by vrothberg** [comment]
Shall we force merge?

**Comment by mheon** [comment]
At this point, yeah, not worth waiting for the bot.

**Pull request merged**
