### PR TITLE
docs: Fix typo for "healthcheck"

### PR DESCRIPTION
**Pull request by cgwalters**
Just spotted while reading the manpage for something else.

### CODE REVIEW

**Comment by mheon** [comment]
@cgwalters Can you add a signoff and re-push? Should fix gitvalidation

**Comment by TomSweeneyRedHat** [comment]
gag, how'd I miss that?  Thanks @cgwalters .
LGTM

**Comment by giuseppe** [comment]
LGTM, @cgwalters could you add a `Signed-off-by`?

**Comment by rhatdan** [comment]
Needs a rebase to get the SELinux fixes.  And needs a signature @cgwalters

**Comment by mheon** [comment]
Closing in favor of #3056

**Pull request closed without merging**
