### PR TITLE
Sigh; disable pod-top test, it's unreliable (#2780)

### PR DESCRIPTION
**Pull request by edsantiago**
Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
This is failing very frequently on RHEL8, preventing me from packaging gating tests. It's a simple fix, I'd appreciate expedited approval. TIA.

**Comment by giuseppe** [comment]
LGTM

**Comment by edsantiago** [comment]
Github didn't autolink the issue in the title: #2780

**Pull request merged**
