### PR TITLE
fix more swagger inconsistencies

### PR DESCRIPTION
**Pull request by edsantiago**
I'm getting really tired of doing this manually.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by edsantiago** [comment]
Tests green, but @cevich, in scrum you mentioned that the "rdo" test should not affect the red/green status on the github "main page". I interpreted "main page" to mean [/libpod/pulls](https://github.com/containers/libpod/pulls); but as of the time I write this, that page shows my PR with a red X:
with a red X even though "rdo" is the only failing test. Did I misunderstand what you meant by "main page"?

**Comment by cevich** [comment]
> but @cevich, in scrum you mentioned that the "rdo" test should not affect the red/green status on the github "main page".  

@edsantiago FYI, naw, I was referring to the magic permalink [icon in the readme](
https://github.com/containers/libpod/blob/master/README.md):

[Continuous Integration:](contrib/cirrus/README.md) [Build Status](https://cirrus-ci.com/github/containers/libpod/master)

That only reflects the status from Cirrus-CI, which doesn't include RDO.  Though it's still red because of all the post-merge flakes :confounded:

**Pull request merged**
