### PR TITLE
minor typo fix in 'podman top' usage

### PR DESCRIPTION
**Pull request by edsantiago**
Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
```
2019/03/12 22:34:46 Errors on clone:
github.com/containers/buildah: Err: exit status 128, out: fatal: reference is not a tree: 345ffc2b29b4255a83cfa763db88799d8ec9c569
```
I'm guessing that's not something I broke, nor something under my control...

**Comment by mheon** [comment]
Yeah, our buildah needs revendoring now

**Comment by mheon** [comment]
LGTM, but you'll probably need a rebase once the vendor fix lands

**Pull request merged**
