### PR TITLE
test docs fixups

### PR DESCRIPTION
**Pull request by baude**
adding some clarification on testing based on tom's input.

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat At least in the part of the doc that I reviewed, it looks like PAPR was removed.

**Comment by baude** [comment]
yeah i removed it

**Comment by TomSweeneyRedHat** [comment]
You're right @rhatdan, musta missed that review (or forgot) when it flew by.
Straght up LGTM then.

**Comment by baude** [comment]
@TomSweeneyRedHat pull the trigger on it then :)

**Comment by TomSweeneyRedHat** [comment]
Fixes: #2189

**Comment by TomSweeneyRedHat** [comment]
Done and I've added the issue to today's log, thx again @baude.

**Pull request merged**
