### PR TITLE
We were not handling the user option on create

### PR DESCRIPTION
**Pull request by rhatdan**
With this patch we can get run_passwd_test.go to pass

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@jwhonce @mheon @baude @vrothberg @giuseppe @TomSweeneyRedHat @QiWang19 PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by QiWang19** [comment]
LGTM

**Pull request merged**
