### PR TITLE
Attempt to install go-md2man only if missing

### PR DESCRIPTION
**Pull request by ssbarnea**
Fixes: #4632
Signed-off-by: Sorin Sbarnea <ssbarnea@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@edsantiago PTAL

**Comment by TomSweeneyRedHat** [comment]
@ssbarnea TYVM for the quick turn around.

**Comment by rhatdan** [comment]
Since I just pushed the exact same PR, /lgtm

**Comment by edsantiago** [comment]
Followup: podman is [building again](https://koji.fedoraproject.org/koji/packageinfo?packageID=26289). Thank you.

**Pull request merged**
