### PR TITLE
Bump github.com/containers/psgo from 1.4.0 to 1.5.0

### PR DESCRIPTION
**Pull request by rhatdan**
Bumps [github.com/containers/psgo](https://github.com/containers/psgo) from 1.4.0 to 1.5.0.
- [Release notes](https://github.com/containers/psgo/releases)
- [Commits](https://github.com/containers/psgo/compare/v1.4.0...v1.5.0)

Signed-off-by: dependabot-preview[bot] <support@dependabot.com>
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
not sure how we should deal with dependencies for now.  All tests are disabled so it is not possible to know if we are introducing regressions.

**Comment by rhatdan** [comment]
@giuseppe @vrothberg @mheon @baude @TomSweeneyRedHat @QiWang19 @jwhonce Can we get this one in.  ps_test.go is running now, and this would be the tool to break if this was going to cause an issue.

**Comment by mheon** [comment]
If we're all rebased, then sure, LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
