### PR TITLE
Cirrus: Add BATS package for all platforms

### PR DESCRIPTION
**Pull request by cevich**
***NOTE:*** THIS PR DISABLES TESTING ON RHEL

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@cevich CI/CD does not like you,

**Comment by giuseppe** [comment]
LGTM

**Comment by cevich** [comment]
@rhatdan gosh it sure doesn't...I thought we fixed that problem a loooong time ago...jeepers what ever did I break...

**Comment by cevich** [comment]
My gosh, how the heck could adding a package cause all the checkpoint tests to fail :confounded:

**Comment by adrianreber** [comment]
@cevich It seems runc is downgraded during testing:
```
Running transaction
  Preparing        :                                                        1/1 
  Downgrading      : runc-2:1.0.0-55.dev.git578fe65.fc28.x86_64             1/2 
  Erasing          : runc-2:1.0.0-68.dev.git6635b4f.fc28.x86_64             2/2 
  Running scriptlet: runc-2:1.0.0-68.dev.git6635b4f.fc28.x86_64             2/2 
  Verifying        : runc-2:1.0.0-55.dev.git578fe65.fc28.x86_64             1/2 
  Verifying        : runc-2:1.0.0-68.dev.git6635b4f.fc28.x86_64             2/2 
Downgraded:
  runc.x86_64 2:1.0.0-55.dev.git578fe65.fc28                                    
```

That runc version is from September 2018. I guess it is too old.

**Comment by cevich** [comment]
@adrianreber *sigh* yep we stuck [that hack in to override runc at runtime](https://github.com/containers/libpod/blob/master/contrib/cirrus/setup_environment.sh#L63) because the latest package causes other problems.  However, that's happening in every other CI job and does not break.  That's what I'm confused about :confused:

**Comment by adrianreber** [comment]
It is indeed strange, that adding one new package gives so many failures. The Ubuntu and RHEL 7 errors are not checkpoint related. RHEL 7 is skipping the checkpoint tests because CRIU is too old. The only CRIU problem I am aware of is SELinux related (#2334), so it will not happen on Ubuntu.

I will open a PR to disable the Fedora based tests until I have solved the SELinux errors.

**Comment by cevich** [comment]
@adrianreber thx m8.  Ya I think I need to sleep on this one. There must be something happening from the image-build I'm overlooking.  That's the only place where "new" stuff can come in.

**Comment by cevich** [comment]
(rebased & force-pushed)

**Comment by cevich** [comment]
(rebased & force-pushed)

**Comment by vrothberg** [comment]
restarted Ubuntu

**Comment by cevich** [comment]
There's a problem with RHEL + installed vs vendored ginkgo/gomega.  Trying to solve this by avoiding 'go get' -ing those.

**Pull request merged**
