### PR TITLE
Cirrus: Use branch-specific image tags

### PR DESCRIPTION
**Pull request by cevich**
Also, since 19.04 is EOL, update to Ubuntu 19.10 + Backport use of OBS packages.

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
Hrmmm, not sure about the test failures.  It's possible they are flakes as there was a github or cirrus 'hiccup' in the last few minutes  (I saw some tests elsewhere, get auto-rescheduled b/c `git clone` problems).  I removed the ***WIP*** from this PR, since otherwise it's ready to go.  I'm just out of time waiting for the tests to fail, so I can smash the 're-run' button :confounded:

**Comment by mheon** [comment]
We marked everything as optional for one of the branches because we weren't expecting the tests to pass because the VMs might be different?

**Comment by mheon** [comment]
I swore it was 1.6, but that appears to be incorrect. It was 1.4.2: https://github.com/containers/libpod/commit/9a50c1c2f85952edd4fc2873ce6a0845394c2613

**Comment by mheon** [comment]
I think we need basically the same treatment here. If we need to merge this before you're back, I'll take over and do so.

**Comment by cevich** [comment]
> I swore it was 1.6, but that appears to be incorrect. It was 1.4.2

Double-drat, well this PR will fix CI for the `v1.6` branch (it is genuinely broken) based on #6178

I did ***NOT*** enable any cron-based "keep-alive" builds for `v1.4.2` tag only `v1.4.2-stable` branch.  If a similar fix is needed for `1.4.2-stable` while I'm away, the process is documented.  For reference, the main trouble I ran into here was Ubuntu 19.04 no longer existing (it's 19.10 now) and the older `ubuntu_setup.sh` trying/failing to use the old PPA's.  So I cherry-picked the OBS setup from master and back-ported it here.

**Comment by rhatdan** [comment]
@cevich Still working on this one?

**Comment by cevich** [comment]
oh :hankey: completely forgot about this. Thanks for the reminder @rhatdan 

@baude FYI...this use to work on the 1.6 branch :smile:  I'm working on it now and will let you know when it's ready.  Sorry for dropping the ball.

**Comment by cevich** [comment]
@baude summary of our chat:  This PR is ready to go in, fresh VM images are built and there are some other small changes to help keep the v1.6 branch chooching.  However, we decided that the ongoing maintenance of this setup for old/gold branches is too heavy.  You're going to work up a PR that greatly simplifies CI for old branches.  I'll close this PR now, but if we need it or pieces of it, it can be re-opened and should still be valid for a few more weeks.

**Pull request closed without merging**
