### PR TITLE
Support --restart=no for restart

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1694662

**Comment by mheon** [comment]
#2826

**Comment by rhatdan** [comment]
I would like to discuss whether we want to support #2826. This adds a support burden, that I believe is better handled in systemd.

**Comment by mheon** [comment]
Our original mandate was Docker 1.12 compatability. We've done that in other places it would create a burden (volumes, for example). I don't see this as serious added complexity; it was two hours of dev time and around two hundred lines of code to implement. It's a lot less complex than our remote client work, for example.

**Comment by rhatdan** [comment]
My concern is long term support and opening up pandora's box of what it means for process management.

**Comment by mheon** [comment]
We're not really managing processes - we trigger a standard container restart if we detect the container exited. It's all things that Podman already does, just with a bit of plumbing to tell it when to do them.

**Comment by rhatdan** [comment]
I believe this opens a whole can of worms, that is better handled by systemd.  I believe it would be better for our customers in the long run to use systemd for this, and for us to document it.   We should discuss this at next meeting.  BTW I think we would need to handle this type of stuff in PODs as well.

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
Closing and going with @mheon version.

**Pull request closed without merging**
