### PR TITLE
V2 Restore exists E2E tests

### PR DESCRIPTION
**Pull request by jwhonce**
* Fix setting exit code in */exists.go

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM
@jwhonce Did this fix a test?

**Comment by jwhonce** [comment]
> LGTM
> @jwhonce Did this fix a test?

Yes, exists_test.go

**Comment by rhatdan** [comment]
/lgtm
I don't know how I missed it.

**Pull request merged**
