### PR TITLE
Improved readability in image json output

### PR DESCRIPTION
**Pull request by kunalkushwaha**
Changes made in json output to improve readability of
podman images output.

Fixes: https://github.com/containers/libpod/issues/5001

Signed-off-by: Kunal Kushwaha <kunal.kushwaha@gmail.com>

### CODE REVIEW

**Comment by kunalkushwaha** [comment]
@HarryMichal PTAL

**Comment by rhatdan** [comment]
Looks like some of the tests need to be modified.

Changes look good to me, though.

**Comment by rhatdan** [comment]
LGTM
@vrothberg @giuseppe @mheon @baude @QiWang19 @TomSweeneyRedHat PTAL

**Comment by mheon** [comment]
/approve
LGTM

**Pull request merged**
