### PR TITLE
Allow identical duplicate volumes and mounts

### LINKED ISSUE #4217: podman rejects duplicate mount specifications
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

podman rejects duplicate mount specifications in the run command, contrary to docker

**Steps to reproduce the issue:**

1. $ podman run -it --rm -v $PWD:$PWD -v $PWD:$PWD fedora:30 bash

**Describe the results you received:**

Error: /home/avi: duplicate mount destination

**Describe the results you expected:**

Successful execution of the container with the mounts deduplicated

**Additional information you deem important (e.g. issue happens only occasionally):**

The duplicate mount specifications were generated by a script. I could deduplicate it, but I believe full command line compatibility is the goal.

**Output of `podman version`:**

```
podman version 1.6.1
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.9
  podman version: 1.6.1
host:
  BuildahVersion: 1.11.2
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.1-1.fc30.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.1, commit: 4346fbe0b2634b05857973bdf663598081240374'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 4698271744
  MemTotal: 33600290816
  OCIRuntime:
    package: runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: e3b4c1108f7d1bf0d09ab612ea09927d9b59b4e3
      spec: 1.0.1-dev
  SwapFree: 16869486592
  SwapTotal: 16869486592
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: tmp.scylladb.com
  kernel: 5.2.17-200.fc30.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-4.git19d199a.fc30.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.2
      commit: 19d199a6ca424fcf9516320a327cedad85cf4dfb
  uptime: 69h 19m 2.3s (Approximately 2.88 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/avi/.config/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.6.3-2.0.dev.git46c0f8e.fc30.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.6.3
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/avi/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 3
  RunRoot: /run/user/1000
  VolumePath: /home/avi/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.1-2.fc30.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

None

### PR DESCRIPTION
**Pull request by mheon**
Docker allows exactly identical mounts and volumes to be passed without throwing an error. If a volume is exactly identical, we should not error - otherwise, we'll still give a duplicate mount destination error.

Fixes #4217

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
all kinds of test unhappiness @mheon

**Comment by rhatdan** [comment]
I don't see why we should be bug for bug compatible with Docker.  I think this is bad, it allows users to make mistakes in the containers and not notice it.

**Comment by 1ace** [comment]
This `docker-compose.yml` reproduces the issue:
```yaml
version: "3.7"

services:
  postgres:
    image: postgres:alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: random
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
```

```
$ docker-compose up
[+] Running 3/1
 ⠿ Network tmp_default         Created                                                                             0.1s
 ⠿ Volume "tmp_postgres_data"  Created                                                                             0.0s
 ⠿ Container tmp-postgres-1    Created                                                                             0.0s
Attaching to tmp-postgres-1
tmp-postgres-1  | The files belonging to this database system will be owned by user "postgres".
tmp-postgres-1  | This user must also own the server process.
[...]
```

```
$ export DOCKER_HOST="unix://$XDG_RUNTIME_DIR/podman/podman.sock"
$ docker compose up
[+] Running 2/0
 ⠿ Network tmp_default         Created                                                                             0.0s
 ⠿ Volume "tmp_postgres_data"  Created                                                                             0.0s
 ⠋ Container tmp-postgres-1    Creating                                                                            0.0s
Error response from daemon: fill out specgen: /var/lib/postgresql/data: duplicate mount destination
```

**Comment by 1ace** [comment]
Sorry, I assumed you knew this wasn't just a "duplicate `-v` in the command line" issue and chose not to fix it.
Apologies if my first message was a bit too strong :pray:

**Comment by mheon** [comment]
Are  you running Docker Compose v2.0? There's a known issue with v2.0 against Podman where this is showing up. The fix is almost certainly *not* the one in the PR, there's something deeper going on there.

**Comment by 1ace** [comment]
> Are you running Docker Compose v2.0?

Yes, I am actually; I'll try docker-compose v1.x when I'm back in the office on Monday. I'll also try to compile podman with this change to see if it helps, I didn't have time to do this on Friday but I'm hoping I'll be able to next week.

> There's a known issue with v2.0 against Podman where this is showing up.

Ah, I don't know why I missed #11822 when I searched earlier. I've subscribed to that issue now, and providing downgrading docker-compose fixes this problem, I'll stick with it for now. I'm also happy to help test patches to get v2 compatibility :slightly_smiling_face:

**Pull request closed without merging**
