### PR TITLE
Fix typo.

### PR DESCRIPTION
**Pull request by mavit**
Fix typo in manpage for `podman auto update`.

Signed-off-by: Peter Oliver <git@mavit.org.uk>

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @mavit but could you sign  your PR.
git commit -a --amend -s
git push --force
and then we can merge
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM once signed
/ok-to-test

**Comment by QiWang19** [comment]
@mavit can you rebase the commit to get test pass?

**Pull request merged**
