### PR TITLE
Cirrus: Confirm networking is working

### PR DESCRIPTION
**Pull request by cevich**
Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
/hold

need to check why we get a missing podman during build

https://cirrus-ci.com/task/5418525380837376

**Comment by cevich** [comment]
https://cirrus-ci.com/task/5826420010385408

**Comment by cevich** [comment]
@edsantiago when you have a moment, could you take a quick peek?

We were having loads of problems today with CI jobs failing 15+ minutes in, because of one networking issue or another.  This PR isn't a perfect check, but hopefully in the common-case (like unreachable docker.io) we don't waste time and resources on further testing.  It also (maybe) helps make it obvious there's a networking problem, rather than having to troll through the test-logs.

**Comment by edsantiago** [comment]
Isn't this a wee bit more complicated than it needs to be? `netcat` is already installed on all the systems, isn't it?
```bash
while read host port; do nc -zv -w 10 $host $port || die; done < LIST-OF-HOST-PORTS
```
No need for containers, Dockerfiles, complicated scripts. (For future such endeavors, though, could you give scripts a more descriptive name than `entrypoint`?)

**Comment by cevich** [comment]
> Isn't this a wee bit more complicated than it needs to be?

Likely :grinning: 

> netcat is already installed on all the systems, isn't it?

We need to use a container image since they start and run so much faster than VMs.  Not sure about netcat, though it's a great suggestion.  I can check into doing it that way, perhaps with an image we already build.

Thanks!

**Comment by cevich** [comment]
No `netcat` in either Fedora nor Centos container images.  Will check our existing gate and imgts images when I have a better network link myself (I'm on the bus).

**Comment by edsantiago** [comment]
alpine has it:
```
# podman run alpine nc -z -v -w 10 l.edsantiago.com 800
nc: l.edsantiago.com (72.14.191.63:800): Operation timed out
```

**Comment by rhatdan** [comment]
A hack I do, is to execute on a Fedora box

podman run -v /usr/bin/nc:/usr/bin/nc fedora  nc -z -v -w 10 l.edsantiago.com 800

Then you don't need to do anything special in the container, one problem with this is if the containers libraries are different then the hosts.

**Comment by cevich** [comment]
Checked, and found our gate container has it, so I just added a new section with @edsantiago magic loop.

**Comment by cevich** [comment]
Yay, thanks @edsantiago 

```
while read host port; do nc -zv -w 13 $host $port || exit 1; done < ${CIRRUS_WORKING_DIR}/${SCRIPT_BASE}/required_host_ports.txt
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 192.30.253.113:22.
Ncat: 0 bytes sent, 0 bytes received in 0.04 seconds.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 52.54.178.62:443.
Ncat: 0 bytes sent, 0 bytes received in 0.06 seconds.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 23.21.165.246:443.
Ncat: 0 bytes sent, 0 bytes received in 0.04 seconds.
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connected to 209.132.181.16:443.
Ncat: 0 bytes sent, 0 bytes received in 0.13 seconds.
```

**Comment by edsantiago** [comment]
Sweet! Thank you!

/lgtm

**Comment by cevich** [comment]
Rebased and --force pushed

**Comment by mheon** [comment]
@cevich I'll unhold once podman-in-podman passes

**Pull request merged**
