### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by damdo**
- `Similar` is misspelled
- a `to` is missing after `Similar`

Signed-off-by: Damiano Donati <damiano.donati@gmail.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
Nice eagle eye and fix @damdo , TY!

**Comment by QiWang19** [comment]
LGTM

**Comment by rhatdan** [comment]
/lgtm
Thanks @damdo

**Pull request merged**
