### PR TITLE
Document --net as an alias of --network in podman run & create

### LINKED ISSUE #1615: Podman run & create man pages do not mention --net
**Is this a BUG REPORT or FEATURE REQUEST?**:

# Uncomment only one, leave it on its own line:

[//]: # **kind bug**

**Description**

The podman run and podman create manpages should mention that --net is an alias for --network, but they do not

**Steps to reproduce the issue:**

1. man podman-run and scroll to --network

**Describe the results you received:**

The --network flag is documented but not --net

**Describe the results you expected:**

The --net flag is documented as an alias of --network

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Current master

### PR DESCRIPTION
**Pull request by QiWang19**
This commit fixes #1615
Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM, assuming happy tests.

**Comment by mheon** [comment]
@QiWang19 Mind rebasing to pick up CI fixes?

**Pull request merged**
