### PR TITLE
preparation for remote-client create container

### PR DESCRIPTION
**Pull request by baude**
to prepare for being able to remotely run a container, we need to
perform a refactor to get code out of main because it is not
reusable.  the shared location is a good starting spot though
eventually some will likely end up in pkg/spec/ at some point.

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by jwhonce** [comment]
LGTM

**Comment by rhatdan** [comment]
@baude needs a rebase.

**Pull request merged**
