### PR TITLE
remove -c for podman remote global options

### PR DESCRIPTION
**Pull request by baude**
it conflicts with commit

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM once tests go green

**Comment by rhatdan** [comment]
Why not make it "C"?  --connection is a lot to type.

**Comment by mheon** [comment]
We need this to fix CI on master.
@TomSweeneyRedHat @vrothberg @giuseppe @haircommander Anyone want to whack this with an LGTM? We can readd a short option that doesn't conflict later.

**Pull request merged**
