### PR TITLE
When creating exit command, pass storage options on

### LINKED ISSUE #3326: podman inspect on stopped container: inconsistent status
At some recent point, podman inspect started reporting 'stopped' for nonroot and 'exited' for root:

```
$ podman run -d --name foo alpine sleep 60;podman stop foo;podman inspect --format '{{.State.Status}}' foo
003cdf7dc49ebaff3261c05ed1cc928e26383f5b065b5f835b30a1e909aaffbd
003cdf7dc49ebaff3261c05ed1cc928e26383f5b065b5f835b30a1e909aaffbd
stopped
```

```
# podman run -d --name foo alpine sleep 60;podman stop foo;podman inspect --format '{{.State.Status}}' foo
2a5a082ef5dee2babb0ef4597984f640dd5e35194788c21f025399ca792e9991
2a5a082ef5dee2babb0ef4597984f640dd5e35194788c21f025399ca792e9991
exited
```

Caught by BATS tests (which expect, and have long expected, 'exited')

### PR DESCRIPTION
**Pull request by mheon**
We made changes earlier that empty storage options when setting storage driver explicitly. Unfortunately, this breaks rootless cleanup commands, as they lose the fuse-overlayfs mount program path.

Fix this by passing along the storage options to the cleanup process.

Also, fix --syslog, which was broken a while ago (probably when we broke up main to add main_remote).

Fixes #3326

### CODE REVIEW

**Comment by mheon** [comment]
@edsantiago PTAL. Can't promise this does anything about #3325 but I confirmed it fixes 3326.

**Comment by edsantiago** [comment]
Good news / bad news. You've fixed the problems when running as nonroot; but those problems (both 3325 and 3326) are now present when run as root. (via sudo, at least)

**Comment by edsantiago** [comment]
More news: the (root) hang on `podman logs -f` happens only when `mountopt = "nodev,metacopy=on"`. Without `metacopy`, both the container and the logs process exit fine. Have a nice day :-(

**Comment by mheon** [comment]
So... metacopy is breaking cleanup processes, somehow. That's rather confusing.

**Comment by mheon** [comment]
```
bin/podman[29233]: time="2019-06-13T17:38:35-04:00" level=error msg="could not get runtime: overlay: Unknown option metacopy"
```

**Comment by mheon** [comment]
This is rather confusing because I'm pretty sure metacopy is overlay-specific?

**Comment by edsantiago** [comment]
I can't reproduce that error message. I've tried using all manner of combinations of `driver` and `mountopt` in `storage.conf`.

Tomorrow is another day, and maybe the bits will behave better then.

**Comment by mheon** [comment]
@edsantiago `podman run -d -t --log-level=debug --syslog fedora sleep 60; podman stop --timeout=0 --latest` and check syslog - you'll see that error out of the podman cleanup process

**Comment by giuseppe** [comment]
LGTM

**Comment by giuseppe** [comment]
I confirm this fixes https://github.com/containers/libpod/issues/3325

**Comment by edsantiago** [comment]
@giuseppe please try it as root, with `driver = "overlay"` and `mountopt = "nodev,metacopy=on"`

**Comment by giuseppe** [comment]
`nodev,metacopy=on` should not be converted to `--storage-opt nodev --storage-opt metacopy=on` but to `--storage-opt $DRIVER.mountopt=nodev,metacopy=on`.  The issue now is that cobra splits the option in `$DRIVER.mountopt=nodev` and `metacopy=on` which is also not correct

**Comment by giuseppe** [comment]
with the following patch it seems to work for me:

```
diff --git a/cmd/podman/main_local.go b/cmd/podman/main_local.go
index b4f21bd0..132f35ab 100644
--- a/cmd/podman/main_local.go
+++ b/cmd/podman/main_local.go
@@ -48,7 +48,7 @@ func init() {
        rootCmd.PersistentFlags().StringVar(&MainGlobalOpts.Runtime, "runtime", "", "Path to the OCI-compatible binary used to run containers, default is /usr/bin/runc")
        // -s is depracated due to conflict with -s on subcommands
        rootCmd.PersistentFlags().StringVar(&MainGlobalOpts.StorageDriver, "storage-driver", "", "Select which storage driver is used to manage storage of images and containers (default is overlay)")
-       rootCmd.PersistentFlags().StringSliceVar(&MainGlobalOpts.StorageOpts, "storage-opt", []string{}, "Used to pass an option to the storage driver")
+       rootCmd.PersistentFlags().StringArrayVar(&MainGlobalOpts.StorageOpts, "storage-opt", []string{}, "Used to pass an option to the storage driver")
        rootCmd.PersistentFlags().BoolVar(&MainGlobalOpts.Syslog, "syslog", false, "Output logging information to syslog as well as the console")
 
        rootCmd.PersistentFlags().StringVar(&MainGlobalOpts.TmpDir, "tmpdir", "", "Path to the tmp directory")
```

**Comment by mheon** [comment]
Repushed with your patch @giuseppe - thanks

**Comment by mheon** [comment]
podman-in-podman seems like it might be failing consistently on the runlabel global options test...

Going to try again. If we get another failure I'll fix it.

**Comment by mheon** [comment]
Alright, I got a theory. Pushed a commit. Let's see...

**Comment by mheon** [comment]
Alright, that wasn't it...

**Comment by mheon** [comment]
Alright, I have no idea what's going on with the test failure here. No clues in the logs and I can't reproduce...

Probably going to just skip (for podman in podman only, if possible)

**Comment by mheon** [comment]
@haircommander @rhatdan @jwhonce Can I get a `/lgtm` and `/hold` on this one, so we can merge and start the release?

**Comment by mheon** [comment]
It's ready. Finally.
/hold cancel

**Pull request merged**
