### PR TITLE
Cirrus: Enable updates-testing repo for Fedora

### PR DESCRIPTION
**Pull request by cevich**
***CIRRUS: TEST IMAGES***

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by haircommander** [comment]
LGTM

**Comment by rhatdan** [comment]
/lgtm
/hold 
Feel free to `hold cancel` when this passes and podman 1.5 is released.

**Comment by haircommander** [comment]
@cevich uh we never actually got these vm images did we?

**Comment by cevich** [comment]
@haircommander probably not, but, err, they build successfully :grin: 

I've got a number of other PRs running that include new images, one of them will pick up this change.  Though if you need something sooner, let me know.

**Comment by haircommander** [comment]
nope no worries! can you ping me when the images get changed wherever they do? https://github.com/containers/libpod/pull/3792 is blocked on it

**Pull request merged**
