### PR TITLE
Validate ENV/LABEL Change options in varlink

### PR DESCRIPTION
**Pull request by rhatdan**
If you pass in an invalid CHANGE ENV or LABEL option without the "=" character
podman crashes.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Closes: https://github.com/containers/libpod/issues/2869

**Comment by baude** [comment]
LGTM

**Comment by mheon** [comment]
LGTM once we clear our lint issues

**Comment by mheon** [comment]
@rhatdan Rebase to fix lint and I'll merge

**Comment by rhatdan** [comment]
Please merge this when it finishes.

**Comment by rhatdan** [comment]
Closes: https://github.com/containers/libpod/issues/2869

**Comment by TomSweeneyRedHat** [comment]
Still unhappy tests @rhatdan

**Comment by rhatdan** [comment]
@mheon @baude @vrothberg @TomSweeneyRedHat @giuseppe Tests pass now can someone give this a /lgtm

**Pull request merged**
