### PR TITLE
rootless: add new netmode "slirp4netns"

### PR DESCRIPTION
**Pull request by giuseppe**
so that inspect reports the correct network configuration.

Closes: https://github.com/containers/libpod/issues/1453

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
I've marked it as WIP as I want to work more on this PR and add tests

**Comment by rhatdan** [comment]
So far LGTM

**Comment by giuseppe** [comment]
I wonder if we should open the possibility of using `slirp4netns` also to the root user and not having this special case only for rootless containers.

**Comment by AkihiroSuda** [comment]
Is slirp4netns useful for rootful mode?

**Comment by giuseppe** [comment]
> Is slirp4netns useful for rootful mode?

I think it is not.  I've only wanted to make it possible to use, if the user wishes so, but I cannot find any reason why do it.

**Comment by rhatdan** [comment]
Well I don't think we want it default, but would it be useful for running inside of a container which had not net-admin capabiltiies?

**Comment by giuseppe** [comment]
> but would it be useful for running inside of a container which had not net-admin capabiltiies?

probably yes.  It should enable the use case of running podman as root without having `CAP_NET_ADMIN`

**Comment by giuseppe** [comment]
all tests are green!

**Comment by vrothberg** [comment]
LGTM

**Comment by giuseppe** [comment]
@rhatdan @vrothberg there are two LGTM, can someone do the `/ lgtm`? :-)

**Comment by TomSweeneyRedHat** [comment]
LGTM and all happy green test buttons.

**Comment by vrothberg** [comment]
Ah. Didn't know one person can approve and do the lgtm.

**Pull request merged**
