### PR TITLE
v2, podman: propagate --network settings

### PR DESCRIPTION
**Pull request by giuseppe**
it fixes tests using --net=host

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
I think this should happen on the server side not in the client.

**Comment by mheon** [comment]
Client-side sounds right, but we should try and leave the namespace defaulted whenever possible so the server can autoselect slirp for rootless, and pod mode if in a pod.

**Comment by giuseppe** [comment]
should we drop `ContainerCLIOpts.Net` and just pass down strings?

**Comment by mheon** [comment]
We can definitely parse from string in the client...

Maybe we should move `containers.conf` parsing into the server, and only set network-related stuff in SpecGen if the user explicitly set it. That might be better than what we're doing.

**Comment by rhatdan** [comment]
The problem with doing that is the podman --help values start being incorrect.

**Comment by mheon** [comment]
I think we still display the default in the client code, but we only forward to the user if the flag was set - if it's the default we don't bother

**Comment by rhatdan** [comment]
@mheon Does your PR replace the need for this PR?

**Comment by mheon** [comment]
I think it does

**Comment by giuseppe** [comment]
> I think it does

How so?  I don't see any namespace setting from the CLI being honored.  It is also introducing other regressions (e.g. `--userns=auto` is not working again).

**Comment by giuseppe** [comment]
I'll work on the user namespace part and sync with @mheon once it is ready

**Pull request closed without merging**
