### PR TITLE
[ci skip] Add critical note about skip-ci and merge bot

### PR DESCRIPTION
**Pull request by cevich**
Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
hmmm, I think I want that warning to stand out a bit more...

**Comment by cevich** [comment]
[Rendered preview of changes](https://github.com/containers/libpod/blob/8fdbbcd34008a80f790ae29a1b067ffcdcfbfe58/CONTRIBUTING.md#bot-interactions)

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
