### PR TITLE
Only modify conmon cgroup if we have running containers

### LINKED ISSUE #5072: f31 rootless: podman pod rm: error updating pod: .../pids.max: no such file or directory
```console
$ podman pod create --name=foo
fae80ab038ebb1cd8a3e32d8e6e098b6795f260e36652ba7b5aa34cbd1d6d12e
$ podman pod rm foo
Error: error updating pod fae80ab038ebb1cd8a3e32d8e6e098b6795f260e36652ba7b5aa34cbd1d6d12e conmon group: open /sys/fs/cgroup/libpod_parent/fae80ab038ebb1cd8a3e32d8e6e098b6795f260e36652ba7b5aa34cbd1d6d12e/conmon/pids.max: no such file or directory
$ echo $?
125
```
podman-1.8.0-0.1.fc31.x86_64
crun-0.11-1.fc31.x86_64
conmon-2.0.10-2.fc31.x86_64

### PR DESCRIPTION
**Pull request by mheon**
If there are no running containers - for example, if the pod was just created - the cgroup in question may not exist (under certain circumstances that we're not 100% sure about). However, regardless, we don't need to set a PID limit, as nothing will be making cleanup processes (no running conmon processes), so not changing the cgroup is safe regardless.

Fixes #5072

### CODE REVIEW

**Comment by mheon** [comment]
@edsantiago Poke - can I bother you to test this? I think this fixes it, but I'm not certain.

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by edsantiago** [comment]
LGTM. In log below, `podman` is rpm-installed, `podman.X` is built from sources with your patch:
```console
$ podman pod create --name=foo
a28021a6497946873bbe6355e10761db5803d4cc5826bea685ab76da248768ec
$ podman pod rm foo
Error: error updating pod a28021a6497946873bbe6355e10761db5803d4cc5826bea685ab76da248768ec conmon group: open /sys/fs/cgroup/libpod_parent/a28021a6497946873bbe6355e10761db5803d4cc5826bea685ab76da248768ec/conmon/pids.max: no such file or directory


$ podman.X pod create --name=foo
5df02bf436d37769d9948d2b24bde24b7f77ba619dfac21af90c5063c0bf1a26
$ podman.X pod rm foo
5df02bf436d37769d9948d2b24bde24b7f77ba619dfac21af90c5063c0bf1a26
```

**Comment by edsantiago** [comment]
tests are flaking
/hold

**Comment by mheon** [comment]
I've seen the in-podman flake a few times this morning - I think we might be having registry issues

**Comment by edsantiago** [comment]
Yeah, fedora registry is definitely hosed

**Comment by edsantiago** [comment]
Now I'm seeing what look like real failures tho:
```
Error: error configuring network namespace for container c91448b0b75d0130791956204d7c170711d99c76fa3c185f999daa43e9dbbeb2: running [/usr/sbin/iptables -t filter -N CNI-ADMIN --wait]: exit status 1: iptables v1.8.2 (nf_tables): Chain already exists
....
Running: podman [options] --events-backend file --storage-driver=vfs pod rm -f test1
[+0559s] time="2020-02-05T20:09:59Z" level=error msg="Error deleting pod eb696dc6a5291d20a8a7bcbe82cf64ebf02a6c4c656ff7b704ea76760ee261a0 cgroup /libpod_parent/eb696dc6a5291d20a8a7bcbe82cf64ebf02a6c4c656ff7b704ea76760ee261a0: remove /sys/fs/cgroup/systemd/libpod_parent/eb696dc6a5291d20a8a7bcbe82cf64ebf02a6c4c656ff7b704ea76760ee261a0: remove /sys/fs/cgroup/systemd/libpod_parent/eb696dc6a5291d20a8a7bcbe82cf64ebf02a6c4c656ff7b704ea76760ee261a0/conmon: remove /sys/fs/cgroup/systemd/libpod_parent/eb696dc6a5291d20a8a7bcbe82cf64ebf02a6c4c656ff7b704ea76760ee261a0/conmon: device or resource busy"
...
https://api.cirrus-ci.com/v1/task/5519400170160128/logs/integration_test.log#t--podman-pod-rm--fa-removes-everything

**Comment by mheon** [comment]
Oh no. That's the case that we were trying to fix with this code in the first place - ensuring that cleanup processes never spawned.

**Comment by edsantiago** [comment]
Good news, bad news. Good news first: I can reproduce [the failure](https://api.cirrus-ci.com/v1/task/6243504007413760/logs/integration_test.log#t--podman-pod-rm-removes-a-pod-with-a-container) on f30:
```
# podid=$(podman --cgroup-manager=cgroupfs pod create --infra=false --share='');podman --cgroup-manager=cgroupfs run --pod $podid -d alpine ls;podman --cgroup-manager=cgroupfs pod rm $podid
44e9dc690aee39b33059cc12a58663b23c77a1219f4b08707f923a0fb6d3e98b
ERRO[0000] Error deleting pod 3f90166a3d10ef8627caca66045560db5c238ff5c488f77563ebe3d5bb2f0771 cgroup /libpod_parent/3f90166a3d10ef8627caca66045560db5c238ff5c488f77563ebe3d5bb2f0771: remove /sys/fs/cgroup/systemd/libpod_parent/3f90166a3d10ef8627caca66045560db5c238ff5c488f77563ebe3d5bb2f0771: remove /sys/fs/cgroup/systemd/libpod_parent/3f90166a3d10ef8627caca66045560db5c238ff5c488f77563ebe3d5bb2f0771/conmon: remove /sys/fs/cgroup/systemd/libpod_parent/3f90166a3d10ef8627caca66045560db5c238ff5c488f77563ebe3d5bb2f0771/conmon: device or resource busy
Error: error removing pod 3f90166a3d10ef8627caca66045560db5c238ff5c488f77563ebe3d5bb2f0771 conmon cgroup: remove /sys/fs/cgroup/systemd/libpod_parent/3f90166a3d10ef8627caca66045560db5c238ff5c488f77563ebe3d5bb2f0771/conmon: remove /sys/fs/cgroup/systemd/libpod_parent/3f90166a3d10ef8627caca66045560db5c238ff5c488f77563ebe3d5bb2f0771/conmon: remove /sys/fs/cgroup/systemd/libpod_parent/3f90166a3d10ef8627caca66045560db5c238ff5c488f77563ebe3d5bb2f0771/conmon: device or resource busy
```
Bad news: I can also reproduce on master, without your patch. I think this is a broken test: I think there's a race condition, because adding `sleep 5` between the `podman run` and `podman pod rm` makes the problem go away. If I had to guess, I'd say `podmanTest.RunLsContainerInPod()` should not be running with `-d` or at least the test should wait for the container to finish, but ginkgo makes my head hurt so I'm not going to guess.

I don't know if we're seeing real failures or not, and am giving up for the day.

**Comment by mheon** [comment]
That is plan B if I can't get this approach to work

**Comment by mheon** [comment]
Fedora registries being problematic again

**Comment by mheon** [comment]
@rhatdan @vrothberg @baude Anyone want to hit this one with a held LGTM? Last flake should be going green soon

**Comment by rhatdan** [comment]
@mheon wishful thinking on the flake.

**Pull request merged**
