### PR TITLE
APIv2:doc: Fix swagger doc to refer to volumes

### PR DESCRIPTION
**Pull request by maybe-sybr**

### CODE REVIEW

**Comment by maybe-sybr** [comment]
From reading the contrib guide, it sounds like I need to just add sign-off on the commit here (and any future PRs). Since my account is a pseud, is signing off with my real name and the github proxied email address okay?

**Comment by mheon** [comment]
That should be fine

**Comment by mheon** [comment]
/approve
/ok-to-test
LGTM

**Comment by maybe-sybr** [comment]
Thanks @mheon - new commit pushed. LMK if you need anything else from me here :)

**Pull request merged**
