### PR TITLE
fix `podman -v` regression

### PR DESCRIPTION
**Pull request by vrothberg**
Re-add the shortflag for --version and add e2e tests to avoid regressing
in the future.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
CI is sick atm, see https://github.com/containers/libpod/pull/3647

**Comment by mheon** [comment]
I think that we had to remove this because Cobra really, strongly disliked having `-podman run -v src:dst:options` and `podman -v` both be possible... Might be misremembering, though

**Comment by mheon** [comment]
```[+2466s] panic: unable to redefine 'v' shorthand in "rm" flagset: it's already used for "volumes" flag```

Yep, I think that's our culprit here.

**Comment by baude** [comment]
@mheon you are right

**Comment by rhatdan** [comment]
Seems like a bug in cobra, but not something we can easily fix.

**Comment by vrothberg** [comment]
I read a bit through the docs and found a solution. The issue was that `--version` was marked as a persistent flag, so it was propagated to all subcommands. Making it a local flag solved the issue.

This comes at the cost of `./bin/podman --version run alpine ls` really executing a container and the `--version` being ignored. Personally I prefer the new behaviour.

**Comment by TomSweeneyRedHat** [comment]
All kinds of test unhappiness @vrothberg

**Comment by vrothberg** [comment]
> All kinds of test unhappiness @vrothberg

That was a brain fart in the tests I added. `s/BeFalse/BeTrue` will fix it :)

**Comment by mheon** [comment]
Huh. Nice to know we can work around issues like this.

Code LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM but would like a head nod from @baude

**Comment by rhatdan** [comment]
This makes sense to me.
Since podman run -v ... continues to work.
/lgtm

**Pull request merged**
