### PR TITLE
Vendor in containers/storage v1.12.16

### PR DESCRIPTION
**Pull request by rhatdan**
This will allow podman to run with a single rootless UID Map and ignore
chown errors.  Potential use case for HPC Customers.

Other optimizations and bugfixes in containers/storage.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM once tests go green

**Comment by vrothberg** [comment]
I can reproduce locally and will take a look

```
[+0400s] TYPE            TOTAL   ACTIVE   SIZE    RECLAIMABLE
[+0400s] Images          8       2        111MB   109MB (98%)
[+0400s] Containers      2       0        0B      0B (0%)
[+0400s] Local Volumes   1       1        0B      0B (0%)
...
[+0400s]   Expected
[+0400s]       <string>: 8
[+0400s]   to equal
[+0400s]       <string>: 9
[+0400s] 
[+0400s]   /var/tmp/go/src/github.com/containers/libpod/test/e2e/system_df_test.go:59
```

**Comment by vrothberg** [comment]
`/var/tmp/go/src/github.com/containers/libpod/test/e2e/system_df_test.go:59` is also failing on master. I'll try to fix it there so you can rebase here.

**Pull request merged**
