### PR TITLE
podman remote cp

### PR DESCRIPTION
**Pull request by QiWang19**
support podman cp on the remote. This enables copy file/folder between remote container and Podman nodes

Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by baude** [comment]
Ill review this when I get back from PTO.

**Comment by baude** [comment]
@QiWang19 My general comment here is that we should be able to do this function without adding multiple endpoints, specifically, to the varlink API. 

For example, there should be a Copy endpoint.  When the remote client connects to the endpoint, it should call into the copy endpoint.  that endpoint, depending on how you set this up, should call a libpod API for Copy or at worst several APIs.  The reason you want less calls is so you don't have to duplicate this for the local client calls.

there are already calls for sending and receiving files through varlink. see export, import, save, load for examples of that and I can of course help.

**Comment by mheon** [comment]
@baude Honestly I think we should have separate endpoints for copying into the container, and copying out of the container... we can share the code on the backend if we want, but it gets really confusing determining how copy works otherwise IMO

**Comment by baude** [comment]
> @baude Honestly I think we should have separate endpoints for copying into the container, and copying out of the container... we can share the code on the backend if we want, but it gets really confusing determining how copy works otherwise IMO

thats fine, i dont care where the logic lives.

**Comment by QiWang19** [comment]
inside this function [func (r *LocalRuntime) Copy](https://github.com/containers/libpod/pull/3327/files#diff-4d0250b516fbac4efaf286206cfa3d3fR1171) I called functions that uses the varlink API `SendFileOverVarlink`, and `GetFileFromRemoteHost`, I think this follows the comment above. 

But the file was sent to /tmp, I want to move/untar it to the path inside the container, and also need to do `os.Stat()` to the path related with the remote, I don't kown how to make this so I added two the varlink APIs to help this. How can I make it better?

**Pull request closed without merging**
