### PR TITLE
Add the missing return in the API handlers' image_build method

### PR DESCRIPTION
**Pull request by zhangguanzhang**
Signed-off-by: zhangguanzhang <zhangguanzhang@qq.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Should there be one here as well https://github.com/containers/libpod/blob/31cf1b38550ee9a5c5662333e692fcca9958bee0/pkg/api/handlers/compat/images_build.go#L266

**Comment by zhangguanzhang** [comment]
@rhatdan PTAL,  I updated the code submission

**Comment by rhatdan** [comment]
LGTM
But would want @jwhonce @baude @mheon To review.

**Comment by mheon** [comment]
LGTM, but would prefer to wait to merge until @jwhonce can look

**Pull request merged**
