### PR TITLE
podmanv2 events

### PR DESCRIPTION
**Pull request by baude**
add the ability to monitor events

Signed-off-by: Brent Baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by vrothberg** [comment]
I am getting the following error on all invocations:
```
libpod (v2events) $ sudo ./cmd/podmanV2/podmanV2 events
ERRO[0000] failed to read message field: bad message    
```

V1 does not throw it. I try to have a look but today is filled with meetings until late :/

**Pull request merged**
