### PR TITLE
Release notes for 1.3.1

### PR DESCRIPTION
**Pull request by mheon**
As the title says

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@mheon heads up, ubuntu tests aren't hip

**Comment by mheon** [comment]
What the hell? These are the pod removal flakes we just fixed

**Comment by mheon** [comment]
Alright, hold this for a bit. We have more things that need to go in and will need release notes.

**Comment by mheon** [comment]
Rebased, updated with the extra PRs that got in.

**Comment by mheon** [comment]
It's green. Anyone want to hit this with an LGTM?

**Pull request merged**
