### PR TITLE
tests: fix rootless tests with an updated runc

### PR DESCRIPTION
**Pull request by giuseppe**

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe Why is this a WIP PR?

**Comment by giuseppe** [comment]
@rhatdan I have to see if it is enough to get the CI tests working or I'll have to do more changes

**Comment by giuseppe** [comment]
ok it is a regression in runc, PR here: https://github.com/opencontainers/runc/pull/1918

**Comment by rhatdan** [comment]
LGTM
@mheon @umohnani8 @baude @vrothberg PTAL

**Pull request merged**
