### PR TITLE
goland autocorrections

### PR DESCRIPTION
**Pull request by baude**
just ran the autocorrect code corrections from goland and it found a few
nits.

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@mheon @vrothberg @giuseppe @QiWang19 @TomSweeneyRedHat @jwhonce PTAL

**Comment by giuseppe** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM if you can get the tests happy

**Comment by rhatdan** [comment]
I am not sure if this needs a rebase to fix the testing_in_podman issue.

**Comment by jwhonce** [comment]
Once test pass you can /hold cancel

/hold
/lgtm

**Pull request merged**
