### PR TITLE
Add ability to specify static IPs with --ip flag

### PR DESCRIPTION
**Pull request by mheon**
Missing tests, but otherwise ready.

Vendor an updated OCICNI to allow specifying static IP Addresses when launching containers. The addresses must be within the CNI default network range.

### CODE REVIEW

**Comment by mheon** [comment]
We have bash completions

**Comment by mheon** [comment]
Tests added

**Comment by mheon** [comment]
Codewise this should be finished now. @umohnani8 @vrothberg @rhatdan @baude @TomSweeneyRedHat  PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM, but tests are teetering.

**Comment by umohnani8** [comment]
LGTM

**Comment by mheon** [comment]
Tests green. @baude Mind dropping an LGTM on this?

**Pull request merged**
