### PR TITLE
vendor c/psgo@v1.3.2

### PR DESCRIPTION
**Pull request by vrothberg**
Now supports cgroupsv2.

Fixes: #4192
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@rhatdan @giuseppe PTAL

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
Tested locally and fixes my issue.
/lgtm
/hold
hold cancel when tests pass.

**Pull request merged**
