### PR TITLE
Close tarSource when finished using it

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1797599

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@mtrmac @vrothberg PTAL

**Comment by rhatdan** [comment]
@mheon @baude @TomSweeneyRedHat @QiWang19 PTAL

**Comment by mheon** [comment]
LGTM once things go green

**Pull request merged**
