### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by fzoske**

### CODE REVIEW

**Comment by mheon** [comment]
Needs a signoff - `git commit --amend -s` and re-push.

Otherwise, changed LGTM.
/approve
/ok-to-test

**Comment by TomSweeneyRedHat** [comment]
Thanks for the PR @fzoske 
LGTM once signed.

**Comment by rhatdan** [comment]
@mheon @TomSweeneyRedHat Is there anyway for us to get this added via the website.  I think a lot of these fixes come directly from people going to the website and opening a PR.  If there was a way to sign from the Website or to at least tell people to sign then we could avoid the back and forth.

**Comment by mheon** [comment]
That's on the Github side of things - I'll check, but I don't think you can do it easily through Github's webpage.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan @mheon I know on some projects you can directly change things from the website on GitHub.  There must be some bits buried deep in the settings for the libpod project that we could turn on, but I don't know where they lie.

**Comment by fzoske** [comment]
@TomSweeneyRedHat signed the commit

**Comment by rhatdan** [comment]
/lgtm
/hold
Feel free to cancel the hold once tests pass.
Thanks @fzoske welcome to libpod/podman

**Pull request merged**
