### PR TITLE
Docs improvement

### PR DESCRIPTION
**Pull request by vrothberg**

### CODE REVIEW

**Comment by vrothberg** [comment]
This PR addresses only some of the format and layout issues. No changes to any content.

**Comment by TomSweeneyRedHat** [comment]
LGTM
Really nice scrubbing @vrothberg, TYVM!
Smoke tests aren't hip though.

**Comment by vrothberg** [comment]
bot, retest this please

**Comment by vrothberg** [comment]
Thanks, @TomSweeneyRedHat. I restarted the tests; again a timeout.

**Comment by rhatdan** [comment]
`$ podman ...`
Indicates you run this command as non root
`# podman ...` 
indicates you execute the command as root.

Does changing these would indicate we want people to run these commands as non root?

**Comment by vrothberg** [comment]
> Does changing these would indicate we want people to run these commands as non root?

I wasn't aware of that at all. But it doesn't seem to be used consistently as some cases where `$ sudo podma ...`. I would prefer to leave a note in the description of each command that it works rootless as well, which I consider to be more explicit and easier to understand.

**Comment by TomSweeneyRedHat** [comment]
FWIW, when I see '$' in a man page, I think I can run it as either non-root or root.  If there's a '#' there, then I'm thinking only root.  When I saw the changes that added the '$' I liked it as a subtle way to show that you can run them as non-root.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
