### PR TITLE
Turn on Fedora31 testing.

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
Fedora looks like it's working. Ubuntu is failing on a registry system test, looks like?

**Comment by rhatdan** [comment]
@mheon Split the pr into Fedora and Ubuntu to try to get the Fedora tests turned on.

**Comment by rhatdan** [comment]
@baude @mheon @TomSweeneyRedHat @giuseppe @vrothberg @QiWang19 @jwhonce PTAL
This one is ready to go in, and turns on another platform test.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
