### PR TITLE
Show volume options in 'volume inspect'

### PR DESCRIPTION
**Pull request by mheon**
We initialized the map to show them, but didn't actually copy them in, so they weren't being displayed.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat @giuseppe @baude @jwhonce @QiWang19 @vrothberg PTAL

**Comment by rhatdan** [comment]
@mheon Should probably add a tests to make sure we don't regress in the future.

**Comment by mheon** [comment]
Added a test

**Comment by mheon** [comment]
```

[+1174s] Running: (env: [PODMAN_VARLINK_ADDRESS=unix:/run/podman/io.podman-58a3d2dabb74c90295a4e9266c269f590d2fdf7d760a0416b9a6353609178a13]) /var/tmp/go/src/github.com/containers/libpod/bin/podman-remote volume inspect testvol
[+1174s] [
[+1174s]      {
[+1174s]           "Runtime": {
[+1174s]                "Conn": {
[+1174s]                     "Closer": null,
[+1174s]                     "Reader": {},
[+1174s]                     "Writer": {}
[+1174s]                },
[+1174s]                "Remote": true
[+1174s]           }
[+1174s]      }
[+1174s] ]
[+1174s] output: [ { "Runtime": { "Conn": { "Closer": null, "Reader": {}, "Writer": {} }, "Remote": true } } ]
```

Well that doesn't look right. I think `volume inspect` is rather broken for remote.

**Comment by mheon** [comment]
I have rewritten the remote endpoint for `volume inspect` in a way that will hopefully resolve this

**Comment by mheon** [comment]
Tests passing now
@rhatdan @baude @vrothberg @giuseppe @TomSweeneyRedHat PTAL

**Pull request merged**
