### PR TITLE
docs: symlink to host device is resolved

### PR DESCRIPTION
**Pull request by stefanb2**
Also apply changes from commit 3fd9f0c028f9dab7c8923629d4dc5d38e594db1a
to the other two commands that have the --device option.

Documents #4550

Signed-off-by: Stefan Becker <chemobejk@gmail.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
/ok-to-test
LGTM

**Comment by rhatdan** [comment]
Thanks @stefanb2

**Comment by mheon** [comment]
LGTM

**Pull request merged**
