### PR TITLE
Fix up play kube to use image data

### PR DESCRIPTION
**Pull request by rhatdan**
podman play kube was ignoring the
imageData.Config
   Volumes
   WorkingDir
   Labels
   StopSignal

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@haircommander @baude PTAL

**Comment by rhatdan** [comment]
Fixes: https://github.com/containers/libpod/issues/5174

**Comment by rhatdan** [comment]
@gfokkema  PTAL

**Comment by gfokkema** [comment]
Wow that was fast!

Just finished compiling, below looks good to me!
```
┌─gerlof@gerlof-laptop ~/docker/demo $
└─╼cat demo.Dockerfile 
FROM alpine:latest
WORKDIR /bin
CMD ["pwd"]
┌─gerlof@gerlof-laptop ~/docker/demo $
└─╼cat demo.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: demo_pod
spec:
  containers:
  - image: localhost/demo:1.0
    name: demo_kube
┌─gerlof@gerlof-laptop ~/docker/demo $
└─╼sudo podman play kube demo.yaml 
Pod:
f52609fbfd31a8a7bc68853f00d1020e4741c06fa8650bd98c2494e48ec6f74d
Container:
124dd351e82ee6948f8410292824a9c8add49c29f76c4596c48dd06ff72edb83
┌─gerlof@gerlof-laptop ~/docker/demo $
└─╼sudo podman logs 124dd351e82ee6948f8410292824a9c8add49c29f76c4596c48dd06ff72edb83
/bin
```

**Comment by mheon** [comment]
LGTM

**Comment by haircommander** [comment]
LGTM, though some test cases would be nice 🙂

**Comment by rhatdan** [comment]
@haircommander Tests took longer to write then fix the bug.  Lets see if they pass, then we can merge.

**Pull request merged**
