### PR TITLE
play kube: refactor test suite

### PR DESCRIPTION
**Pull request by haircommander**
The play kube test suite has many different cases to cover, and should only grow in coverage over time

The old design was difficult to extend, and there was lots of duplicated code.
The largest pain point was the Container struct needed to be changed often, and doing so caused changes to every test case

Instead, adopt the `withOption` idiom. Now, adding a new option for customizing just involves adding a new withOption function, and changing the struct definition and initialization in one place.

also s/Container/Ctr/ because it is more brief and easier to read IMO

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by rhatdan** [comment]
LGTM but tests are failing.

**Comment by haircommander** [comment]
happy tests PTAL

**Pull request merged**
