### PR TITLE
rootless: store only subset of storage.conf

### PR DESCRIPTION
**Pull request by giuseppe**
do not store the entire file but only the subset of what we have
modified.  Also, we were not writing the correct data.  Since it is
not trivial to serialize storage.conf correctly and all the various
supported options, serialize only what we care about.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
this is how the generated `storage.conf` file looks like now:
```toml
[storage]
  driver = "overlay"
  runroot = "/run/user/1000"
  graphroot = "/home/foo/.local/share/containers/storage"
  [storage.options]
    mount_program = "/usr/bin/fuse-overlayfs"
```

**Comment by umohnani8** [comment]
LGTM

**Comment by mheon** [comment]
LGTM - solid change

**Comment by mheon** [comment]
I'm going to assume the papr stuff is just papr being papr

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by rhatdan** [comment]
/retest
bot, retest this please

**Pull request merged**
