### PR TITLE
add dns flags to docs

### PR DESCRIPTION
**Pull request by ashley-cui**
Added same dns flags from buildah documentation to podman
documents https://github.com/containers/libpod/issues/2755

Signed-off-by: Ashley Cui <ashleycui16@gmail.com>

### CODE REVIEW

**Comment by ashley-cui** [comment]
@rhatdan PTAL

**Comment by baude** [comment]
bot, add author to whitelist

**Comment by baude** [comment]
LGTM. @ashley-cui welcome to the game!

**Comment by mheon** [comment]
We really need a better way of syncing manpages for podman-build and buildah-bud, but that's entirely out of scope for this... LGTM, congrats on your first PR!

**Comment by rhatdan** [comment]
LGTM
closes: #2755

**Pull request merged**
