### PR TITLE
slirp4netns: use --disable-host-loopback

### PR DESCRIPTION
**Pull request by giuseppe**
Closes: https://github.com/containers/libpod/issues/2642

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by giuseppe** [comment]
looks like there are two broken tests but still the openshift-robot merged :(

**Comment by mheon** [comment]
I don't know if I trust it anymore - it doesn't seem to work well for our multi-CI-system environment.

We might have to start restricting /lgtm to having manually inspected all the tests and verified they are green.

**Comment by giuseppe** [comment]
@mheon: PR here: https://github.com/containers/libpod/pull/2653

**Pull request merged**
