### PR TITLE
Modify papr scripts to get better insight into failures

### PR DESCRIPTION
**Pull request by mheon**
As recommended by @jlebon in https://github.com/projectatomic/papr/issues/101

Should help to debug our timeout-after-clean-exit issues

### CODE REVIEW

**Comment by mheon** [comment]
bot, retest this please

**Comment by mheon** [comment]
@jlebon I added the journal artifact as you suggested - but it doesn't seem to be firing (see CAH smoketested). This seems to mean that the container runtime is returning cleanly?

**Comment by jlebon** [comment]
> This seems to mean that the container runtime is returning cleanly?

Yeah, I think you're right. Will take a closer look.

**Comment by mheon** [comment]
I think we're set to close this

**Pull request closed without merging**
