### PR TITLE
Add dependency for python3-psutil module

### PR DESCRIPTION
**Pull request by jwhonce**
Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by baude** [comment]
LGTM

**Comment by jwhonce** [comment]
@lsm5 Is this enough to get packaging working across platforms?

**Comment by jwhonce** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by jwhonce** [comment]
bot, retest this please

**Comment by jwhonce** [comment]
bot, retest this please

**Comment by baude** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
