### PR TITLE
vendor: update container/storage

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
Sure, LGTM
/approve

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@giuseppe needs a rebase.

**Comment by mheon** [comment]
@giuseppe Mind rebasing to pick up CI fixes?

**Comment by giuseppe** [comment]
tests are passing

**Pull request merged**
