### PR TITLE
rootless: do not enable lingering mode

### PR DESCRIPTION
**Pull request by giuseppe**
do not automatically enable lingering mode.

Closes: https://github.com/containers/libpod/issues/4224

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by cgwalters** [comment]
/approve

BTW, even if a user has lingering enabled, that doesn't mean they want all libpod containers to linger.  Or to say it another way, there should probably be an option like `--bind-to-session` or something to have them die with the last session.  (Think about the case of running some desktop app inside a podman container)

**Comment by rhatdan** [comment]
@giuseppe Why not add a `podman create --linger` flag and leave the code, then users could create containers that remain running, if the user session is set to linger.

**Comment by giuseppe** [comment]
rebased.


> @giuseppe Why not add a `podman create --linger` flag and leave the code, then users could create containers that remain running, if the user session is set to linger.

if the user session is configured to linger, then the containers remain running also now.

The original code was doing it silently, to behave more like root users.  IMO, an additional command flag is equivalent to suggest using `loginctl enable-linger $UID`.

**Comment by giuseppe** [comment]
tests are green

**Pull request merged**
