### PR TITLE
fix tutorial link to install.md

### PR DESCRIPTION
**Pull request by juhp**

### CODE REVIEW

**Comment by juhp** [comment]
Done finally

**Comment by TomSweeneyRedHat** [comment]
LGTM
I'm not sure why prow is thinking for so long....

**Comment by rhatdan** [comment]
bot, add author to whitelist

**Comment by dustymabe** [comment]
> @juhp: The following test **failed**, say `/retest` to rerun them all:

noise because couldn't sync down fedora modular repo: `Error: Failed to synchronize cache for repo 'fedora-modular'`

**Pull request merged**
