### PR TITLE
HACK Update container-selinux on host

### PR DESCRIPTION
**Pull request by mheon**
Let's see if this fixes our CI issues.

### CODE REVIEW

**Comment by mheon** [comment]
I took at look at regenerating the base images we use (the correct fix) but I've never really worked with GCP before, so I got a little lost. This band-aid will hopefully resolve things until we can get a proper fix worked up.

**Comment by rhatdan** [comment]
LGTM, if this passes test.

**Comment by mheon** [comment]
Hm. Doesn't look like container-selinux is the problem.

**Comment by rhatdan** [comment]
Test timed out, not the same error, I am running tests again.

**Comment by rhatdan** [comment]
Fixed in upstream.

**Pull request closed without merging**
