### PR TITLE
rootless: fix regression when using exec on old containers

### PR DESCRIPTION
**Pull request by giuseppe**
fallback to the previous behavior of joining only the user namespace,
when we cannot join the conmon userns+mount namespaces.

Closes: https://github.com/containers/libpod/issues/2673

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
@debarshiray Can you test this and verify it resolves the regression with exec?
Code LGTM

**Comment by baude** [comment]
code LGTM

**Comment by rhatdan** [comment]
:+1:

**Comment by TomSweeneyRedHat** [comment]
Code LGTM, but tests aren't hip.

**Comment by mheon** [comment]
@giuseppe Mind rebasing to pick up CI fixes?

**Comment by giuseppe** [comment]
@debarshiray had a chance to test it?

**Comment by debarshiray** [comment]
Yes, this unbreaks `podman exec` with containers created using 1.1.2 and older Podman versions. Thanks everybody.

**Comment by mheon** [comment]
Good enough for me!
/lgtm

**Pull request merged**
