### PR TITLE
Add support & documentation to run containers with different file types

### PR DESCRIPTION
**Pull request by rhatdan**
Add tests to make sure users can change file types

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@wrabcak FYI

**Comment by rhatdan** [comment]
@mheon @baude @giuseppe @vrothberg @TomSweeneyRedHat PTAL

**Comment by mheon** [comment]
Code LGTM, considering it's just a revendor. Docs also look fine.

**Comment by rhatdan** [comment]
@mheon Hey I also added a tests.... :+1:

**Comment by vrothberg** [comment]
New tests aren't happy yet
```
[+0897s] [Fail] Podman run [It] podman run selinux file type setup test 
[+0897s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/run_selinux_test.go:159
```

**Comment by rhatdan** [comment]
@vrothberg Trying again.

**Comment by rhatdan** [comment]
@vrothberg @giuseppe @TomSweeneyRedHat @ashley-cui @QiWang19 @jwhonce @baude PTAL
Lets get this merged.

**Pull request merged**
