### PR TITLE
Update Code of Conduct to Containers variant

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
As the title says.  I renamed the old file from the lower case to the
upper case name.  This makes it appear higher up in the listing on GitHub
and also is in line with the rest of the containers projects.  Due to this
change, I also had to change a few references in a couple of build related
files.

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM but tests are red

**Comment by TomSweeneyRedHat** [comment]
Thanks for the heads up @mheon, I'd a trailing blank line that the validator didn't like.  Touched that up and added the CI:DOCS tag.

**Comment by TomSweeneyRedHat** [comment]
The RHEL 8 build failed, but all the other rpm builds completed.  The failure doesn't look to be related to this change, but I'm not 100% certain.  @mheon is there a way to restart the test?

```
2020-02-10 14:33:07.081869 | test | Error: Unable to find a match: device-mapper-devel glibc-static go-compilers-golang-compiler gpgme-devel libassuan-devel
2020-02-10 14:33:07.124595 | test | make: *** [Makefile:626: package] Error 1
2020-02-10 19:33:07.214696 | test | ERROR
```

**Pull request merged**
