### PR TITLE
Make list of approvers same as reviewers

### PR DESCRIPTION
**Pull request by rhatdan**
Can't see any reason for a difference here. If you can review, you can approve.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
LGTM (waiting for green tests)

**Comment by rhatdan** [comment]
@mheon @umohnani8 @baude @giuseppe PTAL

**Comment by TomSweeneyRedHat** [comment]
So much power now!
LGTM, but I'm fine if I'm only a reviewer.

**Comment by giuseppe** [comment]
LGTM

**Pull request merged**
