### PR TITLE
WIP: move to sysregistriesv2

### PR DESCRIPTION
**Pull request by vrothberg**
Work in progress...

Signed-off-by: Valentin Rothberg <vrothberg@suse.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@vrothberg Can we get this one moving again now?

**Comment by vrothberg** [comment]
> @vrothberg Can we get this one moving again now?

It is moving, but all work is being done `containers/image` at the moment. The `sysregistriesv2` has been updated, and currently we're sorting out some rough edges regarding TLS verification. Once that's done, the pull code from libpod and buildah goes into `containers/image/docker`. Then we can update libpod, buildah and skopeo and all will have sysregsv2 support including mirrors etc.

**Comment by mheon** [comment]
bot, add author to whitelist

**Comment by rhatdan** [comment]
@vrothberg Needs a rebase.

**Comment by vrothberg** [comment]
We can finally close this one. There's #1930 now, which does all the integration.

**Pull request closed without merging**
