### PR TITLE
Should be defaulting to pull not pull-always

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @vrothberg @mheon @baude @giuseppe PTAL

**Comment by mheon** [comment]
We need to verify that this will pull an updated image if the image is present locally but a newer version of the tag is on the registry

**Comment by TomSweeneyRedHat** [comment]
Addresses: #2469

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.  This fixes the reported issue, I'm just spending a little time seeing if we should get the local image if all of the registries fail.  I think we should, but need to poke further.

**Comment by TomSweeneyRedHat** [comment]
@mheon I pulled an image, updated it by touching `/mynewtest.txt`, verified the file was present, repulled and then saw the file was no longer there.  A little opposite of what you were asking for, bu I think we're covered.

```
# podman pull docker://quay.io/tomsweeneyredhat/myalpine:latest 
Trying to pull docker://quay.io/tomsweeneyredhat/myalpine:latest...Getting image source signatures
Copying blob 8e3ba11ec2a2 [======================================] 1.4GiB / 1.4GiB
Copying blob a3ed95caeb02 [======================================] 1.4GiB / 1.4GiB
Writing manifest to image destination
Storing signatures
11cd0b38bc3ceb958ffb2f9bd70be3fb317ce7d255c8a4c3f4af30e298aa1aab

# podman images
REPOSITORY                          TAG      IMAGE ID       CREATED        SIZE
quay.io/tomsweeneyredhat/myalpine   latest   11cd0b38bc3c   7 months ago   4.68 MB

# podman run --net=host 11cd0b38bc3c touch /mynewtest.txt
# podman ps -a
CONTAINER ID  IMAGE                                     COMMAND               CREATED         STATUS                     PORTS  NAMES
b7b8dcf0fc5c  quay.io/tomsweeneyredhat/myalpine:latest  touch /mynewtest....  10 seconds ago  Exited (0) 10 seconds ago         condescending_curie

# podman commit b7b8dcf0fc5c quay.io/tomsweeneyredhat/myalpine
Getting image source signatures
Copying blob 73046094a9b8 [======================================] 4.5MiB / 4.5MiB
Copying blob 11f58c859b3a [======================================] 4.0KiB / 4.0KiB
Copying config 75be1a8b36 [======================================] 795b / 795b
Writing manifest to image destination
Storing signatures
75be1a8b36117fdaabc81279966019eba5bf7e19f358b32169551ca75838c474

# podman run quay.io/tomsweeneyredhat/myalpine ls /
bin
dev
etc
home
lib
media
mnt
mynewtest.txt
proc
root
run
sbin
srv
sys
tmp
usr
var

# podman pull docker://quay.io/tomsweeneyredhat/myalpine:latest 
Trying to pull docker://quay.io/tomsweeneyredhat/myalpine:latest...Getting image source signatures
Copying blob 8e3ba11ec2a2 [======================================] 1.4GiB / 1.4GiB
Copying blob a3ed95caeb02 [======================================] 1.4GiB / 1.4GiB
Writing manifest to image destination
Storing signatures
11cd0b38bc3ceb958ffb2f9bd70be3fb317ce7d255c8a4c3f4af30e298aa1aab

# podman images
REPOSITORY                          TAG      IMAGE ID       CREATED          SIZE
<none>                              <none>   75be1a8b3611   33 seconds ago   4.68 MB
quay.io/tomsweeneyredhat/myalpine   latest   11cd0b38bc3c   7 months ago     4.68 MB

# podman run quay.io/tomsweeneyredhat/myalpine ls /
bin
dev
etc
home
lib
media
mnt
proc
root
run
sbin
srv
sys
tmp
usr
var
```

**Comment by TomSweeneyRedHat** [comment]
@rhatdan unhappy tests

**Comment by mheon** [comment]
@TomSweeneyRedHat if it passes your build baseline I'm plenty satisfied

**Comment by TomSweeneyRedHat** [comment]
@mheon it does indeed pass the baseline with this fix in place.

**Comment by mheon** [comment]
LGTM then!

**Pull request merged**
