### PR TITLE
In shared networkNS /etc/resolv.conf&/etc/hosts should be shared

### PR DESCRIPTION
**Pull request by rhatdan**
We should just bind mount the original containers /etc/resolv.conf and /etchosts
into the new container.  Changes in the resolv.conf and hosts should be seen
by all containers,  This matches Docker behaviour.

In order to make this work the labels on these files need to have a shared
SELinux label.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
First step to fixing. https://github.com/containers/libpod/issues/2355

**Comment by rhatdan** [comment]
@mheon @baude @vrothberg @TomSweeneyRedHat @giuseppe PTAL

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
tests still aren't hip @rhatdan

**Comment by mheon** [comment]
One question: what happens if one container deletes resolv.conf? Does it disappear for all of them?

**Comment by rhatdan** [comment]
@mheon Yes

**Pull request merged**
