### PR TITLE
Revert "Cirrus: Temp. workaround missing imgprune image"

### PR DESCRIPTION
**Pull request by cevich**
Also includes one other occasional/minor flake-fix

This reverts commit 9b2e98f1e872354f0708a86b59e16b8b86e9f8b2.

### CODE REVIEW

**Comment by cevich** [comment]
@baude I tested and verified behavior, FROM does need to specify the FQIN (annoyingly).  I'll return the nice cookie you gave me...errr...shortly (munch...munch) :grin:

**Comment by cevich** [comment]
This one is ready to go, @mheon @baude PTAL when things settle down.

**Comment by rhatdan** [comment]
/lgtm
/hold
Don't cancel until 1.5 is release.

**Comment by rhatdan** [comment]
@cevich I think this needs a rebase

**Comment by cevich** [comment]
Uggg, I thought I just rebased/pushed it this morning.  Rolling it again...

**Comment by rhatdan** [comment]
/lgtm
/hold
hold cancel when it passes.

**Pull request merged**
