### PR TITLE
WIP: Eventsprobs

### PR DESCRIPTION
**Pull request by baude**

### CODE REVIEW

**Comment by mheon** [comment]
Closing, we got this one tracked down

**Comment by vrothberg** [comment]
@mheon what was going on?

**Comment by mheon** [comment]
This was our debugging VM for the events issues. Ended up being us not propagating events settings into cleanup processes.

**Comment by mheon** [comment]
(And by "events issues" I mean the ones that were tying up the memory leaks PR in CI)

**Pull request closed without merging**
