### PR TITLE
Update containers/storage, containers/image, and containers/buildah

### PR DESCRIPTION
**Pull request by nalind**
Bump `github.com/containers/storage`, and versions of `github.com/containers/image` and `github.com/projectatomic/buildah` that work with it.

### CODE REVIEW

**Comment by nalind** [comment]
Currently vendors the proposed changes from https://github.com/containers/image/pull/505 and https://github.com/containers/buildah/pull/1024; this can't be merged until those have been resolved.

**Comment by mheon** [comment]
FAH28 failure is the known exit 1 after successful tests

**Comment by mheon** [comment]
Sorry for the spam here, we're testing new CI

**Comment by nalind** [comment]
@mheon No worries; it's instructive.

**Comment by nalind** [comment]
This will obsolete #1471.

**Comment by nalind** [comment]
I think the use of `$GIT_CHECK_EXCLUDE` with `git-validation` ends up requiring at least git 1.9.0 in order for the arguments that `git-validation` adds to its invocations of `git` when that environment variable is set to not trigger the `fatal: Invalid pathspec magic 'exclude' in ':(exclude)./vendor'` error.

**Comment by mheon** [comment]
@nalind https://github.com/vbatts/git-validation/issues/37 to track

**Comment by rhatdan** [comment]
@nalind Needs a rebase.  Is this still a WIP?

**Comment by nalind** [comment]
bot, retest this please

**Comment by nalind** [comment]
bot, retest this please

**Comment by mheon** [comment]
bot, retest this please

**Comment by mheon** [comment]
@nalind Mind rebasing to pick up CI fixes?

**Comment by rhatdan** [comment]
Does not look like this got the CI Fixes.  Not sure it was rebased correctly.

**Pull request closed without merging**
