### PR TITLE
Complete switch from projectatomic to containers for repo

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Tests aren't happy @rhatdan 

```
vendor/github.com/projectatomic/buildah/add.go:19:2: cannot find package "github.com/projectatomic/libpod/pkg/chrootuser" in any of:
	/go/src/github.com/containers/libpod/vendor/github.com/projectatomic/libpod/pkg/chrootuser (vendor tree)
	/usr/local/go/src/github.com/projectatomic/libpod/pkg/chrootuser (from $GOROOT)
	/go/src/github.com/projectatomic/libpod/pkg/chrootuser (from $GOPATH)
vendor/github.com/projectatomic/buildah/run.go:34:2: cannot find package "github.com/projectatomic/libpod/pkg/secrets" in any of:
	/go/src/github.com/containers/libpod/vendor/github.com/projectatomic/libpod/pkg/secrets (vendor tree)
	/usr/local/go/src/github.com/projectatomic/libpod/pkg/secrets (from $GOROOT)
	/go/src/github.com/projectatomic/libpod/pkg/secrets (from $GOPATH)
```

More projectatomic to containers tweaks needed?

**Comment by vrothberg** [comment]
> More projectatomic to containers tweaks needed?

@TomSweeneyRedHat Looks like we have to first change the references in buildah, and once that's vendored, we can make it work here.

**Comment by rhatdan** [comment]
PTAL https://github.com/projectatomic/buildah/pull/928

**Comment by baude** [comment]
LGTM

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r=mheon

**Pull request closed without merging**
