### PR TITLE
Cirrus: Support special-case modes of testing

### PR DESCRIPTION
**Pull request by cevich**
Previously libpod CI was fairly straight-forward, run unit and
integration tests in a standard set of 3 VMs.  Off on the side was a
single special case of running tests as an ordinary user.  There is a
desire to stop using the PAPR system to support testing inside of a
container.

Since having two special cases potentially invites more
down the road, make provisions to handle them more gracefully.  This
commit introduces an environment variable:  ``$SPECIALMODE``.  It's
value has the following meanings within the CI scripts:

Mode 'none': Nothing special, business as usual (default)
Mode 'rootless': Rootless testing
Mode 'in_podman': Build container, run integration tests in it.

This will make adding additional special-cases later easier, as well as
extending the special cases in a Matrix across multiple OS's.

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by baude** [comment]
LGTM

**Comment by mheon** [comment]
LGTM!

**Comment by cevich** [comment]
Ref: [first attempt passing tests](https://cirrus-ci.com/task/5437333129134080)

**Pull request merged**
