### PR TITLE
Randomize IP addresses during checkpoint/restore tests

### PR DESCRIPTION
**Pull request by adrianreber**
There have been CI failures with some checkpoint/restore tests which could be related to running tests in parallel and using the same IP address.

This tries to run all (almost) checkpoint/restore tests with random IP addresses.

### CODE REVIEW

**Comment by adrianreber** [comment]
Looks pretty good on the first try, no checkpoint/restore related failures. Let's try a second time.

**Comment by adrianreber** [comment]
Second CI run also without errors.

**Comment by adrianreber** [comment]
Rebased, repushed and removed WIP from title. Not sure if this actually makes sense or if it is a useless optimization. The first two CI runs looked pretty good, not sure if I am just lucky.

**Comment by rhatdan** [comment]
LGTM
@vrothberg @giuseppe @mheon @baude @ashley-cui @QiWang19 PTAL

**Pull request merged**
