### PR TITLE
Homebrew installation in install.md

### PR DESCRIPTION
**Pull request by ashley-cui**
Add brew installation instructions to docs & small fix to brew makefile

Signed-off-by: Ashley Cui <ashleycui16@gmail.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM
But remote test isn't happy.  I don't think it's related, but don't know that.

**Comment by mheon** [comment]
We have too many test VMs and too many infrequent flakes at this point - every PR is almost guaranteed to hit at least one.

**Pull request merged**
