### PR TITLE
hack/man_page_checker - improve diagnostics

### PR DESCRIPTION
**Pull request by edsantiago**
Make the errors more readable, with clearer instructions on
what to look for, and which filename, and what we expect to
see, and perhaps even how to approach a fix.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
Sample output from current network-create pr:
```
Inconsistent subcommand descriptions:
  podman-network-create.1.md       = 'Create a Podman CNI network'
  podman-network.1.md              = 'Create a CNI network for Podman'
Please ensure that the NAME section of podman-network-create.1.md
matches the subcommand description in podman-network.1.md
```
Sample output from files hand-tweaked to produce errors:
```
Inconsistent capitalization in SYNOPSIS in podman-network-create.1.md
  '**podman network creat**  [*options*] NAME' should not contain upper-case characters

Inconsistent program name in SYNOPSIS in podman-volume-create.1.md:
  SYNOPSIS = podman volumes create (expected: 'podman volume create')

Inconsistent program NAME in podman-volume-create.1.md:
  NAME= podman-volume-creat  (expected: podman-volume-create)
```

**Comment by mheon** [comment]
Changes LGTM

**Comment by edsantiago** [comment]
@baude PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
