### PR TITLE
[CI:DOCS] Fix typo in path

### PR DESCRIPTION
**Pull request by fenech**

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @fenech 
You need to sign your PR.

```
git commit -a -s --amend
git push --force
```

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM, thx @fenech

**Comment by mheon** [comment]
/hold
/approve

Integration tests flaked

**Pull request merged**
