### PR TITLE
Fix event cleanup when client closes connection

### PR DESCRIPTION
**Pull request by mheon**
Supercedes #6680

### CODE REVIEW

**Comment by mheon** [comment]
@edsantiago Any chance you remember if these are the same errors #6680 saw?

**Comment by edsantiago** [comment]
Yep, that's exactly it. Now where did I write down my reproducer? It's a trivial two-liner.

**Comment by mheon** [comment]
@edsantiago No need, I don't think I'm brave enough to try and salvage this. I'll go with a different approach.

**Comment by edsantiago** [comment]
@mheon check your email, date 24 June, subject 'PR 6680 reproducer in 1minutetip'. I wrote down a lot of notes there.

**Pull request closed without merging**
