### PR TITLE
[1.6] bump c/storage to v1.13.6

### PR DESCRIPTION
**Pull request by vrothberg**
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

@mheon @baude PTAL

### CODE REVIEW

**Comment by mheon** [comment]
LGTM once things go green.

**Comment by mheon** [comment]
I think CI on the 1.6 branch might be having problems. Probably safe to update the images to the latest ones we use for master?

**Comment by mheon** [comment]
Oh. I think it's just the Fedora 29 tests. Because we stopped testing on F29.

**Comment by mheon** [comment]
#4670 has a patch to fix CI

**Comment by mheon** [comment]
#4670 is landed, rebase and CI should go green

**Comment by vrothberg** [comment]
> #4670 is landed, rebase and CI should go green

Done :heavy_check_mark:

**Comment by mheon** [comment]
Restarted flake

**Comment by TomSweeneyRedHat** [comment]
LGTM all green.

**Comment by TomSweeneyRedHat** [comment]
/hold
will let @mheon hit the cancel

**Comment by mheon** [comment]
...It merged? Well, that doesn't seem right.

**Comment by mheon** [comment]
(Ah well, I was going to merge anyways...)

**Comment by mheon** [comment]
For sequencing, we're going to cut 1.6.4 first, then 1.7.0 immediately after - so autobuild scripts won't unintentionally obsolete 1.7.0 when the 1.6.4 tag appears

**Pull request merged**
