### PR TITLE
install.md: added slirp4netns dependency to ubuntu

### PR DESCRIPTION
**Pull request by nitrocode**
https://github.com/containers/libpod/issues/1234

### CODE REVIEW

**Comment by giuseppe** [comment]
thanks for the patch.  Could you please sign your commit?

You can do it with `git commit --amend -s` and then `push -f` it

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM once tests are happy.

**Comment by rhatdan** [comment]
/approve
/lgtm
/hold
hold cancel once tests pass.

**Pull request merged**
