### PR TITLE
seccomp.json moved to @seccomp/containers-golang

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@baude @mheon @rhatdan

### CODE REVIEW

**Comment by vrothberg** [comment]
Can you elaborate on why this change is needed? I feel rather strongly against this change for a multitude of reasons:

- Removing the file here will certainly break package builds of at least openSUSE and SUSE. Those packages would then be forced to add yet another source to the package just to fetch the seccomp.json.

- Why do we need to rely on an github.com/containers external project for such an important config?

- The two seccomp.json files are different.

- Compiling libpod from scratch is becoming rediculously hard. I don't think it's user or even developer friendly to force them to fetch configs and files from 3+ projects inside and outside of github.com/containers.

If this change is really desired, I really want to know why and request to document this somewhere (and to highlight it in the changelogs for the next release).

**Comment by lsm5** [comment]
>     * Removing the file here will certainly break package builds of at least openSUSE and SUSE. Those packages would then be forced to add yet another source to the package just to fetch the seccomp.json.

Ack, Fedora includes that file in the dist-git source itself. I'd really like 1 canonical location for that file, wherever that may be.

> 
>     * Why do we need to rely on an github.com/containers external project for such an important config?

@rhatdan can we move @seccomp/containers-golang to @containers?

> 
>     * The two seccomp.json files are different.

Ack. They're being installed to the same location so maybe we should work on making these consistent?

> 
>     * Compiling libpod from scratch is becoming rediculously hard. I don't think it's user or even developer friendly to force them to fetch configs and files from 3+ projects inside and outside of github.com/containers.

Ack, see question above about moving the repo here.
> 
> 
> If this change is really desired, I really want to know why and request to document this somewhere (and to highlight it in the changelogs for the next release).

Will do, I can add this if we decide to go ahead with this.

**Comment by rhatdan** [comment]
Is there a way to handle this via github?  Subpackages?  I agree with both of you @lsm5 and @giuseppe,

**Comment by lsm5** [comment]
> Is there a way to handle this via github? Subpackages? I agree with both of you @lsm5 and @giuseppe,

I guess you meant @vrothberg :) . How about vendoring like we did for registries.conf in skopeo?

**Comment by vrothberg** [comment]
I am still seeking for an answer to why this change is needed :^)

It's already very complex to know which packages/dependencies in which version is used/required where. The packaging efforts for Debian keep revealing more and more issues and I am worried that this change will increase the complexity.

To be fair, it's not a huge thing but I would rather go in the opposite direction and make the projects more self-contained. Especially the configs are important. Imagine the seccomp.json config has a bug. We first had to update the go-seccomp version, then revendor into the tools. How do we handle issues for stable versions where upstream keeps diverging? Do we need to patch a config in the vendor folder? If upstream developers are already fighting the dependencies, it is even harder for downstream packagers. It really doesn't feel right.

I am sorry to hijack this PR, @lsm5. My concerns are more of a general nature then being specific to the proposed change.

**Comment by lsm5** [comment]
@rhatdan @mrunalp so I see that seccomp.json is being installed to `/usr/share/containers` in [libpod's Makefile](https://github.com/containers/libpod/blob/master/Makefile#L246) and to `/etc/crio/` in [cri-o's Makefile](https://github.com/kubernetes-sigs/cri-o/blob/master/Makefile#L255). If those are the final locations for both, then I'm fine with closing this PR.

**Comment by rhatdan** [comment]
Well I would prefer to have them all share the same location.  I don't like the fact that CRI-O has this in a different location.  The more the configurations are shared the easier it is for an admin to manage.

**Comment by vrothberg** [comment]
> Well I would prefer to have them all share the same location. I don't like the fact that CRI-O has this in a different location. The more the configurations are shared the easier it is for an admin to manage.

I don't see how this change is achieving it. libpod is already required as a package source now for containers-common (or libcontainers-common on openSUSE) because of the oci-hooks manpage and the seccomp.json. CRI-O could just use the seccomp.conf from libpod.

**Comment by mheon** [comment]
I'd really like to deprecate CRI-O's `/etc/crio` location - it should default to the same paths Podman and Buildah do, so config changes affect the whole system.

@vrothberg While I agree that this causes packaging concerns, config files like this don't really belong to any one project. In your Seccomp profile bug case, right now, we have to fix it in at least two locations (CRI-O and Podman repos). I think that's just as bad for packaging complexity.

I don't know is containers-seccomp is the best place for the config - maybe we should have a github.com/containers/configs to store the default mounts.conf, storage.conf, etc files, and then submodule that into our projects?

**Comment by vrothberg** [comment]
> @vrothberg While I agree that this causes packaging concerns, config files like this don't really belong to any one project. In your Seccomp profile bug case, right now, we have to fix it in at least two locations (CRI-O and Podman repos). I think that's just as bad for packaging complexity.

The config file has been in libpod since I know it. Removing it breaks downstream packages. Currently, CRI-O ships it's own seccomp.json but there are plans to change that. Executing the current plan means work for _everybody_, upstream and downstream. I don't think that's necessary.

**Comment by rhatdan** [comment]
Can we move this to containers common and then vendor it into podman and cri-o.

**Comment by rhatdan** [comment]
@lsm5 Any update on this?

**Comment by lsm5** [comment]
> @lsm5 Any update on this?

I guess we gotta have everyone agree on a single `seccomp.json` before we can proceed with this.

**Comment by lsm5** [comment]
Also, if we're moving to `go mod` on this, I don't know how that'd affect this file if it's in seccomp/containers-golang.

**Comment by rhatdan** [comment]
@vrothberg @lsm5 Where do we stand with this one?

**Comment by vrothberg** [comment]
As @lsm5 mentioned, as soon as we move to use go modules, we cannot use such files from the `./vendor` directory anymore. I am okay with any solution that does not rely on `./vendor` but we need to be verbose in the changelogs to avoid breaking packages for other distros.

**Comment by vrothberg** [comment]
@lsm5, can you rebase?
LGTM

**Comment by vrothberg** [comment]
Needs a rebase

**Comment by vrothberg** [comment]
Ping @lsm5

**Comment by baude** [comment]
@lsm5 is this needed anymore?

**Comment by rhatdan** [comment]
@lsm5 Whats the scoop on this one?

**Pull request closed without merging**
