### PR TITLE
libpod.conf: add backward compatibility for runtime_path

### PR DESCRIPTION
**Pull request by giuseppe**
Add backward compatibility for `runtime_path` that was used by older versions of Podman.
    
The issue was introduced with: 650cf122e1b33f4d8f4426ee1cc1a4bf00c14798
    
If `runtime_path` is specified, it overrides any other configuration and a warning is printed.
    
`runtime_path` should be considered deprecated and will be removed in future.

### CODE REVIEW

**Comment by vrothberg** [comment]
Code LGTM but I just noticed that `man libpod.conf` needs to be updated as it doesn't mention the new options. @giuseppe, mind doing that in this PR?

**Comment by giuseppe** [comment]
> Code LGTM but I just noticed that `man libpod.conf` needs to be updated as it doesn't mention the new options. @giuseppe, mind doing that in this PR?

yes, good idea.  I've just pushed another commit

**Comment by vrothberg** [comment]
> yes, good idea. I've just pushed another commit

Thanks! LGTM

**Comment by rhatdan** [comment]
/lgtm
@giuseppe Did you verify this works with the new libpod.conf?

**Pull request merged**
