### PR TITLE
go build: use `-mod=vendor` for go >= 1.11.x

### PR DESCRIPTION
**Pull request by vrothberg**
Go 1.13.x isn't sensitive to the GO111MODULE environment variable
causing builds to not use the vendored sources in ./vendor. Force builds
of module-supporting go versions to use the vendored sources by setting
-mod=vendor.

Verified in a fedora:rawhide container.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by mheon** [comment]
LGTM

**Comment by vrothberg** [comment]
Ready to merge?

**Comment by mheon** [comment]
Whacking it.

/lgtm

**Pull request merged**
