### PR TITLE
Move selinux labeling support from pkg/util to pkg/selinux

### PR DESCRIPTION
**Pull request by rhatdan**
The goal here is to make the package less heavy and not overload
the pkg/util.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@mheon @vrothberg PTAL

**Comment by mheon** [comment]
LGTM

**Comment by stevekuznetsov** [comment]
```
 Required status check \"success\" is cancelled."
```

/hold

**Comment by mheon** [comment]
Lot of integration test failures

**Pull request merged**
