### PR TITLE
Vendor in latest containers/buildah

### PR DESCRIPTION
**Pull request by rhatdan**
This will take a significant size away from the podman-remote executables.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@baude @mheon @TomSweeneyRedHat @giuseppe @vrothberg @QiWang19 @jwhonce PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by vrothberg** [comment]
> This will take a significant size away from the podman-remote executables.

I see a drop from 41M to 33M, nice! @rhatdan, can you elaborate what has changed?

**Comment by rhatdan** [comment]
@vrothberg @baude gets all the credit https://github.com/containers/buildah/pull/2370
He found that we were pulling in a 3 line struct from OpenShift that was adding all of the size.

**Pull request merged**
