### PR TITLE
docs: add missing hyphen for '-t' option, command '$' prompts

### PR DESCRIPTION
**Pull request by rpjday**

### CODE REVIEW

**Comment by mheon** [comment]
/approve
LGTM

**Comment by vrothberg** [comment]
Oha ... running `make validate` locally on this PR fails but the CI is green.

@baude @mheon @rhatdan @cevich FYI ... I will investigate immediately

**Comment by vrothberg** [comment]
```
[+0004s] GIT_CHECK_EXCLUDE="./vendor:docs/make.bat" /go/bin/git-validation -run DCO,short-subject,dangling-whitespace -range ..HEAD
```

Looks like `EPOCH_TEST_COMMIT` isn't set ...

**Comment by rpjday** [comment]
My fault about the missing "SoB" line, I force-pushed an update.

**Pull request merged**
