### PR TITLE
Move rootless directory handling to the libpod/pkg/util directory

### PR DESCRIPTION
**Pull request by rhatdan**
This should allow us to share this code with buildah.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
@mheon @baude @umohnani8 @vrothberg PTAL

@giuseppe don't do `/lgtm` until we get at least one other LGTM.

**Comment by mheon** [comment]
Sure, LGTM

**Comment by mheon** [comment]
@rhatdan I think the bot can't do anything with webhooks down for Github

**Comment by rhatdan** [comment]
Ok, I am going to manually merge, so that buildah can start to use these.

**Pull request merged**
