### PR TITLE
Ensure test container in running state

### LINKED ISSUE #1643: Python podman/varlink stopped status
# **kind bug**

**Description**

On Fedora 28, many python podman integration tests fail with podman <= 0.10.1.

**Steps to reproduce the issue:**

1. Modify ``.cirrus.yml`` so only the ``image_name: "fedora..."`` line is un-commented.

2. Modify ``contrib/cirrus/integration_test.sh`` to run the following commands for fedora:

```
make install.tools
make
make install PREFIX=/usr ETCDIR=/etc
make localintegration
```

3. Temporarily commit, and push into upstream PR.

**Describe the results you received:**

Many integration tests fail, particularly ``test_create`` [w/o temporary band-aid](https://github.com/containers/libpod/pull/1635/files#diff-707c5769a9a7943fee6b9fd8e776c710R67)

**Describe the results you expected:**

The ``test_create`` (and hopefully other) integration tests pass on Fedora.

### PR DESCRIPTION
**Pull request by jwhonce**
* Save storage if tests fail

Fixes #1643

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests, but looks like F28 Cloud is kicking up its heals.

**Comment by baude** [comment]
LGTM

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by cevich** [comment]
@jwhonce Ugg, sorry I'm too slow.  Didn't get a chance to take a look at this.  Does this mean we can simply ignore the cgroup/mount race until a customer stumbles into it (somehow)?

After three days working on it...I'm not able to come up with a reliable repdocuer (so either it's accidentally fixed, or just too time-consuming to continue to track down).

**Comment by jwhonce** [comment]
@cevich I'm still trying to track down the cgroup issue.  This change covered the status race between podman and runc.

**Comment by cevich** [comment]
@jwhonce kk, thx.  Let me know if I can help.

**Pull request merged**
