### PR TITLE
vendor c/image v5.4.2

### PR DESCRIPTION
**Pull request by vrothberg**
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by mheon** [comment]
One flake, exec preserve FDs on ubuntu 18.

**Comment by mheon** [comment]
`[+0820s] time="2020-04-07T10:44:26Z" level=error msg="failed to close libpod db: \"db file close: close /tmp/podman_test662441145/crio/libpod/bolt_state.db: bad file descriptor\""`

I think preserve-fds may be closing too many FDs - potentially including the DB connection

**Pull request merged**
