### PR TITLE
Fix README.md -> rootless.md link

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @giuseppe @mheon @baude @jwhonce @vrothberg PTAL

**Comment by mheon** [comment]
LGTM

**Comment by jwhonce** [comment]
Flagged tests to rerun.  LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM and ooops!  I shoulda caught that prior.

**Pull request merged**
