### PR TITLE
Cirrus: Remove "too new" runc hack

### PR DESCRIPTION
**Pull request by cevich**
Ref: https://bodhi.fedoraproject.org/updates/FEDORA-2019-b4356521ba

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
@giuseppe I will keep an eye on this and make sure it passes.

**Comment by cevich** [comment]
@giuseppe ugg, it's never easy.  Summary: This change makes the integration tests worse for some reason.  Both Fedoras fail the kernel memory e2e tests, all with the same error:

```
[It] podman run kernel-memory test
  /var/tmp/go/src/github.com/containers/libpod/test/e2e/run_memory_test.go:61
Running: /var/tmp/go/src/github.com/containers/libpod/bin/podman --root /tmp/podman_test492480904/crio --runroot /tmp/podman_test492480904/crio-run --runtime /usr/bin/runc --conmon /usr/libexec/podman/conmon --cni-config-dir /etc/cni/net.d --cgroup-manager systemd --storage-driver vfs run --kernel-memory=40m docker.io/library/alpine:latest cat /sys/fs/cgroup/memory/memory.kmem.limit_in_bytes
container create failed: container_linux.go:344: starting container process caused "process_linux.go:311: applying cgroup configuration for process caused \"failed to set memory.kmem.limit_in_bytes, because either tasks have already joined this cgroup or it has children\""
: internal libpod error
```

@baude do you remember this error?  I thought this was one *fixed* by using a new/different runc, no?

**Comment by cevich** [comment]
Note to me:  This still needs an even newer runc RPM build.  Wrote @lsm5 about this.

**Comment by cevich** [comment]
@lsm5 ping :smile:

Hitting this in [another PR too :cry:](https://github.com/containers/libpod/pull/2435)

**Comment by cevich** [comment]
Rebasing and trying with latest/greates runc packages available...

**Comment by rhatdan** [comment]
@cevich You still working on this?
/approve

**Comment by cevich** [comment]
@lsm5 (rebased & force-pushed)

**Comment by cevich** [comment]
(rebased & force-pushed)

**Comment by cevich** [comment]
@rhatdan yes, there's a in-the-wild problem in F28/29 WRT podman and runc, found by one of our e2e tests.  A fix was recently merged upstream in runc, now we just need new packages.  So I've got a request out to @lsm5 and a jira card.  

Keeping this PR open and rebasing, in case I miss the new-package notice, causing the tests to pass :smile:

**Comment by cevich** [comment]
/hold

Okay! I guess this long-running problem has been fixed.

***note to me:*** Drop the yum updates and the hack, simply use new cache-images.

**Comment by cevich** [comment]
@lsm5 ping - any news on newer runc packages for F28/29?

**Comment by lsm5** [comment]
@cevich runc updated on fedora and ubuntu ppa.

**Comment by cevich** [comment]
@lsm5 thanks, testing ubuntu now.

**Comment by cevich** [comment]
@lsm5 looks like fedora is good (thanks)

**Comment by cevich** [comment]
Still testing, need to build new images for this.

/hold

**Comment by cevich** [comment]
Ubuntu images are good to go.  Combining this PR with #2561 since automated testing of newly built images is much better than by-hand.

**Pull request closed without merging**
