### PR TITLE
WIP Implement podman-remote exec

### PR DESCRIPTION
**Pull request by jwhonce**
* Cleanup some orphaned code

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@jwhonce Needs a rebase.

**Comment by mheon** [comment]
Retagging for 1.5

**Comment by rhatdan** [comment]
@jwhonce Are you still working on this?

**Comment by jwhonce** [comment]
@rhatdan Blocked on conmon support. Once https://github.com/containers/libpod/pull/3143 merges I'll pick this work back up.

**Comment by haircommander** [comment]
closing in favor of https://github.com/containers/libpod/pull/3624

**Pull request closed without merging**
