### PR TITLE
Need to set security options even if user does not specify options

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@mheon @baude We are not applying seccomp.json rules unless the user specifies a security option.  This is needed for 1.9.0.

**Comment by rhatdan** [comment]
@baude @mheon @giuseppe @vrothberg @TomSweeneyRedHat @QiWang19 PTAL

**Comment by baude** [comment]
any way this can have a test so when it fails in v2 we can catch it?

**Comment by rhatdan** [comment]
I think we should add this to podman info, then we could at least look for it.

**Comment by rhatdan** [comment]
Only reason I caught this, was that I was playing with it to containers.conf running podman in container.

**Comment by TomSweeneyRedHat** [comment]
So prior to you change, the StringArray was returning 'nil' instead of an empty array?  If so, that's subtle.  

The remote tstsaren't happy, I restarted the remote one, I don't think it's related.  A new test would also be good.

**Comment by rhatdan** [comment]
The problem is the code fails over to the built in.  I guess we could check a syscall that we know is blocked by the default seccomp filters.

mount/unshare perhaps.

But for now lets get this merged, so we can get podman 1.9.0 released.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Prior to this PR, the code was not setting the seccomp.json file to /usr/share/containers/containers.conf unless the user specified ANY --security-opt rule.  We want this set if the user did not override the seccomp file.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan got it, thanks.  I wasn't catching that `config.SetSecurityOpts()` was setting stuff to the default location if it got an empty array.

**Comment by TomSweeneyRedHat** [comment]
late, but LGTM

**Pull request merged**
