### PR TITLE
Ensure we have a valid store when we refresh

### LINKED ISSUE #3520: Crashed on Silverblue (via toolbox) with different shell on host than in pod
/kind bug

**Description**

Podman crashes.

**Steps to reproduce the issue:**

I am not entirely sure, but if you have:
* zsh on the host 
* in the pod, I have also had ` zsh`  installed (but that does not actually matter, I had the same crash before when there was no zsh in the pod)
* `toolbox enter`

The image is all defaults, i.e. toolbox Fedora 30 image.

For more complete STRs/the whole backstory, please refer to https://discussion.fedoraproject.org/t/toolbox-and-zsh/2035?u=rugk

**Describe the results you received:**

```sh
$ toolbox enter
/usr/bin/toolbox: Zeile 1126: 31015 Aborted                 (Speicherabzug geschrieben) $prefix_sudo podman container exists "$toolbox_container_old_v1" 2>&3
/usr/bin/toolbox: Zeile 1126: 31032 Aborted                 (Speicherabzug geschrieben) $prefix_sudo podman container exists "$toolbox_container_old_v2" 2>&3
toolbox: container fedora-toolbox-30 not found
Entering container fedora-toolbox-30 instead.
Use the 'create' command to create a different toolbox.
Try 'toolbox --help' for more information.
```

**Describe the results you expected:**
no crash

If you re-enter the toolbox later, it does not happen again. (only after a restart)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```sh
$ podman version                                         
Version:            1.4.5-dev
RemoteAPI Version:  1
Go Version:         go1.12.6
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.6
  podman version: 1.4.5-dev
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-1.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.2.0, commit: 41010e63c287618b1dc34ee11d10d268e2feeefe'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 223256576
  MemTotal: 3965403136
  OCIRuntime:
    package: runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: e3b4c1108f7d1bf0d09ab612ea09927d9b59b4e3
      spec: 1.0.1-dev
  SwapFree: 3567251456
  SwapTotal: 4102025216
  arch: amd64
  cpus: 4
  hostname: ATravel
  kernel: 5.1.16-300.fc30.x86_64
  os: linux
  rootless: true
  uptime: 1h 33m 48.11s (Approximately 0.04 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/rugk/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /var/home/rugk/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 1
  RunRoot: /run/user/1000
  VolumePath: /var/home/rugk/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora Silverblue 30
30.20190707.0 (2019-07-07T00:38:42Z)
BaseCommit: 751d21e610448544298604e5cd984179e62439cb253939cbb4d371d0661e1e74

---

I have to correct myself, when executing this one command, it actually crashes **three times**:
```sh
$ coredumpctl list -r  
TIME                            PID   UID   GID SIG COREFILE  EXE
Mon 2019-07-08 20:56:19 CEST  31032  1000  1000   6 present   /usr/bin/podman
Mon 2019-07-08 20:56:17 CEST  31015  1000  1000   6 present   /usr/bin/podman
Mon 2019-07-08 20:56:15 CEST  30989  1000  1000   6 present   /usr/bin/podman
[…]
```

Details:
```sh
$
PID: 31032 (podman)
           UID: 1000 (rugk)
           GID: 1000 (rugk)
        Signal: 6 (ABRT)
     Timestamp: Mon 2019-07-08 20:56:17 CEST (3min 58s ago)
  Command Line: podman container exists fedora-toolbox-rugk:30
    Executable: /usr/bin/podman
 Control Group: /user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
          Unit: user@1000.service
     User Unit: gnome-terminal-server.service
         Slice: user-1000.slice
     Owner UID: 1000 (rugk)
       Boot ID: e4a8f0edf05843d3a114cd0b3b9fb75f
    Machine ID: d0627b093df145ad95477bc5bdcc924d
      Hostname: ATravel
       Storage: /var/lib/systemd/coredump/core.podman.1000.e4a8f0edf05843d3a114cd0b3b9fb75f.31032.1562612177000000.lz4
       Message: Process 31032 (podman) of user 1000 dumped core.
                
                Stack trace of thread 31035:
                #0  0x00005604cce68ef1 n/a (podman)
                #1  0x00005604cce4f7ed n/a (podman)
                #2  0x00005604cce4e900 n/a (podman)
                #3  0x00005604cce691e3 n/a (podman)
                #4  0x00007f4c7b262e80 __restore_rt (libpthread.so.0)
                #5  0x00005604cce68ef1 n/a (podman)
                #6  0x00005604cce4f3fa n/a (podman)
                #7  0x00005604cce39c16 n/a (podman)
                #8  0x00005604cce395c9 n/a (podman)
                #9  0x00005604cce4f175 n/a (podman)
                #10 0x00005604cdcd2bbf n/a (podman)
                #11 0x00005604cdc72276 n/a (podman)
                #12 0x00005604cdcbd1ae n/a (podman)
                #13 0x00005604cdcba312 n/a (podman)
                #14 0x00005604cdcb77be n/a (podman)
                #15 0x00005604cdd72021 n/a (podman)
                #16 0x00005604cdd85f82 n/a (podman)
                #17 0x00005604cde44df5 n/a (podman)
                #18 0x00005604cde8a788 n/a (podman)
                #19 0x00005604ccfeeda7 n/a (podman)
                #20 0x00005604ccfef85e n/a (podman)
                #21 0x00005604cde5431a n/a (podman)
                #22 0x00005604cce3b324 n/a (podman)
                #23 0x000000c0000a8000 n/a (n/a)
                #24 0x0000000000000000 n/a (n/a)
```

```
coredumpctl dump 31015 
           PID: 31015 (podman)
           UID: 1000 (rugk)
           GID: 1000 (rugk)
        Signal: 6 (ABRT)
     Timestamp: Mon 2019-07-08 20:56:15 CEST (5min ago)
  Command Line: podman container exists fedora-toolbox-rugk-30
    Executable: /usr/bin/podman
 Control Group: /user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
          Unit: user@1000.service
     User Unit: gnome-terminal-server.service
         Slice: user-1000.slice
     Owner UID: 1000 (rugk)
       Boot ID: e4a8f0edf05843d3a114cd0b3b9fb75f
    Machine ID: d0627b093df145ad95477bc5bdcc924d
      Hostname: ATravel
       Storage: /var/lib/systemd/coredump/core.podman.1000.e4a8f0edf05843d3a114cd0b3b9fb75f.31015.1562612175000000.lz4
       Message: Process 31015 (podman) of user 1000 dumped core.
                
                Stack trace of thread 31024:
                #0  0x0000562a90cb4ef1 n/a (podman)
                #1  0x0000562a90c9b7ed n/a (podman)
                #2  0x0000562a90c9a900 n/a (podman)
                #3  0x0000562a90cb51e3 n/a (podman)
                #4  0x00007f4f8f4f1e80 __restore_rt (libpthread.so.0)
                #5  0x0000562a90cb4ef1 n/a (podman)
                #6  0x0000562a90c9b3fa n/a (podman)
                #7  0x0000562a90c85c16 n/a (podman)
                #8  0x0000562a90c855c9 n/a (podman)
                #9  0x0000562a90c9b175 n/a (podman)
                #10 0x0000562a91b1ebbf n/a (podman)
                #11 0x0000562a91abe276 n/a (podman)
                #12 0x0000562a91b091ae n/a (podman)
                #13 0x0000562a91b06312 n/a (podman)
                #14 0x0000562a91b037be n/a (podman)
                #15 0x0000562a91bbe021 n/a (podman)
                #16 0x0000562a91bd1f82 n/a (podman)
                #17 0x0000562a91c90df5 n/a (podman)
                #18 0x0000562a91cd6788 n/a (podman)
                #19 0x0000562a90e3ada7 n/a (podman)
                #20 0x0000562a90e3b85e n/a (podman)
                #21 0x0000562a91ca031a n/a (podman)
                #22 0x0000562a90c87324 n/a (podman)
                #23 0x000000c0000a8000 n/a (n/a)
                #24 0x0000000000000000 n/a (n/a)
```

```
PID: 30989 (podman)
           UID: 1000 (rugk)
           GID: 1000 (rugk)
        Signal: 6 (ABRT)
     Timestamp: Mon 2019-07-08 20:56:12 CEST (6min ago)
  Command Line: podman container exists fedora-toolbox-30
    Executable: /usr/bin/podman
 Control Group: /user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
          Unit: user@1000.service
     User Unit: gnome-terminal-server.service
         Slice: user-1000.slice
     Owner UID: 1000 (rugk)
       Boot ID: e4a8f0edf05843d3a114cd0b3b9fb75f
    Machine ID: d0627b093df145ad95477bc5bdcc924d
      Hostname: ATravel
       Storage: /var/lib/systemd/coredump/core.podman.1000.e4a8f0edf05843d3a114cd0b3b9fb75f.30989.1562612172000000.lz4
       Message: Process 30989 (podman) of user 1000 dumped core.
                
                Stack trace of thread 31005:
                #0  0x0000563aac56eef1 n/a (podman)
                #1  0x0000563aac5557ed n/a (podman)
                #2  0x0000563aac554900 n/a (podman)
                #3  0x0000563aac56f1e3 n/a (podman)
                #4  0x00007f47ac923e80 __restore_rt (libpthread.so.0)
                #5  0x0000563aac56eef1 n/a (podman)
                #6  0x0000563aac5553fa n/a (podman)
                #7  0x0000563aac53fc16 n/a (podman)
                #8  0x0000563aac53f5c9 n/a (podman)
                #9  0x0000563aac555175 n/a (podman)
                #10 0x0000563aad3d8bbf n/a (podman)
                #11 0x0000563aad378276 n/a (podman)
                #12 0x0000563aad3c31ae n/a (podman)
                #13 0x0000563aad3c0312 n/a (podman)
                #14 0x0000563aad3bd7be n/a (podman)
                #15 0x0000563aad478021 n/a (podman)
                #16 0x0000563aad48bf82 n/a (podman)
                #17 0x0000563aad54adf5 n/a (podman)
                #18 0x0000563aad590788 n/a (podman)
                #19 0x0000563aac6f4da7 n/a (podman)
                #20 0x0000563aac6f585e n/a (podman)
                #21 0x0000563aad55a31a n/a (podman)
                #22 0x0000563aac541324 n/a (podman)
                #23 0x000000c0000a8000 n/a (n/a)
                #24 0x0000000000000000 n/a (n/a)
```

If you want a complete coredump file, tell me a mail or so of a dev, where I can sent it to and which PID you want.

### PR DESCRIPTION
**Pull request by mheon**
Fixes #3520

### CODE REVIEW

**Comment by baude** [comment]
LGTM

**Comment by giuseppe** [comment]
LGTM

**Comment by mheon** [comment]
Rebasing to hopefully fix tests

**Comment by mheon** [comment]
@baude Mind whacking this with another LGTM?

**Pull request merged**
