### PR TITLE
Swap from FFJSON to easyjson

### PR DESCRIPTION
**Pull request by mheon**
FFJSON has serialization issues related to `MarshalText`/`UnmarshalText` that most notably affect serializing `net.IP` and cause incompatibility with containers created with DNS servers prior to FFJSON being re-added.

I investigated adding support for these to FFJSON, but didn't make much progress. Swapping to an alternative JSON generator seems like a better option.

Caveat: easyjson is newer and less mature, and potentially more buggy in other areas.

### CODE REVIEW

**Comment by mheon** [comment]
Should fix #1283

**Comment by rhatdan** [comment]
If we make this change we should also look at doing this in buildah and containers/storage?

**Comment by mheon** [comment]
Hm. It seems like we might need to vendor the easyjson repo (the generated files seem to be referring back to it).

@rhatdan It might be worth looking into, but it's not really a big real for c/storage and buildah because they've used FFJSON exclusively for a long time, and slight encoding/decoding differences vs encoding/json don't matter as much there. Here, we do need near-exact compatibility because we're transitioning an existing database created with encoding/json.

**Comment by mheon** [comment]
I'm not really sure why travis is showing as pending here - it's green when you actually click on it...

**Comment by rhatdan** [comment]
Sadly needs a rebase.

**Comment by mheon** [comment]
Rebased

**Comment by mheon** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
