### PR TITLE
rootless: fix segfault on refresh if there are containers

### PR DESCRIPTION
**Pull request by giuseppe**
create immediately a namespace if we need a refresh.  This is
necessary to access the rootless storage.

Closes: https://github.com/containers/libpod/issues/2894

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
Oh, this ought to work nicely. LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM, assuming happy tests.

**Comment by giuseppe** [comment]
I am still unshare though on the best way to create the first user namespace.  I'll surely need to fix it to happen with some locking, but at the same time we require containers to be running for having a process that keeps the namespace alive.

**Pull request merged**
