### PR TITLE
Update install.md ostree Debian dependencies.

### PR DESCRIPTION
**Pull request by jjwatt**
Add more Debian dependencies that I needed in Debian 9.9.

### CODE REVIEW

**Comment by rhatdan** [comment]
@jjwatt You have to sign your PR.

git commit -a --amend -s
git push --force

LGTM.   Although I would want @vrothberg to verify.

**Comment by TomSweeneyRedHat** [comment]
LGTM once signed

**Comment by rhatdan** [comment]
bot, add author to whitelist

**Comment by rhatdan** [comment]
bot, test pull request

**Pull request merged**
