### PR TITLE
run --rmi test: make it work

### PR DESCRIPTION
**Pull request by edsantiago**
The recently-added 'run --rmi' test was not actually doing
what it thinks it was doing: for one, 'run_podman | grep'
is never going to work; also, the test was leaving behind
stray images.

Rework to do what I believe the intention was; and, combine
into one test (down from two) for readability.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
/approve
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM, 
But is there a test to actually see if rmi works?

**Comment by edsantiago** [comment]
> But is there a test to actually see if rmi works?

`podman run --rmi`, or just plain `rmi`? The last two lines of the new test confirm that `run --rmi` removes the image. As for plain `rmi`, good question: it's used all throughout the tests, but I don't see an explicit confirmation. Now on my TODO list.

**Pull request merged**
