### PR TITLE
vendor github.com/containers/image/v5@v5.2.0

### PR DESCRIPTION
**Pull request by vrothberg**
See release notes:
	https://github.com/containers/image/releases/tag/v5.2.0

Fixes: #4877
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM pending green tests

**Comment by vrothberg** [comment]
```
gcc errors for preamble:
In file included from _build/src/github.com/containers/libpod/vendor/github.com/mtrmac/gpgme/data.go:6:0:
./go_gpgme.h:15:1: error: unknown type name 'gpgme_off_t'
 extern gpgme_off_t gogpgme_data_seek(gpgme_data_t dh, gpgme_off_t offset, int whence);
 ^
./go_gpgme.h:15:55: error: unknown type name 'gpgme_off_t'
 extern gpgme_off_t gogpgme_data_seek(gpgme_data_t dh, gpgme_off_t offset, int whence);
                                                       ^
```

@cevich any chance we can get add fresher centos?

**Comment by mheon** [comment]
The image used for ci/prow/images lives in Openshift CI, but I forget where the dockerfiles are stored - @baude do you remember?

**Comment by vrothberg** [comment]
Please do not merge until we @mtrmac 's ACK on the gpg issue.

**Comment by mtrmac** [comment]
`gpgme_off_t` was defined in 1.4.1 > 1.3.2, I’m afraid I missed this new reference when updating the mtrmac/gpgme fork.

Note to self, for now: `GPGME_VERSION_NUMBER` exists in current versions, but not in 1.3.2. How to detect whether to add a `typedef`?

**Comment by mtrmac** [comment]
This should be fixed in `github.com/mtrmac/gpgme@v0.1.2`; hopefully Dependabot will propagate that throughout the stack (like https://github.com/containers/image/pull/810 ), though a new c/image release explicitly dragging it in might make sense anyway.

(Sadly, with semantic versioning enforcing vX.Y.Z, we can’t make a v0.1.1.1, and the version will drift from proglottis/gpgme. The alternative, using something like v0.1.2-mtrmac.1, would not be picked up by other consumers by default.)

**Comment by vrothberg** [comment]
Ready to be merged. @TomSweeneyRedHat @rhatdan @mtrmac @mheon @baude PTAL

**Comment by mheon** [comment]
Restarted two flakes, LGTM once things go green

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.  Some tests still look unhappy though.

**Comment by vrothberg** [comment]
The Cirrus tests are running but somehow GitHub and Cirrus are not playing along very well for a while so the web UI is not showing that the tests are (re) running.

Finger's crossed :crossed_fingers:

**Pull request merged**
