### PR TITLE
Use buildah/pkg/parse volume parsing rather then internal version

### PR DESCRIPTION
**Pull request by rhatdan**
We share this code with buildah, so we should eliminate the podman
version.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@QiWang19 PTAL
@baude @mheon @giuseppe @vrothberg @TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
looks like some lint issues @rhatdan

**Comment by QiWang19** [comment]
@rhatdan  can also vendor `parse.GetBindMount`, `parse.GetTmpfsMount`.

**Comment by rhatdan** [comment]
@QiWang19 I don't see those?

**Comment by QiWang19** [comment]
of, yes, they are not here. only can be vendored after my PR merged.

**Comment by rhatdan** [comment]
Fine, but these are not used in libpod yet, is this something we will need in libpod?

**Comment by QiWang19** [comment]
@rhatdan  and changes added to `func ValidateVolumeOpts`  in this pr https://github.com/containers/libpod/pull/3369 is not in buildah now, this vendor will wipe that out

**Comment by rhatdan** [comment]
Correct, could you convert the buildah version to do this and then we can fix up my PR.

**Comment by rhatdan** [comment]
@QiWang19 BTW Good Catch.

**Comment by mheon** [comment]
Hold this. I made changes to option parsing during my big refactor of the
volume code, and I don't know if these are in the Buildah code.

**Comment by mheon** [comment]
Looking further, I'm confident that the Buildah code is not usable as is.
It's missing at least one bugfix I made.

**Comment by rhatdan** [comment]
Yup, @QiWang19 will add the changes to buildah code and then we can revendor that here.

**Comment by QiWang19** [comment]
I created this PR in buildah https://github.com/containers/buildah/pull/1698 to vendor ValidateVolumeOpts
but I think it makes sense to hold this.

**Comment by rhatdan** [comment]
@baude @mheon @vrothberg @giuseppe @TomSweeneyRedHat @ashley-cui @QiWang19 PTAL
This finally passes tests, removing code from Podman to share it with buildah.

**Comment by mheon** [comment]
LGTM

**Comment by QiWang19** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green tests

**Pull request merged**
