### PR TITLE
change search test to look for fedora and not fedora-minimal

### PR DESCRIPTION
**Pull request by baude**
Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by mheon** [comment]
Alright, I'm going to manually merge this because it seems to be last in Homu's (long) line, and all the tests are magically green for once

**Pull request merged**
