### PR TITLE
seccomp: use github.com/seccomp/containers-golang

### PR DESCRIPTION
**Pull request by vrothberg**
Use the github.com/seccomp/containers-golang library instead of the
docker package.  The docker package has changed and silently broke
on F31.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@giuseppe @nalind @rhatdan PTAL

The regression was introduced with the manifest change. Somehow lucky that we regressed because we should have really been using the other library.

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests
Do we know why Docker made the changes?  Just hoping it's not something that's yet to come in the golang variant too.

**Comment by rhatdan** [comment]
We should be using the upstream.  @TomSweeneyRedHat Could you verify what Buildah is using?
/lgtm

**Comment by TomSweeneyRedHat** [comment]
Buildah looks to have a little of both, I'll see if I can fix that.

**Comment by vrothberg** [comment]
> Do we know why Docker made the changes? Just hoping it's not something that's yet to come in the golang variant too.

At some point we need to whitelist the uring syscalls as well. They're fairly young (Linux v5.1) and were added through https://github.com/moby/moby/issues/39396 but the libseccomp library in Fedora is too old and doesn't know these syscalls yet.

**Comment by TomSweeneyRedHat** [comment]
Actually we're not using the Docker variant in Buildah, we're instead using:
```
chroot/seccomp.go:	libseccomp "github.com/seccomp/libseccomp-golang"
seccomp.go:	seccomp "github.com/seccomp/containers-golang"
```
Do we need to change the first one or is that fine also?

**Comment by vrothberg** [comment]
We need both but Buildah is using `containers-golang` for the default profile which is good: https://github.com/containers/buildah/blob/master/seccomp.go#L10

**Comment by rhatdan** [comment]
I have asked the upstream libseccomp guys to cut a release, but they have not done so far.  I have also asked Fedora Package maintainer to carry a patch until they release and I need to follow up on that.  But this will need to get released eventually to RHEL8.  

@nalind and I figured out what was causing the failure with the podman play kube, and have not fixed it so Podman should not hit the errors he was seeing.

**Pull request merged**
