### PR TITLE
Fix cgo includes for musl

### LINKED ISSUE #3284: FTBFS musl
```
_build-podman-xbps/src/github.com/containers/libpod/pkg/rootless/rootless_linux.go:27:8: error: unknown type name 'uid_t'
 extern uid_t rootless_uid();
        ^~~~~
_build-podman-xbps/src/github.com/containers/libpod/pkg/rootless/rootless_linux.go:28:8: error: unknown type name 'uid_t'
 extern uid_t rootless_gid();
        ^~~~~
```

### PR DESCRIPTION
**Pull request by CameronNemo**
closes #3284

Signed-off-by: Cameron Nemo <cnemo@tutanota.com>

### CODE REVIEW

**Comment by mheon** [comment]
/ok-to-test
/approve

Code LGTM

**Comment by TomSweeneyRedHat** [comment]
bot, add author to whitelist

**Comment by TomSweeneyRedHat** [comment]
LGTM, thx @CameronNemo !

**Pull request merged**
