### PR TITLE
codespell: spelling corrections

### PR DESCRIPTION
**Pull request by onlyjob**

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@onlyjob Thanks for the PR.  Our CI requires that all PR's get signed and I don't think you signed this one.  Can you please 'git commit --amend -s' and then repush the PR?

**Comment by TomSweeneyRedHat** [comment]
WOWSA!  Really nice change @onlyjob , thanks for all the corrections.  LGTM once the gating issue (signature me thinks) is solved.

**Comment by rhatdan** [comment]
/ok-to-test
Thanks @onlyjob, you need to sign your commit.
Was this a tool that you ran to generate this?
Would it be worth adding tests to make sure PRs do not contain additional typos?

**Comment by rhatdan** [comment]
LGTM

**Comment by onlyjob** [comment]
Signed, thanks.
I've used "codespell" utility (e.g. `codespell -i1 -w`) installed by corresponding Debian package.
Incorporating spell check to CI may be a nice idea but _codespell_ is not great for automatic checking - it is more of a manual correction tool...

**Comment by TomSweeneyRedHat** [comment]
@onlyjob thanks for the info on codespell, that's a tool I'm unfamiliar with, but will definitely look it up.

This PR made it through the gating test, so we're over the signature hurdle.  A remote_client test failed, but I think that's an unrelated hiccup.  I've restarted the test and hopefully that will clear it up.

**Pull request merged**
