### PR TITLE
Cirrus: Support testing with F31

### LINKED ISSUE #3447: Testing Flake: iptables chain already exists
/kind bug

**Description**

Occasionally, automated testing fails due to a [race-condition involving CNI iptables (though others CNI tools could also race)](https://github.com/containernetworking/plugins/issues/335).  Since `firewalld` is intended to mitigate this, but use is forbidden, synchronization either needs to happen within CNI or within libpod.

**Steps to reproduce the issue:**

1. Run CI tests hundreds of billion times under slightly varying conditions.

**Describe the results you received:**

Multiple tests fail with error from CNI claiming "iptables chain FOO already exists"

**Describe the results you expected:**

Testing continuously passes despite slightly varying conditions.

**Additional information you deem important (e.g. issue happens only occasionally):**

containernetworking-plugins-0.7.5-1.fc30.x86_64

**Output of `podman version`:**

```
Version:            1.4.2
RemoteAPI Version:  1
Go Version:         go1.12.5
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.5
  podman version: 1.4.2
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.2-1.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.2.0, commit: d7234dc01ae2ef08c42e3591e876723ad1c914c9'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 2929360896
  MemTotal: 4133994496
  OCIRuntime:
    package: runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: e3b4c1108f7d1bf0d09ab612ea09927d9b59b4e3
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 2
  hostname: cevich-fedora-30-libpod-5081463649730560
  kernel: 5.1.12-300.fc30.x86_64
  os: linux
  rootless: false
  uptime: 5m 23.78s
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - quay.io
  - registry.fedoraproject.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev,metacopy=on
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  ImageStore:
    number: 0
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora 30 VM running in GCE

``/etc/cni/net.d/87-podman-bridge.conflist``:

```json
{
    "cniVersion": "0.3.0",
    "name": "podman",
    "plugins": [
      {
        "type": "bridge",
        "bridge": "cni0",
        "isGateway": true,
        "ipMasq": true,
        "ipam": {
            "type": "host-local",
            "subnet": "10.88.0.0/16",
            "routes": [
                { "dst": "0.0.0.0/0" }
            ]
        }
      },
      {
        "type": "portmap",
        "capabilities": {
          "portMappings": true
        }
      }
    ]
}
```

### LINKED ISSUE #5285: CI: update VMs to add skopeo, newer containernetworking
This is a reminder to update the VMs used in CI:
* Install `skopeo`, wanted by #5265 
* Update f30 to `containernetworking-plugins >= 0.8.5`, to address #3447

### PR DESCRIPTION
**Pull request by cevich**
Add F31 + Drop F29

***Depends on: #3754 #4028 #4028 #4154 #4222 #4825***

Fixes #5285
Fixes #3447

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
F31 VM setup packaging failures:

```
[+0148s] 
    fedora-31: [2019-08-30T09:12:56-04:00] No match for argument: atomic-registries
[+0148s] 
    fedora-31: [2019-08-30T09:12:56-04:00] Package bzip2-1.0.8-1.fc31.x86_64 is already installed.
[+0148s] 
    fedora-31: [2019-08-30T09:12:56-04:00] Package findutils-1:4.6.0-24.fc31.x86_64 is already installed.
[+0148s] 
    fedora-31: [2019-08-30T09:12:56-04:00] Package gnupg2-2.2.17-2.fc31.x86_64 is already installed.
[+0148s] 
    fedora-31: [2019-08-30T09:12:56-04:00] No match for argument: golang-github-cpuguy83-go-md2man
[+0148s] 
    fedora-31: [2019-08-30T09:12:56-04:00] Package iproute-5.2.0-2.fc31.x86_64 is already installed.
[+0148s] 
    fedora-31: [2019-08-30T09:12:56-04:00] Package libseccomp-2.4.1-1.fc31.x86_64 is already installed.
[+0148s] 
    fedora-31: [2019-08-30T09:12:56-04:00] Package procps-ng-3.3.15-6.fc31.x86_64 is already installed.
[+0148s] 
    fedora-31: [2019-08-30T09:12:56-04:00] Package python-unversioned-command-3.7.4-5.fc31.noarch is already installed.
[+0148s] 
    fedora-31: [2019-08-30T09:12:56-04:00] No match for argument: python2-future
[+0148s] 
    fedora-31: [2019-08-30T09:12:56-04:00] Package python3-dateutil-1:2.8.0-3.fc31.noarch is already installed.
[+0148s] 
    fedora-31: [2019-08-30T09:12:56-04:00] Package python3-psutil-5.6.3-2.fc31.x86_64 is already installed.
[+0148s] 
    fedora-31: [2019-08-30T09:12:56-04:00] Package which-2.21-15.fc31.x86_64 is already installed.
[+0148s] 
    fedora-31: [2019-08-30T09:12:56-04:00] Package xz-5.2.4-6.fc31.x86_64 is already installed.
[+0148s] 
    fedora-31: [2019-08-30T09:12:56-04:00] Error: Unable to find a match: atomic-registries golang-github-cpuguy83-go-md2man python2-future
```

**Comment by cevich** [comment]
***All:*** Earliest working F31 cache-image build is `fedora-31-libpod-5654728358232064` that should fire up successfully with `hack/get_ci_vm.sh`.  Please play!

(I will work on stripping the xfedora / crun stuff and just install crun)

**Comment by cevich** [comment]
Note to me:  We need both runc and crun testing happening in F31 and F30.

**Comment by rhatdan** [comment]
runc tests will not pass in F31 until runc supports cgroupsv2 or you need to boot the kernel in cgroupv1 mode

**Comment by cevich** [comment]
> or you need to boot the kernel in cgroupv1 mode

Yeah, that's what I'm worried about needing to do.  The only way that's possible (the booting part) is by using a custom, snowflake image - a.k.a. a PITA.

We currently do this for giuseppe's playground in F30 and I was hoping to be able to drop that in this PR...now it sounds like I need to ADD another snowflake image (the 'P' part of the PITA).  It complicates automation and ongoing maintenance - and therefor impacts reliability, and flakes, and sleepless nights, and ... :disappointed: 

Maybe we can "strategically" decide to not ship **runc** with F31 and drop **crun** from F30 :smile_cat:

@rhatdan is there significant risk added if we were to only test crun in F31 and only test runc in F30?
(with the understanding we may need to swap testing to runc in F31 later if patches are accepted)

**Comment by cevich** [comment]
note to me: Still need to address the what/how/where of `crun` and `runc`.  Last commit does:

* Test crun in F31
* Test runc in F30 and Ubuntu

**Comment by rhatdan** [comment]
I am fine with only testing crun on f31 and runc on f30.  Once we get to f31 and f32 and runc has support for cgroupfs, we can start testing with both.

**Comment by cevich** [comment]
Got a new F31 cloud-image on the download site, produced a new F31 base image.  Rolling new cache-images now.

**Comment by cevich** [comment]
*note to me*: Need new crun 0.10 to prevent VM lockups and test timeouts

**Comment by cevich** [comment]
note to me: Ubuntu failures expected (no builds happening w/ packaged conmon).  Need #4222 to help investigate system-test failures (varlink process died?)

**Comment by cevich** [comment]
***grumble grumble grumble*** Even with the official F31 cloud images, I've got VMs locking up during integration testing (different test every time).  For example: https://cirrus-ci.com/task/6425946084605952

Oddly, it always seems to happen about 20-25minutes into testing :confounded:

**Comment by cevich** [comment]
linked https://bugzilla.redhat.com/show_bug.cgi?id=1767539 kernel panic in F31

**Comment by cevich** [comment]
Attempting to avoid kernel panic by switching to deadline scheduler on F31.

**Comment by cevich** [comment]
@giuseppe @haircommander mind taking a peek at these two F31 rootless failures (they're similar)?

* [special_testing_rootless TEST_REMOTE_CLIENT:false](https://api.cirrus-ci.com/v1/task/5471569836507136/logs/integration_test.log)
* [special_testing_rootless TEST_REMOTE_CLIENT:true](https://api.cirrus-ci.com/v1/task/6034519789928448/logs/integration_test.log)

Note: I already temporarily disabled [podman-in-podman testing because of massive numbers of failures](https://cirrus-ci.com/task/6024371776258048).  So debugging that will need to come also / after this PR merges.  I'm also mentioning this in case it's related to the rootless test failures.

**Comment by cevich** [comment]
(Peter I mentioned you because I seen the word "conmon" in some of the error messages :smile: )

**Comment by rhatdan** [comment]
This is still something we want.

**Comment by cevich** [comment]
Status: Working on verifying the BFQ kernel patch (this PR reproduces the panic).  Will resume here once the fix is confirmed (and I no longer need this PR to repro the problem)...

**Comment by cevich** [comment]
...no dice, patch does not fix problem.  Now reported/tracking upstream: https://bugzilla.kernel.org/show_bug.cgi?id=205447

To allow libpod to move forward, I'll put my workaround back in place, build fresh VM images, and go from there.  Then the kernel panic debugging can continue in parallel.

**Comment by cevich** [comment]
note to me:  PR took too long, it's F30 and F31 base images got pruned, need to re-add them.

**Comment by cevich** [comment]
note to self: need chroups systemd option, and rootless should install certs before becoming a user.

**Comment by cevich** [comment]
@edsantiago tried to catch ya on IRC.  I'm whittling down through the last few problems holding us back from F31 support in libpod PR CI.  Current focus is on the 'special_testing_rootless TEST_REMOTE_CLIENT:true' that is reporting a "timeout" failure coming from the system-tests.
I've re-run this part of the matrix a few times, and the failure seems repeatable (and so I'm doubting a service timeout is the root-cause).

Prior to hitting this reported "timeout" in the system-tests, the same job (F31 + rootless + remote) was failing much earlier during the integration tests.  Matt suggested setting `export CGROUP_MANAGER=systemd` and this solved the problem (the ginkgo tests are sensitive to this env. var).  I do **not** believe that env. var. value is preserved for the subsequent step of system-tests (but I can make it so, if need be).

Any idea if this "timeout" indicates another problem and/or could be related to not using "--cgroup-manager systemd" on the podman command line for the system-tests?

**Comment by cevich** [comment]
(Rebased and enabled two more F31 tests).

**Comment by cevich** [comment]
(Rebased and updated setup to force `OCI_RUNTIME=/usr/bin/crun`)

**Comment by cevich** [comment]
@edsantiago sorry, the reference to the error got lost, here's it again:  https://cirrus-ci.com/task/5793941895249920

```
...all ok so far...
[+0124s] not ok 43 podman kill - test signal handling in containers
[+0124s] # (from function `die' in file test/system/helpers.bash, line 274,
[+0124s] #  from function `kill_and_check' in file test/system/130-kill.bats, line 40,
[+0124s] #  in test file test/system/130-kill.bats, line 46)
[+0124s] #   `kill_and_check $s' failed
...sig 2 is failing...
[+0124s] # $ ./bin/podman-remote kill -s 2 ddb22f856b7a04f0d01018bc2fb0ec78b9b98453fdfc1cc6a5079759d09bd8a7
[+0124s] # ddb22f856b7a04f0d01018bc2fb0ec78b9b98453fdfc1cc6a5079759d09bd8a7
[+0124s] # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
[+0124s] # #| FAIL: Timed out: no ACK for kill -s 2
[+0124s] # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I poked at this and am not sure what to make of it, it only seems to happen w/ F31 + podman-remote system-testing.  I've added a temporary commit to remove signal '2' in this case, as an experiment to see if the subsequent `kill_and_check -INT      2` behaves differently.  I also wonder if maybe, `podman-remote` is gobbling up the signal and not passing it on to the container?

**Comment by cevich** [comment]
Found bug #5004

**Comment by cevich** [comment]
note to me: Check last run for affect of enabling selinux on F31

**Comment by cevich** [comment]
@edsantiago un-ping, I think we have this signal problem figured out.

**Comment by mheon** [comment]
LGTM

**Pull request merged**
