### PR TITLE
Automate production of MSI release files

### PR DESCRIPTION
**Pull request by cevich**
***Depends on: #3710***

### CODE REVIEW

**Comment by cevich** [comment]
@jwhonce very early prototype, PTAL.   This would add a zip-to-msi building container (`contrib/zip2msi`), and the hook to execute it (`contrib/cirrus/build_release.sh`).  I haven't quite worked out how to process the file for uploading (`contrib/upldrel` container) but this is not an impossible task.

**Comment by cevich** [comment]
Okay @jwhonce nearly almost done here.  There are changes to the upload-container image which cannot be tested w/o the `￼DO NOT MERGE - TESTING` commit, so I'm trying to be through.

Once I remove that commit from this PR, the `upload_release_archive.sh` will start silently-failing b/c the currently in-use container image is not compatible.  After this PR merges, a new image will be built and start working (I'll monitor for this).

**Comment by cevich** [comment]
(rebased/force-pushed: was missing pandoc package)

**Comment by cevich** [comment]
force pushed a rebase to latest master + added fix for double-dist name in filename.

**Comment by cevich** [comment]
(need to remove do-not-merge temporary commit)

**Comment by cevich** [comment]
Release now available for download at:
     https://storage.cloud.google.com/libpod-pr-releases/podman-remote-latest-pr3879-windows-amd64.msi
     https://storage.cloud.google.com/libpod-pr-releases/podman-remote-v1.6.0-rc1-75-gc8525f3a-pr3879-windows-amd64.msi
     https://storage.cloud.google.com/libpod-pr-releases/podman-remote-latest-pr3879-darwin-amd64.zip
     https://storage.cloud.google.com/libpod-pr-releases/podman-remote-v1.6.0-rc1-75-gc8525f3a-pr3879-darwin-amd64.zip

**Comment by rhatdan** [comment]
LGTM
@baude @mheon @vrothberg @giuseppe @TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green test buttons.

**Pull request merged**
