### PR TITLE
Fix directory pull image name for OCI images

### PR DESCRIPTION
**Pull request by saschagrunert**
This is a breaking change and modifies the resulting image name when
pulling from an directory via `oci:...`.

Without this patch, the image names pulled via a local directory got
processed incorrectly, like this:

```
> podman pull oci:alpine
> podman images
REPOSITORY      TAG      IMAGE ID       CREATED       SIZE
localhost/oci   alpine   4fa153a82426   5 weeks ago   5.85 MB
```

We now use the same approach as in the corresponding [buildah fix][1] to
adapt the behavior for correct `localhost/` prefixing.

[1]: https://github.com/containers/buildah/pull/1800

After applying the patch the same OCI image pull looks like this:

```
> ./bin/podman pull oci:alpine
> podman images
REPOSITORY         TAG      IMAGE ID       CREATED       SIZE
localhost/alpine   latest   4fa153a82426   5 weeks ago   5.85 MB
```

End-to-end tests have been adapted as well to cover the added scenario.

Relates to: https://github.com/containers/buildah/issues/1797

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@mheon @giuseppe @baude @TomSweeneyRedHat @vrothberg @QiWang19 @ashley-cui PTAL

**Comment by mheon** [comment]
Changes LGTM

**Comment by rhatdan** [comment]
/lgtm
/hold
Cancel hold when tests pass.

**Comment by rhatdan** [comment]
@saschagrunert Is this broken for the dir: transport as well?

**Comment by saschagrunert** [comment]
> @saschagrunert Is this broken for the dir: transport as well?

No, this works and worked as before (images are prefixed with localhost)

**Comment by saschagrunert** [comment]
>  I would expect `docker.io/library/alpine:latest` to be listed and not `localhost/alpine`.
> 
> I'd prefer setting `org.opencontainers.image.ref.name` when using the oci transport as a destination and use it when using oci as a source.
> **update**: I didn't check it but that might require touching `containers/image`.

This sounds like a new feature to me. I'm not sure if it's cool to modify the image manifest on push, but we could make it configurable. I guess it should definitely go into containers/image because it would work with all consumers of the API...

**Comment by vrothberg** [comment]
> > I would expect `docker.io/library/alpine:latest` to be listed and not `localhost/alpine`.
> > I'd prefer setting `org.opencontainers.image.ref.name` when using the oci transport as a destination and use it when using oci as a source.
> > **update**: I didn't check it but that might require touching `containers/image`.
> 
> This sounds like a new feature to me. 

We're about to change behaviour in any case. I want to make sure we're not patching symptoms. The `'localhost/` prefix was usually used to avoid defaulting to a registry (traditionally `docker.io`) for unqualified names. In case of the `dir:/` transport, we don't (maybe even can't) store the name but in case of `oci:` we can do that which is why I think we should tackle it in `c/image` rather than in libpod.

If others prefer the `localhost/` prefix, I don't block the PR. But maybe we need to check other transports as well (oci-archive, docker-archive, docker-daemon, etc.).

> I'm not sure if it's cool to modify the image manifest on push, but we could make it configurable.

That's fine. We're converting to OCI which supports embedding the reference in the manifest.

**Comment by rhatdan** [comment]
Well I am fine with this for now and then fixing it correctly in the long run.  Creating
localhost/oci is definitely a bug.

**Comment by vrothberg** [comment]
Alright, then let's get this in :)

**Pull request merged**
