### PR TITLE
Add three test cases for podman attach test

### PR DESCRIPTION
**Pull request by ypu**
Add following test cases for podman attach test:
1. podman attach to a running container
2. podman attach to the latest container
3. podman attach to a container with --sig-proxy set to false

### CODE REVIEW

**Comment by rhatdan** [comment]
:+1:

**Comment by TomSweeneyRedHat** [comment]
LGTM
Test failure seems to be some kind of network flake.

**Comment by mheon** [comment]
Restarted the flakes

**Pull request merged**
