### PR TITLE
Attempt to turn on special_testing_in_podman tests

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe @baude These tests are failing attempting to write to cgroup control while sitting in a container?

**Comment by jwhonce** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
add the hold cancel once the tests wrap

**Pull request merged**
