### PR TITLE
Ensure storage options are properly initialized

### PR DESCRIPTION
**Pull request by mheon**
If one of storage GraphRoot or RunRoot are specified, but the other is not, c/storage will not use the default, and will throw an error instead. Ensure that in cases where this would happen, we populate the fields with the c/storage defaults ourselves.

### CODE REVIEW

**Comment by mheon** [comment]
@TomSweeneyRedHat I think this resolves the issue you were seeing in the baseline tests

**Comment by TomSweeneyRedHat** [comment]
@mheon, ack.  I'll give it a test run.  FWIW, looks like F28 Cloud tests aren't hip atm.

**Comment by baude** [comment]
yeah LGTM

**Comment by baude** [comment]
bot, retest this please

**Comment by baude** [comment]
bot, retest this please

**Comment by mheon** [comment]
I don't think so - I don't think `--root` is a very common option, it's mostly just for tests (your baseline tests, the integration tests, etc)

**Comment by baude** [comment]
bot, retest this please

**Comment by giuseppe** [comment]
LGTM

**Comment by rhatdan** [comment]
bot, retest this please

**Pull request merged**
