### PR TITLE
Vendor in latest containers/storage

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@baude @mheon @umohnani8 @vrothberg @giuseppe This is ready to merge now.  
Great speed up in podman run --uid-map.

**Comment by umohnani8** [comment]
LGTM

**Comment by mheon** [comment]
/approve
LGTM
/lgtm

**Pull request merged**
