### PR TITLE
[Makefile] Fix docker documentation install and generation

### PR DESCRIPTION
**Pull request by Foxboron**
The final versions of the documentation has been shifted from `docs/` to
`docs/build/man`. Most of the Makefile has been changed accordingly, but
the docker documentation generation was not.

Introduced by #4354

Signed-off-by: Morten Linderud <morten@linderud.pw>

### CODE REVIEW

**Comment by Foxboron** [comment]
Seems like there was some sections forgotten while doing the restructure. Unsure if this is everything or if there are more stuff missing from #4354

**Comment by TomSweeneyRedHat** [comment]
The changes look reasonable to me, but I'd like @baude to weigh in.

**Comment by baude** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
I'll add an official LGTM as @baude is hip with these changes.

**Comment by rhatdan** [comment]
Thanks @Foxboron 
/lgtm

**Comment by Foxboron** [comment]
Should be noted that `make install.docker` is currently broken in the `1.6.3` release.

**Comment by Foxboron** [comment]
Why wasn't this included in `1.6.4`? `make install.docker` is still broken.

**Comment by mheon** [comment]
1.6.4 is a backports-only long term support release. The next proper mainline release will be 1.7.0 - the first RC is out, the final tag should be pushed later today or tomorrow.

**Comment by mheon** [comment]
(The timing here worked out to be very confusing - sorry for that. Ideally 1.7.0 final would be out before we did a backports release for 1.6.x)

**Comment by Foxboron** [comment]
I don't quite see how this patch would be excluded from backports. But that means `make install.docker` is not expected to work on the LTS release?

**Comment by mheon** [comment]
Right now, we're only adding critical-severity bugfixes. We should do a better job of marking these releases, though, we don't intend on them being consumed by most distros. The intention was to get 1.7.0 out soon enough that most people would go straight from 1.6.3 to 1.7.0.

**Comment by Foxboron** [comment]
Ack. I'll just not bother with `1.6.4` then :) Thanks for the explanation!

**Pull request merged**
