### PR TITLE
Add 'podman events' to podman(1)

### PR DESCRIPTION
**Pull request by edsantiago**
Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM
/approve

**Comment by edsantiago** [comment]
Found another bug. Fix in progress; will force-push when ready.

**Comment by edsantiago** [comment]
/hold cancel

Man page bug found by `hack/podman-commands.sh` checker; issue #2630 filed to see if we can get that into CI instead of having a monkey check every day or two.

Usage bug found by BATS tests. It might be a good idea to start running those in CI as well.

**Comment by edsantiago** [comment]
CI clean; TIL about the `Re-run` button.

**Pull request merged**
