### PR TITLE
DO-NOT-MERGE Minor grammatical fix in README

### PR DESCRIPTION
**Pull request by edsantiago**
I need a PR CI failure for my demo

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Since you're looking for a CI failure, I'll assume this will turn all green....

**Comment by mheon** [comment]
@edsantiago For future reference, for docs-only PRs, you can prepend the title of the PR with `[CI:DOCS]` to skip most integration tests

**Comment by mheon** [comment]
LGTM
/approve

**Comment by mheon** [comment]
Oh. I need to actually read PR descriptions before I comment.

**Comment by edsantiago** [comment]
@mheon thanks. I _want_ the integration tests, those are the ones that always fail.

**Comment by edsantiago** [comment]
This isn't funny, trickster gods of CI.

**Comment by vrothberg** [comment]
:rofl:

**Comment by TomSweeneyRedHat** [comment]
My bad @edsantiago, I put the KOD on it with my comment.

**Comment by edsantiago** [comment]
@TomSweeneyRedHat I knocked on salt and sprinkled wood over my shoulder when I read your comment, is that not protection enough?

**Pull request closed without merging**
