### PR TITLE
fix unit test using strings.Contains

### PR DESCRIPTION
**Pull request by gabibeyer**
The Expect function does not return a result of True or False
depending on the value of the first instance, but instead requires
a comparison using ".To(", so change to use ".To(ContainSubsring("

Signed-off-by: gabi beyer <gabrielle.n.beyer@intel.com>

### CODE REVIEW

**Comment by mheon** [comment]
/approve
/ok-to-test

Changes LGTM

**Comment by rhatdan** [comment]
/lgtm
/hold
Feel free to hold cancel, when the tests pass.

**Comment by TomSweeneyRedHat** [comment]
LGTM, thanks @gabibeyer

**Comment by gabibeyer** [comment]
My pleasure! I found a few of the same type of bug in other tests, would you like me to add them to this PR, or open a new one?

**Comment by TomSweeneyRedHat** [comment]
I'd vote for a separate PR personally, but it's a six of one, half dozen of another type of decision.  If you need to touch up this one for whatever reason, then feel free to add them here.

**Comment by gabibeyer** [comment]
Thank you @TomSweeneyRedHat 

@baude I think this test may not be working as originally intended, or the mounts are not being cleaned up correctly. Is it possible the conmon process doing the cleanup may need more time between the `stop` call and reading the mount output?

**Comment by mheon** [comment]
I'm actually dealing with a very similar case in #3931 - my solution was https://github.com/containers/libpod/blob/951ecb3e816ed12dee7e3c148393777fce10e6a0/test/e2e/run_volume_test.go#L230-L238

Basically, I force a manual run of `podman container cleanup` after `podman stop`. The cleanup process normally runs in the background, but we can spawn our own copy of it to force cleanup to occur.

**Comment by rhatdan** [comment]
I suggest you do a
```
		stop := podmanTest.Podman([]string{"stop", cid})
		stop.WaitWithDefaultTimeout()
		Expect(stop.ExitCode()).To(Equal(0))

```

**Comment by gabibeyer** [comment]
Thank you @mheon, I'll try that out. Would that defeat the purpose of having a 'test mount cleanup', if it needs to be forced?

**Comment by mheon** [comment]
@gabibeyer Somewhat... but at the same time, I don't think we can necessarily avoid it. There's no easy way to verify that `podman container cleanup` completed in the background, except polling the mounts to see if cleanup happened yet?

Alternatively - we could replace `podman stop` with `podman rm --force` - that includes cleanup as part of it, so it's guaranteed to have run by the time `rm --force` is done. Arguable also defeats part of the test, though.

**Comment by rhatdan** [comment]
Wouldn't podman wait be better it should wait to get an exit code and then you know that the container has stopped.

**Comment by mheon** [comment]
Doesn't guarantee the cleanup process ran, though - Conmon only spawns that after the container is stopped.

**Comment by gabibeyer** [comment]
@mheon is it expected for a running container to automatically mount its rootfs to a location for the host to be read? Or does it require the `mount` call, like the other mount tests? I think this test is doing the former, and possibly that is why it is failing, but I'm not confident on the process.

**Comment by gabibeyer** [comment]
Also, thank you for the detailed response, that makes sense!

**Comment by gabibeyer** [comment]
Oh, maybe this test failure is because rootless uses vfs instead of overlay?

**Comment by mheon** [comment]
You know, I don't think we even expect this test to work on rootless.

@giuseppe We don't expect anything in `mounts` from fuse-overlay, right?

@gabibeyer Sorry for the delay, but I think you can skip this if rootless

**Comment by giuseppe** [comment]
> @giuseppe We don't expect anything in `mounts` from fuse-overlay, right?

yes correct, there is nothing mounted in the host mount namespace.

You can find the fuse-overlayfs mount once you do `podman unshare` and join the user namespace+mount namespace used by the rootless containers

**Pull request merged**
