### PR TITLE
Ensure we do not overlap mounts in the spec

### PR DESCRIPTION
**Pull request by mheon**
When user-specified volume mounts overlap with mounts already in the spec, remove the mount in the spec to ensure there are no conflicts.

Partial fix for #1412 - I think we need to check for conflicts with --volumes-from and --tmpfs as well, but we can do that in a subsequent PR.

### CODE REVIEW

**Comment by EmilienM** [comment]
The patch didn't fix #1412 yet - I had to bind mount /dev/null in my container as a workaround.

**Comment by mheon** [comment]
I actually completely broke volume mounts with this PR. Amazing our tests failed to catch this.

**Comment by mheon** [comment]
@EmilienM Think I found the problem. I didn't actually break volume mounts - it was a precedence issue. We refused to override mounts already in the spec, and as such would not override default mounts like /dev. This should be fixed now.

**Comment by mheon** [comment]
Anyways, should be fixed now.

**Comment by baude** [comment]
bot, retest this please

**Comment by mheon** [comment]
Should be good to merge

**Comment by mheon** [comment]
We've accumulated enough acks, so I'll merge this
@rh-atomic-bot r=TomSweeneyRedHat

**Pull request closed without merging**
