### PR TITLE
Vendor in latest containers/storage

### PR DESCRIPTION
**Pull request by rhatdan**
Vendor in containers/storage to fix issues with metacopyup when specifying
new usernamespace.  Also fixes issues with zfs back end.

Rest of changes come from running make vendor.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
A ton more adds for this than in Buildah.  Is that expected?

**Comment by mheon** [comment]
I think you picked up a lot more than just c/storage @rhatdan

**Comment by rhatdan** [comment]
Yup, I did not know if we should be doing make vendor now, rather then just vndr.  This is basically picking up the latest content vndr wants.

What do you think @vrothberg ?

**Comment by giuseppe** [comment]
if we are pinpointing exact commits/tags it should be fine to revendor everything under `vendor` instead of a single package

**Comment by vrothberg** [comment]
> Yup, I did not know if we should be doing make vendor now, rather then just vndr. This is basically picking up the latest content vndr wants.
> 
> What do you think @vrothberg ?

I recommend to always use `make vendor` as we can whitelist things there. In theory, when updating c/storage only vendor/.../c/storage should be changed with a `make vendor`. But `vndr` is full dark magic and might go wild, so I expect we have to continuously tame it.

I suggest to only add changes to vendor/.../c/storage to this commit and we can have a look what's wrong (and clean up things) after that.

**Comment by rhatdan** [comment]
I think we should hold off on this until the new zfs fix in containers/storage gets merged.
https://github.com/containers/storage/pull/265

**Comment by rhatdan** [comment]
New ZFS fix is in.
@baude @mheon @umohnani8 @vrothberg @TomSweeneyRedHat @giuseppe PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Pull request merged**
