### PR TITLE
Adjust LISTEN_PID for reexec in varlink mode

### PR DESCRIPTION
**Pull request by haraldh**
Because the varlink server honors the socket activation protocol,
LISTEN_PID has to be adjusted with the new PID.

https://varlink.org/FAQ.html#how-does-socket-activation-work
Signed-off-by: Harald Hoyer <harald@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
bot, add author to whitelist

**Comment by giuseppe** [comment]
LGTM

**Pull request merged**
