### PR TITLE
fix NOTIFY_SOCKET in e2e testfix NOTIFY_SOCKET in e2e tests

### PR DESCRIPTION
**Pull request by baude**
Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by baude** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by baude** [comment]
bot, retest this please

**Comment by baude** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
Looks like we are getting permission denied when mounting /dev/shm.  Probably an SELinux issue?

**Comment by baude** [comment]
bot, retest this please

**Comment by baude** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by baude** [comment]
bot, retest this please

**Pull request merged**
