### PR TITLE
Fix create_test for remote integration

### PR DESCRIPTION
**Pull request by baude**
fixes tests to pass for remote integration.  the two remaining tests that are skipped are due to lack of logs command.

Signed-off-by: Brent Baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
one issue with this is that we are no longer testing the -l flag, but I don't think that is a big deal.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by mheon** [comment]
Can we ensure that we do not completely drop testing of `--latest` as part of this? Adding separate, gated tests that only run local seems like a good idea.

**Pull request merged**
