### PR TITLE
[CI:DOCS] podman system service doc fixes

### PR DESCRIPTION
**Pull request by marusak**
It took me much longer to realize that it is `podman system service` since examples were pointing me to the `podman service` and `podman system <tab>` showed there is no `service` subcommand.

### CODE REVIEW

**Comment by rhatdan** [comment]
@marusak Thanks for the PRS, but could you sign them?

**Comment by TomSweeneyRedHat** [comment]
changes LGTM, but our CI requires the PR is signed.  Please do a `git commit --amend -s` and then repush.

**Comment by mheon** [comment]
Oh, oops - figured I'd missed something...

**Comment by marusak** [comment]
> could you sign them?

Done

**Comment by mheon** [comment]
f077f27561110c0e148f2e7d8a84f26e9feec173 still seems to be missing a signoff

**Comment by marusak** [comment]
> f077f27 still seems to be missing a signoff

`<irony>` I am doing such great job today `</irony>`

Sorry about that, was not signing commits for some time and don't have that in my muscle memory anymore. Should be right now.

**Comment by mheon** [comment]
Thank you, looks good. Since this is docs only I'm renaming with CI:DOCS to not trigger the full CI suite.

**Comment by mheon** [comment]
Hm. Might actually be too late. Oh well.

/lgtm
/hold

**Pull request merged**
