### PR TITLE
Fix minor typos in podman-run docs.

### PR DESCRIPTION
**Pull request by chrahunt**

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by baude** [comment]
the libpod project requires you to sign your commits.  please perform a `git commit --amend -s` to sign this PR.  Then run a `make validate` to ensure that things are OK.  Thanks for your submission.

**Comment by rhatdan** [comment]
/approve
bot, add author to whitelist

**Comment by rhatdan** [comment]
/lgtm
/hold
Feel free to hold cancel when tests pass.

**Pull request merged**
