### PR TITLE
fix bug creats directory copying file

### LINKED ISSUE #3384: Podman creates directory when copying a file from and to container
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

when podman copies file to/from container, it creates a directory with the same name on destination and copies file to it
**Steps to reproduce the issue:**

```bash
echo "blabla" > /tmp/bla
podman cp --pause=false /tmp/bla instance:/root/
podman exec -it instance ls -lash /root/
4.0K drwx------.  2 root root 4.0K Jun 20 17:07 bla

podman exec -it instance ls -lash /root/bla
total 12K
4.0K drwx------. 2 root root 4.0K Jun 20 17:07 .
4.0K dr-xr-x---. 6 root root 4.0K Jun 20 17:07 ..
4.0K -rw-rw-r--. 1 root root    7 Jun 20 17:07 bla
```
Exactly the same thing when copying file from container to host.

**Describe the results you received:**
Directories with files

**Describe the results you expected:**
Just files

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 1.4.0
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.11.10
  podman version: 1.4.0
host:
  BuildahVersion: 1.8.3
  Conmon:
    package: podman-1.4.0-2.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.2.0, commit: 80f19b1591b03dbbc53bf28b154230c7ea372281'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 362270720
  MemTotal: 25142366208
  OCIRuntime:
    package: runc-1.0.0-93.dev.gitb9b6cc6.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: 82f4855a8421018c9f4d74fbcf2da7f8ad1e11fa
      spec: 1.0.1-dev
  SwapFree: 10366218240
  SwapTotal: 12645822464
  arch: amd64
  cpus: 4
  hostname: sshnaidm.remote
  kernel: 5.1.8-200.fc29.x86_64
  os: linux
  rootless: true
  uptime: 173h 16m 38.78s (Approximately 7.21 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/sshnaidm/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/sshnaidm/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 26
  RunRoot: /tmp/1000
  VolumePath: /home/sshnaidm/.local/share/containers/storage/volumes

```

### PR DESCRIPTION
**Pull request by QiWang19**
close #3384

Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
@QiWang19 Can you add some tests for this?

**Comment by QiWang19** [comment]
I have made changes in the tests to cat the file.

**Comment by rhatdan** [comment]
I don't  see a Cat of a file?

**Comment by QiWang19** [comment]
I start the container has `cat foo` command

**Comment by QiWang19** [comment]
can this get in? Do I need to add more tests for the changes?
@mheon @TomSweeneyRedHat

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
