### PR TITLE
troubleshooting: fix useradd no-log-init argument

### PR DESCRIPTION
**Pull request by manics**
`--log-no-init` should be `--no-log-init`

```
# useradd --log-no-init -u 99999000 -g users newuser
useradd: unrecognized option '--log-no-init'
Usage: useradd [options] LOGIN
       useradd -D
       useradd -D [options]

Options:
  -b, --base-dir BASE_DIR       base directory for the home directory of the
                                new account
  -c, --comment COMMENT         GECOS field of the new account
  -d, --home-dir HOME_DIR       home directory of the new account
  -D, --defaults                print or change default useradd configuration
  -e, --expiredate EXPIRE_DATE  expiration date of the new account
  -f, --inactive INACTIVE       password inactivity period of the new account
  -g, --gid GROUP               name or ID of the primary group of the new
                                account
  -G, --groups GROUPS           list of supplementary groups of the new
                                account
  -h, --help                    display this help message and exit
  -k, --skel SKEL_DIR           use this alternative skeleton directory
  -K, --key KEY=VALUE           override /etc/login.defs defaults
  -l, --no-log-init             do not add the user to the lastlog and
                                faillog databases
  -m, --create-home             create the user's home directory
  -M, --no-create-home          do not create the user's home directory
  -N, --no-user-group           do not create a group with the same name as
                                the user
  -o, --non-unique              allow to create users with duplicate
                                (non-unique) UID
  -p, --password PASSWORD       encrypted password of the new account
  -r, --system                  create a system account
  -R, --root CHROOT_DIR         directory to chroot into
  -P, --prefix PREFIX_DIR       prefix directory where are located the /etc/* files
  -s, --shell SHELL             login shell of the new account
  -u, --uid UID                 user ID of the new account
  -U, --user-group              create a group with the same name as the user
  -Z, --selinux-user SEUSER     use a specific SEUSER for the SELinux user mapping
```

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @manics for you PR.  But you must sign it.

git commit -a -s --amend
git push --force

**Comment by rhatdan** [comment]
Patch LGTM

**Comment by manics** [comment]
@rhatdan done.

**Comment by rhatdan** [comment]
Saving the planet since this PR is not causing the test to fail, merging manually.

**Comment by baude** [comment]
unfortunately the tests need to be fixed ...

**Comment by TomSweeneyRedHat** [comment]
@baude, this isn't something for the submitor @manics to worry about right?  It's unrelated to this PR me thinks.

**Comment by rhatdan** [comment]
Yes unrelated.

**Comment by mheon** [comment]
@cevich Is this related to the crun issues you were talking about yesterday?

**Comment by cevich** [comment]
yes

**Pull request merged**
