### PR TITLE
Build catatonit

### PR DESCRIPTION
**Pull request by vrothberg**
@baude PTAL

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@vrothberg looks like your script needs a little tickling....
```
[+0195s] ./hack/install_catatonit.sh: line 16: autoreconf: command not found
[+0195s] make: *** [Makefile:312: install.catatonit] Error 127
```

**Comment by vrothberg** [comment]
Thanks for checking, @TomSweeneyRedHat! Eeek ... looks like I need to update the package dependencies and add them to the build docs as well.

**Comment by vrothberg** [comment]
@cevich, I need your pair of eyes. The task is failing since `autoreconf` is not installed in the container. However, the `fedora_setup.sh` is installing `autoconf` which provides that. Where do I need to tweak?

**Comment by mheon** [comment]
LGTM

**Comment by cevich** [comment]
Sadly there's no mechanism (yet) to build and test container images w/in a PR.  That also means any PR testing which relies on image changes, won't have them (and fail as it is here).  Worse, even after merging it will fail since quay will not likely have had time to finish building, it will have to be re-run.

For this PR, one possibility is to manually build the image and jam it up into quay as 'latest'.  The risk here is EVERYBODY's PR will start using it, so you'll very rapidly know if it's incompatible and need to scramble to push a working image up to fix it :confused:

I have a PR open to make this easier, but other priorities are currently piled up on top of it...and it's also a complicated thing to do (similar to the VM cache-image building level of complexity).

**Comment by vrothberg** [comment]
@cevich, thanks for the detailed explanation! Maybe we can add a hook to install new packages at runtime?

**Comment by vrothberg** [comment]
@cevich @baude @mheon, I updated the Dockerfiles and tested it locally. I noticed that the `Dockerfile` and the `Dockerfile.centos` don't build (also in master) - shall we delete them?

**Comment by vrothberg** [comment]
Opened https://github.com/containers/libpod/pull/4106 to first update the Dockerfile.fedora and hence the container image used in the failing CI job here.

**Comment by vrothberg** [comment]
Restarted the job. Looks like the other PR to update the container image worked :^)

@baude @rhatdan @TomSweeneyRedHat PTAL

**Comment by cevich** [comment]
#3901 will pick up the changes to the VM images (eventually) when I rebuild them again (shortly).  If you need something sooner, just follow the documented process of opening a PR w/ magic string.

**Pull request merged**
