### PR TITLE
Fixes issue #3577.

### PR DESCRIPTION
**Pull request by hooksie1**
I think I got most of it, let me know if you see something you don't like.

### CODE REVIEW

**Comment by haircommander** [comment]
/ok-to-test
bot, test pull request

**Comment by haircommander** [comment]
Thanks for the PR @hooksie1 can you add a sign-off with
`git commit --amend -s` and `git push -f origin issue-#3577`

**Comment by giuseppe** [comment]
LGTM

**Comment by rhatdan** [comment]
/lgtm
Thanks @hooksie1

**Pull request merged**
