### PR TITLE
Fix -f logs follow with stopped container

### LINKED ISSUE #6531: podman logs -f continues indefinitely on a stopped container
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
/kind bug

**Description**
Running `podman logs -f` on a stopped container run indefinitely and does not exit
This is a regression of Issue https://github.com/containers/libpod/issues/435 and PR https://github.com/containers/libpod/pull/437

**Steps to reproduce the issue:**

1. Run a container which exits immediately
```
podman run -d --name hello-world hello-world
```

2. Follow logs of stopped container
```
podman logs -f hello-world
```

**Describe the results you received:**
Command does not exit; hangs indefinitely

**Describe the results you expected:**
Command should exit.

**Additional information you deem important (e.g. issue happens only occasionally):**
The expected behavior of Docker is to exit when following a log of a stopped container

**Output of `podman version`:**

```
Version:      2.0.0-dev
API Version:  1
Go Version:   go1.14.3
Git Commit:   d857275901e8c1ea7515360631e5894018e17f30
Built:        Fri Jun  5 17:00:00 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0-dev
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.18-0.6.dev.git50aeae4.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.18-dev, commit: 51e91bbc42aaf0676bb4023fb86f00460bf7a0a2'
  cpus: 4
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: file
  hostname: gallucci-fedora.devlnk.net
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.7.0-1.fc33.x86_64
  linkmode: dynamic
  memFree: 15239475200
  memTotal: 16783962112
  ociRuntime:
    name: crun
    package: crun-0.13-2.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 22h 20m 14.55s (Approximately 0.92 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 4
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 3
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 1
  Built: 1591401600
  BuiltTime: Fri Jun  5 17:00:00 2020
  GitCommit: d857275901e8c1ea7515360631e5894018e17f30
  GoVersion: go1.14.3
  OsArch: linux/amd64
  Version: 2.0.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.0-0.121.dev.git1fcb678.fc33.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 33 (Rawhide Prerelease)

### PR DESCRIPTION
**Pull request by QiWang19**
Fix -f logs follow with stopped container. Close #6531

Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@QiWang19 Could you rebase and repush.  Tests do not seem to have run.  Have you confirmed that this is running the way it should?

**Comment by QiWang19** [comment]
This PR not fully fixed the issue. Still  need more work on this.

**Comment by jgallucci32** [comment]
@QiWang19 I just tested this and following the logs hangs indefinitely if the container is running before running `logs -f container` and after it stops. It will no long hang if the container is already stopped, but stopping a container while tailing the logs continues to be an issue.

**Comment by jgallucci32** [comment]
@QiWang19 I have traced the hang in the code to this line
https://github.com/containers/libpod/blob/033743cbee180d9a4149f574375cc1201e573d06/libpod/container_log.go#L61
Since the `Lines()` function is external to libpod we're likely going to have to loop and check for it like the original fix was written 2 years ago (it had a `time.Sleep(1 * time.Second)` line within a loop to check the state of the container every second)

**Comment by jgallucci32** [comment]
@QiWang19 I created a PR against your branch which handles multiple scenarios of following a log with stopped (or stopping) containers.
https://github.com/QiWang19/libpod/pull/1

What this does is create a subroutine which checks the state of the container every second. This is a similar approach taken when this bug was fixed 2 years ago. The difference here is we are using `github.com/hpcloud/tail` which effectively follows a log until it is given an exit command. It had several options `Kill, Stop, StopAtEOF` so I chose what I thought would allow the function to exist most gracefully which is `StopAtEOF()`.

I tested the following conditions with this PR:
* Tail and follow logs of running container
* Tail and follow logs of stopped container
* Tail and follow logs of running container which exits after some time

**Comment by rhatdan** [comment]
@jgallucci32 Could you open a PR for libpod with Yours and @QiWang19 Changes combined and here tests, Leave her signature and then we can merge the combination.

**Comment by jgallucci32** [comment]
@rhatdan I created PR https://github.com/containers/libpod/pull/6591 which is a merge of our two commits. It will supercede this PR.

Not sure how to leave her signature, but there are 2 commits in the PR one from each of us.

**Pull request closed without merging**
