### PR TITLE
Vendor in latest psgo code

### PR DESCRIPTION
**Pull request by rhatdan**
There is a race condition in psgo, that can cause some tests
to flake.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
@vrothberg @giuseppe @mheon @baude @TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM, assuming happy tests.  I'm just a bit suspicous about gofmt and rmi.go

**Comment by giuseppe** [comment]
LGTM

**Comment by vrothberg** [comment]
@rhatdan I think `psgo` has more cases like this internally. Let fix them, I'll ping you over there.

**Comment by baude** [comment]
rebase and should be good to go

**Comment by rhatdan** [comment]
@vrothberg This PR should have latest psgo code.

**Comment by vrothberg** [comment]
Waiting for tests to pass, then we can merge. Thanks a lot, @rhatdan !

**Pull request merged**
