### PR TITLE
Move install.md to podman.io, leave link page

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
The installation instructions for podman were on this site and a
second copy on podman.io.  I've created https://github.com/containers/podman.io/pull/193
which has a merging of the installation instructions from both sites.

Since the one on podman.io was created a few months ago, we've had a number
of divergences.  Maintaining only one copy should assist with that problem
plus make it easier for people updating them.

This PR should NOT be merged before the one in podman.io.

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
Pre-commit linter's angry at the changes... Not sure why, though

**Comment by TomSweeneyRedHat** [comment]
It looks like the bane of my documentation existence.  I'd left a space after two separate lines.  Ugh.  Thanks for the heads up.

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
The PR in podman.io with the updated install guide, containers/podman.io#193, has merged.  Safe to merge this one now, can we make it so?  All green test buttons and in short, this changes the install.md file to point at the file on podman.io.

**Pull request merged**
