### PR TITLE
Update containers/image to v2.0.0, and buildah to v1.8.4

### PR DESCRIPTION
**Pull request by mtrmac**
This adds the the mirror-by-digest-only option to mirrors, and moves the search order to an independent list.

Also includes a ~unrelated bug fix in dealing with the affected c/image API.

AFAICS needs https://github.com/containers/buildah/pull/1634 to be merged first.

### CODE REVIEW

**Comment by mheon** [comment]
Changes LGTM

**Comment by rhatdan** [comment]
@mtrmac Any movement on this PR?  Any closer to cutting a version of containers/image?

**Comment by mtrmac** [comment]
> @mtrmac Any closer to cutting a version of containers/image?

Updated https://github.com/containers/image/pull/617 to try to have at least _somewhat_ readable documentation.

**Comment by mtrmac** [comment]
DO NOT MERGE as is, this includes unmarked https://github.com/containers/buildah/pull/1634 . After that is merged, this should revendor from the upstream repo (or an upstream release) again.

**Comment by rhatdan** [comment]
@mtrmac buildah 1.8.4 release has been created can you rebase this against that so we can merge?

**Comment by mtrmac** [comment]
Revendored from released c/image v2.0.0 and buildah v1.8.4.

**Comment by mheon** [comment]
Reiterating my LGTM.
/ok-to-test
/approve

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.

**Comment by mtrmac** [comment]
```
"open /tmp/podman/imagecachedir/vfs/dir/7f8c074fb5158ba84eae5287d0d1580f5661f8267c0cee8ad62caa2ad8e01b87/var/lib/nginx: permission denied"
```
Does anyone know what this is about?

**Comment by rhatdan** [comment]
No idea, re-kicking tests.
/lgtm
/hold

**Pull request merged**
