### PR TITLE
Add history names to image inspect data

### PR DESCRIPTION
**Pull request by saschagrunert**
During writing the tests I found it would be probably useful to have the
tag history part of the inspect data.

### CODE REVIEW

**Comment by rhatdan** [comment]
Man page example needs to be updated.

**Comment by saschagrunert** [comment]
> Man page example needs to be updated.

I will give the inspect man page a complete update, some other fields seem missing too.

**Comment by rhatdan** [comment]
Thanks, I would figure it is out of date.

**Comment by mheon** [comment]
Code LGTM, going to kick the tests

**Pull request merged**
