### PR TITLE
Vendor in latest containers/storage

### PR DESCRIPTION
**Pull request by rhatdan**
This should improve performance on vfs images on top of xfs/reflink drives.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM once tests pass

**Comment by mheon** [comment]
@rhatdan Looks like we have some breaking API changes in c/image - I think @mtrmac had a PR out to address those?

**Comment by mtrmac** [comment]
https://github.com/containers/libpod/pull/1930

**Comment by rhatdan** [comment]
Dropped containers/image, we will get it from the other PR,  Now just storage.

**Comment by baude** [comment]
rebase and should be good @rhatdan

**Pull request merged**
