### PR TITLE
Remove unused function in runtime.go

### PR DESCRIPTION
**Pull request by mheon**
Don't really want this to be part of the public API, and nothing uses it, so axe it.

### CODE REVIEW

**Comment by vrothberg** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
LGTM
Not sure if the bot is waiting on other stuff to complete, but no apparent movement since @rhatdan 's last comment.

**Comment by mheon** [comment]
@rh-atomic-bot r+

**Comment by mheon** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
