### PR TITLE
Allow security-opts to be parsed even if container is --privileged

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
lint if biting you @rhatdan

**Comment by rhatdan** [comment]
These validation errors have nothing to do with this PR.
@mheon PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
Force merging.

**Pull request merged**
