### PR TITLE
Replace root-based rootless tests

### PR DESCRIPTION
**Pull request by cevich**
Since CI automation is now executing all tests as a regular user, there
is no need for root-based testing to run special rootless tests.  Remove
them.

However, the root-based rootless tests did include one test for exercising
the '--rootfs' option which is needed.  Add a new general, and more through
test to replace it - meaning it will be executed as root and non-root.

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
@mheon @giuseppe as we discussed :smile:   

Assuming this works, may I also strip out [the python exec debugging-horror](https://github.com/containers/libpod/blob/master/test/utils/utils.go#L80-L84) or do we still need that for some other purpose?

**Comment by TomSweeneyRedHat** [comment]
Do we need to run any tests as root?  Not my call, but I like the thought of running the tests as both root and rootless.
Beyond that, tests aren't hip atm.

**Comment by cevich** [comment]
@TomSweeneyRedHat An interesting thought, thx for sharing.  I know the number of tests we need to run as root is larger than 1 :smile:  But I think you're correct that most can be run rootless, and better still, most can probably be run rootless and remotely.  I'm sure there are at least a few medium-large testing efficiencies to be gained by consolidating.  OTOH, it's likely costly to convert to that scheme in terms of engineer-time on the needed changes :frowning_face: 

@baude WDYT about ^^^ and relating to the remote/local testing split you're working on?  Maybe Tom's idea could simplify that?  i.e. skip (as-is) rootless testing and only do remote + rootless.   Or does that miss too many tests?

**Comment by rhatdan** [comment]
I would like as many tests as possible run in all three modes.

Root, Rootless, Remote

**Comment by cevich** [comment]
@rhatdan Backstory:  The tests removed by this PR are duplicates of rootless tests we otherwise run as a regular user.  The removed tests depend on some convoluted, complicated, hard to debug exec wizardry, to start off as root, but then execute podman as a regular user.

In other words, these removed tests predate the current CI setup, where we actually run all/most of the integration tests as a regular user on the system, no root involvement at all.  The only exception is the case of `--rootfs`, which (I'm told) cannot be tested as a non-root user.  So this PR adds a dedicated test to cover that.

**Comment by rhatdan** [comment]
@cevich Ok understood.

**Comment by mheon** [comment]
/approve
@cevich Hit this with a rebase, and I'll merge away. I think this will get master back into a less buggy state.

**Comment by cevich** [comment]
@mheon okay, tests all green (woot!)

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
I'm going to hold this until #3140 lands to keep things clean until the new version lands

**Comment by mheon** [comment]
Alright, it's landed, let's get this in
/lgtm

**Pull request merged**
