### PR TITLE
Add another Fedora VM with cgroups v2 enabled

### PR DESCRIPTION
**Pull request by cevich**
Depends on #3632

### CODE REVIEW

**Comment by cevich** [comment]
@giuseppe so as you saw, there's no built-in way to safely reboot during testing.  Though a newly added unrelated feature, does support this possibility in "future Cirrus-CI".  For now, we'll have to add a snowflake VM image, which this PR should do.

What were you thinking about for testing, should it execute the regular integration tests for now?  [Either way, I need to update this comment.](https://github.com/containers/libpod/pull/3607/files#diff-cba47a19668b204ffc8b35cd17ce548bR40)

**Comment by giuseppe** [comment]
> What were you thinking about for testing, should it execute the regular integration tests for now? [Either way, I need to update this comment.](https://github.com/containers/libpod/pull/3607/files#diff-cba47a19668b204ffc8b35cd17ce548bR40)

I was thinking of running the e2e tests using crun instead of runc

**Comment by cevich** [comment]
> I was thinking of running the e2e tests using crun instead of runc

Ahh okay, not sure what that is, but IIRC we can affect that by exporting `$RUNC_BINARY`.  While I'm messing with adding a new cache-image anyway, how do I make "crun" available?

**Comment by cevich** [comment]
@giuseppe PTAL.  Assuming tests pass as they did earlier, I'm going to leave the rest to you.  There's spot for runtime tweaks in `contrib/cirrus/integration_test.yml`.  If you need anything else cached in the VM image, take a look at the `xfedora` section at the end of `contrib/cirrus/packer/fedora_setup.sh`.  If you get stuck, just let me know.

**Comment by giuseppe** [comment]
@cevich is special_testing_cgroupv2 running on cgroupv2?  How are tests passing there? :-)

**Comment by cevich** [comment]
@giuseppe yes it should be, at least it's running the intended VM image with modified kernel options.  I didn't do anything special for the tests, were you expecting they should fail?

I will check the VM image, and confirm the kernel option is still set...

**Comment by giuseppe** [comment]
yes, there is no support for cgroup v2 in runc so I'd expect them to fail.

**Comment by cevich** [comment]
@giuseppe okay thanks, I added a image-verification test, and am re-building images.  Let's see if it fails...

**Comment by cevich** [comment]
...yep, and I found the problem as well (missing `sudo` to grubby command).

**Comment by cevich** [comment]
[Okay, this looks like the expected breakage]([+1740s] FAIL! -- 261 Passed | 417 Failed | 1 Flaked | 0 Pending | 22 Skipped) and the image check test I added gives me more confidence as well:

```
[+0001s] Checking items specific to xfedora-30-libpod-4703143915421696
[+0001s] Kernel Command-line: BOOT_IMAGE=(hd0,msdos1)/boot/vmlinuz-5.1.20-300.fc30.x86_64 root=UUID=ea711a29-e460-4879-9d70-9da99ae021f9 ro no_timer_check net.ifnames=0 console=tty1 console=ttyS0,115200n8 systemd.unified_cgroup_hierarchy=1
[+0001s] ok On xfedora-30 images, the /sys/fs/cgroup/unified directory does NOT exist
[+0001s] Total failed tests: 0
```

@giuseppe I'll squash all this new stuff up again, and comment out the line that actually executes the tests, so you can do what you like as far as what's needed to get them working.  This will all still be part of the normal workflows, so feel free if you need to modify the VM images further.

**Comment by giuseppe** [comment]
thanks, it looks better now :D

Is it possible to have the two combinations cgroups2 AND rootless, cgroups2 and root.  It makes no sense to test the remote client.  So we can skip it

**Comment by cevich** [comment]
@giuseppe yes, in fact I was going to ask if you wanted that, but then thought maybe we should leave it for a future update.  The primary reasons I had in mind were:

* Conflict over `$SPECIALMODE`, perhaps there's a better/simpler design for this (i.e. `$TESTSUITE`?)
* Uncertainty over differences between cgroupv2 testing vs "standard" integration testing - the new tests don't _have_ to re-use the current ginkgo suite, they could do something entirely different if that makes more sense.
* This PR is already Size/L, representing a non-trivial maintenance-burden increase (adding a snowflake VM image).

I can strip out the client-testing easy enough though, that's not a big deal.

How would you feel about: merging this and working up the actual testing (however that needs to be done).  Then when the testing is running and stable, come bother me and we'll figure out how to best to integrate rootless testing.  Would that be okay?

---

A related thought:  We're currently automatically publishing the binaries which have passed testing.  Third-party or out-of-band testing is the intended use-case for these. It happens for both PRs and master, providing a publicly accessible "latest" zip archive.  Would you be interested in having one of these made for cgroupv2?   It's not much work, since the machinery is already in place.

**Comment by cevich** [comment]
(rebase, force-push w/o cgroupv2 remote testing)

**Comment by giuseppe** [comment]
> How would you feel about: merging this and working up the actual testing (however that needs to be done). Then when the testing is running and stable, come bother me and we'll figure out how to best to integrate rootless testing. Would that be okay?

I am fine with merging it as it is, so we can start using it and see what tests are failing.  Thanks!

LGTM

**Comment by rhatdan** [comment]
@cevich This needs a rebase.  Should we wait until podman 1.5 is released before putting this in?  I don't want to jeopardise the release.

**Comment by cevich** [comment]
> Should we wait until podman 1.5 is released before putting this in? I don't want to jeopardise the release.

Yes, most definitely we should wait.

**Comment by cevich** [comment]
Okay, this one is ready.  @giuseppe @baude @mheon PTAL (when things quiet down a little).

**Comment by rhatdan** [comment]
/lgtm
/hold
Wait to cancel after the release of 1.5

**Comment by mheon** [comment]
/hold
Something send to be stalling this, will investigate when I get to a
computer

**Comment by giuseppe** [comment]
@cevich could you rebase it?

I've moved crun under github.com/containers.  Once we set up tests with cgroups v2, we will probably want to setup some tests on the crun repository as well to avoid regressions

**Comment by cevich** [comment]
> we will probably want to setup some tests on the crun repository as well to avoid regressions

Can they be performed inside a container?  I'm happy to help, but there's one "implement CI on $REPO" request ahead of it.

Rebasing this, rebuilding images, and re-testing...

**Comment by cevich** [comment]
@giuseppe @mheon @baude this one is ready whenever y'all are.

**Pull request merged**
