### PR TITLE
Add multiple networks explanation to docs

### LINKED ISSUE #4341: Podman container doesn't connect to multiple networks
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Not sure if it's bug or additional feature though.
Docker supports connection to multiple network:
```
$ docker network create test1
bc1e8df612b28bd1986466b0d2fe97e09834bcc7c09c177d40962096d6afe257
$ docker network create test2
cc7f95d23fbddd854dfcc8d89cf6568519cef2fd2ff0ad39762cdfbd55183e6a
$ docker network ls
NETWORK ID          NAME                            DRIVER              SCOPE
18c8d06eedbc        bridge                          bridge              local
5a775f9a9c4f        host                            host                local
98a3288a99a8        none                            null                local
bc1e8df612b2        test1                           bridge              local
cc7f95d23fbd        test2                           bridge              local

$ docker create -it --name dockertest --network test1  alpine sh
56abc390eee0e322f5e89b831b249403863124f82ffdf438a22afbdd8eb48c4e

$ docker ps -a | grep dockertest
56abc390eee0        alpine                                   "sh"                       18 seconds ago      Created                                                                     dockertest

$ docker network connect test2 dockertest
$ docker start dockertest
$ docker exec -it dockertest sh
/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
137: eth1@if138: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:ac:17:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.23.0.2/16 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe17:2/64 scope link
       valid_lft forever preferred_lft forever
139: eth0@if140: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:ac:16:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.22.0.2/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe16:2/64 scope link
       valid_lft forever preferred_lft forever
/ #

```

Podman container connect to one only even if running with multiple `--network` options:

**Steps to reproduce the issue:**

1. `sudo ./bin/podman run --rm --name test -it --network next --network custom alpine sh`

2.
```
/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
3: eth0@if124: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether aa:30:1d:08:c0:81 brd ff:ff:ff:ff:ff:ff
    inet 10.89.0.10/24 brd 10.89.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a830:1dff:fe08:c081/64 scope link
       valid_lft forever preferred_lft forever

```

3.
```
114: cni-podman1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether ca:d2:a3:49:82:7a brd ff:ff:ff:ff:ff:ff
    inet 10.89.0.1/24 brd 10.89.0.255 scope global cni-podman1
       valid_lft forever preferred_lft forever
    inet6 fe80::c8d2:a3ff:fe49:827a/64 scope link
       valid_lft forever preferred_lft forever
116: cni-podman2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether ca:34:40:70:1c:83 brd ff:ff:ff:ff:ff:ff
    inet 10.99.99.1/24 brd 10.99.99.255 scope global cni-podman2
       valid_lft forever preferred_lft forever
    inet6 fe80::c834:40ff:fe70:1c83/64 scope link
       valid_lft forever preferred_lft forever
121: veth95c7f126@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master cni-podman1 state UP group default
    link/ether a2:56:71:4b:08:5a brd ff:ff:ff:ff:ff:ff link-netns cni-dc9bde39-f51a-4a60-be43-1528768cd56a
    inet6 fe80::a056:71ff:fe4b:85a/64 scope link
       valid_lft forever preferred_lft forever

```

**Describe the results you received:**
Podman connected to first created network only

**Describe the results you expected:**
Podman connect to multiple networks, specified in CLI or with `network connect` as in `docker`.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.6.3-dev
RemoteAPI Version:  1
Go Version:         go1.12.10
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.10
  podman version: 1.6.3-dev
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.1-1.fc30.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.1, commit: 4346fbe0b2634b05857973bdf663598081240374'
  Distribution:
    distribution: fedora
    version: "30"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 1914847232
  MemTotal: 25091493888
  OCIRuntime:
    name: runc
    package: runc-1.0.0-95.rc9.gitc1485a1.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc9+dev
      commit: 0840802d505e28d3adcbc7a275cbeadbdf64ddec
      spec: 1.0.1-dev
  SwapFree: 11718504448
  SwapTotal: 12645822464
  arch: amd64
  cpus: 4
  eventlogger: file
  hostname: sshnaidm.remote
  kernel: 5.3.6-200.fc30.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-4.git19d199a.fc30.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.2
      commit: 19d199a6ca424fcf9516320a327cedad85cf4dfb
  uptime: 58h 43m 17.64s (Approximately 2.42 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/sshnaidm/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.6.4-2.fc30.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.6.4
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/sshnaidm/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 21
  RunRoot: /tmp/1000
  VolumePath: /home/sshnaidm/.local/share/containers/storage/volumes
```

### PR DESCRIPTION
**Pull request by sshnaidm**
Mention how to pass multiple networks option, because it wasn't clear enough
Closes #4341

### CODE REVIEW

**Comment by mheon** [comment]
@sshnaidm Can you add a signoff with `git commit --amend -s` and re-push? Should make the CI go green

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
