### PR TITLE
    fix commands without input

### PR DESCRIPTION
**Pull request by baude**
in cases where commands require input and we dont provide it, we often would segv.  This can be attributed in many cases to the subcommand not picked up the cobra Args attribute or neither had them.

this includes eds pr #6054

### CODE REVIEW

**Comment by edsantiago** [comment]
LGTM. I don't understand the build error; the first thing I did was git-pr this locally and build it.

**Comment by mheon** [comment]
Probably one of the two commits does not build on its own; I'd try squashing them down to one.

LGTM otherwise.

**Comment by edsantiago** [comment]
>Probably one of the two commits does not build on its own

That seems impossible at first glance; and no matter how I look at it it's still impossible. The error message makes no sense. I'm starting to think there's something broken in the build_each_commit test.

**Comment by edsantiago** [comment]
Aha - `build_all_commits` is rebasing onto master, which now has #6047, which relies on `errors`. @baude, you need to rebase onto master and re-add the `pkg/errors` include.

**Comment by edsantiago** [comment]
Oops. Sorry, I meant to run the full BATS suite but got distracted.

**Pull request merged**
