### PR TITLE
Replace podman.svg

### PR DESCRIPTION
**Pull request by dankohn**
On a computer that doesn't have the font Montserrat installed, the old SVG won't render correctly.
We converted the font text to be objects so that it renders correctly on all computers. See https://github.com/cncf/landscape#proper-svgs.

### CODE REVIEW

**Comment by dankohn** [comment]
Addresses #3350

**Comment by giuseppe** [comment]
thanks for the patch.  The changes LGTM.  Could you please squash them in one commit and add a the signoff?

**Comment by dankohn** [comment]
Done.

**Comment by rhatdan** [comment]
/lgtm
Thanks @dankohn

**Pull request merged**
