### PR TITLE
Some BATS cleanup: run and systemd tests

### PR DESCRIPTION
**Pull request by edsantiago**
run test: run positive test before negative; and actually
implement real negative tests. Note that '--conmon-pidfile'
will happily clobber an existing file; I don't know if that
is desired behavior. Also, add confirmation tests for
cidfile/pidfile, not just 'exit status is good'.

systemd test: enable rootless, and again add actual content
testing.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
@vrothberg ptal

**Comment by mheon** [comment]
LGTM but want a signoff from @vrothberg before merge

**Comment by edsantiago** [comment]
I'd rather not merge with that giant FIXME. @vrothberg can you comment on whether or not --conmon-pidfile should clobber existing file?

**Comment by vrothberg** [comment]
> I'd rather not merge with that giant FIXME. @vrothberg can you comment on whether or not --conmon-pidfile should clobber existing file?

cidfile and conmon-pidfile behave differently. AFAICS, it's expected that cidfile fails (Docker compat) while pidfile overwrites (to make conmon simpler).

**Comment by edsantiago** [comment]
Thank you. I've removed the FIXME and the commented-out code. Tests are green.

**Pull request merged**
