### PR TITLE
Support podman-remote help on windows

### PR DESCRIPTION
**Pull request by jwhonce**
* Update scipts to produce darwin and windows output
* Update batch file to re-direct help requests to browser
* Add pandoc filter for markdown to html links

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by cevich** [comment]
LGTM and thanks for re-writing that `podman-remote.sh` looks **much** better.  WRT my #3879 as long as the output msi ends up in the repo-root, the part the publishes it up into the cloud should be happy

ref: https://github.com/containers/libpod/pull/3879/files#diff-0f7067c31caedf7df2739c9b07efa122R487

Speaking of which...I really need to get back to dabbling on that.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
