### PR TITLE
Fixup README.md to give proper information

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @baude @giuseppe @vrothberg @ashley-cui @QiWang19 @jwhonce PTAL

**Comment by TomSweeneyRedHat** [comment]
FYI @jberkus another README.md update with Podman incoming

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
