### PR TITLE
Small fix to readme to force tests to run

### PR DESCRIPTION
**Pull request by mheon**
Tests against master are broken. Let's make them not broken.

First change is a small readme fix to convince CI to run said tests.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM, but tests aren't happy still.

**Comment by mheon** [comment]
0x2 is ENOENT, coming out of `ioutil.WriteFile()`...

**Comment by mheon** [comment]
Ok, it's an `ENOENT` out of `open` with `O_CREAT` set, so a file in the path doesn't exist. Need an `os.MkdirAll` to fix...

**Comment by mheon** [comment]
Alternatively, just make it after the container is running...

**Pull request merged**
