### PR TITLE
Bump to v2.0.0-RC2

### PR DESCRIPTION
**Pull request by mheon**
As the title says

### CODE REVIEW

**Comment by rhatdan** [comment]
I think we should wait until by big test enablement gets in.  Lots of fixes in it.

**Comment by mheon** [comment]
@rhatdan I think there's value in getting this out today - what PR are you talking about, so we can whack it quickly?

**Comment by rhatdan** [comment]
https://github.com/containers/libpod/pull/6341

**Comment by mheon** [comment]
Going to close and recreate once 6341 merges

**Pull request closed without merging**
