### PR TITLE
Fix up linter failures

### PR DESCRIPTION
**Pull request by rhatdan**
For now we need to commend out deadcode, since I can not figure out how to stop
it looking at cGo Generated code.

I removed all of the go dead code that it was finding.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@saschagrunert Do you know how to make the linter ignore cgo generated code for deadcode check?

**Comment by rhatdan** [comment]
@mrunalp Any idea how to get the linter into OpenShift?

**Comment by saschagrunert** [comment]
> @saschagrunert Do you know how to make the linter ignore cgo generated code for deadcode check?

If we know the names of the files/dirs we could exlude them via the configuration:
https://github.com/golangci/golangci-lint/blob/8c1237b/.golangci.example.yml#L22-L37

**Comment by baude** [comment]
@rhatdan the change has to be made in the openshift git repo as well as have them approve and merge it.  this is why i wanted to revert it so we could still be useful while that happens.

**Comment by baude** [comment]
also, we could just disable the deadcode check for now by altering `.golangci.yml`

**Comment by rhatdan** [comment]
@baude Understood on disabling the #deadcode.  And this PR Actually does disable it, although I would love to figure out how to fix or ignore the cgo failures.

**Comment by saschagrunert** [comment]
@rhatdan Do you have a run where the actual issues with the deadcode linter happens?

I would like to support here but I'm not sure how to reproduce the mentioned issue. I thought that #2863 + the availability of `golangci-lint` on the machine running `ci/prow/lint` should be enough to make the pipeline working again.

**Comment by baude** [comment]
> @rhatdan Do you have a run where the mentioned issues with the deadcode linter happen?
> 
> I would like to support here but I'm not sure how to reproduce it. I thought that #2863 + the availability of `golangci-lint` on the machine running `ci/prow/lint` should be enough to make the pipeline working again.

again, the availability of the the new linter on prow is not a snap of the fingers.  It would be more prudent to do that first and then do what was done.

**Comment by stevekuznetsov** [comment]
FYI y'all control what container image is used to run the linting job (it's not a machine and nobody installs anything to it!!). Add the linter to your [`build_root`](https://github.com/openshift/release/blob/cd52819800ec1cb4e695a0f30875ebf313e9961f/ci-operator/config/containers/libpod/containers-libpod-master.yaml#L29-L34) and also to your other base image [here](https://github.com/openshift/release/blob/cd52819800ec1cb4e695a0f30875ebf313e9961f/ci-operator/config/containers/libpod/containers-libpod-master.yaml#L36-L40) -- @baude added the Dockerfiles for those images [here](https://github.com/openshift/release/blob/master/projects/libpod/libpod.yaml). You should be able to (and feel free to) check in any OWNERS file you want into those directories so that you can your teams can control and merge into them at will, without having to ask anyone else for help. If you make sure that applying your build YAML to the cluster is part of the `make postsubmit-update` target in `openshift/release`, changes to the `libpod.yaml` will automatically be applied to the cluster on merge.

**Comment by mheon** [comment]
Assuming we can get the image we use for lint regnerated, per Steve's instructions...
LGTM.

**Comment by mheon** [comment]
We merged the revert to unblock work.

I'll leave this open for now, but it should include the original patches as well.

**Comment by rhatdan** [comment]
We can wait for @cevich to return, to finish the work.  I hate to go back, but this seems to be best for now.

**Comment by mheon** [comment]
I'm going to close this. We should handle the migration back to golangci-lint in a separate PR.

**Pull request closed without merging**
