### PR TITLE
Only include ports in one container in Kube YAML

### LINKED ISSUE #3408: podman generate kube results in broken ports configuration
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

YAML generated by `podman generate kube` contains broken ports configuration. There is also a bonus bug found during removing the pod.

**Steps to reproduce the issue:**

```
podman pod create --name postgresql -p 5432 -p 9187
baf367c1e7baf627c383ef1d80efa69b34dc9b0c0c06839b371fc5599c0d0e08
podman run -d --pod postgresql -e POSTGRES_PASSWORD=password postgres:latest                                                                           
9b8f325ff257d5670e1a1161c4bef168cf0bc7be0d3308da76a560678c389692
podman run -d --pod postgresql -e DATA_SOURCE_NAME="postgresql://postgres:password@localhost:5432/postgres?sslmode=disable" wrouesnel/postgres_exporter
0b933d2d4f056670143917057f67b7d933c27097fab3a274b79e52447a059046
podman generate kube postgresql > postgresql.yaml
podman pod rm postgresql -f
```
Last command throws this error:

```
ERRO[0000] cleanup volume (&{3e9db716f4210d923945df5c92f17231a171305c517b395eee5f5bc1b3d67072 /var/lib/postgresql/data [rprivate rw nodev rbind]}): volume 3e9db716f4210d923945df5c92f17231a171305c517b395eee5f5bc1b3d67072 is being used by the following container(s): 9b8f325ff257d5670e1a1161c4bef168cf0bc7be0d3308da76a560678c389692: volume is being used 
baf367c1e7baf627c383ef1d80efa69b34dc9b0c0c06839b371fc5599c0d0e08
```

But it's probably m'kay, because pod is removed and all good. Let's continue the road to primary bug of this issue:

```
podman play kube postgresql.yaml
```

This throws:

```
ERRO[0000] error starting some container dependencies   
ERRO[0000] "error from slirp4netns while setting up port redirection: map[desc:bad request: add_hostfwd: slirp_add_hostfwd failed]" 
Error: error starting some containers: internal libpod error
```

**Describe the results you received:**

Faulty postgresql.yaml that is not usable due to incorrect port configuration. Somehow the command resulted in this port config for __both__ containers:

```
    ports:
    - containerPort: 5432
      hostPort: 5432
      protocol: TCP
    - containerPort: 9187
      hostPort: 9187
      protocol: TCP
```

If I leave 5432 for PostgreSQL and 9187 for exporter, then `podman play kube` works. But then there is another issue: for postgres_exporter Podman generated following config:

```yaml
  containers:
  - command:
    - /postgres_exporter
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: HOSTNAME
    - name: container
      value: podman
    - name: DATA_SOURCE_NAME
      value: postgresql://postgres:password@localhost:5432/postgres?sslmode=disable
    image: docker.io/wrouesnel/postgres_exporter:latest
    name: cockymirzakhani
    ports:
    - containerPort: 9187
      hostPort: 9187
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    workingDir: /
```

Notice the `command` part: this is wrong, because the image itself has `/postgres_exporter` as an _entrypoint_. So when I run `podman play kube` container tries to run `/postgres_exporter /postgres_exporter` and fails to start. If I remove generated `command` then it starts just fine. And if I run `podman pod rm postgresql -f` on the pod started with `podman play kube` with a fixed postgresql.yaml, then I don't hit a bonus bug described earlier.

**Describe the results you expected:**

Correct YAML that can be used straight ahead.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 1.4.2
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.5
  podman version: 1.4.2
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.2-1.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.2.0, commit: d7234dc01ae2ef08c42e3591e876723ad1c914c9'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 4364161024
  MemTotal: 25005821952
  OCIRuntime:
    package: runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: e3b4c1108f7d1bf0d09ab612ea09927d9b59b4e3
      spec: 1.0.1-dev
  SwapFree: 12574236672
  SwapTotal: 12574519296
  arch: amd64
  cpus: 8
  hostname: localhost.localdomain
  kernel: 5.0.14-300.fc30.x86_64
  os: linux
  rootless: true
  uptime: 390h 49m 52.58s (Approximately 16.25 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/fodoj/.config/containers/storage.conf
  ContainerStore:
    number: 6
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/fodoj/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 13
  RunRoot: /tmp/1000
  VolumePath: /home/fodoj/.local/share/containers/storage/volumes

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Just my personal laptop with Fedora 30.

### PR DESCRIPTION
**Pull request by mheon**
This likely broke when we made containers able to detect that they shared a network namespace and grab ports from the dependency container - prior to that, we could grab ports without concern for conflict, only the infra container had them. Now, all containers in a pod will return the same ports, so we have to work around this.

Fixes #3408

Still needs a test, writing one now.

### CODE REVIEW

**Comment by rhatdan** [comment]
Nice easy fix.
LGTM

**Comment by Fodoj** [comment]
Don't want to be picky, but doesn't it break portability of generated yaml to k8s environment? Assuming there will be no infra container on k8s it means that pod yaml won't expose any ports.

**Comment by mheon** [comment]
While writing a test, I realized that all the `generate kube` tests are verifying the YAML using `yaml.Marshal` instead of `yaml.Unmarshal()` which is really not good. Will see about fixing as part of this.

**Comment by mheon** [comment]
@Fodoj We actually take the ports from the infra container and stick them on the first container in the generated output, so even if there is no infra container, we should be good.

**Comment by Fodoj** [comment]
@mheon correct me if I am wrong, but then if I have two containers A and B, A has something running on port 1234, B on 4567. Then YAML exposes both ports on container A, but not container B, meaning that B:4567 can't be reached when connecting to the port, and A:4567 is useless, as nothing is running on this port inside A. Of course if 4567 is "exposed" in the container image behind container B, then it probably won't be an issue, but still generated YAML is kind of misleading (A exposes 2 ports, B exposes none via YAML definition, but exposes one as part of an image).

**Comment by mheon** [comment]
Within Podman alone, if you're using `play kube` to play the YAML, all ports are properly of the infra container only, and point to the pod as a whole (unless you explicitly opt out of sharing the network namespace when creating a new container). So this will work as expected there - the ports are detected, and added to the infra container once more on container creation.

If moving up to Kube, if you generate a service object, the ports are again forwarded to the pod, so it should work there too.

The question would be importing the YAML into Kube without a service.

(The ability for containers to request individual ports within a pod is coming, hopefully soon, but they'll still all be managed by the infra container - it'll just be taking the requested ports of other containers in the pod into account).

**Comment by Fodoj** [comment]
> If moving up to Kube, if you generate a service object, the ports are again forwarded to the pod, so it should work there too.

My concern is more around that one container (the one that exposes _only_ 1234) would have this config:

```yaml
    ports:
    - containerPort: 1234
      hostPort: 1234
      protocol: TCP
    - containerPort: 4567
      hostPort: 4567
      protocol: TCP
```

And another one (that exposes 4567) won't have any port configuration at all.

According to Kubernetes container spec:

> List of ports to expose from the container. Exposing a port here gives the system additional information about the network connections a container uses, but is primarily informational. Not specifying a port here DOES NOT prevent that port from being exposed. Any port which is listening on the default "0.0.0.0" address inside a container will be accessible from the network. 

So even though not specifying a port wont prevent it from being exposed if container does listen on this port, YAML configuration produced by Podman would be still a bit misleading.

**Comment by baude** [comment]
@Fodoj can you join us on irc.freenode.net #podman to discuss?  we can probably get down to an answer quicker?

**Comment by mheon** [comment]
My port-detection logic seems to be failing in the tests. Investigating...

**Comment by mheon** [comment]
Decode is definitely failing - we're seeing 0 containers in the pod.

**Comment by mheon** [comment]
Throwing a hold on here - even if tests go green I want to do some more work on them.
/hold

**Comment by mheon** [comment]
Alright. Tests are in a better spot. Cancelling hold
/hold cancel

**Pull request merged**
