### PR TITLE
WIP Recursively stop a pod.

### PR DESCRIPTION
**Pull request by haircommander**
Before, there existed an edge case where a container in a pod stop would fail to stop, which would allow it to stop after the pod infra container. This breaks the invariant that the infra container should be running while any container is running. fix this by recursively stopping in a pod.

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
@mheon PTAL the first version. I'm not sure I'm happy yet because the pod version of the reproducer of #2577 still fails to stop (I can kill the memcache container, but then I can't stop the infra container with a 'pod stop'). It does, however, keep the infra container running if memcache can't be stopped, which maintains the invariant.

**Comment by mheon** [comment]
@haircommander Didn't we figure out that this was actually a rootless issue?

I'm not opposed to these patches though, just don't think we have an actual race here

**Comment by rhatdan** [comment]
Isn't there a simpler way to do this. By stopping all of the containers first and then stopping the infracontainer?

BTW:In a shared PID Namespace as soon as the infracontainer stops all of the other containers will die.

**Comment by mheon** [comment]
We can't guaranteed shared PID namespace, though.

I don't actually know if this one is necessary. I think the main issue we ran into was permissions, not ordering.

**Comment by haircommander** [comment]
Yeah I'm also unconvinced it's necessary

**Comment by haircommander** [comment]
I'll keep the branch around but I'm inclined to not add such complex code for a problem that isn't really supposed to be a problem

**Comment by rhatdan** [comment]
I was just adding info on the PID Namespace, not saying it solves all issues.  I would prefer to stay away from the complexity of this code also.

**Pull request closed without merging**
