### PR TITLE
Mention officially supported OSes, fixes #2208

### LINKED ISSUE #2208: Specify which platforms are supported
The following is said in README.md

> available on most Linux platforms

This could be improved to specifically support certain platforms. For example:

> RHEL 7.0 and Ubuntu 18.10 host platforms are officially supported, although the community has also reported success with other Linux distributions. Windows and macOS and other OS hosts are not supported at this time.

### PR DESCRIPTION
**Pull request by fulldecent**

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
bot, add author to whitelist

**Comment by vrothberg** [comment]
I am not a big fan of the RHEL branding on the main README (and am a RH employee).

Where do we draw the line between "officially supported" and "community supported"? Who is the community? Who is the support? For instance, Podman is *by default installed* on SUSE CaaS Platform (enterprise beta) and also on openSUSE Kubic. Implicitly claiming that RHEL is the only supported platform can be interpreted negatively by those putting a lot of work into the project for other distributions and products. If I have a veto, I am using it here :^)

My suggestion is to add such information to https://github.com/containers/libpod/blob/master/install.md and mention that Red Hat officially supports Podman and list the versions etc. This way, the entity is clear and we don't mix the project/community with a company and its enterprise products.

**Comment by fulldecent** [comment]
The word "officially" was ambiguous so I removed it. Is the new wording an improvement?

**Comment by vrothberg** [comment]
> The word "officially" was ambiguous so I removed it. Is the new wording an improvement?

Thanks a lot for updating it! The tests fail because all commits must be signed (e.g., via `git commit --amend -s`).

My statement from https://github.com/containers/libpod/pull/2237#issuecomment-458884508 still holds. The `install.md` should contain such information and the agents must be clear.

> This project supports builds on RHEL7 and RHEL8 Beta, although the community has also reported success with other Linux flavors.

This gives me the impression that I can download RPMs from GitHub and install them on RHEL7 and RHEL8 Beta, but that's not the case. What I believe the sentence is targetting at is that Red Hat offers support for Podman on those products but that is cleary something Red Hat needs to say and I feel confident in saying that `Red Hat != this project` although most contributors work for Red Hat (including myself).

We validate each commit against Fedora, RHEL and Ubuntu, so they're somehow equally "supported".

The devil lies in the details but I find it very important to keep this project vendor/distribution neutral and to make sure that enterprise supports means that the vendors support it not the project as a whole. A RHEL customer should open a bug in Red Hat's bugzilla first. I know that's not the intention of this PR but the text can be interpreted in a way that is not beneficial to the project.

**Comment by fulldecent** [comment]
New version. This avoids the word support altogether and provides only the literal explanation about which builds are in CI.

Rather than specific linux flavor version numbers, this provides a context that could be more helpful.

Commit does use sign off.

After the text is correct I hope we discuss its location afterward. I believe the README is appropriate because you read that first. Personally, I originally decided not to continue reading the INSTALL file or learn more because it was not clear to me if this was a hobby project or if RHEL was going to work. Infrastructure is important for my production environment so I don't hope to change it multiple times :-p

**Comment by mheon** [comment]
Change LGTM on my end.
@TomSweeneyRedHat @rhatdan PTAL

**Comment by mheon** [comment]
bot, retest this please

**Comment by vrothberg** [comment]
Thanks for addressing my major concerns, @fulldecent! A small nit in the text: `s/RedHat/Red Hat/`.

**Comment by fulldecent** [comment]
Red Hat spelling corrected.

**Pull request merged**
