### PR TITLE
Remove Papr - it's no longer functional on this repo

### PR DESCRIPTION
**Pull request by mheon**
Necessary to land further commits in this branch

### CODE REVIEW

**Comment by mheon** [comment]
We need to land this prior to #2890

**Comment by TomSweeneyRedHat** [comment]
LGTM, assuming happy tests

**Comment by mrunalp** [comment]
Is the integration failure a known issue or a flake?

**Comment by mheon** [comment]
Rerunning. This branch is months old, so I'm no longer sure what flakes to expect on it.

**Comment by wking** [comment]
All green here now :)

**Pull request merged**
