### PR TITLE
Revert #6591 to fix issue with failed tests

### PR DESCRIPTION
**Pull request by jgallucci32**
Signed-off-by: jgallucci32 <john.gallucci.iv@gmail.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
but I think @mheon had another thought elsewhere and I can't find it quickly.

**Comment by jgallucci32** [comment]
@TomSweeneyRedHat I did a rebase with the recent #6640 push from @edsantiago to verify his change in log testing still works and it has passed all the checks. This is ready for review.

**Comment by rhatdan** [comment]
@jgallucci32 This looks fine to me because it removes functionality, but does the logs --follow code work correctly after this reversal?

Does `podman logs -f CTR` work if Container is stopped? Paused?

If I am doing `podman logs -F CTR` and CTR is stopped, does podman logs stop?

LGTM

**Comment by TomSweeneyRedHat** [comment]
This is all green now and I think will solve a number of CI tests issues once merged.

**Comment by rhatdan** [comment]
Ok Thanks @jgallucci32

**Pull request merged**
