### PR TITLE
[CI:DOCS] Fixed typo on podman network create man

### PR DESCRIPTION
**Pull request by e-minguez**

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @e-minguez 
But you need to sign your PR.

git commit -a -s --ammend
git push --force

**Comment by e-minguez** [comment]
> Thanks @e-minguez
> But you need to sign your PR.
> 
> git commit -a -s --ammend
> git push --force

Kids, always read the CONTRIBUTING.md, don't be like me :sweat_smile: 

Sorry, fixed now. Thanks

**Comment by rhatdan** [comment]
/approve
LGTM

**Comment by mheon** [comment]
/hold

Integration flaked

**Pull request merged**
