### PR TITLE
Correct logic for demux'ing channels

### LINKED ISSUE #6574: podman-remote: exec: Error: unrecognized channel in header: 1, 0-3 supported
Window 1:
```console
$ MYSOCK=unix:/tmp/mypodmansock
$ ./bin/podman --log-level=debug system service --timeout=0 $MYSOCK
```
Window 2:
```console
$ MYSOCK=unix:/tmp/mypodmansock
$ $ ./bin/podman-remote --url $MYSOCK run --name foo -d alpine top
88ea90c55e35429bf11ce08609bf54cb4ca8b91d35e3fe71ede1a2835bdcc863
$ ./bin/podman-remote --url $MYSOCK exec foo date
Error: unrecognized channel in header: 1, 0-3 supported
```
(note that 'date' output never appears).

master @ 142e62cb45e54a0e77b598c76886e5cff0cdbb45

### PR DESCRIPTION
**Pull request by jwhonce**
* Move check for requesting output into case statement

reference #6574 

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by jwhonce** [comment]
@mheon This commit fixes demux'ing the output.  But now messages from conmon appear to be exposed...

```
$ bin/podman-remote --url $MYSOCK run --name foo1 -d alpine top
f5c4cf63f2e206aa99a12b625c72fa9de4b740e6f02b493abe3eb35f03c3cc11
$ bin/podman-remote --url $MYSOCK exec foo1 date
[conmon:d]: exec with attach is waiting for start message from parent
[conmon:d]: exec with attach got start message from parent
```

**Comment by mheon** [comment]
Damn - took me a second to realize, but yeah, this is definitely the fix.

LGTM

**Comment by mheon** [comment]
@jwhonce Hmmm. When I was testing Exec, those were fd=3...

**Comment by mheon** [comment]
Do you know what stream they're coming in on?

**Comment by jwhonce** [comment]
@mheon fd=1

**Comment by mheon** [comment]
@jwhonce Even worse, it's not showing the output of `date` unless I provide `-i`

**Comment by mheon** [comment]
The `conmon` output only happens with `--log-level=debug` is specified on the server, so I don't know if printing Conmon debug is the worst thing. Not printing the output of `date` is a serious bug though.

**Comment by mheon** [comment]
It's specific to `exec`, `podman run` works

**Comment by mheon** [comment]
We're getting an early EOF/dropped connection out of Conmon. Maybe we're not draining the buffer entirely in the exec case?

**Comment by mheon** [comment]
@jwhonce IMO, we should just merge this, file a bug for the further issue and we'll look into it later.

**Comment by rhatdan** [comment]
Please fix the commit message.  This will not work well when someone goes back to look at history in git.

**Pull request merged**
