### PR TITLE
Update run_test to be more robust

### PR DESCRIPTION
**Pull request by saschagrunert**
Hey there, I would skip these tests if not supported by the running platform.

### CODE REVIEW

**Comment by vrothberg** [comment]
Thanks! The changes LGTM but the commit message could be more descriptive.

**Comment by saschagrunert** [comment]
> Thanks! The changes LGTM but the commit message could be more descriptive.

Alright, I changed the message to be a more precise.

**Comment by mheon** [comment]
/ok-to-test
LGTM
@baude PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch.

**Pull request merged**
