### PR TITLE
Manpage: fix podman-varlink and -version mixup

### PR DESCRIPTION
**Pull request by marcusmueller**
just a minor bugfix

### CODE REVIEW

**Comment by mheon** [comment]
Can you add a signoff with `git commit --amend -s` and re-push? Otherwise, LGTM

**Comment by marcusmueller** [comment]
@mheon ha! collision. Signed off the commit. Thanks!

**Comment by rhatdan** [comment]
Thanks @marcusmueller.  LGTM
/lgtm

**Comment by TomSweeneyRedHat** [comment]
Kicked off the failing test here too, I can't imagine it's related to this PR change.

**Pull request merged**
