### PR TITLE
Add support for /usr/local installation

### PR DESCRIPTION
**Pull request by afbjorklund**
In the default `libpod.conf` configuration

### CODE REVIEW

**Comment by mheon** [comment]
bot, add author to whitelist

**Comment by TomSweeneyRedHat** [comment]
@mheon an administration question.  I thought we white-listed @afbjorklund prior, do we have to white-list him every time or am I mis-remembering?

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by mheon** [comment]
I think the whitelist was cleared at some recent point during all our CI troubles. Which is sort of unfortunate...

Unfortunately, I think we need to do per-PR approval for Cirrus and Openshift too.

**Comment by TomSweeneyRedHat** [comment]
@mheon thanks, the ci troubles clearing it makes sense and I'm not completely losing my marbles.

**Pull request merged**
