### PR TITLE
DO NOT MERGE: WIP: Revert "vendor containers/image v1.4"

### PR DESCRIPTION
**Pull request by cevich**
This reverts commit c069d117594d72159157aa48d0693d8571be45c5.

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
@mheon @vrothberg I have no idea why, but this was the commit where the +10min slowdown on all OS began.  Testing here to see if reverting gains back that time.  If not, I'll throw the PR away.

**Comment by vrothberg** [comment]
Note that reverting this commit will yield broken progress bars. If this update is truly responsible, I suggest bumping the timeouts as a symptomatic patch until we figured out the root cause.

**Comment by cevich** [comment]
*note:* [Ubuntu failure](https://cirrus-ci.com/task/5954628865753088) in [first run is a flake (http timeout)](https://cirrus-ci.com/build/5735403366645760)

**Comment by cevich** [comment]
Going through (manually) the history of post-merge test results, this looks to be the history:

1. [Merge of PR #2321 appears to be the last one matching baseline.](https://cirrus-ci.com/build/4867130735460352)
2. [Merge of PR #2336 appears to have made results worse only on Ubuntu](https://cirrus-ci.com/build/5658814322835456)
3. [Merge of PR #2332 appears to have made results worse on F29](https://cirrus-ci.com/build/6560841089417216)
4. [Merge of PR #2295 appears to have made results worse on F28](https://cirrus-ci.com/build/5142407252279296)

This is all based on "bisecting" the [chain of master merges reported by cirrus](https://cirrus-ci.com/github/containers/libpod/master).  Clicking on them, and eyeballing the times vs the baseline.  The results may vary +/- a PR depending on which way you tilt your head.

Conclusion: Adding features and fixing bugs appears to grows code, and makes crap run slower :frowning_face:   I'm not sure anyone could look at those PRs and pick with certainty what the "smoldering weapon" was (w/o spending oodles of time).  Consider if time is best spent on that, or if more "explosions for currency-units" would be gained by more controlled performance analysis for each platform.  IMHO, the later probably has a bigger RoI in the long-term.

**Comment by vrothberg** [comment]
Thanks for the great analyses, @cevich! I think we could really need some more profiling and dedicate some time to improving the speed of the code.

**Comment by cevich** [comment]
@vrothberg I only wish I could be more accurate.  We're really starting to hurt in the data gathering / tracking department.  I should probably drop an official TODO item or some thinking on HOWTO for that.

**Pull request closed without merging**
