### PR TITLE
Add remote exec

### PR DESCRIPTION
**Pull request by haircommander**
Make appropriate changes to varlink exec api and containers_remote to implement remote exec.
Update the exec e2e tests to run with remote exec.

~Note, there currently exists one flaw with this implementation, where running a shell in -ti and calling exit causes the runtime to exit with 130 and print an ugly message. not sure why this happens in remote and not local. Stay tuned, but I figured I'd get this out there for review in the meantime~
Edit: the above is no longer a problem, and this is ready for review

### CODE REVIEW

**Comment by haircommander** [comment]
PTAL @baude @jwhonce @mheon @rhatdan @QiWang19 @TomSweeneyRedHat @ashley-cui

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green tests

**Pull request merged**
