### PR TITLE
Do not default WorkingDir to / on client side

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

Fixes https://github.com/containers/libpod/issues/6585

### CODE REVIEW

**Comment by rhatdan** [comment]
@goochjj  @jdoss PTAL

**Comment by jdoss** [comment]
LGTM!

```
$ podman version
Version:      2.0.0-dev
API Version:  1
Go Version:   go1.14.3
Git Commit:   2386a2ef2dd3ab4976a3e1dd6d76616e8558d85b
Built:        Fri Jun 12 07:23:57 2020
OS/Arch:      linux/amd64

$ podman run --rm --name redis-testing -p 6379:6379 redis:6.0.1
1:C 12 Jun 2020 12:25:57.161 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 12 Jun 2020 12:25:57.161 # Redis version=6.0.1, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 12 Jun 2020 12:25:57.161 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 12 Jun 2020 12:25:57.162 * Increased maximum number of open files to 10032 (it was originally set to 1024).
1:M 12 Jun 2020 12:25:57.162 * Running mode=standalone, port=6379.
1:M 12 Jun 2020 12:25:57.162 # Server initialized
1:M 12 Jun 2020 12:25:57.162 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 12 Jun 2020 12:25:57.162 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 12 Jun 2020 12:25:57.163 * Ready to accept connections
```

**Comment by goochjj** [comment]
Yep, confirmed fixed.
```
podman run --rm -it testimage sh
/tmp #
```

**Comment by rhatdan** [comment]
This led me to find another bug. https://github.com/containers/buildah/issues/2402

**Pull request merged**
