### PR TITLE
Only include container SizeRootFs when requested

### LINKED ISSUE #1876: pypodman inspect: option "size" should be option "--size"
**Is this a BUG REPORT or FEATURE REQUEST?**:

**kind bug**

**Description**
For keeping consistent with `podman`, the option `size` for **`pypodman`** should be `--size`, then `pypodman` will have the same usage as `podman` has:
https://github.com/jwhonce/libpod/blob/842320d2f7922c2ea66f57a07d0a5f67d980de48/contrib/python/pypodman/pypodman/lib/actions/inspect_action.py#L26

### PR DESCRIPTION
**Pull request by jwhonce**
* API always returns value, so we remove it if not asked for

Fixes #1876

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by jwhonce** [comment]
@Edward5hen PTAL

Good chance https://github.com/containers/libpod/pull/1893 is going to cause a conflict.

**Comment by mheon** [comment]
API always returns it? Eeesh

@baude @jwhonce We probably want to fix that, container rootfs size calculation is VERY expensive

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
Rootless tests should be fixed on master, so cirrus should pass now

**Pull request merged**
