### PR TITLE
update systemd & dbus dependencies

### PR DESCRIPTION
**Pull request by vrothberg**
Update the outdated systemd and dbus dependencies which are now provided
as go modules.  This will further tighten our dependencies and releases
and pave the way for the upcoming auto-update feature.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@giuseppe PTAL

**Comment by mheon** [comment]
Change LGTM

**Comment by vrothberg** [comment]
Had to run another `go mod tidy` to clean up the `go.mod` file. I wonder why `make vendor` didn't do that. Maybe we need to check the call order ?

**Pull request merged**
