### PR TITLE
Add retry decorator for flakey tests

### PR DESCRIPTION
**Pull request by jwhonce**
* Update doc strings

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by jwhonce** [comment]
@baude @TomSweeneyRedHat @umohnani8 Please review.  Thanks.

**Comment by umohnani8** [comment]
LGTM

**Comment by jwhonce** [comment]
@TomSweeneyRedHat That is the very flake we're trying to beat into submission. :) I added some debugging to see if I can determine more.

**Comment by jwhonce** [comment]
@TomSweeneyRedHat @baude Updating delay worked on this iteration.  Time will tell how much improvement we get.

**Comment by baude** [comment]
Lets give it a go ... good show @jwhonce !

**Comment by baude** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
