### PR TITLE
Fix podman-remote images

### PR DESCRIPTION
**Pull request by rhatdan**
Looks like we went too far with the linters.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@edsantiago PTAL
I think this fixes the podman-remote images.

**Comment by rhatdan** [comment]
Fixes: https://github.com/containers/libpod/issues/6623

**Comment by edsantiago** [comment]
Fix confirmed:
```console
$ ./bin/podman-remote --url $MYSOCK images
REPOSITORY                TAG     IMAGE ID      CREATED      SIZE
docker.io/library/alpine  latest  a24bb4013296  2 weeks ago  5.85 MB
```

**Comment by edsantiago** [comment]
Gating test failure looks exactly like the one @mheon encountered in his PR

**Comment by baude** [comment]
lgtm

**Comment by edsantiago** [comment]
Test failures: one is a known flake ("streaming something") that has been causing huge problems the past week. Two others are very weird (signal handling), but cirrus-flake-xref knows about them so I'm going to restart them all and hope they go away.

**Comment by edsantiago** [comment]
CI is passing after many, many test restarts! (the "podman logs" problem being discussed in #6614). 

/hold cancel

**Comment by edsantiago** [comment]
cirrus-flake-analyze: 

#### test ubuntu-19 ubuntu-19

  2020-06-16T11:30:48  [system_test](https://api.cirrus-ci.com/v1/task/4922638323679232/logs/system_test.log)
*   [47 podman kill - test signal handling in containers](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4922638323679232/html/system_test.log.html)

  2020-06-16T11:35:47  [integration_test](https://api.cirrus-ci.com/v1/task/6330013207232512/logs/integration_test.log)
*   [Podman trust [It] podman image trust show ](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6330013207232512/html/integration_test.log.html#t--podman-image-trust-show--1)
*   [Podman logs [It] streaming output ](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6330013207232512/html/integration_test.log.html#t--streaming-output--1)
  *   [[same]](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6330013207232512/html/integration_test.log.html#t--streaming-output--2)
  *   [[same]](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6330013207232512/html/integration_test.log.html#t--streaming-output--3)

  2020-06-16T12:32:30  [integration_test](https://api.cirrus-ci.com/v1/task/4622192845520896/logs/integration_test.log)
*   [Podman logs [It] streaming output ](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4622192845520896/html/integration_test.log.html#t--streaming-output--1)
  *   [[same]](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4622192845520896/html/integration_test.log.html#t--streaming-output--2)
  *   [[same]](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4622192845520896/html/integration_test.log.html#t--streaming-output--3)
*   [Podman trust [It] podman image trust show ](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4622192845520896/html/integration_test.log.html#t--podman-image-trust-show--1)
*   [Podman rmi [It] podman rmi image that is a parent of another image ](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4622192845520896/html/integration_test.log.html#t--podman-rmi-image-that-is-a-parent-of-another-image--1)

#### test ubuntu-20 ubuntu-20

  2020-06-16T11:33:11  [system_test](https://api.cirrus-ci.com/v1/task/5204113300389888/logs/system_test.log)
*   [47 podman kill - test signal handling in containers](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5204113300389888/html/system_test.log.html)

  2020-06-16T12:28:57  [system_test](https://api.cirrus-ci.com/v1/task/5393789894262784/logs/system_test.log)
*   [47 podman kill - test signal handling in containers](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5393789894262784/html/system_test.log.html)

  2020-06-16T13:13:38  [system_test](https://api.cirrus-ci.com/v1/task/6442968296980480/logs/system_test.log)
*   [47 podman kill - test signal handling in containers](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6442968296980480/html/system_test.log.html)

  2020-06-16T14:22:50  [system_test](https://api.cirrus-ci.com/v1/task/5920937906274304/logs/system_test.log)
*   [47 podman kill - test signal handling in containers](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5920937906274304/html/system_test.log.html)

**Pull request merged**
