### PR TITLE
Disable SELinux labeling if --privileged

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes https://github.com/containers/libpod/issues/1575

Added test to make sure this regression does not happen again.

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
bot, retest this please

**Pull request merged**
