### PR TITLE
Attempt to turn on special_testing_endpoint tests

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@sujil02 PTAL
@baude @giuseppe @vrothberg @TomSweeneyRedHat @QiWang19 @jwhonce @mheon PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by sujil02** [comment]
LGTM

**Pull request merged**
