### PR TITLE
Backports for v1.6.4

### PR DESCRIPTION
**Pull request by mheon**
We're looking to cut a 1.6.4 including a fresh c/storage version with Valentin's patches for RHEL/Cent 8.2. These are the backports we want for that branch.

This is NOT targetted against master and is NOT our next master release - this is a separate one for RHEL.

### CODE REVIEW

**Comment by mheon** [comment]
(This is doubly confusing because we are ALSO cutting v1.7.0 on the master branch)

**Comment by giuseppe** [comment]
LGTM

**Comment by mheon** [comment]
@baude @rhatdan @vrothberg @TomSweeneyRedHat PTAL and merge

**Pull request merged**
