### PR TITLE
install.md:  point to containers/libpod

### PR DESCRIPTION
**Pull request by miabbott**

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by baude** [comment]
LGTM

**Comment by baude** [comment]
@rh-atomic-bot r+

**Comment by mheon** [comment]
@rh-atomic-bot r+

**Comment by mheon** [comment]
@miabbott Your commits are missing signoffs (the `git commit -s` kind) - can you add them and re-push?

**Comment by miabbott** [comment]
Oops!  Repushed with another edit.

**Pull request closed without merging**
