### PR TITLE
APIv2: Fixed syscall.Signal not convertable by decoder

### PR DESCRIPTION
**Pull request by schubter**
fixes `INFO[0057] Request Failed(Internal Server Error): failed to kill Container: schema: error converting value for "signal" `

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@schubter is there an issue in GitHub for this?  Just want to make sure it gets closed once this merges if there is one.

**Comment by schubter** [comment]
not sure, I haven't created one for this in particular but I will check.
i am trying to get the gitlab-runner to work with podman and fixing things as I go

**Comment by TomSweeneyRedHat** [comment]
OK, no worries.  Was just concerned we'd might leave behind an open issue that had been fixed.  Thanks for the submission!
LGTM

**Comment by mheon** [comment]
LGTM
@baude @jwhonce PTAL

**Pull request merged**
