### PR TITLE
Clean destination paths during mount generation

### PR DESCRIPTION
**Pull request by mheon**
We identify and resolve conflicts in paths using destination path matches. We require exact matches, largely for performance reasons (we use maps to efficiently access, keyed by destination). This usually works fine, until you get mounts that are targetted at /output and /output/ - the same path, but not the same string.

Use filepath.Clean() aggressively to try and solve this.

### CODE REVIEW

**Comment by mheon** [comment]
@vrothberg PTAL. I'm testing this one locally, but it ought to solve our issues

**Comment by vbatts** [comment]
hah woah

**Comment by vbatts** [comment]
i wonder why it was racy though?

**Comment by vrothberg** [comment]
> i wonder why it was racy though?

Maybe the two mounts were in a race? Sometimes the image volume won, sometimes the one from the cli?

**Comment by mheon** [comment]
I think we ended up with both mounts in the spec, and runc ended up choosing one - usually the wrong one - but I'm not sure why the order varied...

**Comment by vbatts** [comment]
fair. LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Pull request merged**
