### PR TITLE
Update readme for v1.0.0

### PR DESCRIPTION
**Pull request by mheon**
Also bump gitvalidation epoch - we usually do this every release, but v1.0.0 is on a branch so we need a separate commit for master.

### CODE REVIEW

**Comment by mheon** [comment]
Hold this until Monday, so we can get a blog on podman.io out to go with it.

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat @vrothberg @umohnani8 @giuseppe @baude PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM for a Monday merge

**Comment by mheon** [comment]
Rebased

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Pull request merged**
