### PR TITLE
Update vendor of boltdb and containers/image

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@vrothberg @mtrmac Any idea what is going on here?
[+0073s] Running: /var/tmp/go/src/github.com/containers/libpod/bin/podman --root /tmp/crio --runroot /tmp/crio-run --runtime /usr/bin/runc --conmon /usr/bin/conmon --cni-config-dir /etc/cni/net.d --cgroup-manager systemd --tmpdir /tmp --events-backend file --storage-driver vfs save -o /tmp/alpine_nginx-latest.tar quay.io/libpod/alpine_nginx:latest
[+0073s] Error: unable to save "quay.io/libpod/alpine_nginx:latest": Error copying image to the remote destination: Error creating an updated image manifest: Error preparing updated manifest: layer count changed from 3 to 7

**Comment by mtrmac** [comment]
Yeah, that’s almost certainly a bug in https://github.com/containers/image/pull/836 . I’ll take a look later today.

**Comment by mtrmac** [comment]
Test-only PR: https://github.com/containers/libpod/pull/5622 .

**Comment by mtrmac** [comment]
https://github.com/containers/image/pull/869 to release c/image v5.3.1.

**Comment by TomSweeneyRedHat** [comment]
Needs a rebase
I don't see the auth changes happening due to the vendor update.  I'd much prefer that in a separate PR, or at least noted in the title/description of this PR.

**Comment by TomSweeneyRedHat** [comment]
and a rebase is needed.

**Comment by rhatdan** [comment]
@mheon @vrothberg @mtrmac @TomSweeneyRedHat @baude @jwhonce @QiWang19 PTAL

**Comment by mheon** [comment]
/lgtm

Merging away

**Pull request merged**
