### PR TITLE
oci_conmon: not make accessible dirs if not needed

### PR DESCRIPTION
**Pull request by giuseppe**
do not change the permissions mask for the rundir and the tmpdir when running a container with a user namespace and the current user is mapped inside the user namespace.
    
The change was introduced with 849548ffb8e958e901317eceffdcc2d918cafd8d, that dropped the intermediate mount namespace in favor of allowing root into the user namespace to access these directories.

Closes: https://github.com/containers/libpod/issues/4846

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Very cool if this works.
LGTM

**Comment by giuseppe** [comment]
> Very cool if this works.
> LGTM

so now I remember where it was failing.  If the user is not mapped inside of the user namespace, it won't have access to any temporary file we create (such as hostname, .containerenv, passwd) and the OCI runtime will fail.

The correct check is to verify if the current user is mapped inside the user namespace.

**Comment by mheon** [comment]
Huh. Neat. LGTM once this goes green.

**Pull request merged**
