### PR TITLE
Fix play to show up in podman help

### PR DESCRIPTION
**Pull request by rhatdan**
Also change generate cli calls to match other commands.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes https://github.com/containers/libpod/issues/2303

**Comment by mheon** [comment]
Partially... It doesn't address the volumes part of 2303, but it does get our critical issue fixed.

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
@baude @TomSweeneyRedHat @giuseppe @vrothberg PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM but would like a head nod from @baude

**Comment by vrothberg** [comment]
Should we add tests checking for such cli issues? It may end up with pure string compares but we'd avoid regressions.

**Pull request merged**
