### PR TITLE
Re-add Fedora 31 migration code.

### PR DESCRIPTION
**Pull request by mheon**
In the process, make everything in the config omitempty in TOML. We're seeing issues (notably [1]) where, after rewriting libpod.conf, fields that were not previously populated are written - and, because they were not previously written, they are included as empty. This is unfortunately different from not included at all - it means that we need to assume the user explicitly unset the value, and we can't use defaults. Setting omitempty prevents us from writing things that should not be written as they were not set originally.

[1] https://github.com/containers/libpod/issues/4210

### CODE REVIEW

**Comment by mheon** [comment]
@vrothberg @baude @giuseppe @rhatdan PTAL - we need this for 1.7.0

Would not merge without an OK from @vrothberg though

**Comment by rhatdan** [comment]
LGTM

**Comment by giuseppe** [comment]
LGTM

**Pull request merged**
