### PR TITLE
Fix path of tmp_dir

### PR DESCRIPTION
**Pull request by xcffl**

### CODE REVIEW

**Comment by mheon** [comment]
Hi, can you add a signoff to your commit with `git commit --amend -s` and repush?

**Comment by mheon** [comment]
/approve
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM once tests are happy.  @xcffl TYVM for the fix up!

**Comment by TomSweeneyRedHat** [comment]
crud, hit the wrong button, I did not mean to close this.

**Comment by xcffl** [comment]
> Hi, can you add a signoff to your commit with `git commit --amend -s` and repush?

Fixed

**Comment by xcffl** [comment]
Looks like the previous problem is fixed dispite some unrelated fatal?

**Pull request merged**
