### PR TITLE
install podman on fah28 before running tests

### PR DESCRIPTION
**Pull request by baude**
Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM!

**Comment by mheon** [comment]
Everything is failing with the registry search test

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by baude** [comment]
My CI rework will hit this.

**Pull request closed without merging**
