### PR TITLE
APIv2 tests: add tests for stop

### PR DESCRIPTION
**Pull request by edsantiago**
...and allow status 'stopped' in addition to 'exited'.

Fixes: #5336

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by mheon** [comment]
LGTM

**Comment by baude** [comment]
giving hold and /lgtm if you can get the tests to pass

**Comment by edsantiago** [comment]
Thanks. It's just been the same old flakes, over and over (restarted 5 times now, I think)

**Pull request merged**
