### PR TITLE
WIP - revert to storage v1.12.13

### PR DESCRIPTION
**Pull request by vrothberg**
The latest image has caused some flakes in the past two days. It is
unclear what has caused the issue, likely an outdated mirror. Using
a stable image should the update rate and thereby the chance of causing
flakes.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
Unfortunately the problem appears to be more systemic, and just changing image did not resolve it.

**Comment by vrothberg** [comment]
> Unfortunately the problem appears to be more systemic, and just changing image did not resolve it.

It only targets the `save ... different digest` error in the e2e tests.

**Comment by vrothberg** [comment]
Which I just hit again locally...

**Comment by vrothberg** [comment]
It happens with `:30` as well now :-/ I'll chase that down.
For the record:
```
[libpod (change-fm)]$ ./bin/podman save -o fm.tar registry.fedoraproject.org/fedora-minimal:30
Error: unable to save "registry.fedoraproject.org/fedora-minimal:30": Error copying image to the remote destination: Error writing blob: Digest did not match, expected sha256:f4119231eb4d87dfc14c23d0f0bbf7cdb88946d21a2c44374923b79dec7638ef, got sha256:8ae3b674494bd7b6d62b8ff72071a6a4d1b2294ea254919bc84b8742f9a30667
```
I can't reproduce with v1.4.4.

**Comment by vrothberg** [comment]
@nalind, I don't get the error with storage v1.12.13 but with storage v1.12.6.

**Comment by vrothberg** [comment]
The regression starts with storage v1.12.14. I am going to roll back to v1.12.13 to unblock CI.

**Comment by vrothberg** [comment]
@mheon I pushed a commit rolling back to v1.12.13 to this PR so we preserve the discussion.

**Comment by vrothberg** [comment]
@baude @rhatdan FYI

**Comment by vrothberg** [comment]
I bisected and found that https://github.com/containers/storage/commit/0d4a46ce285b0f5295561e1845f75537e80d2d53 introduces the regression.

**Comment by vrothberg** [comment]
@nalind, it looks like the tarlogger has side effects. Using a dummy logger for the compressed stream makes the `save` pass but the `load` on the archive then fails with a digest mismatch.

**Comment by mheon** [comment]
Can we get this fixed upstream, potentially? I kind of want to have a newer c/storage with the ignore chown errors option available for 1.5

**Comment by vrothberg** [comment]
@mheon, I am currently looking into it but this thing is really hairy.

**Comment by mheon** [comment]
Ack. We can release without if things don't look promising.

**Comment by vrothberg** [comment]
I had another look and found that using `os.Pipe()` alters the digest.  Using `io.Pipe()` requires a little workaround as it doesn't accept writes after being closed. I'll wrap up a PR for storage...

**Comment by vrothberg** [comment]
I now vendored my fork of c/storage to test https://github.com/containers/storage/pull/406. It works locally on my machine. To be clear: I have no clue why using `os.Pipe()` has the side-effect but I hope to find that out at some point.

**Comment by vrothberg** [comment]
Closing in favour of https://github.com/containers/libpod/pull/3704

**Pull request closed without merging**
