### PR TITLE
rootless: fix CI regression when using slirp4netns

### PR DESCRIPTION
**Pull request by giuseppe**
Older versions of slirp4netns do not have the --disable-host-loopback
flag.

Remove the check once we are sure the updated version is available
everywhere.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by giuseppe** [comment]
@cevich could we update the Fedora images?

**Comment by cevich** [comment]
@giuseppe Yes happy to make new images. PR #2561 should help (assuming I can get it working) with this process.

**Comment by cevich** [comment]
Opened #2689 w/ updated images.  @giuseppe somehow I missed the e-mail notice for this...feel free to ping me on IRC for this next time - it's not much effort on my part.

**Pull request merged**
