### PR TITLE
Add bindings for exec and enable attached remote exec

### PR DESCRIPTION
**Pull request by mheon**
This adds bindings for starting exec sessions, and then uses them to wire up detached exec. Code is heavily based on Attach code for containers, slightly modified to handle exec sessions.

Bindings are presently attached-only, detached is pending on a Conmon update landing in CI. I'll probably get to that next.

Initial attach works, but STDIN doesn't seem to be copied into the container. I've begun chasing this, but my attempts to compare to Attach to debug look to have found bugs in Attach as well.

### CODE REVIEW

**Comment by mheon** [comment]
Stripping WIP. Should be working now.

**Comment by mheon** [comment]
@baude @jwhonce @rhatdan @TomSweeneyRedHat It's green. PTAL.

**Comment by jwhonce** [comment]
LGTM

**Pull request merged**
