### PR TITLE
Attempt to turn on build-commands tests

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@haircommander Looks like we need a newer version of conmon in our CI/CD?
[+0000s] Error: could not find a working conmon binary (configured options: [/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon]): invalid argument

**Comment by baude** [comment]
looks like the man page change failed the command checker

**Comment by mheon** [comment]
We definitely need a newer Conmon anyways, I need to pick up v2.0.16 or higher to make the remote exec tests work.

**Comment by haircommander** [comment]
I would guess the image running the gating test doesn't have conmon in the expected spots

**Pull request closed without merging**
