### PR TITLE
fix race condition in `libpod.GetEvents(...)`

### PR DESCRIPTION
**Pull request by vrothberg**
Fix a race that could cause read errors to be masked.  Masking such
errors is likely to report red herrings since users don't see that
reading failed for some reasons but that a given event could not be
found.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM, and a very good catch!

@baude @giuseppe @rhatdan PTAL

**Comment by baude** [comment]
nice!
/hold

**Pull request merged**
