### PR TITLE
[CI:DOCS] Fix Markdown typo in podman-create.1.md

### PR DESCRIPTION
**Pull request by eriksjolund**
Fix a Markdown syntax typo

Signed-off-by: Erik Sjölund <erik.sjolund@gmail.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM
/approve

**Comment by jwhonce** [comment]
@eriksjolund Sorry for the extra work, but if you rebase and re-push this will now go through.

**Comment by rhatdan** [comment]
Thanks Eric

**Pull request merged**
