### PR TITLE
doc: update rootless_tutorial.md

### PR DESCRIPTION
**Pull request by simon04**
Most changes are typographic improvements, in particular using using ` for commands/files.

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by mheon** [comment]
Looks like you're missing a signoff - please add one with `git commit --amend -s` and re-push and CI should go green.

**Comment by simon04** [comment]
Done. (I always miss this step when doing commits/PRs directly from the GitHub website.)

**Comment by rhatdan** [comment]
Yes we are looking into ways to make this automatic, but we have found nothing in github.com...

**Comment by rhatdan** [comment]
@simon04 This needs a rebase.

**Pull request closed without merging**
