### PR TITLE
Use standard remove functions for removing pod ctrs

### PR DESCRIPTION
**Pull request by mheon**
Instead of rewriting the logic, reuse the standard logic we use for removing containers, which is much better tested.

### CODE REVIEW

**Comment by mheon** [comment]
This *theoretically* will fix the bad CGroup flakes on master, but I haven't tested it for that yet.

**Comment by rhatdan** [comment]
LGTM but tests not happy.

**Comment by mheon** [comment]
Pod tests still failing, amongst everything else

**Comment by mheon** [comment]
Nevermind, mistake on my part

**Comment by mheon** [comment]
Alright, my flake is fixed

**Comment by mheon** [comment]
Added a commit to fix the other CI issues (thanks @baude for finding them)

**Comment by jwhonce** [comment]
LGTM

**Comment by mheon** [comment]
The pod tests are back to failing...

**Comment by stevekuznetsov** [comment]
/hold
https://prow.svc.ci.openshift.org/tide-history?repo=containers%2Flibpod

**Comment by mheon** [comment]
Current status: I think I made it worse. Cleanup processes are still firing and now they have even more time to start up.

Per discussion with @jwhonce and @baude we have a way forward. Set the PID limit to 0 on the CGroups in question, so they stop accepting forks, so no cleanup processes.

If this fails, we freeze the cgroup, SIGKILL conmon, unfreeze it, and conmon has no opportunity to cleanup.

This is very much a Monday thing. Very, very much.

**Comment by mheon** [comment]
Added a commit to set PIDs limit to 0, which seems to resolve the races locally on my laptop. Let's see if CI agrees.

**Comment by mheon** [comment]
LGTM is gone, so I'll unhold

/hold cancel

**Comment by mheon** [comment]
It's still broken... Exact same errors. Is this even a race against the cleanup process? We inhibited forking...

**Comment by mheon** [comment]
Nevermind. Kernel interprets a PID limit of 0 as unlimited. Setting to 1 fixes locally. Repushing.

**Comment by mheon** [comment]
The tests are passing.
@baude @rhatdan @jwhonce @vrothberg Someone want to merge this to fix CI on master?

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
