### PR TITLE
Use the same SELinux label for CRIU log files

### PR DESCRIPTION
**Pull request by adrianreber**
The SELinux label for the CRIU dump.log was explicitly set in Podman.
The label for the restore.log, however, not. This just moves the code
to label the log file into a function and calls that functions during
checkpoint and restore.

Signed-off-by: Adrian Reber <areber@redhat.com>

### CODE REVIEW

**Comment by adrianreber** [comment]
This is related to the discussion in https://github.com/containers/container-selinux/issues/68

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@mheon @baude @giuseppe @TomSweeneyRedHat @vrothberg PTAL

**Pull request merged**
