### PR TITLE
Add cirrus-ci: eventual replacement for papr and travis

### PR DESCRIPTION
**Pull request by cevich**

### CODE REVIEW

**Comment by cevich** [comment]
> I'm waiting for a containers member to verify that this patch

/not-ok-to-test

**Comment by cevich** [comment]
Status:
    * VM Image production Ci/CD 90% complete, 100% working and reproducible
    *  Ubuntu & Fedora pass verification and unit-tests, but fail in integration-tests.
    *  RHEL & CentOs pass verification, but fail in unit-tests.

**Comment by mheon** [comment]
This LGTM

**Pull request merged**
