### PR TITLE
runlabel: use shlex for splitting commands

### PR DESCRIPTION
**Pull request by vrothberg**
Use github.com/google/shlex for splitting commands instead of splitting
at whitespaces.  This way, we avoid accidentally splitting single string
arguments into mutliple ones.

Signed-off-by: Valentin Rothberg <vrothberg@suse.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Looks like a useful utility.  LGTM

**Comment by baude** [comment]
LGTM, would like @mheon  to double check as well

**Comment by mheon** [comment]
Sure, LGTM

**Pull request merged**
