### PR TITLE
V1.0 backports

### PR DESCRIPTION
**Pull request by mheon**
Backports for v1.0.1

Bunch of cherry-picks off of master. Notably missing: anything related to the remote client work, any vendor changes aside from a small containers/selinux change.

### CODE REVIEW

**Comment by mheon** [comment]
@baude @rhatdan @vrothberg @giuseppe Anyone care to give this an LGTM?

**Comment by baude** [comment]
LGTM

**Comment by rhatdan** [comment]
Needs a version bump.  v1.0.1?
I question backporting
`Add varlink support for prune `
We should not do anything for varlink at this point.
`podman image prune -- implement all flag `
We should not backport any new features

But not enought to block the process.

**Comment by mheon** [comment]
Image prune isn't a new feature so much as a major behavior change - it
matches us to the expected behavior of 'docker prune' instead of removing
far more images by default than people would expect.

The Varlink patch was mostly to convince the other prune patch to apply
cleanly without a complete rewrite.

**Comment by vrothberg** [comment]
@mheon there was one AppArmor fix:
* commit 18b7009754df

I think we may also need to vendor the latest containers/{image,storage} to pull in fixes, do we?

**Comment by giuseppe** [comment]
the rootless commits LGTM

**Comment by mheon** [comment]
@vrothberg Since this is an 8-specific backport, I didn't pull in the apparmor stuff. Same reason on c/storage and c/image - we did a massive revendor after 1.0 and I didn't want to break anything

**Comment by mheon** [comment]
@rhatdan Now includes a version bump to 1.0.1

I'll do proper release notes for the main branch once this lands

**Comment by rhatdan** [comment]
LGTM
bot, retest this please

**Comment by mheon** [comment]
Alright bumping build_each_commit timeout just for this branch - if we do more backports we'll probably hit it again

**Pull request merged**
