### PR TITLE
exec: get the exit code from sync pipe instead of file

### PR DESCRIPTION
**Pull request by haircommander**
Before, we were getting the exit code from the file, in which we waited an arbitrary amount of time (5 seconds) for the file, and segfaulted if we didn't find it. instead, we should be a bit more certain conmon has sent the exit code. Luckily, it sends the exit code along the sync pipe fd, so we can read it from there

Adapt the ExecContainer interface to pass along a channel to get the pid and exit code from conmon, to be able to read both from the pipe

Also slightly change the way we report a bogus value when failing to read from the conmon pipe. we now set it to a value that cannot be a valid pid * -1, to make sure we correctly report the place an error comes from

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by baude** [comment]
code lgtm

**Comment by mheon** [comment]
This may cause issues with my detached exec code for APIv2 - how do we
source exit codes there?

**Comment by haircommander** [comment]
> This may cause issues with my detached exec code for APIv2 - how do we source exit codes there?

it would probably take an entirely different code path. We only wait on the exit code when we are attached to it. In updating the exec exit code (for an podman exec list or something, whatever the api will be for listing a container's exec session), we could check for the existence of the exit code via file. 

If need be, we could even save the pipe fd in the db or the location of the file, and open it as needed. This PR should fit right into your exec rework PR, and we can logic through how detach works with this when you get there. But for now this solves an immediate CI flake, so I'm inclined to go forward and think about reworks later.

**Comment by haircommander** [comment]
This is ready

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
