### PR TITLE
auto update: skip non-image policies

### PR DESCRIPTION
**Pull request by vrothberg**
Fix a bug in the auto-update logic causing all images to be checked and
not only the ones of containers with the specific auto-update policy.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
Good we're having demos...@rhatdan, @baude, @mheon PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
LGTM. Tests are not running, though. @cevich Anything going on with Cirrus?

**Comment by stevekuznetsov** [comment]
Required Cirrus checks are not present.

**Comment by vrothberg** [comment]
Rebased and repushed.

**Pull request merged**
