### PR TITLE
cirrus: upgrade slirp4netns

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
seems to solve the slirp4netns issue in the CI

**Comment by mheon** [comment]
@cevich PTAL when you're feeling better

**Comment by giuseppe** [comment]
this is just a workaround to temporarily fix the CI.  Could we get it merged quickly so we can rebase the other PRs?

/cc @vrothberg @rhatdan

**Comment by cevich** [comment]
New VM images w/ updated packages in: #2689

**Pull request merged**
