### PR TITLE
Cleanup OCI runtime before storage

### PR DESCRIPTION
**Pull request by mheon**
Some runtimes (e.g. Kata containers) seem to object to having us unmount storage before the container is removed from the runtime. This is an easy fix (change the order of operations in cleanup) and seems to make more sense than the way we were doing things.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by snir911** [comment]
doesn't fix the issue :/

**Comment by mheon** [comment]
Still worth merging, IMO, this makes more sense than the way we did it before.

**Comment by mheon** [comment]
This does sound like a Kata bug as this point, from what I'm hearing. Podman, on stopping a container, calls the OCI runtime's `kill` (which should guarantee the container and associated VM stops), and then deletes it from the runtime, and then unmounts storage. This sounds like a correct workflow.

**Comment by TomSweeneyRedHat** [comment]
LGTM
bummer it doesn't fix the bug, but a good change regardless.

**Comment by mheon** [comment]
I pushed another commit that might actually resolve it, but haven't checked

**Comment by snir911** [comment]
I  can confirm this is working, i had a similar version but i was not sure if doing the cleanup before setting the Removing state will make Removing state redundant (or even to regress the bug< #3906> was fixed with 25cc43c)

**Pull request merged**
