### PR TITLE
Improves STD output/readability in combination

### LINKED ISSUE #3490: pull: add new line after `Trying to pull $image...`
A user asked for improving the readability for the logs:

```
...
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.mountopt=nodev,metacopy=on]localhost:5000/busybox:latest" 
Trying to pull localhost:5000/busybox...DEBU[0000] reference rewritten from 'localhost:5000/busybox:latest' to 'docker.io/library/busybox:latest' 
DEBU[0000] reference rewritten from 'localhost:5000/busybox:latest' to 'fakeserver.com/bar/busybox:latest' 
...
```

Note the `Trying to pull localhost:5000/busybox...DEBU[0000]` which is on a normal log level followed by `Getting image source signatures`.

### PR DESCRIPTION
**Pull request by deefin**
Improves standard output with debug output.

Added \n char to specific standard output

Closes #3490

Signed-off-by: dom finn <dom.finn00@gmail.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
bot, test pull request

**Comment by mheon** [comment]
This LGTM

**Comment by mheon** [comment]
@deefin Can you rebase? There's a fix for the tests on master

**Comment by rhatdan** [comment]
@deefin you need to rebase your PR.

git pull origin master
git rebase -i origin
git push --force

Then we can merge.

**Comment by deefin** [comment]
@rhatdan Thanks, 

I previously just tried to merge as seen below:

```
git branch
git remote show
git fetch upstream --all
git status
git log
git merge upstream/master
git add libpod/image/pull.go
git status
git commit
git push origin deefin-3490-logging
```

In respect the below config:

```
$ git remote -v
origin	git@github.com:deefin/libpod.git (fetch)
origin	git@github.com:deefin/libpod.git (push)
upstream	git@github.com:containers/libpod (fetch)
upstream	git@github.com:containers/libpod (push)
```

Should the commands you gave me be?

```
git pull upstream master
git rebase -i upstream
git push --force
```

**Comment by mheon** [comment]
Generally I use `git fetch upstream; git rebase upstream/master; git push --force origin $BRANCH_NAME`

**Comment by deefin** [comment]
Thanks @mheon. 

Please excuse my giteracy (git literacy)

Its looking better now from what i can see.

**Pull request merged**
