### PR TITLE
rename pod when we have a name collision with a container

### PR DESCRIPTION
**Pull request by baude**
when podman generate kube runs, it names the pod based on the first
container it finds. the resulting yaml file is perfectly acceptable
in a kubernetes environment.  But when replaying the YAML file
with podman, we cannot have a container and pod with the same name.
therefore, we rename the pod if find a collision to name_pod.

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
@baude So Kube allows pods and containers to share names?

**Comment by baude** [comment]
> @baude So Kube allows pods and containers to share names?
yes

**Comment by baude** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
Does the yaml, specify a name for the pod?

Should podman play kube --name exist?

**Comment by mheon** [comment]
Needs to update RELEASE_NOTES.md with changes

**Comment by mheon** [comment]
Nevermind the noise

@baude Please tag all of these with the 1.2.0 release notes label when you make them, so I can accurately list remote client changes

**Pull request merged**
