### PR TITLE
Add volume mounting to podman play kube

### PR DESCRIPTION
**Pull request by haircommander**
Before, podman play kube ignored HostPath and VolumeMounts fields in a k8s yaml file. Add this functionality, allowing for a user to create a volume mount from a .yaml file

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
fixes #2536

**Comment by haircommander** [comment]
I also want to add the other direction in generate kube, but I'm having some trouble differentiating default mounts to ones the user added (e.g. /etc/hosts vs '...-v <HOST_MNT>:<CTR_MNT>')

**Comment by mheon** [comment]
Hold the latter part until my volume refactor is finished - that will make it clear what named volumes were in use

**Comment by haircommander** [comment]
@mheon ah perfect SGTM

**Comment by haircommander** [comment]
@mheon @rhatdan @TomSweeneyRedHat @baude PTAL

**Comment by baude** [comment]
LGTM

**Pull request merged**
