### PR TITLE
--replace for containers and pods

### PR DESCRIPTION
**Pull request by vrothberg**
Add a `--replace` flag to `podman {create,run}` and `podman pod create` to allow for replacing and removing existing named containers and pods.

Use that flag in `generate systemd` to make the generated units more robust and remove named containers or pods even after a system crash.

Fixes: #5485

### CODE REVIEW

**Comment by vrothberg** [comment]
@mheon, I wired the flag into `pod create` and into the systemd units as well. The big --new pod PR was merged, so I could complete --replace.

**Comment by vrothberg** [comment]
@giuseppe @rhatdan @TomSweeneyRedHat PTAL

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
