### PR TITLE
Pass path environment down to the OCI runtime

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@andrewssobral  does this fix your problem?

**Comment by rhatdan** [comment]
Discussion of this issue is happening here https://github.com/containers/libpod/issues/3659

**Comment by rhatdan** [comment]
There could be still a problem is conmon does not pass the PATH down to the OCI runtime when it executes it.
@haircommander FYI

**Comment by mheon** [comment]
Hmm. I think we'll need Conmon changes as well, here.

LGTM though

**Comment by andrewssobral** [comment]
> @andrewssobral does this fix your problem?

Hi @rhatdan , thanks for the PR, however I'm unable to rebuild podman from source code to make tests in my gpu server, I think I will wait for a new packaged version of Podman.

**Comment by jamescassell** [comment]
Do we have packit in this repo? Would help testing changes like these...

**Comment by haircommander** [comment]
conmon does not pass PATH down, so yes we'd need the changes. I can spin that up once I've tied up what I'm doing now

**Comment by andrewssobral** [comment]
Hi @rhatdan , answering your previous question https://github.com/containers/libpod/pull/5712#issuecomment-608516075
I was able to install the new version of podman, and it works fine with my GPU, however, I am getting this strange behavior at the end of the execution, please see:

```
andrews@deeplearning:~/Projects$ podman run -it --rm --runtime=nvidia --privileged nvidia/cuda:10.0-cudnn7-runtime nvidia-smi 
Mon May 18 21:30:17 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    Off  | 00000000:01:00.0  On |                  N/A |
| 37%   30C    P8     9W / 175W |    166MiB /  7979MiB |      5%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
2020/05/18 23:30:18 ERROR: /usr/bin/nvidia-container-runtime: find runc path: exec: "runc": executable file not found in $PATH
ERRO[0003] Error removing container 672a332467da4e91d8ac2fdc8f3c2973a808321341c2d80caa8d0ecad4f0db65: error removing container 672a332467da4e91d8ac2fdc8f3c2973a808321341c2d80caa8d0ecad4f0db65 from runtime: `/usr/bin/nvidia-container-runtime delete --force 672a332467da4e91d8ac2fdc8f3c2973a808321341c2d80caa8d0ecad4f0db65` failed: exit status 1 
andrews@deeplearning:~/Projects$
```

**Comment by mheon** [comment]
I don't think we ever landed Conmon changes to go along with this, which would explain that.

**Comment by mheon** [comment]
I don't see any commits in Conmon referencing $PATH in the last 6 months, so it appears I'm right.

**Comment by rhatdan** [comment]
Doesn't common just pass it's environment to the child's environment?   @haircommander What needs to be changed here?

**Comment by haircommander** [comment]
for some reason I'm under the impression this happens automagically. don't parent processes pass their children their env?

**Comment by mheon** [comment]
We're using `execv` in Conmon, which does not seem to overwrite environment (there's no argument in the call to do it). I can't find any documentation that it preserves the caller's environment, but it seems like it would stand to reason?

**Comment by rhatdan** [comment]
My reading of the man page is that is what is happening.
```
man execv
...

   e - execle(), execvpe()
       The  environment of the caller is specified via the argument envp.  The
       envp argument is an array of pointers to  null-terminated  strings  and
       must be terminated by a null pointer.

       All  other  exec()  functions  (which do not include 'e' in the suffix)
       take the environment for the new process image from the external  vari‐
       able environ in the calling process.
```

**Pull request merged**
