### PR TITLE
Update WaitForTimeOut to output OutputString to help with debugging.

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM, but I'd like an ack from @baude before merging

**Comment by baude** [comment]
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by mheon** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
I wonder if this is a race condition, caused by golang threads.

**Comment by mheon** [comment]
@rh-atomic-bot retry

**Comment by mheon** [comment]
@rh-atomic-bot retry

**Comment by mheon** [comment]
@rh-atomic-bot retry

Getting awful tired of this...

**Comment by TomSweeneyRedHat** [comment]
@mheon, you really need to keybind a macro for that somewhere....

**Pull request closed without merging**
