### PR TITLE
Fix trivial missing markup in manpage

### PR DESCRIPTION
**Pull request by stickster**

### CODE REVIEW

**Comment by rhatdan** [comment]
@stickster The Test is going to be anal and require you to sign your PR.

```
git commit --amend -s -a
git push --force
```

**Comment by mheon** [comment]
bot, add author to whitelist

**Comment by mheon** [comment]
LGTM

**Comment by umohnani8** [comment]
LGTM

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by mheon** [comment]
@stickster Mind rebasing to pick up CI fixes?

**Pull request merged**
