### PR TITLE
container prune command fixed as per docker prune command

### PR DESCRIPTION
**Pull request by kunalkushwaha**
makes `podman container prune` aligned with docker image prune command.
_This PR is in continuation of https://github.com/containers/libpod/pull/4512 for `container prune` command_

This PR makes following changes.

- default `podman container prune` now ask for confirmation from user with warning message.

```
$ .podman container prune
WARNING! This will remove all stopped containers.
Are you sure you want to continue? [y/N] 
```
- adds ``--filter`` flag, which supports label & until format.
e.g.

```
$ podman container prune -a --filter until=10m             
WARNING! This will remove all stopped containers.
Are you sure you want to continue? [y/N] 

$ podman container prune -a --filter label=test-app                            
WARNING! This will remove all stopped containers.
Are you sure you want to continue? [y/N] 
```

Signed-off-by: Kunal Kushwaha kunal.kushwaha@gmail.com

### CODE REVIEW

**Comment by rhatdan** [comment]
Missing completions and man page updates.

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green tests

**Comment by rhatdan** [comment]
/lgtm
Thanks @kunalkushwaha

**Pull request merged**
