### PR TITLE
fix and enable systemd system tests

### PR DESCRIPTION
**Pull request by vrothberg**
The systemd unit test never ran in CI and was broken for various
reasons.  Fix the test to execute Podman in systemd units and to also
run generated units files.

Note: more tests will be added in the future.  The simple check for now
will prevent regressions.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@baude @giuseppe @mheon @TomSweeneyRedHat PTAL and Merge

**Comment by mheon** [comment]
Would really like a signoff from @edsantiago before merge

**Comment by edsantiago** [comment]
Already looked this morning, but it's Friday so I didn't want to admit to working. LGTM and a welcome addition.

**Pull request merged**
