### PR TITLE
Add gating tasks

### PR DESCRIPTION
**Pull request by baude**
to protect against regressions, we need to add a few gating tasks:
 * build with varlink
 * build podman-remote
 * build podman-remote-darwin

we already have a gating task for building without varlink

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
Why do we need varlink build? Everything else we do uses the varlink tag, including build_each_commit

Other two LGTM

**Comment by cevich** [comment]
LGTM

**Comment by baude** [comment]
> Why do we need varlink build? Everything else we do uses the varlink tag, including build_each_commit
> 
> Other two LGTM

if we are going to claim this is a gating task, we should build targets before all the other vms fire and figure it out after the fact.

**Comment by mheon** [comment]
LGTM then

**Comment by mheon** [comment]
Our buildah vendor would appear to be in bad shape

**Comment by TomSweeneyRedHat** [comment]
@mheon, working on updating the Buildah vendor.

**Comment by mheon** [comment]
@TomSweeneyRedHat thanks. I did a quick check but it didn't update cleanly.

**Comment by TomSweeneyRedHat** [comment]
yeah, it will be a beast mheon, needs updated imagebuilder and docker/docker too.

**Comment by mheon** [comment]
CI should be fixed, rebase please

**Pull request merged**
