### PR TITLE
docs: add note about failing rhel7 systemd on cgroups v2

### PR DESCRIPTION
**Pull request by giuseppe**
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1747933

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
> Text LGTM. Can we mention which version of systemd is required? I expect non-RH images to hit similar issues.

sure.  Added in the new version.

**Comment by giuseppe** [comment]
> Maybe worth a micro blog?

good idea.  It will make easier for people to discover the issue on internet

**Comment by rhatdan** [comment]
@fatherlinux fyi

**Pull request merged**
