### PR TITLE
WIP: [ci skip]: Fix podman-remote docs install WRT automatic release

### PR DESCRIPTION
**Pull request by cevich**
Depends on: #3710

### CODE REVIEW

**Comment by ashley-cui** [comment]
Docs LGTM :smile: but I'm not entirely clear on the upload release part. Is the zip file uploaded to quay? Can it be downloaded using a link?

**Comment by cevich** [comment]
@jwhonce maybe I can close this PR (started work in cd19b5ea63da4b06dcafcab4b8b0e748faab2bf4)?

(I heard you already fixed docs-building)

**Comment by cevich** [comment]
Okay, closing as discussed.

**Comment by jwhonce** [comment]
Work moved to https://github.com/containers/libpod/pull/4042

**Pull request closed without merging**
