### PR TITLE
tests: fix rootless tests

### PR DESCRIPTION
**Pull request by giuseppe**
based on #2695

### CODE REVIEW

**Comment by giuseppe** [comment]
root tests are passing!

/cc @baude @rhatdan 

let's merge this :-)

**Comment by rhatdan** [comment]
LGTM

**Comment by cevich** [comment]
``SUCCESS! -- 463 Passed | 0 Failed | 3 Flaked | 0 Pending | 159 Skipped``

Wow that's really nice to see!

**Pull request merged**
