### PR TITLE
rootless: add an entry to /etc/hosts when using slirp4netns

### PR DESCRIPTION
**Pull request by giuseppe**
Closes: https://github.com/containers/libpod/issues/3405

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, just wondering if we should also add a trailing comment to the line too, something like "# used by rootless Podman"  or "# used by slirp4netns"  or perhaps just "# slirp4netns"

**Comment by rhatdan** [comment]
@giuseppe Yes please add a comment.  Is there a possibility for a conflict here?  If the hostname was added twice?  What happens?

**Comment by giuseppe** [comment]
> @giuseppe Yes please add a comment. Is there a possibility for a conflict here? If the hostname was added twice? What happens?

comment added.  In that case the resolver will use all the specified addresses.

```
# printf "192.168.10.1 foo\n192.168.10.2 foo\n192.168.10.3 foo\n" >> /etc/hosts
# python -c 'import socket; print(socket.gethostbyname_ex("foo"))'
('foo', [], ['192.168.10.1', '192.168.10.2', '192.168.10.3'])

```

**Pull request merged**
