### PR TITLE
vendor github.com/containers/{image@v3.0.1,buildah@v1.10.0}

### PR DESCRIPTION
**Pull request by vrothberg**
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM once tests go green

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but it looks like there may be some real test errors.

**Comment by vrothberg** [comment]
@mheon @baude @TomSweeneyRedHat now updated with image v3.0.1 and storage v1.13.0 along with the latest Buildah.

**Comment by mheon** [comment]
Alright, once this is green we should be good to make a release branch and do some reverts

**Comment by mheon** [comment]
Rerunning failed checks.

The release appears to have slipped again. Oops.

**Comment by TomSweeneyRedHat** [comment]
Does buildah need to get bumped to c/storage 1.13.0 and c/image 3.0.1 and then bump a new Buildah 1.10.1 to be merged here?

**Comment by vrothberg** [comment]
> Does buildah need to get bumped to c/storage 1.13.0 and c/image 3.0.1 and then bump a new Buildah 1.10.1 to be merged here?

We're good here as the libraries are already vendored with this PR.

**Comment by vrothberg** [comment]
```
[+0836s] [Fail] Podman run [It] podman run --mount type=bind,bind-nonrecursive 
[+0836s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/run_test.go:709
[+0836s] 
[+0836s] [Fail] Podman login and logout [It] podman login and logout with multi registry 
[+0836s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/login_logout_test.go:237
[+0836s] 
[+0836s] [Fail] Podman login and logout [It] podman login and logout with multi registry 
[+0836s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/login_logout_test.go:197
[+0836s] 
[+0836s] [Fail] Podman login and logout [It] podman login and logout with multi registry 
[+0836s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/login_logout_test.go:197
```

Preparing slides for Flock at the moment, not sure if I can track that down today.

**Comment by vrothberg** [comment]
Now back to looking into it:

seeing `Error: cannot listen on the TCP port: listen tcp4 :5000: bind: address already in use`

**Comment by vrothberg** [comment]
> Now back to looking into it:
> 
> seeing `Error: cannot listen on the TCP port: listen tcp4 :5000: bind: address already in use`

Red herring. Had a moby container running.

**Comment by mheon** [comment]
Test `podman login and logout with multi registry` is failing very consistently.

Rootless tests are probably a separate issue.

**Comment by mheon** [comment]
```

[+0341s] • Failure [17.129 seconds]
[+0341s] Podman login and logout
[+0341s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/login_logout_test.go:20
[+0341s]   podman login and logout with multi registry [It]
[+0341s]   /var/tmp/go/src/github.com/containers/libpod/test/e2e/login_logout_test.go:165
[+0341s] 
[+0341s]   Expected
[+0341s]       <int>: 0
[+0341s]   not to equal
[+0341s]       <int>: 0
```

**Comment by mheon** [comment]
Oh, missing one thing there - it's line 237. Very last expect.

**Comment by mheon** [comment]
I have no idea how this test works or does not work, and why this push is supposed to fail.

**Comment by mheon** [comment]
This has a hold, so
/lgtm

**Comment by rhatdan** [comment]
Replaced by https://github.com/containers/libpod/pull/3765

**Pull request closed without merging**
