### PR TITLE
bump(github.com/containers/storage,github.com/containers/image)

### PR DESCRIPTION
**Pull request by nalind**
Bump github.com/containers/storage and github.com/containers/image, to commits 06b6c2e4cf254f5922a79da058c94ac2a65bb92f and 93bced01015eb94bec4821df1876314be8197680, respectively.

This should incorporate the fixes for manifest digest mismatches that were made for CRI-O in https://github.com/cri-o/cri-o/pull/2066 and https://github.com/cri-o/cri-o/pull/2071.

### CODE REVIEW

**Comment by mheon** [comment]
/approve
LGTM once tests go green

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by mheon** [comment]
Oh dear, it's the 1.0 branch. CI is 100% broken here, the code to actually run Papr was removed on their end.

**Comment by mheon** [comment]
Need to land #2891 first to fix CI for this branch

**Comment by mheon** [comment]
@nalind Please rebase and we can merge

**Comment by mheon** [comment]
Rerunning ubuntu test - seems like it's a flake. Will merge once green.

**Pull request merged**
