### PR TITLE
Fix integration tests for untag

### PR DESCRIPTION
**Pull request by baude**
Signed-off-by: Brent Baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by jwhonce** [comment]
LGTM

**Comment by vrothberg** [comment]
Not sure if the test should be green or not. @jwhonce @rhatdan ?

**Comment by rhatdan** [comment]
/hold cancel
Integration tests are failing because of userns default. Fixed in a different PR>

**Comment by stevekuznetsov** [comment]
/hold

```
 success Cancelled after 14m — Task Summary 
```

**Pull request closed without merging**
