### PR TITLE
Merge of Giuseppe Scrivano's UserNSRoot to podman 1.6.4-dev

### PR DESCRIPTION
**Pull request by qfunq**

### CODE REVIEW

**Comment by mheon** [comment]
What's the intent here? These seem like major, invasive changes (the CreateContainer one in particular seems like it will break a lot).

**Comment by giuseppe** [comment]
we dropped the intermediate mounting namespace as it was very fragile.  I don't think we have to add it again.  Are you seeing any issue with user namespaces?

**Comment by qfunq** [comment]
Hi Matthew,

Thanks so much, you are absolutely right, the CreateContainer code
contained dreadful bugs. While reviewing it I noticed something really
strange, that the issues I was having with the main branch of podman had
completely vanished.

I have pinned down the issue ... previously I was making the volumes using
podman create before issuing the podman -v call. The idea of the patch was
to be able to mount a pre-created volume, but on testing it now, it doesn't
work at doing that!

The end result is I will create volumes using a podman run command rather
than podman create, and delete the bugged branch.

Thanks for your help,

Jonathan

**Comment by qfunq** [comment]
I realised this is related to some usability issues in the main branch:

The call to makeAccessible in CreateContainer has no balancing chown back
to the original when the mounts are taken down, potentially leaving the
volume in a state other than it was created in.


If the chowning is done earlier, and a balancing unchown later, it's more
transparent, gaining associativity for volume based podman commands.



With these ideas, the following will work ...
podman --rm --uidmap 0:4096:4095 -v testvol:test:Z alpine cat hello >
/test/msg

podman --rm --uidmap 0: 8192:4095 -v testvol:test:Z alpine cat hello >
/test/msg


The volume commands are reduced to atomic actions, in the above case ::

podman create volume testvol //create the volume in the original users name
space

chown --uidmap 0:4096:4095  testvol    //make testvol accessible ...
reduces makeAccessible in CreateContainer to a nop.
podman run --rm --uidmap 0:4096:4095 -v testvol:/test:Z  alpine touch
/test/msg      ///do something with the volume
unchown --uidmap 0:4096:4095 testvol   //return the volume to the original
user

chown --uidmap 0:8192:4095 testvol
podman run --rm --uidmap 0:8192:4095 -v testvol:/test:Z  alpine   touch
/test/msg
unchown --uidmap 0: 8192 :4095 testvol

currently none of the 3 raw podman commands above will work together ...
which makes setting up volumes very context specific: i.e

# podman run --rm  --uidmap 0:8192:4095 -v testvol:/test:Z alpine touch
/test/foo
Error: error stat'ing file
'/var/lib/containers/storage/volumes/testvol/_data': Permission denied: OCI
runtime permission denied error ...

I think this is ginkgo complaining ... podman was launched as root, so the
permission to chown is permitted! I guess ginkgo is getting called before
makeAccessible?

Jonathan

**Pull request closed without merging**
