### PR TITLE
commands: rename file and add likns to readthedocs

### PR DESCRIPTION
**Pull request by cpanato**
rename the commands.md to commands-demo.md per suggestion here: https://github.com/containers/libpod/issues/4414

and update the links to point to the read the docs page

 - fixes https://github.com/containers/libpod/issues/4414

/cc @rhatdan

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
The changes to commands-demo.md look awesome.  However, rather than removing command.md, I'd like to keep it but remove most of the comments and leave something like:

This page has moved [here](commands-demo.md)

**Comment by cpanato** [comment]
thanks for the review @TomSweeneyRedHat 
made the change requested

**Comment by cpanato** [comment]
@TomSweeneyRedHat @rhatdan ping :)

**Comment by stevekuznetsov** [comment]
/hold

"success" is cancelled

**Comment by cpanato** [comment]
@stevekuznetsov rebased to see if fix

**Comment by mheon** [comment]
@stevekuznetsov Sorry this keeps happening... Any chance we could get the robot to add a comment to the issue if it stalls for some length of time (~10 minutes, maybe) so folks like me who aren't actively monitoring CI load can see something is wrong?

**Comment by mheon** [comment]
@cpanato No problems on your end, CI is just flaking badly at the moment (we have an elusive bug in `podman exec` that only occurs on our CI setup)

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM

**Comment by stevekuznetsov** [comment]
It's hard for us to tell from the API why we're failing to merge something we think should be merge-able but I think surfacing it would be useful, yes

**Pull request merged**
