### PR TITLE
handle dns response from cni

### PR DESCRIPTION
**Pull request by baude**
when cni plugins return a list of DNS servers to use, we should honor
them and they should be inserted to the "top" of the list of servers to
resolve with.  this is needed eventually for the dnsmasq cni plugin.

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by baude** [comment]
> LGTM
> 
> Can we add a test?

Not until the CNI work is upstream and available,.

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by baude** [comment]
reworked based on last week's discussion on how to handle these ...

**Pull request merged**
