### PR TITLE
Fix CGroup paths used for systemd CGroup mount

### PR DESCRIPTION
**Pull request by mheon**
We already have functions for retrieving the container's CGroup path, so use them instead of manually generating a path.

### CODE REVIEW

**Comment by baude** [comment]
LGTM

**Comment by mheon** [comment]
Going to wait for the full VM tests to confirm this doesn't blow up the unit tests and merge

**Comment by mheon** [comment]
The tests we expect to go green are green. Merging so we can cut a release with this fix.

**Pull request merged**
