### PR TITLE
WIP: vendor: Update with a fresh vndr run

### PR DESCRIPTION
**Pull request by wking**
Generated by running `vndr` as installed from LK4D4/vndr@1fc68ee0 (preserve directories with .c files, 2018-04-30).

Spot checking one of the changes, the `-io/+syscall` import change in `github.com/containerd/cgroups/blkio.go` is unwinding containerd/cgroups@77e62851 (Use /proc/diskstats to get device names, 2018-01-31), because our `vendor.conf` has pinned containerd/cgroups@7a5fdd83 (Merge pull request \#26 from onorua/error-ignore-example, 2017-08-24) since af64e104 (Vendor in lots of kubernetes stuff to shrink image size, 2018-03-26, #554).  It looks like ae89dc28d (Update containerd/cgroups repo fix perf issue, 2018-02-01, #284) updated the vendored file without updating `vendor.conf`.

We'll probably want to go through and update `vendor.conf` until a fresh `vndr` run doesn't change `vendor`, and I've marked this PR as a WIP until I get to that point.

### CODE REVIEW

**Comment by mheon** [comment]
@wking For `containerd/cgroups` and most of our other pinned libraries - we're mostly pinning specific commits not because we require specific functionality or want to depend on a specific version of a library, but to try and make sure we don't bump vendored libraries except deliberately by updating the pinned commit (and potentially break things in the process). So feel free to update pinned commits as necessary.

**Comment by wking** [comment]
Rebased onto master with a8eb55e -> 3fe410d now that #749 through #752 have landed.  We've shrunk the change size a bit (but more insertions, maybe in `vendor/golang.org/x/crypto`, for some reason?). 
 But we still have a ways to go:

```console
$ git --no-pager show --oneline --shortstat a8eb55e
a8eb55e WIP: vendor: Update with a fresh vndr run
 153 files changed, 4725 insertions(+), 13414 deletions(-)
$ git --no-pager show --oneline --shortstat 3fe410d 
3fe410d (HEAD -> vndr-cleanup) WIP: vendor: Update with a fresh vndr run
 144 files changed, 8280 insertions(+), 3503 deletions(-)
```

**Comment by rhatdan** [comment]
Needs to be redone.

**Comment by baude** [comment]
No action in a long time, closing. Reopen if needed

**Pull request closed without merging**
