### PR TITLE
Ensure that each log line is newline-terminated

### PR DESCRIPTION
**Pull request by mheon**
When writing logs with timestamps to the terminal, ensure that each line is newline-terminated, so we don't end up with an unreadable mess with timestamps interspersed with the actual content being displayed.

An partial fix of the (easy) part of the issue from #2500

### CODE REVIEW

**Comment by mheon** [comment]
Turns this:

```
2019-03-03T21:01:16.219396456-05:00 2019-03-03T21:01:16.220405553-05:00 [root@2c195fd79044 /]# 2019-03-03T21:01:21.297124753-05:00 
2019-03-03T21:01:21.297629293-05:00 2019-03-03T21:01:21.298103445-05:00 [root@2c195fd79044 /]# 2019-03-03T21:01:21.479471092-05:00 
2019-03-03T21:01:21.480303413-05:00 2019-03-03T21:01:21.480527759-05:00 [root@2c195fd79044 /]# 2019-03-03T21:01:21.657164737-05:00 
```

Into this:

```
2019-03-03T21:11:28.902196159-05:00 
2019-03-03T21:11:28.902858904-05:00 [root@d5003ddef6a5 /]# 
2019-03-03T21:11:29.459544487-05:00 
2019-03-03T21:11:29.460010936-05:00 
2019-03-03T21:11:29.460432834-05:00 [root@d5003ddef6a5 /]# 
2019-03-03T21:11:29.60151061-05:00 
2019-03-03T21:11:29.602178337-05:00 
2019-03-03T21:11:29.602316019-05:00 [root@d5003ddef6a5 /]# 
```

Now, we're still printing user-entered newlines on separate lines, and if I was to type in `asdf` each character would appear on a separate line, but this is definitely an improvement in readability

**Comment by mheon** [comment]
The real fix here is probably to wait until we find a newline before printing, but that will probably require a complete rewrite of the output logic for --follow, so I'm going to avoid that part today

**Comment by mheon** [comment]
I found a more complete solution that emulates the expected output from Docker a lot more closely (though it's not without its quirks - Docker prints only when a complete line is entered, we print any time a character is entered, but only print a timestamp at the start of the line). It's a very close approximation, aside from our timestamps not matching (Docker uses time when the enter key was pressed, we use time when the first character of the line was typed).

**Comment by rhatdan** [comment]
@mheon The change you have made so far, code looks good.  But are you done?

**Comment by mheon** [comment]
@rhatdan I think this is good enough. The timestamps issue is annoying, but fixing it would require a wholesale rewrite of most of this code; we can do almost everything Docker can with this five or so line change. This should be ready for merge.

**Comment by rhatdan** [comment]
@vrothberg @baude @TomSweeneyRedHat @giuseppe PTAL

**Comment by vrothberg** [comment]
LGTM

**Pull request merged**
