### PR TITLE
Backports for v2.0.2

### PR DESCRIPTION
**Pull request by mheon**
Bunch of backported bugfixes - last commit is release notes summary of the backports

### CODE REVIEW

**Comment by rhatdan** [comment]
Should the Vendor PRs be done differently?

**Comment by baude** [comment]
lgtm

**Comment by mheon** [comment]
@rhatdan I don't think we want to do much revendoring into an LTS branch?

**Comment by rhatdan** [comment]
@mheon As long as we can continue to use the test suite, I am fine with it.

**Pull request merged**
