### PR TITLE
Remove Travis

### PR DESCRIPTION
**Pull request by baude**
Now that we are testing ubuntu-bionic on a VM, we no longer need
travis.

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@baude full_vm_testing is reporting a failure, not sure that's expected.

**Comment by TomSweeneyRedHat** [comment]
Seems odd not to have travis in the mix, but LGTM (assuming happy tests) and hopefully less of a CI flake headache.

**Comment by umohnani8** [comment]
LGTM

**Comment by mheon** [comment]
All green, let's do it
/lgtm
(I wonder if that needs to be in a separate comment)

**Pull request merged**
