### PR TITLE
Don't set apparmor if --priviliged

### PR DESCRIPTION
**Pull request by rhatdan**
Closes: #3112 

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@vrothberg @giuseppe @mheon @TomSweeneyRedHat @baude PTAL

**Comment by giuseppe** [comment]
LGTM

**Comment by mheon** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.

**Comment by vrothberg** [comment]
The PR did not fix the issue as it just doesn't set the profile in the spec which will yield the application of the default profile. I'll open another one and add some tests.

**Comment by rhatdan** [comment]
Shoot, your right.  I wonder if we should conflict commands with --privileged.
IE 
(--security-opt and --cap-add/cap-drop) and --privileged should not be set at the same time.

**Pull request merged**
