### PR TITLE
Vendor latest containers/image

### PR DESCRIPTION
**Pull request by umohnani8**
Catches more errors when checking for login credentials.

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM

**Comment by umohnani8** [comment]
Do not merge yet, @mtrmac is opening two more cleanup PRs, will pick those once merged as well.

**Comment by umohnani8** [comment]
Should be ready to merge once tests pass.

**Pull request merged**
