### PR TITLE
Refactor test to prevent panic

### PR DESCRIPTION
**Pull request by jwhonce**
Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Where is the panic that you're seeing?  My (maybe mis-)understanding was the FileInfo was not supposed to be nil on error.
Otherwise LGTM, tests aren't hip.

**Comment by TomSweeneyRedHat** [comment]
and fwiw, I'm doing similar in https://github.com/containers/libpod/pull/4389, may need to touch that up too.

**Comment by jwhonce** [comment]
@TomSweeneyRedHat https://github.com/containers/libpod/pull/4404/files#diff-cab9fc8e95d19f0007ff886cff814b55L74 panics when FileInfo is nil.  I reviewed the golang library source and FileInfo is nil on any error.  I didn't trap the error I was seeing just checked the library source and changed your code to stop the de-referencing nil. Maybe permission denied?

**Pull request merged**
