### PR TITLE
Add make depend, no build if there are no changes

### PR DESCRIPTION
**Pull request by afbjorklund**
Generate depend files for make, using a `go list` script.

Also .gopathok cannot be phony, that rebuilds every time.

### CODE REVIEW

**Comment by rhatdan** [comment]
@afbjorklund You need to sign your commits.

**Comment by afbjorklund** [comment]
Signed. Think I prefer the external DCO handling

**Comment by afbjorklund** [comment]
Signed.

**Comment by TomSweeneyRedHat** [comment]
LGTM, but would like a head nod from @baude

**Comment by afbjorklund** [comment]
Too many environment variables (like tags) makes this dependency generation unreliable for podman.

See https://github.com/containers/buildah/pull/1252#issuecomment-450853620

**Pull request closed without merging**
