### PR TITLE
[1.9] vendor github.com/containers/common@v0.8.4

### PR DESCRIPTION
**Pull request by vrothberg**
Fixes: #6163
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@baude @mheon @rhatdan PTAL

**Comment by vrothberg** [comment]
Now is a good moment to cut a release branch for Buildah. We need to vendor c/common there first, then cut a new 1.14.x release and vendor that into libpod here.

@baude @TomSweeneyRedHat @rhatdan PTAL

```
[+0005s] Build Tags: apparmor,seccomp,selinux,!ABISupport,!varlink,remoteclient
[+0025s] cmd/podman/libpodruntime/runtime.go:1: vendor/github.com/containers/buildah/imagebuildah/executor.go:116:18: cannot initialize 1 variables with 2 values (typecheck)
[+0025s] package libpodruntime
[+0025s] pkg/adapter/autoupdate_remote.go:1: vendor/github.com/containers/buildah/imagebuildah/executor.go:116:18: cannot initialize 1 variables with 2 values (typecheck)
[+0025s] // +build remoteclient
[+0025s] cmd/podman/attach.go:1: vendor/github.com/containers/buildah/imagebuildah/executor.go:116:18: cannot initialize 1 variables with 2 values (typecheck)
```

**Comment by vrothberg** [comment]
Cutting a release branch for contianers/common as well!

**Comment by rhatdan** [comment]
LGTM
But failing Gating test.

**Comment by rhatdan** [comment]
Should we just add a PR to containers/common specific to podman 1.9 release?

**Comment by vrothberg** [comment]
Now vendored common@v0.8.4. @rhatdan @mheon PTAL

**Pull request merged**
