### PR TITLE
networking: use firewall plugin

### PR DESCRIPTION
**Pull request by giuseppe**
drop the pkg/firewall module and start using the firewall CNI plugin.
It requires an updated package for CNI plugins.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
@giuseppe We might need this to resolve bugs with CNI 0.8.0 - mind rebasing? We can start looking into CI from there.

**Comment by giuseppe** [comment]
>

> @giuseppe We might need this to resolve bugs with CNI 0.8.0 - mind rebasing? We can start looking into CI from there.

rebased, but I think we need a version of the CNI plugins first

**Comment by rhatdan** [comment]
@giuseppe Any update on this PR?

**Comment by mheon** [comment]
Lokesh is packaging the latest plugins for Fedora so we should be in a good
spot to swap over with upgraded test VMs

**Comment by mheon** [comment]
We have 0.8.1 in the repos now, so we should be good to try this now.

**Comment by mheon** [comment]
Correction: Needs #3534 first

**Comment by giuseppe** [comment]
it fails only on old systems where the CNI plugins are not updated.  What should we do about it?  Can we update the plugins on Ubuntu?

**Comment by mheon** [comment]
I'll poke Lokesh - I think we package them

**Comment by vrothberg** [comment]
@mheon @lsm5 friendly ping

**Comment by mheon** [comment]
I think we might be set. I'll confirm at scrum - if so, we can cut new testing images that include 0.8.1.

(Though, really, we need a 0.8.2 to fix the issue that @edsantiago found with "does not exist" errors on chains... I'll poke the CNI folks.)

**Comment by mheon** [comment]
Ubuntu seems green... I think we might need 0.8.1 in F29, though. Inconvenient.

**Comment by mheon** [comment]
F29 is in testing, should be pushing to stable tomorrow. Once that happens, we bump images and this should pass.

**Comment by mheon** [comment]
Retargetting this for 0.8.1

**Comment by mheon** [comment]
Everything should go green if you rebase @giuseppe

**Comment by giuseppe** [comment]
> Everything should go green if you rebase @giuseppe

rebased

**Comment by mheon** [comment]
/retest

I think we just caught a bunch of flakes here

**Comment by mheon** [comment]
F29 did go green. I think this is going to be ready.

**Comment by edsantiago** [comment]
/retest

error is:
```
http://mirror.cogentco.com/pub/linux/epel/7/x86_64/repodata/d370878dcea587ad1a720619d162d84fc268b44e65721ff72fd872465d4f49de-updateinfo.xml.bz2: [Errno 14] HTTP Error 404 - Not Found
```
I wonder if we could find a way for CI tests not to have to rely on yum/dnf repos?

**Comment by rhatdan** [comment]
LGTM
@mheon @baude @vrothberg @TomSweeneyRedHat @ashley-cui @QiWang19 @jwhonce PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.

**Comment by giuseppe** [comment]
@cevich I think we need to update `quay.io/libpod/in_podman:latest` as it is still using the old version for the CNI plugins

**Comment by cevich** [comment]
>  still using the old version for the CNI plugins

That's in `contrib/podmanimage`, builds automatically after merge (making it complex to test in a PR) :disappointed:

**Comment by giuseppe** [comment]
@cevich I've moved the second patch to https://github.com/containers/libpod/pull/3853

**Comment by giuseppe** [comment]
> That's in `contrib/podmanimage`, builds automatically after merge (making it complex to test in a PR) disappointed

where do we build it?  Can I see the logs?  I am afraid the image is not built correctly since the updated CNI plugins are already present on Fedora

**Comment by giuseppe** [comment]
tests are finally passing!  :tada: :tada: :tada: :tada: 

@mheon PTAL

**Comment by mheon** [comment]
(It's done. It's finally done. We don't have to maintain that code anymore. Immense thanks for @giuseppe for handling this).

**Pull request merged**
