### PR TITLE
rootless: use SYS_renameat2 instead of __NR_renameat2

### PR DESCRIPTION
**Pull request by giuseppe**
use the correct definition for the syscall number.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
@vrothberg https://bugzilla.redhat.com/show_bug.cgi?id=1768519

I didn't link it since the bug is private

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by alicefr** [comment]
I verified the fix on s390x. The fix is required because the syscall `renameat2` is not defined on s390x. At least for the rhel 7.7 kernel `3.10.0-1062`.

**Pull request merged**
