### PR TITLE
Minor typo fixes

### PR DESCRIPTION
**Pull request by edsantiago**
'capabilties' seems to be a common variant

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
FWIW, I saw a similar change for capabilities in a couple of other unrelated projects recently.

**Comment by rhatdan** [comment]
That is the way my fingers type it for some unknown reason.
/lgtm

**Comment by edsantiago** [comment]
Closing in favor of the much-more-thorough #5407

**Pull request closed without merging**
